version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      root-javascript:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /apps/web
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      web-javascript:
        patterns: ['*']

  - package-ecosystem: gomod
    directory: /apps/api
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      api-go:
        patterns: ['*']

  - package-ecosystem: gomod
    directory: /apps/node
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      node-go:
        patterns: ['*']

  - package-ecosystem: gomod
    directory: /apps/operator
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      operator-go:
        patterns: ['*']

  - package-ecosystem: gomod
    directory: /apps/cli
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      cli-go:
        patterns: ['*']
