import { useEffect, useState } from "react";
import type { components } from "@tunnex/shared";
import { api, apiErrorMessage, loadOne, type Loaded } from "../lib/api";
import { Button, Field, Input, Modal } from "./ui";

type Inventory = components["schemas"]["AgentMCPInventory"];
type Policy = components["schemas"]["AgentMCPToolPolicy"];
type Approval = components["schemas"]["AgentMCPToolApprovalRequest"];
type OAuthConnection = components["schemas"]["AgentMCPOAuthConnection"];
type Tool = { endpoint: string; server_name: string; tool_name: string; input_schema_hash: string };
const toolsFrom = (inventory: Inventory): Tool[] => (Array.isArray(inventory.snapshot.servers) ? inventory.snapshot.servers as Array<Record<string, unknown>> : []).flatMap((server) => {
  const endpoint = typeof server.endpoint === "string" ? server.endpoint : "";
  const serverName = typeof server.server_name === "string" ? server.server_name : "";
  return (Array.isArray(server.tools) ? server.tools as Array<Record<string, unknown>> : []).flatMap((tool) => {
    const name = typeof tool.name === "string" ? tool.name : "";
    const hash = typeof tool.input_schema_hash === "string" ? tool.input_schema_hash : "";
    return endpoint && serverName && name && hash ? [{ endpoint, server_name: serverName, tool_name: name, input_schema_hash: hash }] : [];
  });
});

export function AgentMCPToolApprovalPanel({ orgId, deviceId, canApprove }: { orgId: string; deviceId: string; canApprove: boolean }) {
  const [requests, setRequests] = useState<Loaded<Approval[]> | null>(null); const [busy, setBusy] = useState<string | null>(null); const [confirmation, setConfirmation] = useState<Approval | null>(null); const [mutationError, setMutationError] = useState<string | null>(null);
  const load = () => {
    if (!canApprove) { setRequests(null); return; }
    setRequests(null);
    void loadOne(() => api.GET("/api/v1/organizations/{orgId}/agents/{deviceId}/mcp-tool-approval-requests", { params: { path: { orgId, deviceId } } })).then((result) => setRequests(result as Loaded<Approval[]>));
  };
  useEffect(load, [orgId, deviceId, canApprove]);
  const approve = async (item: Approval) => { setBusy(item.id); setMutationError(null); const result = await api.POST("/api/v1/organizations/{orgId}/agents/{deviceId}/mcp-tool-approval-requests/{requestId}/approve", { params: { path: { orgId, deviceId, requestId: item.id } } }); setBusy(null); if (result.error || !result.data) { setMutationError(apiErrorMessage(result.error, "Could not approve this step-up request. It may already have expired or been consumed. Refresh and try again.")); return; } setConfirmation(null); load(); };
  const items = requests?.ok ? requests.data : [];
  return <div data-testid="agent-mcp-tool-approvals" className="text-xs text-slate-300"><p className="text-slate-500">The exact retried invocation consumes approval once. Arguments and credentials are never shown or retained.</p>{!canApprove ? <p role="status" className="mt-2 text-slate-500">You do not have permission to review or approve step-up requests.</p> : requests === null ? <p role="status" className="mt-2 text-slate-500">Loading step-up requests…</p> : !requests.ok ? <><p role="alert" className="mt-2 text-danger">Step-up requests could not be loaded: {requests.error}</p><Button size="sm" variant="ghost" className="mt-2" onClick={load}>Retry</Button></> : items.length === 0 ? <p className="mt-2 text-slate-500">No step-up requests.</p> : items.map((item) => <div key={item.id} className="mt-2 flex flex-wrap items-center gap-2"><span>{item.server_name} · <span className="font-mono">{item.tool_name}</span> · {item.state}</span>{item.state === "pending" && <Button disabled={busy === item.id} onClick={() => { setMutationError(null); setConfirmation(item); }}>Approve once</Button>}</div>)}{confirmation && <Modal title={`Approve ${confirmation.tool_name} once?`} onDismiss={() => !busy && setConfirmation(null)} actions={<><Button variant="ghost" disabled={busy !== null} onClick={() => setConfirmation(null)}>Cancel</Button><Button disabled={busy !== null} onClick={() => void approve(confirmation)}>{busy ? "Approving…" : mutationError ? "Retry approval" : "Approve once"}</Button></>}><p className="text-cell text-ink-tertiary">This authorizes one retried invocation of <strong>{confirmation.server_name} / {confirmation.tool_name}</strong>. The approval is consumed once; arguments and credentials are not displayed or retained.</p>{mutationError && <p role="alert" className="mt-3 text-danger">{mutationError}</p>}</Modal>}</div>;
}

export function AgentMCPToolPolicyPanel({ orgId, deviceId, inventory, canManage }: { orgId: string; deviceId: string; inventory: Inventory; canManage: boolean }) {
  const tools = toolsFrom(inventory); const [policy, setPolicy] = useState<Loaded<Policy | null> | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [controls, setControls] = useState<Record<string, { rate: string; stepUp: boolean; constraints: string }>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const key = (tool: Tool) => `${tool.endpoint}\u0000${tool.server_name}\u0000${tool.tool_name}\u0000${tool.input_schema_hash}`;
  const loadPolicy = () => { if (!canManage) { setPolicy(null); setSelected(new Set()); return; } setPolicy(null); void loadOne(() => api.GET("/api/v1/organizations/{orgId}/agents/{deviceId}/mcp-tool-policy", { params: { path: { orgId, deviceId } } })).then((result) => { if (!result.ok) { setPolicy(result as Loaded<Policy | null>); setSelected(new Set()); return; } if (result.data) { const current = result.data as Policy; setPolicy({ ok: true, data: current }); setSelected(new Set(current.rules.map((rule) => key(rule)))); setControls(Object.fromEntries(current.rules.map((rule) => [key(rule), { rate: rule.rate_limit_per_minute?.toString() ?? "", stepUp: rule.step_up_required ?? false, constraints: rule.argument_constraints ? JSON.stringify(rule.argument_constraints) : "" }]))); } else { setPolicy({ ok: true, data: null }); setSelected(new Set()); } }); };
  useEffect(loadPolicy, [orgId, deviceId, canManage]);
  const save = async () => { setBusy(true); setError(null); let rules; try { rules = tools.filter((tool) => selected.has(key(tool))).map((tool) => { const control = controls[key(tool)] ?? { rate: "", stepUp: false, constraints: "" }; const rate = Number(control.rate); const constraints = control.constraints ? JSON.parse(control.constraints) : undefined; return { ...tool, step_up_required: control.stepUp, ...(Number.isInteger(rate) && rate > 0 ? { rate_limit_per_minute: rate } : {}), ...(constraints ? { argument_constraints: constraints } : {}) }; }); } catch { setBusy(false); setError("Argument constraints must be valid JSON."); return; } const result = await api.PUT("/api/v1/organizations/{orgId}/agents/{deviceId}/mcp-tool-policy", { params: { path: { orgId, deviceId } }, body: { rules } }); setBusy(false); if (result.error || !result.data) { setError("Could not save the MCP tool policy. Refresh inventory and try again."); return; } setPolicy({ ok: true, data: result.data as Policy }); };
  return <div data-testid="agent-mcp-tool-policy" className="text-xs text-slate-300"><p className="text-slate-500">Default deny. Only checked tools may pass through the agent’s explicit local MCP proxy; direct upstream use is not protected.</p>{!canManage ? <p role="status" className="mt-2 text-slate-500">You do not have permission to view or change the MCP tool policy.</p> : policy === null ? <p role="status" className="mt-2 text-slate-500">Loading MCP tool policy…</p> : !policy.ok ? <><p role="alert" className="mt-2 text-danger">MCP tool policy could not be loaded: {policy.error}</p><Button size="sm" variant="ghost" className="mt-2" onClick={loadPolicy}>Retry</Button></> : <>{policy.data ? <p className="mt-1 text-slate-500">Current version {policy.data.version} · based on inventory observed {policy.data.inventory_observed_at}.</p> : <p className="mt-1 text-slate-500">No policy yet: the local proxy denies every tool.</p>}{tools.length === 0 ? <p className="mt-2 text-slate-500">No observed tools are available to allow.</p> : <div className="mt-2 grid gap-2">{tools.map((tool) => { const id = key(tool); const control = controls[id] ?? { rate: "", stepUp: false, constraints: "" }; return <div key={id}><label className="flex items-center gap-2"><input type="checkbox" checked={selected.has(id)} disabled={busy} onChange={(event) => setSelected((previous) => { const next = new Set(previous); if (event.target.checked) next.add(id); else next.delete(id); return next; })} /><span>{tool.server_name} · <span className="font-mono">{tool.tool_name}</span></span></label>{selected.has(id) && <div className="ml-6 mt-1 grid gap-1 sm:grid-cols-3"><Input aria-label={`Rate limit for ${tool.tool_name}`} placeholder="calls/min" value={control.rate} disabled={busy} onChange={(event) => setControls((old) => ({ ...old, [id]: { ...control, rate: event.target.value } }))} /><label className="flex items-center gap-1"><input type="checkbox" checked={control.stepUp} disabled={busy} onChange={(event) => setControls((old) => ({ ...old, [id]: { ...control, stepUp: event.target.checked } }))} />Step-up approval</label><textarea aria-label={`Argument constraints for ${tool.tool_name}`} className="min-h-10 rounded border border-slate-700 bg-surface px-2 py-1 font-mono" placeholder='{"required":[]}' value={control.constraints} disabled={busy} onChange={(event) => setControls((old) => ({ ...old, [id]: { ...control, constraints: event.target.value } }))} /></div>}</div>; })}</div>}<Button className="mt-3" disabled={busy || tools.length === 0} onClick={() => void save()}>{busy ? "Saving…" : "Save tool policy"}</Button></>}{error && <p role="alert" className="mt-2 text-danger">{error}</p>}</div>;
}

export function AgentMCPOAuthPanel({ orgId, deviceId, inventory, canManage }: { orgId: string; deviceId: string; inventory: Inventory; canManage: boolean }) {
  const discovered = (inventory.snapshot.oauth_discovery as { servers?: Array<{ endpoint?: string; status?: string; protected_resource?: string; authorization_servers?: string[]; scopes_supported?: string[] }> } | undefined)?.servers ?? []; const protectedServer = discovered.find((server) => server.status === "protected"); const [clientId, setClientId] = useState(""); const [clientSecret, setClientSecret] = useState(""); const [scopes, setScopes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [connections, setConnections] = useState<Loaded<OAuthConnection[]> | null>(null);
  const loadConnections = () => { if (!canManage) { setConnections(null); return; } setConnections(null); void loadOne(() => api.GET("/api/v1/organizations/{orgId}/agents/{deviceId}/mcp-oauth-connections", { params: { path: { orgId, deviceId } } })).then((result) => setConnections(result as Loaded<OAuthConnection[]>)); };
  useEffect(loadConnections, [orgId, deviceId, canManage]);
  if (!protectedServer) return null; const connected = connections?.ok && connections.data.find((connection) => connection.endpoint === protectedServer.endpoint && connection.state === "connected"); const start = async () => { if (!canManage || !protectedServer.endpoint || !protectedServer.protected_resource || !protectedServer.authorization_servers?.[0]) return; setBusy(true); setError(null); const submittedSecret = clientSecret; setClientSecret(""); const result = await api.POST("/api/v1/organizations/{orgId}/agents/{deviceId}/mcp-oauth-connections", { params: { path: { orgId, deviceId } }, body: { endpoint: protectedServer.endpoint, protected_resource: protectedServer.protected_resource, issuer: protectedServer.authorization_servers[0], scopes: scopes.split(/\s+/).filter(Boolean), client_id: clientId, ...(submittedSecret ? { client_secret: submittedSecret } : {}) } }); setBusy(false); if (result.error || !result.data) { setError("Could not start MCP OAuth consent. Confirm the registered client and issuer metadata."); return; } window.location.assign((result.data as { authorization_url: string }).authorization_url); };
  return <div data-testid="agent-mcp-oauth" className="text-xs text-slate-300"><p className="text-slate-500">Protected resource {protectedServer.protected_resource} · issuer {protectedServer.authorization_servers?.[0]}. Tokens and client secrets are never shown here or sent to the agent.</p>{!canManage ? <p role="status" className="mt-2 text-slate-500">You do not have permission to manage MCP OAuth connections.</p> : connections === null ? <p role="status" className="mt-2 text-slate-500">Loading MCP OAuth connections…</p> : !connections.ok ? <><p role="alert" className="mt-2 text-danger">MCP OAuth connections could not be loaded: {connections.error}</p><Button size="sm" variant="ghost" className="mt-2" onClick={loadConnections}>Retry</Button></> : <>{connections.data.map((connection) => <div key={connection.id} className="mt-2 text-slate-400">{connection.endpoint} · {connection.state}{connection.token_expires_at ? ` · expires ${connection.token_expires_at}` : ""}</div>)}{connected ? <p role="status" className="mt-2 text-success">Connected. Re-consent is not available here.</p> : <div className="mt-3 grid gap-2 sm:grid-cols-2"><Field label="Client ID"><Input value={clientId} onChange={(event) => setClientId(event.target.value)} /></Field><Field label="Client secret (optional)"><Input type="password" autoComplete="new-password" value={clientSecret} onChange={(event) => setClientSecret(event.target.value)} /></Field><Field label="Requested scopes"><Input placeholder={(protectedServer.scopes_supported ?? []).join(" ")} value={scopes} onChange={(event) => setScopes(event.target.value)} /></Field><div className="flex items-end"><Button disabled={busy || !clientId || !scopes} onClick={() => void start()}>{busy ? "Starting consent…" : "Continue to consent"}</Button></div></div>}</>}{error && <p role="alert" className="mt-2 text-danger">{error}</p>}</div>;
}
