import { useCallback, useEffect, useMemo, useState } from "react";
import { api, apiErrorMessage, type AlertDelivery, type AlertDestination, type AlertDestinationKind, type AlertEventKey, type AlertingSetting } from "../lib/api";
import { Badge, Button, Card, EmptyState, ErrorText, Field, Input, Loading, Modal, Select, Switch } from "./ui";

const labels: Record<AlertEventKey,string> = {
  "agent.offline":"Agent offline","agent.denial_spike":"Agent denial spike","agent.access_expiring":"Agent access expiring","agent.rotation_failed":"Agent rotation failed","agent.configuration_drift":"Agent configuration drift",
  "gateway.offline":"Gateway offline","gateway.policy_degraded":"Gateway policy degraded","site.link_down":"Site link down","device.offline":"Device offline","device.posture_blocked":"Device posture blocked",
  "kubernetes.connector_degraded":"Connector degraded","kubernetes.inventory_stale":"Inventory stale","kubernetes.service_unavailable":"Service unavailable",
};
const groups:Array<{label:string;keys:AlertEventKey[]}>=[
  {label:"Gateways & Sites",keys:["gateway.offline","gateway.policy_degraded","site.link_down"]},
  {label:"Devices",keys:["device.offline","device.posture_blocked"]},
  {label:"Kubernetes",keys:["kubernetes.connector_degraded","kubernetes.inventory_stale","kubernetes.service_unavailable"]},
  {label:"AI agents",keys:["agent.offline","agent.denial_spike","agent.access_expiring","agent.rotation_failed","agent.configuration_drift"]},
];
const kinds:Record<AlertDestinationKind,string>={webhook:"Webhook",slack:"Slack",teams:"Microsoft Teams",pagerduty:"PagerDuty",opsgenie:"Opsgenie",discord:"Discord",google_chat:"Google Chat",email:"Email"};
const endpointMeta=(kind:AlertDestinationKind)=>kind==="email"?["Recipient","oncall@example.com","email"]:kind==="pagerduty"?["Routing key","Paste PagerDuty routing key","password"]:kind==="opsgenie"?["API key","Paste Opsgenie API key","password"]:["Endpoint","https://alerts.example.com/tunnex","url"];

export function AlertManagement({orgId,canEdit,canAllowPrivate}:{orgId:string;canEdit:boolean;canAllowPrivate:boolean}) {
  const [setting,setSetting]=useState<AlertingSetting|null>(null),[routes,setRoutes]=useState<AlertDestination[]|null>(null),[deliveries,setDeliveries]=useState<AlertDelivery[]|null>(null);
  const [subs,setSubs]=useState<Record<string,AlertEventKey[]>>({}),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false);
  const load=useCallback(async()=>{
    setError(null);
    const [s,r,d]=await Promise.all([
      api.GET("/api/v1/organizations/{orgId}/alerting-settings",{params:{path:{orgId}}}),
      api.GET("/api/v1/organizations/{orgId}/alert-destinations",{params:{path:{orgId}}}),
      api.GET("/api/v1/organizations/{orgId}/alert-deliveries",{params:{path:{orgId}}}),
    ]);
    if(s.error||r.error||d.error){setError("Could not load the alerting workspace.");return;}
    setSetting(s.data??null);const active=(r.data??[]).filter(x=>!x.archived);setRoutes(active);setDeliveries(d.data??[]);
    const pairs=await Promise.all(active.map(async route=>{const res=await api.GET("/api/v1/organizations/{orgId}/alert-destinations/{destinationId}/subscriptions",{params:{path:{orgId,destinationId:route.id}}});return [route.id,res.data??[]] as const;}));setSubs(Object.fromEntries(pairs));
  },[orgId]);
  useEffect(()=>{void load();},[load]);
  const signalCount=useMemo(()=>new Set(Object.values(subs).flat()).size,[subs]);
  async function toggleDelivery(){if(!setting)return;setBusy(true);setError(null);const res=await api.PUT("/api/v1/organizations/{orgId}/alerting-settings",{params:{path:{orgId}},body:{enabled:!setting.enabled}});if(res.error)setError(apiErrorMessage(res.error,"Could not update alert delivery."));else setSetting(res.data??{...setting,enabled:!setting.enabled});setBusy(false);}
  async function toggleSignal(id:string,key:AlertEventKey){const current=subs[id]??[],on=current.includes(key);setBusy(true);setError(null);const res=on?await api.DELETE("/api/v1/organizations/{orgId}/alert-destinations/{destinationId}/subscriptions/{eventKey}",{params:{path:{orgId,destinationId:id,eventKey:key}}}):await api.POST("/api/v1/organizations/{orgId}/alert-destinations/{destinationId}/subscriptions",{params:{path:{orgId,destinationId:id}},body:{event_key:key}});if(res.error)setError(apiErrorMessage(res.error,"Could not update subscribed signals."));else setSubs(all=>({...all,[id]:on?current.filter(x=>x!==key):[...current,key]}));setBusy(false);}
  async function test(route:AlertDestination){setBusy(true);setError(null);setNotice(null);const res=await api.POST("/api/v1/organizations/{orgId}/alert-destinations/{destinationId}/test",{params:{path:{orgId,destinationId:route.id}}});if(res.data?.delivered)setNotice(`Test delivered to ${route.name}.`);else setError(`Test failed for ${route.name}: ${res.data?.failure_code??"delivery failed"}.`);setBusy(false);await load();}
  async function archive(route:AlertDestination){if(!window.confirm(`Archive ${route.name}? It will stop receiving alerts.`))return;setBusy(true);const res=await api.DELETE("/api/v1/organizations/{orgId}/alert-destinations/{destinationId}",{params:{path:{orgId,destinationId:route.id}}});if(res.error)setError(apiErrorMessage(res.error,"Could not archive the routing policy."));else await load();setBusy(false);}
  if(!setting||!routes||!deliveries)return error?<Card><ErrorText>{error}</ErrorText><Button className="mt-3" variant="ghost" onClick={()=>void load()}>Retry</Button></Card>:<Loading label="Loading alert management..."/>;
  const failed=deliveries.filter(x=>x.state==="failed").length;
  return <div className="space-y-5" data-testid="alert-management">
    <Card className="overflow-hidden p-0"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><h2 className="text-section font-semibold text-ink-heading">Alert delivery</h2><Badge tone={setting.enabled?"ok":"neutral"}>{setting.enabled?"Enabled":"Paused"}</Badge></div><p className="mt-1 text-cell text-ink-tertiary">Route existing product signals to the response channels your team already uses.</p></div><Switch label="Alert delivery" checked={setting.enabled} disabled={!canEdit||busy} onChange={()=>void toggleDelivery()}/></div><div className="grid grid-cols-3 divide-x divide-white/10 border-t border-white/10">{[[routes.length,"Routes"],[signalCount,"Signals covered"],[failed,"Failed deliveries"]].map(([value,label])=><div key={label} className="px-5 py-3"><div className={`font-sans text-stat ${label==="Failed deliveries"&&value?"text-danger":"text-ink-heading"}`}>{value}</div><div className="text-xs text-ink-tertiary">{label}</div></div>)}</div></Card>
    {error?<ErrorText>{error}</ErrorText>:null}{notice?<p className="text-cell text-success" role="status">{notice}</p>:null}
    <section aria-labelledby="routes-heading"><div className="mb-3 flex items-end justify-between gap-4"><div><h2 id="routes-heading" className="text-section font-semibold text-ink-heading">Routing policies</h2><p className="mt-1 text-cell text-ink-tertiary">Channel, severity, cooldown, and subscribed signals in one reusable policy.</p></div><Button disabled={!canEdit} onClick={()=>setCreating(true)}>New routing policy</Button></div>
      {routes.length===0?<Card><EmptyState>No routing policies yet. Create one to connect alerts to a response channel.</EmptyState></Card>:<Card className="overflow-hidden p-0">{routes.map((route,index)=>{const selected=subs[route.id]??[];return <details key={route.id} className={index?"border-t border-white/10":""}><summary className="flex cursor-pointer list-none items-center gap-4 px-5 py-4 hover:bg-white/[0.025]"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-ink-heading">{route.name}</span><Badge tone="neutral">{kinds[route.kind]}</Badge><Badge tone={selected.length?"ok":"warn"}>{selected.length} signal{selected.length===1?"":"s"}</Badge></div><p className="mt-1 truncate text-badge text-ink-tertiary">{route.endpoint_host} / {route.severity_floor}+ / {Math.round(route.cooldown_seconds/60)} min cooldown</p></div><span aria-hidden="true" className="text-ink-tertiary">v</span></summary><div className="border-t border-white/10 bg-black/10 px-5 py-4"><div className="grid gap-4 lg:grid-cols-4">{groups.map(group=><fieldset key={group.label}><legend className="mb-2 text-xs font-medium text-ink-tertiary">{group.label}</legend><div className="space-y-2">{group.keys.map(key=><label key={key} className="flex items-start gap-2 text-cell text-ink-secondary"><input className="mt-0.5" type="checkbox" checked={selected.includes(key)} disabled={!canEdit||busy} onChange={()=>void toggleSignal(route.id,key)}/><span>{labels[key]}</span></label>)}</div></fieldset>)}</div><div className="mt-4 flex gap-2 border-t border-white/10 pt-4"><Button variant="ghost" disabled={!canEdit||busy} onClick={()=>void test(route)}>Send test</Button><Button variant="danger" disabled={!canEdit||busy} onClick={()=>void archive(route)}>Archive</Button></div></div></details>;})}</Card>}</section>
    <section aria-labelledby="delivery-heading"><div className="mb-3"><h2 id="delivery-heading" className="text-section font-semibold text-ink-heading">Delivery activity</h2><p className="mt-1 text-cell text-ink-tertiary">Recent outcomes; secrets and payload bodies are never displayed.</p></div><Card className="overflow-hidden p-0">{deliveries.length===0?<EmptyState>No delivery attempts yet.</EmptyState>:deliveries.slice(0,12).map((d,i)=><div key={d.id} className={`grid gap-2 px-5 py-3 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center ${i?"border-t border-white/10":""}`}><div><div className="text-cell font-medium text-ink-heading">{labels[d.event_key]}</div><div className="text-badge text-ink-tertiary">{d.severity} / attempt {d.attempts}</div></div><Badge tone={d.state==="sent"?"ok":d.state==="failed"?"danger":"warn"}>{d.state}</Badge><span className="text-badge text-ink-tertiary">{d.last_error||"No reported error"}</span></div>)}</Card></section>
    {creating?<CreateRoute orgId={orgId} canAllowPrivate={canAllowPrivate} onDismiss={()=>setCreating(false)} onCreated={async()=>{setCreating(false);await load();}}/>:null}
  </div>;
}

function CreateRoute({orgId,canAllowPrivate,onDismiss,onCreated}:{orgId:string;canAllowPrivate:boolean;onDismiss:()=>void;onCreated:()=>Promise<void>}) {
  const [kind,setKind]=useState<AlertDestinationKind>("webhook"),[name,setName]=useState(""),[endpoint,setEndpoint]=useState(""),[severity,setSeverity]=useState<"info"|"warning"|"critical">("warning"),[cooldown,setCooldown]=useState("900"),[allowPrivate,setAllowPrivate]=useState(false),[events,setEvents]=useState<AlertEventKey[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),meta=endpointMeta(kind);
  const toggle=(key:AlertEventKey)=>setEvents(current=>current.includes(key)?current.filter(x=>x!==key):[...current,key]);
  async function create(){const seconds=Number(cooldown);if(!name.trim()||!endpoint.trim()||!events.length||!Number.isInteger(seconds)||seconds<60||seconds>86400){setError("Add a name, destination, at least one signal, and a cooldown from 60 seconds to 24 hours.");return;}setBusy(true);setError(null);const res=await api.POST("/api/v1/organizations/{orgId}/alert-destinations",{params:{path:{orgId}},body:{kind,name:name.trim(),endpoint:endpoint.trim(),allow_private:canAllowPrivate&&allowPrivate,severity_floor:severity,cooldown_seconds:seconds}});if(res.error||!res.data){setBusy(false);setError(apiErrorMessage(res.error,"Could not create the routing policy."));return;}for(const key of events){const sub=await api.POST("/api/v1/organizations/{orgId}/alert-destinations/{destinationId}/subscriptions",{params:{path:{orgId,destinationId:res.data.id}},body:{event_key:key}});if(sub.error){setError("The route was created, but not every signal could be subscribed.");break;}}setBusy(false);await onCreated();}
  return <Modal title="New routing policy" size="wide" onDismiss={onDismiss} actions={<><Button variant="ghost" onClick={onDismiss}>Cancel</Button><Button disabled={busy} onClick={()=>void create()}>{busy?"Creating...":"Create policy"}</Button></>}><div className="alert-route-builder"><div className="space-y-4"><div><h3 className="text-cell font-semibold text-ink-heading">Destination</h3><p className="mt-1 text-badge text-ink-tertiary">Where matching signals should be delivered.</p></div><Field label="Policy name"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Platform on-call"/></Field><Field label="Channel"><Select value={kind} onChange={e=>setKind(e.target.value as AlertDestinationKind)}>{(Object.keys(kinds) as AlertDestinationKind[]).map(value=><option key={value} value={value}>{kinds[value]}</option>)}</Select></Field><Field label={meta[0]}><Input type={meta[2]} value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder={meta[1]}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Minimum severity"><Select value={severity} onChange={e=>setSeverity(e.target.value as typeof severity)}><option value="info">Info+</option><option value="warning">Warning+</option><option value="critical">Critical only</option></Select></Field><Field label="Cooldown (seconds)"><Input type="number" min="60" max="86400" value={cooldown} onChange={e=>setCooldown(e.target.value)}/></Field></div>{canAllowPrivate?<label className="flex items-center gap-2 text-cell text-ink-secondary"><input type="checkbox" checked={allowPrivate} onChange={e=>setAllowPrivate(e.target.checked)}/>Allow private-network destination</label>:null}</div><div><h3 className="text-cell font-semibold text-ink-heading">Signals</h3><p className="mt-1 text-badge text-ink-tertiary">Any selected existing condition can trigger this policy.</p><div className="alert-signal-groups">{groups.map(group=><fieldset key={group.label} className="alert-signal-group"><legend className="alert-signal-legend">{group.label}</legend><div className="space-y-2">{group.keys.map(key=><label key={key} className="flex items-start gap-2 text-cell text-ink-secondary"><input className="mt-0.5" type="checkbox" checked={events.includes(key)} onChange={()=>toggle(key)}/><span>{labels[key]}</span></label>)}</div></fieldset>)}</div></div></div>{error?<div className="mt-4"><ErrorText>{error}</ErrorText></div>:null}</Modal>;
}
