import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { beamRoomsApi, beamScreenshotURL, type BeamFeedback as Feedback, type BeamFeedbackInput, type BeamNotification } from "../lib/beam-rooms";
import { beamIsTerminal, type BeamPage, type BeamShare } from "../lib/beam";
import { useBeamClock } from "../lib/beam-clock";
import { prepareBeamScreenshot } from "../lib/beam-screenshot";
import { Button, ErrorText, Field, Loading, Modal } from "./ui";
import { Pagination } from "./BeamRooms";
import { Icon } from "./Icon";
import AppAccessEmptyState from "./AppAccessEmptyState";
export function BeamFeedback({ orgId, share, uncertain = false }: { orgId: string; share: BeamShare; uncertain?: boolean }) {
  const [data, setData] = useState<BeamPage<Feedback> | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [reload, setReload] = useState(0); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(20);
  const [body, setBody] = useState(""); const [status, setStatus] = useState<BeamFeedbackInput["status"]>("comment"); const [screenshot, setScreenshot] = useState(""); const [reading, setReading] = useState(false); const [busy, setBusy] = useState(false); const [writeUncertain, setWriteUncertain] = useState(false);
  const clock = useBeamClock();
  const [, tick] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => tick(n => n + 1), 1000); return () => window.clearInterval(timer); }, []);
  const alive = useRef(true); const lock = useRef(false); const upload = useRef(0); const fileInput = useRef<HTMLInputElement | null>(null);
  useEffect(() => { alive.current = true; return () => { alive.current = false; upload.current += 1; }; }, []);
  useEffect(() => { let current = true; setData(null); setError(""); if (uncertain) return; void beamRoomsApi.feedback(orgId, share.id, page * pageSize, pageSize).then(result => { if (!current) return; if (result.ok) { clock.synchronize(result.data.server_time ?? result.server_time); setData(result.data); setWriteUncertain(false); } else setError(result.error); }); return () => { current = false; }; }, [orgId, share.id, share.authority_version, share.state, uncertain, reload, page, pageSize]);
  const canWrite = Boolean(data) && !beamIsTerminal(share, clock.now()) && !uncertain && !writeUncertain;
  async function attachment(file?: File) {
    const sequence = ++upload.current; setScreenshot(""); setError(""); setReading(false); if (!file) return;
    setReading(true);
    try { const raw = await prepareBeamScreenshot(file); if (alive.current && upload.current === sequence) { setScreenshot(raw); setReading(false); } }
    catch (error) { if (alive.current && upload.current === sequence) { setReading(false); setError(error instanceof Error ? error.message : "Could not prepare the screenshot. Choose the file again."); if (fileInput.current) fileInput.current.value = ""; } }
  }
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!canWrite || lock.current || reading || (!body.trim() && status === "comment" && !screenshot)) return;
    lock.current = true; setBusy(true); setError(""); setNotice("");
    try { const result = await beamRoomsApi.addFeedback(orgId, share.id, { body: body.trim(), status, ...(screenshot ? { screenshot_base64: screenshot } : {}) }); if (!alive.current) return;
      if (result.ok) { setBody(""); setScreenshot(""); setStatus("comment"); if (fileInput.current) fileInput.current.value = ""; setNotice("Feedback shared with this preview's participants."); setPage(0); setReload(n => n + 1); }
      else { setError(`${result.error} Refresh feedback before submitting again; your draft is still shown.`); setWriteUncertain(true); }
    } finally { lock.current = false; if (alive.current) setBusy(false); }
  }
  return <section className="beam-feedback beam-section space-y-4"><div className="beam-section-heading"><h2 className="font-semibold">Review feedback</h2><Button variant="ghost" disabled={busy} onClick={() => setReload(n => n + 1)}>Refresh feedback</Button></div><ErrorText>{error}</ErrorText>{notice && <p role="status">{notice}</p>}
    {uncertain ? <p role="status">Refresh the share to check current feedback access.</p> : !data ? !error && <Loading label="Loading review feedback…" /> : !data.items.length ? <AppAccessEmptyState title="No feedback yet" description="Open the preview and share your review here." /> : <ul className="beam-comment-list" aria-label="Review comments">{data.items.map(item => { const image = beamScreenshotURL(orgId, share.id, item); return <li key={item.id} className="space-y-2 border-t border-line pt-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium text-sm">{item.author_name || "Participant"}</span><span className="beam-status">{item.status === "approved" ? "Approved" : item.status === "changes_requested" ? "Changes requested" : "Comment"}</span></div>{item.body && <p className="whitespace-pre-wrap text-sm">{item.body}</p>}{image && <a href={image} target="_blank" rel="noopener noreferrer" className="text-brand text-sm">View screenshot from {item.author_name || "participant"}</a>}<p className="text-xs text-ink-secondary">{new Date(item.created_at).toLocaleString()}</p></li>; })}</ul>}
    {data && <Pagination page={page} count={data.items.length} limit={pageSize} label="comments" onChange={setPage} onPageSizeChange={size => { setPageSize(size); setPage(0); }} />}
    {canWrite ? <form onSubmit={event => void submit(event)} className="space-y-3 border-t border-line pt-4"><Field label="Review decision"><select value={status} disabled={busy} onChange={event => setStatus(event.target.value as BeamFeedbackInput["status"])} className="rounded border border-line bg-surface p-2"><option value="comment">Comment</option><option value="approved">Approved</option><option value="changes_requested">Changes requested</option></select></Field><Field label="Your feedback"><textarea maxLength={4000} rows={4} value={body} disabled={busy} onChange={event => setBody(event.target.value)} className="w-full rounded border border-line bg-surface p-3" placeholder="What worked, or what should change?" /></Field><Field label="Screenshot (optional)"><input ref={fileInput} type="file" accept="image/png,image/jpeg" disabled={busy} onChange={event => void attachment(event.target.files?.[0])} /></Field><p className="text-xs text-ink-secondary">PNG or JPEG, up to 10 MB. Large screenshots are resized for review. Check that your screenshot does not include secrets or personal information.</p>{screenshot && <Button type="button" variant="ghost" disabled={busy} onClick={() => { upload.current += 1; setScreenshot(""); if (fileInput.current) fileInput.current.value = ""; }}>Remove screenshot</Button>}<Button type="submit" disabled={busy || reading || (!body.trim() && status === "comment" && !screenshot)}>{busy ? "Sending…" : "Send feedback"}</Button></form> : <p className="text-sm text-ink-secondary">{writeUncertain ? "Refresh feedback to check the last submission before trying again." : "Feedback can be added while this preview is available to your account."}</p>}
  </section>;
}
export function BeamNotifications({ orgId }: { orgId: string }) {
  const [open, setOpen] = useState(false); const [data, setData] = useState<BeamPage<BeamNotification> | null>(null); const [error, setError] = useState(""); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(20); const [reload, setReload] = useState(0);
  useEffect(() => { if (!open) return; let current = true; setData(null); setError(""); void beamRoomsApi.notifications(orgId, page * pageSize, pageSize).then(result => { if (!current) return; if (result.ok) setData(result.data); else setError(result.error); }); return () => { current = false; }; }, [orgId, open, page, pageSize, reload]);
  useEffect(() => { if (!open) return; const poll = window.setInterval(() => setReload(n => n + 1), 30000); const focus = () => setReload(n => n + 1); window.addEventListener("focus", focus); return () => { window.clearInterval(poll); window.removeEventListener("focus", focus); }; }, [open]);
  return <section aria-label="Preview updates" className="beam-updates"><Button variant="ghost" aria-expanded={open} onClick={() => setOpen(value => !value)}><Icon name="bell" size={15} />{open ? "Hide preview updates" : "Preview updates"}</Button>{open && <Modal placement="right" size="wide" title="Preview updates" showClose onDismiss={() => setOpen(false)}><div className="space-y-4"><Button variant="ghost" onClick={() => setReload(n => n + 1)}>Refresh updates</Button><p className="text-sm text-ink-secondary">Preview readiness, approaching expiry and review feedback for shares you can currently access.</p>{error ? <><ErrorText>{error}</ErrorText><Button onClick={() => setReload(n => n + 1)}>Retry preview updates</Button></> : !data ? <Loading label="Loading preview updates…" /> : !data.items.length ? <AppAccessEmptyState title="No current preview updates." description="Readiness, expiry and feedback updates appear here." /> : <ul className="space-y-3">{data.items.map(item => <li key={item.id}><Link to={`/beam/shares/${encodeURIComponent(item.share_id)}`} className="text-brand text-sm">{item.title}</Link><p className="text-xs text-ink-secondary">{new Date(item.created_at).toLocaleString()}</p></li>)}</ul>}{data && <Pagination page={page} count={data.items.length} limit={pageSize} label="updates" onChange={setPage} onPageSizeChange={size => { setPageSize(size); setPage(0); }} />}</div></Modal>}</section>;
}
