import {useEffect,useRef,useState,type MutableRefObject} from "react";
// The upstream browser client has no bundled TypeScript declarations.
// @ts-expect-error untyped upstream module
import Guacamole from "guacamole-common-js";
import tunnexWordmark from "../assets/tunnex-wordmark.svg";
import {api,apiErrorMessage} from "../lib/api";
import {Button,Card,ErrorText} from "./ui";
import type {components} from "@tunnex/shared";
type Session=components["schemas"]["ServerAccessSession"];
export function BrowserRdp({orgId,session,onClose,passwordRef,clipboardPolicy="off"}:{clipboardPolicy?:string;orgId:string;session:Session;onClose:()=>void;passwordRef:MutableRefObject<string>}){
 const canPaste=clipboardPolicy==="paste"||clipboardPolicy==="both",canCopy=clipboardPolicy==="copy"||clipboardPolicy==="both";
 const [clipboardPanel,setClipboardPanel]=useState(false),[pasteText,setPasteText]=useState(""),[remoteText,setRemoteText]=useState(""),[clipboardMessage,setClipboardMessage]=useState("");
 const paste=useRef<(text:string)=>void>(()=>{});
 async function readClipboard(){setClipboardPanel(true);setClipboardMessage("");try{const text=await navigator.clipboard.readText();if(new TextEncoder().encode(text).length>8192){setClipboardMessage("Text exceeds 8 KB.");return}setPasteText(text)}catch{setClipboardMessage("Paste text below, then send it to Windows.")}}
 async function copyClipboard(){try{await navigator.clipboard.writeText(remoteText);setClipboardMessage("Copied to local clipboard.")}catch{setClipboardPanel(true);setClipboardMessage("Select the Windows text below and copy it.")}}
 function sendClipboard(){const bytes=new TextEncoder().encode(pasteText);if(!bytes.length||bytes.length>8192||pasteText.includes("\0")){setClipboardMessage("Enter text up to 8 KB, without null characters.");return}paste.current(pasteText);setPasteText("");setClipboardPanel(false);setClipboardMessage("Ready to paste in Windows with Ctrl+V.");host.current?.focus()}
 const fullscreenHost=useRef<HTMLDivElement>(null);const [fullscreen,setFullscreen]=useState(false);
 useEffect(()=>{const changed=()=>setFullscreen(document.fullscreenElement===fullscreenHost.current);document.addEventListener("fullscreenchange",changed);return()=>document.removeEventListener("fullscreenchange",changed)},[]);
 async function toggleFullscreen(){try{if(document.fullscreenElement===fullscreenHost.current)await document.exitFullscreen();else await fullscreenHost.current?.requestFullscreen()}catch{setError("Full screen is unavailable in this browser.")}}
 const host=useRef<HTMLDivElement>(null),socket=useRef<WebSocket>();const started=true;const [status,setStatus]=useState("Enter your Windows password.");const [error,setError]=useState("");const secret=passwordRef;
 useEffect(()=>{if(!started||!host.current)return;let disposed=false;let dispose=()=>{};queueMicrotask(()=>{if(disposed||!host.current)return;
 const tunnel=new Guacamole.Tunnel();const parser=new Guacamole.Parser();const client=new Guacamole.Client(tunnel);const url=new URL(`/api/v1/organizations/${orgId}/server-access/sessions/${session.id}/terminal`,window.location.href);url.protocol="wss:";const ws=new WebSocket(url);socket.current=ws;
 const send=(type:string,value:string)=>{if(ws.readyState===WebSocket.OPEN){const bytes=new TextEncoder().encode(value);if(bytes.length>16384){ws.close();return};ws.send(JSON.stringify({type,data:btoa(String.fromCharCode(...bytes))}))}};
 paste.current=(text:string)=>{if(canPaste&&ws.readyState===WebSocket.OPEN)send("clipboard",text)};
 client.onclipboard=(stream:{index:number;onblob?:(blob:string)=>void;onend?:()=>void},mime:string)=>{let chunks:Uint8Array[]=[];let size=0;let rejected=!canCopy||mime!=="text/plain";setRemoteText("");stream.onblob=(blob:string)=>{try{if(rejected)throw new Error();const bytes=Uint8Array.from(atob(blob),c=>c.charCodeAt(0));size+=bytes.length;if(size>8192)throw new Error();chunks.push(bytes);client.sendAck(stream.index,"OK",0)}catch{rejected=true;chunks=[];client.sendAck(stream.index,"Clipboard text rejected",256);setClipboardMessage("Only text up to 8 KB can be copied.")}};stream.onend=()=>{if(!rejected){try{const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length}const text=new TextDecoder("utf-8",{fatal:true}).decode(bytes);if(text.includes("\0"))throw new Error();setRemoteText(text)}catch{setClipboardMessage("Unsupported clipboard text.")}}chunks=[]};};
 parser.oninstruction=(op:string,args:string[])=>tunnel.oninstruction?.(op,args);
 tunnel.connect=()=>{};tunnel.disconnect=()=>ws.close();tunnel.sendMessage=(...parts:(string|number)[])=>send("desktop",parts.map(p=>`${Array.from(String(p)).length}.${p}`).join(",")+";");
 client.onerror=(failure:{code:number;message:string})=>{setError(failure.message.startsWith("SSL/TLS connection failed")?"Windows certificate verification failed. Verify the server fingerprint.":failure.message.startsWith("Authentication failure")?"Windows sign-in failed. Check your account and password.":`Windows desktop connection failed (code ${failure.code}).`)};
 host.current.replaceChildren(client.getDisplay().getElement());client.connect();
 ws.onopen=()=>{send("credentials",JSON.stringify({account:session.account,password:secret.current}));secret.current="";tunnel.setState(Guacamole.Tunnel.State.OPEN);if(host.current&&host.current.clientWidth>0)client.sendSize(Math.min(4096,Math.max(640,host.current.clientWidth)),Math.min(4096,Math.max(480,host.current.clientHeight)));setStatus("Connecting to Windows…")};
 const decoder=new TextDecoder();ws.onmessage=e=>{try{const f=JSON.parse(e.data);if(f.type!=="output")throw new Error();parser.receive(decoder.decode(Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)),{stream:true}));setStatus("Connected")}catch(error){setError("Desktop rendering failed. Reconnect to try again.");ws.close()}};
 ws.onclose=()=>{secret.current="";setRemoteText("");setPasteText("");setStatus("Desktop session ended.");tunnel.setState(Guacamole.Tunnel.State.CLOSED)};ws.onerror=()=>setError("Desktop connection failed. Check the session result.");
 const keyboard=new Guacamole.Keyboard(host.current);keyboard.onkeydown=(key:number)=>{client.sendKeyEvent(1,key);return false};keyboard.onkeyup=(key:number)=>client.sendKeyEvent(0,key);
 // Viewport coordinates include scrolling ancestors which Guacamole's offset-parent calculation misses.
 const displayElement=client.getDisplay().getElement();let pointer={x:0,y:0};
 const trackPointer=(event:MouseEvent)=>{const rect=displayElement.getBoundingClientRect();const display=client.getDisplay();pointer={x:Math.max(0,Math.min(display.getWidth()-1,(event.clientX-rect.left)/display.getScale())),y:Math.max(0,Math.min(display.getHeight()-1,(event.clientY-rect.top)/display.getScale()))};if(event.type==="mousedown")host.current?.focus()};
 const pointerEvents=["mousemove","mousedown","mouseup","wheel"] as const;pointerEvents.forEach(type=>displayElement.addEventListener(type,trackPointer,true));
 const mouse=new Guacamole.Mouse(displayElement);mouse.onmousedown=mouse.onmouseup=mouse.onmousemove=(state:{x:number;y:number;[key:string]:unknown})=>client.sendMouseState({...state,...pointer});
 const resetKeys=()=>keyboard.reset();host.current.addEventListener("blur",resetKeys);
 const observer=new ResizeObserver(()=>{if(host.current&&host.current.clientWidth>0)client.sendSize(Math.min(4096,Math.max(640,host.current.clientWidth)),Math.min(4096,Math.max(480,host.current.clientHeight)))});observer.observe(host.current);
 dispose=()=>{paste.current=()=>{};setRemoteText("");setPasteText("");secret.current="";observer.disconnect();pointerEvents.forEach(type=>displayElement.removeEventListener(type,trackPointer,true));host.current?.removeEventListener("blur",resetKeys);keyboard.reset();keyboard.onkeydown=keyboard.onkeyup=null;mouse.onmousedown=mouse.onmouseup=mouse.onmousemove=null;client.disconnect();ws.close();void api.DELETE("/api/v1/organizations/{orgId}/server-access/sessions/{sessionId}",{params:{path:{orgId,sessionId:session.id}}})};
 });return()=>{disposed=true;secret.current="";dispose()}},[started,orgId,session.id,clipboardPolicy]);
 async function close(){const r=await api.DELETE("/api/v1/organizations/{orgId}/server-access/sessions/{sessionId}",{params:{path:{orgId,sessionId:session.id}}});if(r.error){setError(apiErrorMessage(r.error,"Could not end desktop session."));return};onClose()}
 return <div ref={fullscreenHost} className={fullscreen?"h-screen overflow-auto bg-background p-4":""}><Card className="space-y-3"><h2 className="font-semibold">Windows desktop · {session.account}</h2><p role="status">{status}</p><ErrorText>{error}</ErrorText><div className="relative"><div ref={host} tabIndex={0} onMouseDown={e=>e.currentTarget.focus()} aria-label={`Windows desktop for ${session.account}`} className={fullscreen?"relative isolate h-[calc(100vh-160px)] w-full overflow-auto rounded bg-black":"relative isolate h-[720px] w-full overflow-auto rounded bg-black"}/><img src={tunnexWordmark} alt="" aria-hidden="true" draggable={false} className="pointer-events-none absolute bottom-[72px] right-6 z-10 h-auto w-24 select-none opacity-80 drop-shadow-[0_1px_3px_rgba(0,0,0,0.8)]"/></div><div className="flex gap-2"><Button variant="ghost" onClick={()=>void toggleFullscreen()}>{fullscreen?"Exit full screen":"Full screen"}</Button>{canPaste&&<Button variant="ghost" disabled={status!=="Connected"} onClick={()=>void readClipboard()}>Paste text</Button>}{canCopy&&<Button variant="ghost" disabled={status!=="Connected"||!remoteText} onClick={()=>void copyClipboard()}>Copy text</Button>}<Button variant="ghost" onClick={()=>void close()}>End desktop session</Button></div>{clipboardMessage&&<p role="status" className="text-sm text-muted-foreground">{clipboardMessage}</p>}{clipboardPanel&&<div className="space-y-2">{canPaste&&<><textarea aria-label="Text to paste into Windows" value={pasteText} onChange={e=>setPasteText(e.target.value)} className="w-full rounded border bg-background p-2" rows={4}/><Button onClick={sendClipboard}>Send to Windows</Button></>}{canCopy&&remoteText&&<textarea aria-label="Windows clipboard text" readOnly value={remoteText} className="w-full rounded border bg-background p-2" rows={4}/>}<Button variant="ghost" onClick={()=>{setClipboardPanel(false);setPasteText("")}}>Close clipboard</Button></div>}</Card></div>
}
