import type { components } from "@tunnex/shared";
import { useEffect, useState, type FormEvent } from "react";
import { api, apiErrorMessage } from "../lib/api";
import { Button, ErrorText, Field, Input, Loading, Select, SettingRow, Switch } from "./ui";

type Kind = "postgres" | "filesystem" | "s3" | "gcs" | "azure";
type Destination = {kind: Kind; enabled?:boolean; path?: string; endpoint?: string; bucket?: string; region?: string; prefix?: string; access_key_id?: string; account_name?: string};
export function RecordingStorageForm({orgId,archive=false}:{orgId:string;archive?:boolean}) {
 const route=archive?"/api/v1/organizations/{orgId}/server-access/recording-archive":"/api/v1/organizations/{orgId}/server-access/recording-storage";
 const [destination,setDestination]=useState<Destination>({kind:"postgres"});
 const [saved,setSaved]=useState<Destination>();const [configured,setConfigured]=useState(false);
 const [secret,setSecret]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 const [error,setError]=useState("");const [notice,setNotice]=useState("");const [reload,setReload]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);void api.GET(route,{params:{path:{orgId}}}).then(result=>{if(!live)return;if(result.error||!result.data){setError(apiErrorMessage(result.error,"Could not read recording storage."));return}const value=result.data;const destinationValue={...value,kind:("kind" in value?value.kind:"s3") as Kind};setDestination(destinationValue);setSaved(destinationValue);setConfigured(value.credentials_configured);setSecret("");setError("")}).catch(()=>{if(live)setError("Could not reach recording storage settings.")}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[orgId,reload,archive]);
 function change(key:keyof Destination,value:string){setDestination(previous=>({...previous,[key]:value}));setNotice("")}
 const sameDestination=saved&&["kind","path","endpoint","bucket","region","prefix","access_key_id","account_name"].every(key=>(destination[key as keyof Destination]??"")===(saved[key as keyof Destination]??""));
 const needsSecret=(destination.kind==="s3"||destination.kind==="gcs"||destination.kind==="azure")&&!(sameDestination&&configured);
 function input(){const v=destination;return {kind:v.kind,...(v.kind==="filesystem"?{path:v.path}:(v.kind==="s3"||v.kind==="gcs")?{endpoint:v.endpoint,bucket:v.bucket,region:v.region,prefix:v.prefix,access_key_id:v.access_key_id,...(secret?{secret_access_key:secret}:{})}:v.kind==="azure"?{endpoint:v.endpoint,bucket:v.bucket,prefix:v.prefix,account_name:v.account_name,...(secret?{account_key:secret}:{})}:{})}}
 function body(){const {kind,...fields}=input();return archive?{enabled:destination.enabled??false,...fields}:{kind,...fields}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const test=(e.nativeEvent as SubmitEvent).submitter?.getAttribute("data-action")==="test";setBusy(true);setError("");setNotice("");try{const result=archive?(test?await api.POST("/api/v1/organizations/{orgId}/server-access/recording-archive/test",{params:{path:{orgId}},body:body() as components["schemas"]["ServerAccessRecordingArchiveInput"]}):await api.PUT("/api/v1/organizations/{orgId}/server-access/recording-archive",{params:{path:{orgId}},body:body() as components["schemas"]["ServerAccessRecordingArchiveInput"]})):(test?await api.POST("/api/v1/organizations/{orgId}/server-access/recording-storage/test",{params:{path:{orgId}},body:input()}):await api.PUT("/api/v1/organizations/{orgId}/server-access/recording-storage",{params:{path:{orgId}},body:input()}));if(result.error||!result.data){setError(apiErrorMessage(result.error,test?"Storage test failed.":"Storage configuration could not be saved."));return}if(test){setNotice(archive?"S3 archive connection test passed. Save to use this connection for manual exports or automatic archiving.":"Storage connection test passed. Save to retain this legacy connection.")}else{setSecret("");setReload(value=>value+1);setNotice(archive?"S3 archive settings saved.":"Legacy storage connection saved. New recordings continue to use PostgreSQL.")}}catch{setError("Could not confirm the storage request. Retry after checking connectivity.")}finally{setBusy(false)}}
 return <section className="space-y-4"><div className="app-access-panel-header"><div><h3 className="font-semibold">{archive?"Optional S3 archive":"Legacy storage connections"}</h3><p>{archive?"Keep recordings in PostgreSQL during retention. At expiry, verified S3 archiving completes before PostgreSQL payload deletion. Failures retain the payload and retry.":"Retained connection settings support existing recordings and compatibility. New recordings always use PostgreSQL; use the S3 archive settings above for exports. Existing recordings retain their original destination."}</p></div></div><ErrorText>{error}</ErrorText>{notice&&<p role="status" className="app-access-notice">{notice}</p>}{loading?<Loading/>:!saved?<Button variant="ghost" onClick={()=>setReload(v=>v+1)}>Retry storage settings</Button>:<form onSubmit={submit} className="grid gap-3 sm:grid-cols-2">{archive?<div className="sm:col-span-2"><SettingRow label="Automatically archive to S3 at retention expiry" description="Controls automatic archiving at expiry only. The saved S3 connection remains available for manual Export to S3 while this is off."><Switch checked={destination.enabled??false} disabled={busy} onChange={enabled=>setDestination({...destination,enabled})}/></SettingRow></div>:<Field label="Storage provider"><Select value={destination.kind} disabled={busy} onChange={e=>{setDestination(e.target.value==="gcs"?{kind:"gcs",endpoint:"https://storage.googleapis.com",region:"auto"}:{kind:e.target.value as Kind});setSecret("");setNotice("")}}><option value="postgres">PostgreSQL (default, recommended)</option><option value="filesystem">Mounted filesystem / EFS / EBS</option><option value="s3">S3-compatible object storage</option><option value="gcs">Google Cloud Storage</option><option value="azure">Azure Blob Storage</option></Select></Field>}
 {destination.kind==="postgres"&&<p className="text-sm">PostgreSQL is the default and recommended recording destination. New recordings always store encrypted payloads in PostgreSQL. Optional providers below preserve existing recording compatibility; saving this connection does not change new captures.</p>}
 {destination.kind==="filesystem"&&<><Field label="Mounted recording directory"><Input required disabled={busy} value={destination.path??""} onChange={e=>change("path",e.target.value)} placeholder="/mnt/recordings"/></Field><p className="text-sm sm:col-span-2">Mount the filesystem, EFS or EBS volume on the control plane before configuring its absolute path. Tunnex does not provision or mount cloud storage.</p></>}
 {(destination.kind==="s3"||destination.kind==="gcs"||destination.kind==="azure")&&<><Field label="Storage endpoint"><Input required type="url" disabled={busy} value={destination.endpoint??""} onChange={e=>change("endpoint",e.target.value)}/></Field><Field label={destination.kind==="azure"?"Container":"Bucket"}><Input required disabled={busy} value={destination.bucket??""} onChange={e=>change("bucket",e.target.value)}/></Field><Field label="Object prefix"><Input disabled={busy} value={destination.prefix??""} onChange={e=>change("prefix",e.target.value)}/></Field>{destination.kind!=="azure"?<><Field label="Region"><Input required disabled={busy} value={destination.region??""} onChange={e=>change("region",e.target.value)}/></Field><Field label={destination.kind==="gcs"?"HMAC access key ID":"Access key ID"}><Input required disabled={busy} autoComplete="off" value={destination.access_key_id??""} onChange={e=>change("access_key_id",e.target.value)}/></Field></>:<Field label="Storage account name"><Input required disabled={busy} value={destination.account_name??""} onChange={e=>change("account_name",e.target.value)}/></Field>}<Field label={destination.kind==="azure"?"Storage account key":destination.kind==="gcs"?"HMAC secret access key":"Secret access key"}><Input type="password" required={needsSecret} disabled={busy} autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)}/></Field>{destination.kind==="gcs"&&<p className="text-sm sm:col-span-2">Use Google Cloud Storage HMAC credentials for the XML API endpoint.</p>}<p className="text-sm sm:col-span-2">Credentials are never returned. Leave the secret blank to retain saved credentials for the same destination; enter credentials when changing the destination.</p></>}
 <div className="flex flex-wrap gap-3 sm:col-span-2"><Button type="submit" data-action="test" variant="ghost" disabled={busy}>{archive?"Test S3 archive connection":"Test storage connection"}</Button><Button type="submit" data-action="save" disabled={busy}>{archive?"Save S3 archive settings":"Save recording storage"}</Button></div></form>}</section>
}
