import type {SandboxImageProfile} from "../lib/api";
const megabytes=(bytes:number)=>`${(bytes/1000000).toFixed(1)} MB`;
export function ImageProfileDetails({profile}:{profile?:SandboxImageProfile}){
 if(!profile)return <p className="sb-help">Image size and idle RAM: not measured.</p>;
 return <details className="sb-measurements"><summary>Image measurements · {profile.distro} · {profile.architecture}{profile.emulated?" (emulated)":""}</summary><div className="sb-help"><p>{profile.distro} · {profile.architecture}{profile.emulated?" · Emulated measurement":""}</p><dl className="sb-specs"><div><dt>Compressed download</dt><dd>{megabytes(profile.compressed_image_bytes)}</dd></div><div><dt>Unpacked image</dt><dd>{megabytes(profile.unpacked_image_bytes)}</dd></div><div><dt>Measured idle RAM</dt><dd>{megabytes(profile.idle_memory_bytes)}</dd></div></dl><p>Measured {profile.measured_at}. {profile.evidence_context}</p><p>Measurement fixture: {(profile.measurement_memory_cap_bytes/1048576).toFixed(0)} MiB RAM cap; {(profile.measurement_workspace_cap_bytes/1048576).toFixed(0)} MiB workspace cap. These are test bounds, not this workspace's limits.</p><p className="mt-3">{profile.compatibility}</p><details className="mt-3"><summary>Included tools and omissions</summary><p className="mt-2">Included: {profile.included_tools.join(", ")}</p><p>Not included: {profile.excluded_tools.join(", ")}</p></details></div></details>;
}
export function SandboxCandidateProfiles({profiles}:{profiles?:SandboxImageProfile[]}){
 if(!profiles?.length)return null;
 const groups=new Map<string,SandboxImageProfile[]>();for(const profile of profiles){groups.set(profile.name,[...(groups.get(profile.name)??[]),profile])}
 return <section className="sb-candidates" aria-label="Candidate runtime profiles"><div className="sb-section-title"><h2>Lightweight profiles in preparation</h2><span>{groups.size} profiles</span></div><details className="sb-profile-requirements"><summary>Not launchable · qualification requirements</summary><p className="sb-help">An operator must verify private networking, SSH, restart and cleanup before publication. Architecture variants are measurement details.</p></details><div className="sb-profile-list">{[...groups].map(([name,variants])=><details className="sb-profile-row" key={name}><summary><h3>{name}</h3><span>Awaiting server verification</span><span className="sb-disclosure-label">Measurements ↗</span></summary><div className="sb-profile-body">{variants.map(profile=><div key={profile.image_digest??profile.architecture}><h4>Measurements for {profile.architecture}{profile.emulated?" (emulated)":""}</h4><ImageProfileDetails profile={profile}/></div>)}</div></details>)}</div></section>;
}
