import { Link } from "react-router-dom";
import { useEffect, useRef, useState } from "react";
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import type { components } from "@tunnex/shared";
import { api, apiErrorCode, apiErrorMessage } from "../lib/api";
import { Button, Card, ErrorText } from "./ui";
import "@xterm/xterm/css/xterm.css";
import type { LocalRecording, ImportedRecording } from "../lib/recordingImport";
type Recording = components["schemas"]["ServerAccessRecording"];
type ReplayProps = {onClose:()=>void; canManage?:boolean} & ({orgId:string;sessionId:string;imported?:never} | {imported:ImportedRecording;orgId?:never;sessionId?:never});
export function TerminalReplay({orgId,sessionId,onClose,canManage=false,imported}:ReplayProps) {
 const host=useRef<HTMLDivElement>(null);const term=useRef<Terminal>();const position=useRef(0);const generation=useRef(0);
 const [downloading,setDownloading]=useState(false);
 const [exporting,setExporting]=useState(false);const [exportError,setExportError]=useState("");const [exportNotice,setExportNotice]=useState("");const [setupArchive,setSetupArchive]=useState(false);
 const [recording,setRecording]=useState<LocalRecording & Partial<Recording>>();const [error,setError]=useState("");const [playing,setPlaying]=useState(false);const [progress,setProgress]=useState(0);
 useEffect(()=>{if(imported){generation.current++;position.current=0;setProgress(0);setPlaying(false);term.current?.reset();setRecording(imported.recording);return}if(!orgId||!sessionId)return;let cancelled=false;let initial=true;const load=async()=>{try{const result=await api.GET("/api/v1/organizations/{orgId}/server-access/sessions/{sessionId}/recording",{params:{path:{orgId,sessionId},query:{metadata_only:!initial}}});if(cancelled)return;if(result.error||!result.data){setError(apiErrorMessage(result.error,"Recording access is unavailable."));setRecording(undefined);setPlaying(false);generation.current++;position.current=0;setProgress(0);term.current?.reset();return}if(initial){setRecording(result.data);initial=false}else{if(["expired","failed","disabled"].includes(result.data.status)){setPlaying(false);generation.current++;position.current=0;setProgress(0);setRecording({...result.data,events:[]});term.current?.reset()}else setRecording(previous=>previous?{...previous,...result.data,events:previous.events}:result.data)}}catch{if(!cancelled){setError("Could not verify recording access.");setRecording(undefined);setPlaying(false);generation.current++;position.current=0;setProgress(0);term.current?.reset()}}};void load();const timer=setInterval(()=>void load(),5000);return()=>{cancelled=true;clearInterval(timer)}},[orgId,sessionId,imported]);
 useEffect(()=>{let cancelled=false;let dispose=()=>{};queueMicrotask(()=>{if(cancelled||!host.current)return;const t=new Terminal({disableStdin:true,screenReaderMode:true,scrollback:2000,theme:{background:"#111827"},linkHandler:{activate:()=>{}}});t.parser?.registerOscHandler(52,()=>true);t.parser?.registerOscHandler(8,()=>true);const fit=new FitAddon();t.loadAddon(fit);t.open(host.current);fit.fit();term.current=t;dispose=()=>{generation.current++;term.current=undefined;t.dispose()}});return()=>{cancelled=true;dispose()}},[sessionId]);
 function apply(event:Recording["events"][number],token:number,done:()=>void){const terminal=term.current;if(!terminal||token!==generation.current)return;if(event.type==="output")terminal.write(Uint8Array.from(atob(event.data),c=>c.charCodeAt(0)),()=>{if(token===generation.current)done()});else{terminal.resize(event.cols,event.rows);done()}}
 useEffect(()=>{if(!playing||!recording||!term.current)return;let timer:ReturnType<typeof setTimeout>;const token=++generation.current;const advance=()=>{if(token!==generation.current)return;const event=recording.events[position.current];if(!event){setPlaying(false);return}apply(event,token,()=>{position.current++;setProgress(position.current);const next=recording.events[position.current];if(next)timer=setTimeout(advance,Math.max(0,next.millis-event.millis));else setPlaying(false)})};advance();return()=>{clearTimeout(timer)}},[playing,recording?.events]);
 function seek(count:number){setPlaying(false);const token=++generation.current;const terminal=term.current;if(!terminal)return;terminal.reset();position.current=0;setProgress(0);const events=recording?.events.slice(0,count)??[];const advance=()=>{if(token!==generation.current)return;const event=events[position.current];if(!event)return;apply(event,token,()=>{position.current++;setProgress(position.current);advance()})};setTimeout(()=>{if(token!==generation.current)return;advance()},0)}
 async function download(){if(imported||!orgId||!sessionId||downloading)return;setDownloading(true);setExportError("");try{const result=await api.GET("/api/v1/organizations/{orgId}/server-access/sessions/{sessionId}/recording/download",{params:{path:{orgId,sessionId}},parseAs:"blob"});if(result.error||!result.data){setExportError(apiErrorMessage(result.error,"Could not download this recording."));return}const url=URL.createObjectURL(result.data);const link=document.createElement("a");link.href=url;link.download=`terminal-recording-${sessionId}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setExportError("Could not download this recording. Retry after verifying access.")}finally{setDownloading(false)}}
 async function exportS3(){if(imported||!orgId||!sessionId||exporting)return;setExporting(true);setExportError("");setExportNotice("");setSetupArchive(false);try{const r=await api.POST("/api/v1/organizations/{orgId}/server-access/sessions/{sessionId}/recording/export-s3",{params:{path:{orgId,sessionId}}});if(r.error||!r.data){setExportError(apiErrorMessage(r.error,"Could not request S3 export."));setSetupArchive(["archive_not_configured","recording_archive_not_configured"].includes(apiErrorCode(r.error)??""));return}setExportNotice(r.data.status==="available"?"S3 archive is available.":"S3 export requested. PostgreSQL payload remains through retention and is deleted only after verified archiving at expiry.")}catch{setExportError("Could not confirm S3 export. Check archive status before retrying.")}finally{setExporting(false)}}
 return <Card className="space-y-3"><h2 className="font-semibold">{imported?"Imported recording":"Session recording"}</h2>{imported&&<p role="note">{imported.name} · Imported replay snapshot. Original actor, server and audit assertions are unverified. {imported.source==="encrypted-package"?"The package was uploaded for authorized decryption using this installation key. Replay is a browser snapshot; it does not restore a server session.":"JSON stays in this browser; nothing is uploaded or saved."} Closing clears this replay snapshot.</p>}<p role="status">{recording?.status??"Loading recording…"} · Output and resize only</p><ErrorText>{error}</ErrorText><ErrorText>{exportError}</ErrorText>{exportNotice&&<p role="status">{exportNotice}</p>}{recording&&!imported&&<div className="space-y-2"><p role="status">S3 archive: {recording.archive_status==="uploading"?"Archiving":recording.archive_status==="available"?"Archived":recording.archive_status??"none"}{recording.archive_retry_at?` · Retry scheduled ${new Date(recording.archive_retry_at).toLocaleString()}`:""}</p>{recording.archive_error&&<ErrorText>{recording.archive_error}</ErrorText>}<div className="flex flex-wrap gap-3">{<Button variant="ghost" disabled={exporting||["capturing","active","expired","disabled","failed"].includes(recording.status)} onClick={()=>void exportS3()}>{recording.archive_status==="failed"?"Retry export to S3":"Export to S3"}</Button>}<Button variant="ghost" disabled={downloading||["expired","failed","disabled"].includes(recording.status)} onClick={()=>void download()}>Manual download</Button>{!canManage&&setupArchive&&<p className="text-sm">Ask an administrator to configure S3 archiving.</p>}{canManage&&<Link className="text-brand" to="/browser-access/terminal?view=settings">{setupArchive?"Set up S3 archive":"Manage S3 archive"}</Link>}</div><p className="text-sm">Manual download creates portable JSON for Import recording; it does not change retention or trigger automatic deletion. A complete encrypted S3 .tunnex-recording package can be imported after original database/session deletion using the original installation key and current owner or administrator authorization. Raw chunks and manifests cannot be imported.</p></div>}<div ref={host} className="h-96 w-full min-w-0 overflow-hidden rounded bg-gray-900" aria-label="Read-only terminal recording"/>{recording&&recording.events.length>0&&<><div className="flex gap-2"><Button onClick={()=>{if(position.current>=recording.events.length)seek(0);generation.current++;setPlaying(v=>!v)}}>{playing?"Pause replay":"Play replay"}</Button><Button variant="ghost" onClick={()=>seek(0)}>Restart replay</Button></div><label className="block">Recording position <input className="w-full" type="range" min={0} max={recording.events.length} value={progress} onChange={e=>seek(Number(e.target.value))}/></label></>}<Button variant="ghost" onClick={onClose}>Close recording</Button></Card>
}
