# Dev-only override: existing licensed CP, C7 essential sandbox continuation approved 2026-09-06 IST.
# Merge with /opt/tunnex/tunnex.yml and its existing private .env, project tunnex.
# Recreate ONLY api web nginx, --no-deps --pull never. No signed-release claim.
services:
  api:
    image: 735391218823.dkr.ecr.ap-south-1.amazonaws.com/tunnex-s205-aws-20260905a/api@sha256:bf7e91ee5db09a643501dc931e8878bebc93f5d7ea1022591289962663765ad8
    pull_policy: never
    environment:
      TUNNEX_AUTO_MIGRATE: "true"
      TUNNEX_GATEWAY_CONTROL_URL: https://cp.13.206.39.40.sslip.io:8443
      TUNNEX_NODE_AGENT_IMAGE: 735391218823.dkr.ecr.ap-south-1.amazonaws.com/tunnex-s205-aws-20260905a/node-agent@sha256:7b675392c1500e4767fe4128c60e2239378296b4d1f0bd94bf36cd719a07c69e
      TUNNEX_K8S_HA_ENABLED: "true"
      TUNNEX_RELEASE_UPDATE_CHECK: "false"
      TUNNEX_RELEASE_MANIFEST_PATH: ""
      TUNNEX_RELEASE_MANIFEST_URL: ""
      TUNNEX_RELEASE_CATALOG_URL: ""
      TUNNEX_RELEASE_VERSION: 0.0.0-walk.sha3081f63a0338ed95a444ba69665ca1e8
      TUNNEX_RELEASE_SOURCE_SHA: 3081f63a0338ed95a444ba69665ca1e8de1ef42e
      TUNNEX_RELEASE_SEQUENCE: "0"
      TUNNEX_HOST_UPGRADE_REQUEST_PATH: ""
      TUNNEX_HOST_UPGRADE_STATUS_PATH: ""
  web:
    image: 735391218823.dkr.ecr.ap-south-1.amazonaws.com/tunnex-s205-aws-20260905a/web@sha256:13a89e6b7059ada45dec2e8204fb965f5cd318a91061e1be9dcc7ca9a9eb47a8
    pull_policy: never
  nginx:
    image: 735391218823.dkr.ecr.ap-south-1.amazonaws.com/tunnex-s205-aws-20260905a/nginx@sha256:cb4d45d0b348bec5028afb0fe8725298ecbf539c90a7636481decf8b164c1b78
    pull_policy: never
