// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOrgFlowSeq = `-- name: BumpOrgFlowSeq :one
UPDATE organizations SET flow_seq = flow_seq + $1::bigint
WHERE id = $2 AND deleted_at IS NULL
RETURNING flow_seq
`

type BumpOrgFlowSeqParams struct {
	N     int64     `json:"n"`
	OrgID uuid.UUID `json:"org_id"`
}

// Atomically reserve `n` seq values for an org and return the NEW high-water. The UPDATE
// takes a ROW LOCK on the org, serializing concurrent same-org ingest so two batches can
// never derive colliding seq (review #1). flow_seq lives on organizations and is NEVER swept,
// so seq is monotonic + sweep-proof (review #6). The batch's seqs are (returned-n+1)..returned.
func (q *Queries) BumpOrgFlowSeq(ctx context.Context, arg BumpOrgFlowSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpOrgFlowSeq, arg.N, arg.OrgID)
	var flow_seq int64
	err := row.Scan(&flow_seq)
	return flow_seq, err
}

const distinctAccessEventOrgs = `-- name: DistinctAccessEventOrgs :many
SELECT DISTINCT org_id FROM access_events
`

// lint:cross-org — retention housekeeping enumerates the orgs that actually HOLD events so the
// per-org row-cap sweep bounds every such org's hot-window disk use. This MUST include
// SOFT-DELETED orgs: a deleted org's event flood is exactly what the disk-guard cap must bound
// (fold-3 #3 reverted the fold-2 organizations-table enumeration, which excluded deleted orgs).
// PERF LEDGER: this is a DISTINCT scan of access_events every RetentionSweepInterval; if
// access_events scale makes the 10-min scan measurable, add a supporting index / cheaper
// enumeration (trigger, not a silent now-do-it).
func (q *Queries) DistinctAccessEventOrgs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, distinctAccessEventOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var org_id uuid.UUID
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccessEvent = `-- name: InsertAccessEvent :exec
INSERT INTO access_events (
    id, org_id, seq, node_id, occurred_at, decision, rule_id,
    src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id,
    protocol, dst_port, deny_count, window_end, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18
)
`

type InsertAccessEventParams struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	Seq           int64              `json:"seq"`
	NodeID        pgtype.UUID        `json:"node_id"`
	OccurredAt    time.Time          `json:"occurred_at"`
	Decision      string             `json:"decision"`
	RuleID        pgtype.UUID        `json:"rule_id"`
	SrcDeviceID   pgtype.UUID        `json:"src_device_id"`
	SrcUserID     pgtype.UUID        `json:"src_user_id"`
	SrcIp         string             `json:"src_ip"`
	DstIp         string             `json:"dst_ip"`
	DstResourceID pgtype.UUID        `json:"dst_resource_id"`
	DstGroupID    pgtype.UUID        `json:"dst_group_id"`
	Protocol      string             `json:"protocol"`
	DstPort       *int32             `json:"dst_port"`
	DenyCount     int32              `json:"deny_count"`
	WindowEnd     pgtype.Timestamptz `json:"window_end"`
	CreatedAt     time.Time          `json:"created_at"`
}

// The id is app-generated (uuid v7) so the SAME id identifies the row in BOTH the PG
// hot-window and the JSONL source-of-truth stream. seq comes from BumpOrgFlowSeq (a per-org
// locked counter), so it is unique by construction — this is a PLAIN insert (NO
// `ON CONFLICT DO NOTHING`): the (org_id, seq) unique index is a FAIL-LOUD backstop, so an
// impossible collision errors the batch (agent -> next-report gap) rather than SILENTLY
// dropping audit rows (review #1). No replay path re-inserts: a failed batch rolls the tx
// (and the counter bump) back, so a retry re-reserves a fresh range.
func (q *Queries) InsertAccessEvent(ctx context.Context, arg InsertAccessEventParams) error {
	_, err := q.db.Exec(ctx, insertAccessEvent,
		arg.ID,
		arg.OrgID,
		arg.Seq,
		arg.NodeID,
		arg.OccurredAt,
		arg.Decision,
		arg.RuleID,
		arg.SrcDeviceID,
		arg.SrcUserID,
		arg.SrcIp,
		arg.DstIp,
		arg.DstResourceID,
		arg.DstGroupID,
		arg.Protocol,
		arg.DstPort,
		arg.DenyCount,
		arg.WindowEnd,
		arg.CreatedAt,
	)
	return err
}

const listAccessDenies = `-- name: ListAccessDenies :many
SELECT id, org_id, seq, node_id, occurred_at, decision, rule_id, src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id, protocol, dst_port, deny_count, window_end, created_at FROM access_events
WHERE org_id = $1
  AND decision <> 'allow'
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAccessDeniesParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforeID        uuid.UUID `json:"before_id"`
	PageLimit       int32     `json:"page_limit"`
}

// The security-focused feed: deny + deny_aggregate + terminated only, same keyset shape.
func (q *Queries) ListAccessDenies(ctx context.Context, arg ListAccessDeniesParams) ([]AccessEvent, error) {
	rows, err := q.db.Query(ctx, listAccessDenies,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessEvent{}
	for rows.Next() {
		var i AccessEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Seq,
			&i.NodeID,
			&i.OccurredAt,
			&i.Decision,
			&i.RuleID,
			&i.SrcDeviceID,
			&i.SrcUserID,
			&i.SrcIp,
			&i.DstIp,
			&i.DstResourceID,
			&i.DstGroupID,
			&i.Protocol,
			&i.DstPort,
			&i.DenyCount,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessEvents = `-- name: ListAccessEvents :many
SELECT id, org_id, seq, node_id, occurred_at, decision, rule_id, src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id, protocol, dst_port, deny_count, window_end, created_at FROM access_events
WHERE org_id = $1
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAccessEventsParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforeID        uuid.UUID `json:"before_id"`
	PageLimit       int32     `json:"page_limit"`
}

// Keyset page, newest-first, scoped by org. Expanded (created_at, id) < (cursor) predicate
// (row-value form confuses sqlc's type inference for the id cursor). First page passes a
// far-future created_at + a max uuid so the whole feed is < the cursor. Uses
// access_events_org_created_id_idx.
func (q *Queries) ListAccessEvents(ctx context.Context, arg ListAccessEventsParams) ([]AccessEvent, error) {
	rows, err := q.db.Query(ctx, listAccessEvents,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessEvent{}
	for rows.Next() {
		var i AccessEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Seq,
			&i.NodeID,
			&i.OccurredAt,
			&i.Decision,
			&i.RuleID,
			&i.SrcDeviceID,
			&i.SrcUserID,
			&i.SrcIp,
			&i.DstIp,
			&i.DstResourceID,
			&i.DstGroupID,
			&i.Protocol,
			&i.DstPort,
			&i.DenyCount,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepAccessEventsByAge = `-- name: SweepAccessEventsByAge :execrows
DELETE FROM access_events WHERE created_at < $1
`

// lint:cross-org — retention housekeeping runs across ALL orgs by INGEST age (created_at,
// not the agent-clock occurred_at, so agent skew can't extend retention). The JSONL stream
// keeps the full record; PG is a bounded cache, so this delete is lossless for export.
func (q *Queries) SweepAccessEventsByAge(ctx context.Context, olderThan time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepAccessEventsByAge, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepAccessEventsOverCap = `-- name: SweepAccessEventsOverCap :execrows
DELETE FROM access_events AS target
WHERE target.org_id = $1
  AND target.id NOT IN (
    SELECT ae.id FROM access_events ae
    WHERE ae.org_id = $1
    ORDER BY ae.created_at DESC, ae.id DESC
    LIMIT $2
  )
`

type SweepAccessEventsOverCapParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	KeepNewest int32     `json:"keep_newest"`
}

// Per-org row cap: keep the newest keep_newest rows for the org, delete the rest. Protects
// the disk when one org is noisy without touching quiet orgs.
func (q *Queries) SweepAccessEventsOverCap(ctx context.Context, arg SweepAccessEventsOverCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepAccessEventsOverCap, arg.OrgID, arg.KeepNewest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
