// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_mcp_profiles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignAgentMCPProfile = `-- name: AssignAgentMCPProfile :one
INSERT INTO agent_mcp_profile_assignments (org_id, profile_id, agent_group_id)
VALUES ($1, $2, $3)
RETURNING id, org_id, profile_id, agent_group_id, assigned_at, state, ended_at, ended_by_user_id, quarantine_reason
`

type AssignAgentMCPProfileParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	ProfileID    uuid.UUID `json:"profile_id"`
	AgentGroupID uuid.UUID `json:"agent_group_id"`
}

func (q *Queries) AssignAgentMCPProfile(ctx context.Context, arg AssignAgentMCPProfileParams) (AgentMcpProfileAssignment, error) {
	row := q.db.QueryRow(ctx, assignAgentMCPProfile, arg.OrgID, arg.ProfileID, arg.AgentGroupID)
	var i AgentMcpProfileAssignment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProfileID,
		&i.AgentGroupID,
		&i.AssignedAt,
		&i.State,
		&i.EndedAt,
		&i.EndedByUserID,
		&i.QuarantineReason,
	)
	return i, err
}

const createAgentMCPProfile = `-- name: CreateAgentMCPProfile :one
INSERT INTO agent_mcp_profiles (org_id, name, endpoint)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, endpoint, created_at, updated_at, archived_at
`

type CreateAgentMCPProfileParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Name     string    `json:"name"`
	Endpoint string    `json:"endpoint"`
}

func (q *Queries) CreateAgentMCPProfile(ctx context.Context, arg CreateAgentMCPProfileParams) (AgentMcpProfile, error) {
	row := q.db.QueryRow(ctx, createAgentMCPProfile, arg.OrgID, arg.Name, arg.Endpoint)
	var i AgentMcpProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Endpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAgentMCPProfile = `-- name: GetAgentMCPProfile :one
SELECT id, org_id, name, endpoint, created_at, updated_at, archived_at FROM agent_mcp_profiles WHERE id = $1 AND org_id = $2
`

type GetAgentMCPProfileParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAgentMCPProfile(ctx context.Context, arg GetAgentMCPProfileParams) (AgentMcpProfile, error) {
	row := q.db.QueryRow(ctx, getAgentMCPProfile, arg.ID, arg.OrgID)
	var i AgentMcpProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Endpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listActiveMCPAssignmentsForDevice = `-- name: ListActiveMCPAssignmentsForDevice :many
SELECT a.id, a.org_id, a.profile_id, a.agent_group_id, p.name AS profile_name,
       p.endpoint, g.name AS group_name, a.assigned_at
FROM agent_mcp_profile_assignments a
JOIN agent_mcp_profiles p ON p.id = a.profile_id AND p.org_id = a.org_id
JOIN agent_groups g ON g.id = a.agent_group_id AND g.org_id = a.org_id
JOIN agent_group_members m ON m.org_id = a.org_id AND m.agent_group_id = a.agent_group_id
WHERE a.org_id = $1 AND m.device_id = $2 AND a.state = 'active'
ORDER BY a.assigned_at DESC, a.id DESC
`

type ListActiveMCPAssignmentsForDeviceParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	DeviceID uuid.UUID `json:"device_id"`
}

type ListActiveMCPAssignmentsForDeviceRow struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	ProfileID    uuid.UUID `json:"profile_id"`
	AgentGroupID uuid.UUID `json:"agent_group_id"`
	ProfileName  string    `json:"profile_name"`
	Endpoint     string    `json:"endpoint"`
	GroupName    string    `json:"group_name"`
	AssignedAt   time.Time `json:"assigned_at"`
}

func (q *Queries) ListActiveMCPAssignmentsForDevice(ctx context.Context, arg ListActiveMCPAssignmentsForDeviceParams) ([]ListActiveMCPAssignmentsForDeviceRow, error) {
	rows, err := q.db.Query(ctx, listActiveMCPAssignmentsForDevice, arg.OrgID, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMCPAssignmentsForDeviceRow{}
	for rows.Next() {
		var i ListActiveMCPAssignmentsForDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProfileID,
			&i.AgentGroupID,
			&i.ProfileName,
			&i.Endpoint,
			&i.GroupName,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMCPProfileAssignments = `-- name: ListAgentMCPProfileAssignments :many
SELECT a.id, a.org_id, a.profile_id, a.agent_group_id, a.assigned_at, a.state, a.ended_at, a.ended_by_user_id, a.quarantine_reason, p.name AS profile_name, p.endpoint, g.name AS group_name
FROM agent_mcp_profile_assignments a
JOIN agent_mcp_profiles p ON p.id = a.profile_id AND p.org_id = a.org_id
JOIN agent_groups g ON g.id = a.agent_group_id AND g.org_id = a.org_id
WHERE a.org_id = $1
ORDER BY a.assigned_at DESC, a.id DESC
`

type ListAgentMCPProfileAssignmentsRow struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	ProfileID        uuid.UUID          `json:"profile_id"`
	AgentGroupID     uuid.UUID          `json:"agent_group_id"`
	AssignedAt       time.Time          `json:"assigned_at"`
	State            string             `json:"state"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	EndedByUserID    pgtype.UUID        `json:"ended_by_user_id"`
	QuarantineReason *string            `json:"quarantine_reason"`
	ProfileName      string             `json:"profile_name"`
	Endpoint         string             `json:"endpoint"`
	GroupName        string             `json:"group_name"`
}

func (q *Queries) ListAgentMCPProfileAssignments(ctx context.Context, orgID uuid.UUID) ([]ListAgentMCPProfileAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAgentMCPProfileAssignments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentMCPProfileAssignmentsRow{}
	for rows.Next() {
		var i ListAgentMCPProfileAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProfileID,
			&i.AgentGroupID,
			&i.AssignedAt,
			&i.State,
			&i.EndedAt,
			&i.EndedByUserID,
			&i.QuarantineReason,
			&i.ProfileName,
			&i.Endpoint,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMCPProfiles = `-- name: ListAgentMCPProfiles :many
SELECT id, org_id, name, endpoint, created_at, updated_at, archived_at FROM agent_mcp_profiles WHERE org_id = $1 ORDER BY archived_at NULLS FIRST, lower(name), id
`

func (q *Queries) ListAgentMCPProfiles(ctx context.Context, orgID uuid.UUID) ([]AgentMcpProfile, error) {
	rows, err := q.db.Query(ctx, listAgentMCPProfiles, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMcpProfile{}
	for rows.Next() {
		var i AgentMcpProfile
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Endpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMCPProfilesForDevice = `-- name: ListAgentMCPProfilesForDevice :many
SELECT p.id, p.org_id, p.name, p.endpoint
FROM agent_mcp_profiles p
JOIN agent_mcp_profile_assignments a
  ON a.profile_id = p.id AND a.org_id = p.org_id AND a.state = 'active'
JOIN agent_group_members m
  ON m.agent_group_id = a.agent_group_id AND m.org_id = a.org_id
WHERE p.org_id = $1 AND m.device_id = $2
ORDER BY p.id
`

type ListAgentMCPProfilesForDeviceParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	DeviceID uuid.UUID `json:"device_id"`
}

type ListAgentMCPProfilesForDeviceRow struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	Name     string    `json:"name"`
	Endpoint string    `json:"endpoint"`
}

func (q *Queries) ListAgentMCPProfilesForDevice(ctx context.Context, arg ListAgentMCPProfilesForDeviceParams) ([]ListAgentMCPProfilesForDeviceRow, error) {
	rows, err := q.db.Query(ctx, listAgentMCPProfilesForDevice, arg.OrgID, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentMCPProfilesForDeviceRow{}
	for rows.Next() {
		var i ListAgentMCPProfilesForDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Endpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
