// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listActiveAgentGroupMembersForOrg = `-- name: ListActiveAgentGroupMembersForOrg :many
SELECT m.agent_group_id, m.device_id
FROM agent_group_members m
JOIN agent_groups g
  ON g.id = m.agent_group_id AND g.org_id = m.org_id
JOIN devices d
  ON d.id = m.device_id AND d.org_id = m.org_id
WHERE m.org_id = $1
  AND g.archived_at IS NULL
  AND d.kind = 'agent'
  AND d.status = 'active'
  AND d.deleted_at IS NULL
ORDER BY m.agent_group_id, m.device_id
`

type ListActiveAgentGroupMembersForOrgRow struct {
	AgentGroupID uuid.UUID `json:"agent_group_id"`
	DeviceID     uuid.UUID `json:"device_id"`
}

// Compiler input only: inactive/deleted/non-agent devices must never expand an
// agent-group source. Suspension keeps the membership row but contributes no
// source until the canonical device becomes active again.
func (q *Queries) ListActiveAgentGroupMembersForOrg(ctx context.Context, orgID uuid.UUID) ([]ListActiveAgentGroupMembersForOrgRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgentGroupMembersForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAgentGroupMembersForOrgRow{}
	for rows.Next() {
		var i ListActiveAgentGroupMembersForOrgRow
		if err := rows.Scan(&i.AgentGroupID, &i.DeviceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
