// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAlertSubscription = `-- name: AddAlertSubscription :one
INSERT INTO alert_subscriptions (org_id, destination_id, event_key)
VALUES ($1, $2, $3)
ON CONFLICT (destination_id, event_key) DO NOTHING
RETURNING org_id, destination_id, event_key, created_at
`

type AddAlertSubscriptionParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	DestinationID uuid.UUID `json:"destination_id"`
	EventKey      string    `json:"event_key"`
}

func (q *Queries) AddAlertSubscription(ctx context.Context, arg AddAlertSubscriptionParams) (AlertSubscription, error) {
	row := q.db.QueryRow(ctx, addAlertSubscription, arg.OrgID, arg.DestinationID, arg.EventKey)
	var i AlertSubscription
	err := row.Scan(
		&i.OrgID,
		&i.DestinationID,
		&i.EventKey,
		&i.CreatedAt,
	)
	return i, err
}

const archiveAlertDestination = `-- name: ArchiveAlertDestination :execrows
UPDATE alert_destinations
SET archived_at = now()
WHERE org_id = $1 AND id = $2 AND archived_at IS NULL
`

type ArchiveAlertDestinationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) ArchiveAlertDestination(ctx context.Context, arg ArchiveAlertDestinationParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAlertDestination, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueAlertDeliveries = `-- name: ClaimDueAlertDeliveries :many
WITH due AS (
    SELECT alert_deliveries.id
    FROM alert_deliveries
    WHERE alert_deliveries.state = 'pending' AND alert_deliveries.next_attempt_at <= $1
    ORDER BY alert_deliveries.next_attempt_at, alert_deliveries.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE alert_deliveries d
SET state = 'delivering', attempts = d.attempts + 1
FROM due
WHERE d.id = due.id
RETURNING d.id, d.org_id, d.destination_id, d.event_key, d.severity, d.dedup_key, d.payload, d.state, d.attempts, d.next_attempt_at, d.last_error, d.suppressed_count, d.sent_at, d.failed_at, d.created_at, d.updated_at
`

type ClaimDueAlertDeliveriesParams struct {
	NextAttemptAt time.Time `json:"next_attempt_at"`
	Limit         int32     `json:"limit"`
}

// lint:cross-org — the leader-gated dispatcher claims only its bounded due
// batch, atomically moving each delivery out of the pending queue.
func (q *Queries) ClaimDueAlertDeliveries(ctx context.Context, arg ClaimDueAlertDeliveriesParams) ([]AlertDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueAlertDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDelivery{}
	for rows.Next() {
		var i AlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DestinationID,
			&i.EventKey,
			&i.Severity,
			&i.DedupKey,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.SuppressedCount,
			&i.SentAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlertDelivery = `-- name: CreateAlertDelivery :one
INSERT INTO alert_deliveries (
    org_id, destination_id, event_key, severity, dedup_key, payload,
    next_attempt_at, suppressed_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, destination_id, event_key, severity, dedup_key, payload, state, attempts, next_attempt_at, last_error, suppressed_count, sent_at, failed_at, created_at, updated_at
`

type CreateAlertDeliveryParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	DestinationID   uuid.UUID `json:"destination_id"`
	EventKey        string    `json:"event_key"`
	Severity        string    `json:"severity"`
	DedupKey        string    `json:"dedup_key"`
	Payload         []byte    `json:"payload"`
	NextAttemptAt   time.Time `json:"next_attempt_at"`
	SuppressedCount int32     `json:"suppressed_count"`
}

func (q *Queries) CreateAlertDelivery(ctx context.Context, arg CreateAlertDeliveryParams) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, createAlertDelivery,
		arg.OrgID,
		arg.DestinationID,
		arg.EventKey,
		arg.Severity,
		arg.DedupKey,
		arg.Payload,
		arg.NextAttemptAt,
		arg.SuppressedCount,
	)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DestinationID,
		&i.EventKey,
		&i.Severity,
		&i.DedupKey,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.SuppressedCount,
		&i.SentAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertDeliveryCooldown = `-- name: CreateAlertDeliveryCooldown :one
INSERT INTO alert_delivery_cooldowns (
    org_id, destination_id, event_key, dedup_key, next_eligible_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING org_id, destination_id, event_key, dedup_key, next_eligible_at, suppressed_count, updated_at
`

type CreateAlertDeliveryCooldownParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	DestinationID  uuid.UUID `json:"destination_id"`
	EventKey       string    `json:"event_key"`
	DedupKey       string    `json:"dedup_key"`
	NextEligibleAt time.Time `json:"next_eligible_at"`
}

func (q *Queries) CreateAlertDeliveryCooldown(ctx context.Context, arg CreateAlertDeliveryCooldownParams) (AlertDeliveryCooldown, error) {
	row := q.db.QueryRow(ctx, createAlertDeliveryCooldown,
		arg.OrgID,
		arg.DestinationID,
		arg.EventKey,
		arg.DedupKey,
		arg.NextEligibleAt,
	)
	var i AlertDeliveryCooldown
	err := row.Scan(
		&i.OrgID,
		&i.DestinationID,
		&i.EventKey,
		&i.DedupKey,
		&i.NextEligibleAt,
		&i.SuppressedCount,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertDestination = `-- name: CreateAlertDestination :one
INSERT INTO alert_destinations (
    org_id, kind, name, endpoint_sealed, endpoint_fingerprint, endpoint_host,
    allow_private, severity_floor, cooldown_seconds, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, kind, name, endpoint_sealed, endpoint_fingerprint, endpoint_host, allow_private, severity_floor, cooldown_seconds, archived_at, created_by_user_id, created_at, updated_at
`

type CreateAlertDestinationParams struct {
	OrgID               uuid.UUID `json:"org_id"`
	Kind                string    `json:"kind"`
	Name                string    `json:"name"`
	EndpointSealed      []byte    `json:"endpoint_sealed"`
	EndpointFingerprint string    `json:"endpoint_fingerprint"`
	EndpointHost        string    `json:"endpoint_host"`
	AllowPrivate        bool      `json:"allow_private"`
	SeverityFloor       string    `json:"severity_floor"`
	CooldownSeconds     int32     `json:"cooldown_seconds"`
	CreatedByUserID     uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateAlertDestination(ctx context.Context, arg CreateAlertDestinationParams) (AlertDestination, error) {
	row := q.db.QueryRow(ctx, createAlertDestination,
		arg.OrgID,
		arg.Kind,
		arg.Name,
		arg.EndpointSealed,
		arg.EndpointFingerprint,
		arg.EndpointHost,
		arg.AllowPrivate,
		arg.SeverityFloor,
		arg.CooldownSeconds,
		arg.CreatedByUserID,
	)
	var i AlertDestination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Name,
		&i.EndpointSealed,
		&i.EndpointFingerprint,
		&i.EndpointHost,
		&i.AllowPrivate,
		&i.SeverityFloor,
		&i.CooldownSeconds,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishAlertDeliveryWithAttempt = `-- name: FinishAlertDeliveryWithAttempt :one
WITH finished AS (
    UPDATE alert_deliveries delivery
    SET state = $5,
        next_attempt_at = $6,
        last_error = $4,
        sent_at = CASE WHEN $5 = 'sent' THEN now() ELSE delivery.sent_at END,
        failed_at = CASE WHEN $5 = 'failed' THEN now() ELSE delivery.failed_at END
    WHERE delivery.id = $7 AND delivery.org_id = $8
      AND delivery.state = 'delivering'
    RETURNING delivery.id, delivery.org_id
)
INSERT INTO alert_delivery_attempts (
    org_id, delivery_id, attempt, outcome, response_status, error
) SELECT finished.org_id, finished.id, $1, $2,
         $3, $4
  FROM finished
RETURNING id, org_id, delivery_id, attempt, outcome, response_status, error, created_at
`

type FinishAlertDeliveryWithAttemptParams struct {
	Attempt        int32     `json:"attempt"`
	Outcome        string    `json:"outcome"`
	ResponseStatus *int32    `json:"response_status"`
	LastError      *string   `json:"last_error"`
	DeliveryState  string    `json:"delivery_state"`
	NextAttemptAt  time.Time `json:"next_attempt_at"`
	DeliveryID     uuid.UUID `json:"delivery_id"`
	OrgID          uuid.UUID `json:"org_id"`
}

func (q *Queries) FinishAlertDeliveryWithAttempt(ctx context.Context, arg FinishAlertDeliveryWithAttemptParams) (AlertDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, finishAlertDeliveryWithAttempt,
		arg.Attempt,
		arg.Outcome,
		arg.ResponseStatus,
		arg.LastError,
		arg.DeliveryState,
		arg.NextAttemptAt,
		arg.DeliveryID,
		arg.OrgID,
	)
	var i AlertDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeliveryID,
		&i.Attempt,
		&i.Outcome,
		&i.ResponseStatus,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertDeliveryCooldownForUpdate = `-- name: GetAlertDeliveryCooldownForUpdate :one
SELECT org_id, destination_id, event_key, dedup_key, next_eligible_at, suppressed_count, updated_at FROM alert_delivery_cooldowns
WHERE org_id = $1 AND destination_id = $2 AND event_key = $3 AND dedup_key = $4
FOR UPDATE
`

type GetAlertDeliveryCooldownForUpdateParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	DestinationID uuid.UUID `json:"destination_id"`
	EventKey      string    `json:"event_key"`
	DedupKey      string    `json:"dedup_key"`
}

func (q *Queries) GetAlertDeliveryCooldownForUpdate(ctx context.Context, arg GetAlertDeliveryCooldownForUpdateParams) (AlertDeliveryCooldown, error) {
	row := q.db.QueryRow(ctx, getAlertDeliveryCooldownForUpdate,
		arg.OrgID,
		arg.DestinationID,
		arg.EventKey,
		arg.DedupKey,
	)
	var i AlertDeliveryCooldown
	err := row.Scan(
		&i.OrgID,
		&i.DestinationID,
		&i.EventKey,
		&i.DedupKey,
		&i.NextEligibleAt,
		&i.SuppressedCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertDestination = `-- name: GetAlertDestination :one
SELECT id, org_id, kind, name, endpoint_sealed, endpoint_fingerprint, endpoint_host, allow_private, severity_floor, cooldown_seconds, archived_at, created_by_user_id, created_at, updated_at FROM alert_destinations
WHERE org_id = $1 AND id = $2
`

type GetAlertDestinationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetAlertDestination(ctx context.Context, arg GetAlertDestinationParams) (AlertDestination, error) {
	row := q.db.QueryRow(ctx, getAlertDestination, arg.OrgID, arg.ID)
	var i AlertDestination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Name,
		&i.EndpointSealed,
		&i.EndpointFingerprint,
		&i.EndpointHost,
		&i.AllowPrivate,
		&i.SeverityFloor,
		&i.CooldownSeconds,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertDestinationForDelivery = `-- name: GetAlertDestinationForDelivery :one
SELECT d.id, d.org_id, d.kind, d.name, d.endpoint_sealed, d.endpoint_fingerprint, d.endpoint_host, d.allow_private, d.severity_floor, d.cooldown_seconds, d.archived_at, d.created_by_user_id, d.created_at, d.updated_at
FROM alert_destinations d
JOIN alert_deliveries l
  ON l.org_id = d.org_id AND l.destination_id = d.id
JOIN organizations o
  ON o.id = d.org_id AND o.deleted_at IS NULL AND o.alerting_enabled
WHERE l.id = $1 AND l.org_id = $2 AND d.archived_at IS NULL
`

type GetAlertDestinationForDeliveryParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAlertDestinationForDelivery(ctx context.Context, arg GetAlertDestinationForDeliveryParams) (AlertDestination, error) {
	row := q.db.QueryRow(ctx, getAlertDestinationForDelivery, arg.ID, arg.OrgID)
	var i AlertDestination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Name,
		&i.EndpointSealed,
		&i.EndpointFingerprint,
		&i.EndpointHost,
		&i.AllowPrivate,
		&i.SeverityFloor,
		&i.CooldownSeconds,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAlertDeliveryCooldown = `-- name: IncrementAlertDeliveryCooldown :one
UPDATE alert_delivery_cooldowns
SET suppressed_count = suppressed_count + 1
WHERE org_id = $1 AND destination_id = $2 AND event_key = $3 AND dedup_key = $4
RETURNING org_id, destination_id, event_key, dedup_key, next_eligible_at, suppressed_count, updated_at
`

type IncrementAlertDeliveryCooldownParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	DestinationID uuid.UUID `json:"destination_id"`
	EventKey      string    `json:"event_key"`
	DedupKey      string    `json:"dedup_key"`
}

func (q *Queries) IncrementAlertDeliveryCooldown(ctx context.Context, arg IncrementAlertDeliveryCooldownParams) (AlertDeliveryCooldown, error) {
	row := q.db.QueryRow(ctx, incrementAlertDeliveryCooldown,
		arg.OrgID,
		arg.DestinationID,
		arg.EventKey,
		arg.DedupKey,
	)
	var i AlertDeliveryCooldown
	err := row.Scan(
		&i.OrgID,
		&i.DestinationID,
		&i.EventKey,
		&i.DedupKey,
		&i.NextEligibleAt,
		&i.SuppressedCount,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertDeliveries = `-- name: ListAlertDeliveries :many
SELECT id, org_id, destination_id, event_key, severity, dedup_key, payload, state, attempts, next_attempt_at, last_error, suppressed_count, sent_at, failed_at, created_at, updated_at FROM alert_deliveries
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAlertDeliveriesParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Limit int32     `json:"limit"`
}

func (q *Queries) ListAlertDeliveries(ctx context.Context, arg ListAlertDeliveriesParams) ([]AlertDelivery, error) {
	rows, err := q.db.Query(ctx, listAlertDeliveries, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDelivery{}
	for rows.Next() {
		var i AlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DestinationID,
			&i.EventKey,
			&i.Severity,
			&i.DedupKey,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.SuppressedCount,
			&i.SentAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertDestinations = `-- name: ListAlertDestinations :many
SELECT id, org_id, kind, name, endpoint_sealed, endpoint_fingerprint, endpoint_host, allow_private, severity_floor, cooldown_seconds, archived_at, created_by_user_id, created_at, updated_at FROM alert_destinations
WHERE org_id = $1
ORDER BY archived_at NULLS FIRST, created_at, id
`

func (q *Queries) ListAlertDestinations(ctx context.Context, orgID uuid.UUID) ([]AlertDestination, error) {
	rows, err := q.db.Query(ctx, listAlertDestinations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDestination{}
	for rows.Next() {
		var i AlertDestination
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Name,
			&i.EndpointSealed,
			&i.EndpointFingerprint,
			&i.EndpointHost,
			&i.AllowPrivate,
			&i.SeverityFloor,
			&i.CooldownSeconds,
			&i.ArchivedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertDestinationsForEvent = `-- name: ListAlertDestinationsForEvent :many
SELECT d.id, d.org_id, d.kind, d.name, d.endpoint_sealed, d.endpoint_fingerprint, d.endpoint_host, d.allow_private, d.severity_floor, d.cooldown_seconds, d.archived_at, d.created_by_user_id, d.created_at, d.updated_at
FROM alert_destinations d
JOIN alert_subscriptions s
  ON s.org_id = d.org_id AND s.destination_id = d.id
WHERE d.org_id = $1
  AND d.archived_at IS NULL
  AND s.event_key = $2
  AND CASE d.severity_floor
        WHEN 'info' THEN 0
        WHEN 'warning' THEN 1
        WHEN 'critical' THEN 2
      END <= CASE $3
               WHEN 'info' THEN 0
               WHEN 'warning' THEN 1
               WHEN 'critical' THEN 2
             END
ORDER BY d.created_at, d.id
`

type ListAlertDestinationsForEventParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	EventKey      string    `json:"event_key"`
	SeverityFloor string    `json:"severity_floor"`
}

func (q *Queries) ListAlertDestinationsForEvent(ctx context.Context, arg ListAlertDestinationsForEventParams) ([]AlertDestination, error) {
	rows, err := q.db.Query(ctx, listAlertDestinationsForEvent, arg.OrgID, arg.EventKey, arg.SeverityFloor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDestination{}
	for rows.Next() {
		var i AlertDestination
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Name,
			&i.EndpointSealed,
			&i.EndpointFingerprint,
			&i.EndpointHost,
			&i.AllowPrivate,
			&i.SeverityFloor,
			&i.CooldownSeconds,
			&i.ArchivedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertSubscriptions = `-- name: ListAlertSubscriptions :many
SELECT org_id, destination_id, event_key, created_at FROM alert_subscriptions
WHERE org_id = $1 AND destination_id = $2
ORDER BY event_key
`

type ListAlertSubscriptionsParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	DestinationID uuid.UUID `json:"destination_id"`
}

func (q *Queries) ListAlertSubscriptions(ctx context.Context, arg ListAlertSubscriptionsParams) ([]AlertSubscription, error) {
	rows, err := q.db.Query(ctx, listAlertSubscriptions, arg.OrgID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertSubscription{}
	for rows.Next() {
		var i AlertSubscription
		if err := rows.Scan(
			&i.OrgID,
			&i.DestinationID,
			&i.EventKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueAlertDeliveries = `-- name: ListDueAlertDeliveries :many
SELECT id, org_id, destination_id, event_key, severity, dedup_key, payload, state, attempts, next_attempt_at, last_error, suppressed_count, sent_at, failed_at, created_at, updated_at FROM alert_deliveries
WHERE state = 'pending' AND next_attempt_at <= $1
ORDER BY next_attempt_at, id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDueAlertDeliveriesParams struct {
	NextAttemptAt time.Time `json:"next_attempt_at"`
	Limit         int32     `json:"limit"`
}

// lint:cross-org — the leader-gated dispatcher intentionally claims due
// deliveries across all tenants. It never exposes this query to a human route.
func (q *Queries) ListDueAlertDeliveries(ctx context.Context, arg ListDueAlertDeliveriesParams) ([]AlertDelivery, error) {
	rows, err := q.db.Query(ctx, listDueAlertDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDelivery{}
	for rows.Next() {
		var i AlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DestinationID,
			&i.EventKey,
			&i.Severity,
			&i.DedupKey,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.SuppressedCount,
			&i.SentAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverStaleAlertDeliveries = `-- name: RecoverStaleAlertDeliveries :one
WITH stale AS (
    SELECT delivery.id, delivery.org_id, delivery.destination_id, delivery.event_key, delivery.severity, delivery.dedup_key, delivery.payload, delivery.state, delivery.attempts, delivery.next_attempt_at, delivery.last_error, delivery.suppressed_count, delivery.sent_at, delivery.failed_at, delivery.created_at, delivery.updated_at FROM alert_deliveries delivery
    WHERE delivery.state = 'delivering' AND delivery.updated_at < $1
    FOR UPDATE
), recorded AS (
    INSERT INTO alert_delivery_attempts (
        org_id, delivery_id, attempt, outcome, error
    )
    SELECT stale.org_id, stale.id, stale.attempts,
           CASE WHEN stale.attempts >= $2::integer
                THEN 'terminal_failure' ELSE 'retryable_failure' END,
           'delivery worker lease expired'
    FROM stale
    ON CONFLICT (delivery_id, attempt) DO NOTHING
), recovered AS (
    UPDATE alert_deliveries d
    SET state = CASE WHEN stale.attempts >= $2::integer
                     THEN 'failed' ELSE 'pending' END,
        next_attempt_at = $3,
        last_error = 'delivery worker lease expired',
        failed_at = CASE WHEN stale.attempts >= $2::integer
                         THEN now() ELSE NULL END
    FROM stale
    WHERE d.id = stale.id AND d.org_id = stale.org_id
    RETURNING d.id
)
SELECT count(*)::bigint FROM recovered
`

type RecoverStaleAlertDeliveriesParams struct {
	StaleBefore   time.Time `json:"stale_before"`
	MaxAttempts   int32     `json:"max_attempts"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

// lint:cross-org — the leader-gated dispatcher requeues stale claims across
// every tenant; no human route can call this query.
// A delivery is claimed before outbound I/O. If that worker dies, a later
// leader requeues only claims older than the bounded dispatcher lease.
func (q *Queries) RecoverStaleAlertDeliveries(ctx context.Context, arg RecoverStaleAlertDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, recoverStaleAlertDeliveries, arg.StaleBefore, arg.MaxAttempts, arg.NextAttemptAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const removeAlertSubscription = `-- name: RemoveAlertSubscription :execrows
DELETE FROM alert_subscriptions
WHERE org_id = $1 AND destination_id = $2 AND event_key = $3
`

type RemoveAlertSubscriptionParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	DestinationID uuid.UUID `json:"destination_id"`
	EventKey      string    `json:"event_key"`
}

func (q *Queries) RemoveAlertSubscription(ctx context.Context, arg RemoveAlertSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeAlertSubscription, arg.OrgID, arg.DestinationID, arg.EventKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveAlertDeliveryCooldown = `-- name: ReserveAlertDeliveryCooldown :one
UPDATE alert_delivery_cooldowns
SET next_eligible_at = $5, suppressed_count = 0
WHERE org_id = $1 AND destination_id = $2 AND event_key = $3 AND dedup_key = $4
RETURNING org_id, destination_id, event_key, dedup_key, next_eligible_at, suppressed_count, updated_at
`

type ReserveAlertDeliveryCooldownParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	DestinationID  uuid.UUID `json:"destination_id"`
	EventKey       string    `json:"event_key"`
	DedupKey       string    `json:"dedup_key"`
	NextEligibleAt time.Time `json:"next_eligible_at"`
}

func (q *Queries) ReserveAlertDeliveryCooldown(ctx context.Context, arg ReserveAlertDeliveryCooldownParams) (AlertDeliveryCooldown, error) {
	row := q.db.QueryRow(ctx, reserveAlertDeliveryCooldown,
		arg.OrgID,
		arg.DestinationID,
		arg.EventKey,
		arg.DedupKey,
		arg.NextEligibleAt,
	)
	var i AlertDeliveryCooldown
	err := row.Scan(
		&i.OrgID,
		&i.DestinationID,
		&i.EventKey,
		&i.DedupKey,
		&i.NextEligibleAt,
		&i.SuppressedCount,
		&i.UpdatedAt,
	)
	return i, err
}
