// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access_publication.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateAppAccessServingPublication = `-- name: ActivateAppAccessServingPublication :execrows
INSERT INTO app_access_serving_publications(org_id,app_id,gateway_id,revision,digest,hostname,generation,purpose,authority_version,state)
SELECT op.org_id,op.app_id,op.gateway_id,op.revision,op.digest,op.hostname,op.generation,op.purpose,op.authority_version,'active'
FROM app_access_publication_operations op
JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL
JOIN app_access_settings setting ON setting.org_id=op.org_id AND setting.enabled
JOIN app_access_applications app ON app.org_id=op.org_id AND app.id=op.app_id AND app.state='draft' AND app.version=op.expected_app_version AND app.draft_revision=op.revision
JOIN app_access_hostnames h ON h.hostname=op.hostname AND h.org_id=op.org_id AND h.app_id=op.app_id AND (to_jsonb(h)->>'released_at') IS NULL
JOIN app_access_revisions r ON r.org_id=op.org_id AND r.app_id=op.app_id AND r.gateway_id=op.gateway_id AND r.revision=op.revision AND r.digest=op.digest AND r.public_hostname=op.hostname
JOIN nodes n ON n.org_id=op.org_id AND n.id=op.gateway_id AND n.status='active' AND n.enrolled_kind='gateway' AND n.cert_serial=op.gateway_cert_serial AND n.cert_not_after>now()
JOIN app_access_browser_gateway_runtime runtime ON runtime.org_id=op.org_id AND runtime.gateway_id=op.gateway_id AND runtime.capability_version=1 AND runtime.reported_cert_serial=n.cert_serial AND runtime.reported_at>now()-interval '30 seconds'
JOIN app_access_origin_checks c ON c.org_id=op.org_id AND c.app_id=op.app_id AND c.id=op.origin_check_id AND c.gateway_id=op.gateway_id AND c.revision=op.revision AND c.digest=op.digest AND c.purpose='origin_check' AND c.status='succeeded' AND c.completed_cert_serial=n.cert_serial AND c.completed_at>now()-interval '5 minutes'
JOIN app_access_proxy_credentials proxy ON proxy.id=op.proxy_credential_id AND proxy.version=op.proxy_credential_version AND proxy.revoked_at IS NULL
WHERE op.org_id=$1 AND op.app_id=$2 AND op.id=$3 AND op.version=$4 AND op.status='checking' AND op.deadline>now()
 AND op.public_dns_status='passed' AND op.public_tls_status='passed' AND op.connector_dns_status='passed' AND op.connector_connect_status='passed' AND op.connector_tls_status=CASE WHEN r.origin_url LIKE 'https://%' THEN 'passed' ELSE 'skipped' END AND op.error_code=''
 AND op.origin_proof_completed_at>now()-interval '10 seconds' AND op.public_proof_completed_at>now()-interval '10 seconds'
 AND COALESCE((SELECT current.authority_version FROM app_access_serving_publications current WHERE current.org_id=op.org_id AND current.app_id=op.app_id),0)=op.expected_active_authority_version
ON CONFLICT(org_id,app_id) DO UPDATE SET gateway_id=EXCLUDED.gateway_id,revision=EXCLUDED.revision,digest=EXCLUDED.digest,hostname=EXCLUDED.hostname,generation=EXCLUDED.generation,purpose=EXCLUDED.purpose,authority_version=EXCLUDED.authority_version,state='active',updated_at=now(),withdrawal_confirmed_at=NULL,withdrawal_confirmed_authority_version=NULL,withdrawal_confirmed_generation=NULL
WHERE app_access_serving_publications.authority_version=EXCLUDED.authority_version-1
`

type ActivateAppAccessServingPublicationParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	AppID           uuid.UUID `json:"app_id"`
	OperationID     uuid.UUID `json:"operation_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) ActivateAppAccessServingPublication(ctx context.Context, arg ActivateAppAccessServingPublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateAppAccessServingPublication,
		arg.OrgID,
		arg.AppID,
		arg.OperationID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advanceAppAccessApplicationAuthorityVersion = `-- name: AdvanceAppAccessApplicationAuthorityVersion :one
UPDATE app_access_applications app SET version=app.version+1,updated_at=now()
WHERE app.org_id=$1 AND app.id=$2 AND app.version=$3 AND app.state='draft'
 AND EXISTS(SELECT 1 FROM organizations o WHERE o.id=$1 AND o.deleted_at IS NULL) RETURNING app.version
`

type AdvanceAppAccessApplicationAuthorityVersionParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	AppID           uuid.UUID `json:"app_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) AdvanceAppAccessApplicationAuthorityVersion(ctx context.Context, arg AdvanceAppAccessApplicationAuthorityVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, advanceAppAccessApplicationAuthorityVersion, arg.OrgID, arg.AppID, arg.ExpectedVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const appAccessBrowserGatewayWorkCount = `-- name: AppAccessBrowserGatewayWorkCount :one
SELECT ((SELECT count(*) FROM app_access_serving_publications p WHERE p.org_id=$1 AND p.gateway_id=$2 AND p.state='active')+
(SELECT count(*) FROM app_access_publication_operations op WHERE op.org_id=$1 AND op.gateway_id=$2 AND op.status IN('queued','checking') AND op.deadline>now()))::bigint
`

type AppAccessBrowserGatewayWorkCountParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) AppAccessBrowserGatewayWorkCount(ctx context.Context, arg AppAccessBrowserGatewayWorkCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, appAccessBrowserGatewayWorkCount, arg.OrgID, arg.GatewayID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const appAccessPublicationMatchingUserCount = `-- name: AppAccessPublicationMatchingUserCount :one
SELECT count(*)::bigint FROM (
 SELECT u.id FROM users u JOIN memberships m ON m.user_id=u.id AND m.org_id=$1
 JOIN organizations o ON o.id=m.org_id AND o.deleted_at IS NULL
 JOIN app_access_applications a ON a.org_id=m.org_id AND a.id=$2
 WHERE u.deleted_at IS NULL AND u.status='active' AND u.email_verified_at IS NOT NULL AND NOT u.must_change_password AND m.access_revoked_at IS NULL
 AND (CASE WHEN cardinality(m.roles)>0 THEN m.roles ELSE ARRAY[m.role] END) && $3::text[]
 AND EXISTS(SELECT 1 FROM app_access_grants g WHERE g.org_id=m.org_id AND g.app_id=a.id AND g.enabled AND g.revoked_at IS NULL
 AND (g.starts_at IS NULL OR g.starts_at<=$4::timestamptz) AND (g.expires_at IS NULL OR $4::timestamptz<g.expires_at)
 AND ((g.subject_kind='user' AND g.user_id=u.id) OR (g.subject_kind='group' AND EXISTS(
 SELECT 1 FROM group_members gm JOIN user_groups ug ON ug.id=gm.group_id AND ug.org_id=gm.org_id WHERE gm.org_id=g.org_id AND gm.group_id=g.group_id AND gm.user_id=u.id))))
 ORDER BY u.id LIMIT 1001
) matching
`

type AppAccessPublicationMatchingUserCountParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	AppID         uuid.UUID `json:"app_id"`
	EligibleRoles []string  `json:"eligible_roles"`
	EvaluatedAt   time.Time `json:"evaluated_at"`
}

func (q *Queries) AppAccessPublicationMatchingUserCount(ctx context.Context, arg AppAccessPublicationMatchingUserCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, appAccessPublicationMatchingUserCount,
		arg.OrgID,
		arg.AppID,
		arg.EligibleRoles,
		arg.EvaluatedAt,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const archiveAppAccessApplication = `-- name: ArchiveAppAccessApplication :execrows
UPDATE app_access_applications app SET state='archived',version=app.version+1,updated_at=now() WHERE app.org_id=$1 AND app.id=$2 AND app.version=$3 AND app.state='draft' AND EXISTS(SELECT 1 FROM app_access_serving_publications p WHERE p.org_id=app.org_id AND p.app_id=app.id AND p.state='disabled' AND p.withdrawal_confirmed_at IS NOT NULL AND p.withdrawal_confirmed_authority_version=p.authority_version AND p.withdrawal_confirmed_generation=p.generation) AND NOT EXISTS(SELECT 1 FROM app_access_publication_operations op WHERE op.org_id=app.org_id AND op.app_id=app.id AND op.status IN('queued','checking')) AND EXISTS(SELECT 1 FROM organizations o WHERE o.id=$1 AND o.deleted_at IS NULL)
`

type ArchiveAppAccessApplicationParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	AppID           uuid.UUID `json:"app_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) ArchiveAppAccessApplication(ctx context.Context, arg ArchiveAppAccessApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAppAccessApplication, arg.OrgID, arg.AppID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelAppAccessPublicationOperation = `-- name: CancelAppAccessPublicationOperation :one
UPDATE app_access_publication_operations SET status='cancelled',error_code='assignment_changed',completed_at=now(),version=version+1 WHERE org_id=$1 AND app_id=$2 AND id=$3 AND version=$4 AND status IN('queued','checking') RETURNING id, org_id, app_id, actor_user_id, idempotency_key, reviewed_app_version, expected_app_version, revision, digest, origin_check_id, origin_check_purpose, gateway_id, hostname, generation, purpose, expected_active_authority_version, authority_version, gateway_cert_serial, readiness_request_id, proxy_instance_token_hash, deadline, version, status, proxy_credential_id, proxy_credential_version, claimed_at, origin_proof_completed_at, public_proof_completed_at, completed_at, public_dns_status, public_tls_status, connector_dns_status, connector_connect_status, connector_tls_status, error_code, created_at
`

type CancelAppAccessPublicationOperationParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	AppID           uuid.UUID `json:"app_id"`
	OperationID     uuid.UUID `json:"operation_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) CancelAppAccessPublicationOperation(ctx context.Context, arg CancelAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, cancelAppAccessPublicationOperation,
		arg.OrgID,
		arg.AppID,
		arg.OperationID,
		arg.ExpectedVersion,
	)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const cancelAppAccessPublicationOperations = `-- name: CancelAppAccessPublicationOperations :execrows
UPDATE app_access_publication_operations SET status='cancelled',error_code='assignment_changed',completed_at=now(),version=version+1 WHERE org_id=$1 AND app_id=$2 AND status IN('queued','checking')
`

type CancelAppAccessPublicationOperationsParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) CancelAppAccessPublicationOperations(ctx context.Context, arg CancelAppAccessPublicationOperationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelAppAccessPublicationOperations, arg.OrgID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimAppAccessPublicationReadiness = `-- name: ClaimAppAccessPublicationReadiness :one
UPDATE app_access_publication_operations SET status='checking',proxy_credential_id=$1,proxy_credential_version=$2,proxy_instance_token_hash=$3,claimed_at=now(),version=version+1
WHERE org_id=$4 AND app_id=$5 AND id=$6 AND version=$7 AND status='queued' AND deadline>now() RETURNING id, org_id, app_id, actor_user_id, idempotency_key, reviewed_app_version, expected_app_version, revision, digest, origin_check_id, origin_check_purpose, gateway_id, hostname, generation, purpose, expected_active_authority_version, authority_version, gateway_cert_serial, readiness_request_id, proxy_instance_token_hash, deadline, version, status, proxy_credential_id, proxy_credential_version, claimed_at, origin_proof_completed_at, public_proof_completed_at, completed_at, public_dns_status, public_tls_status, connector_dns_status, connector_connect_status, connector_tls_status, error_code, created_at
`

type ClaimAppAccessPublicationReadinessParams struct {
	ProxyCredentialID      pgtype.UUID `json:"proxy_credential_id"`
	ProxyCredentialVersion *int64      `json:"proxy_credential_version"`
	ProxyInstanceTokenHash []byte      `json:"proxy_instance_token_hash"`
	OrgID                  uuid.UUID   `json:"org_id"`
	AppID                  uuid.UUID   `json:"app_id"`
	OperationID            uuid.UUID   `json:"operation_id"`
	ExpectedVersion        int64       `json:"expected_version"`
}

func (q *Queries) ClaimAppAccessPublicationReadiness(ctx context.Context, arg ClaimAppAccessPublicationReadinessParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, claimAppAccessPublicationReadiness,
		arg.ProxyCredentialID,
		arg.ProxyCredentialVersion,
		arg.ProxyInstanceTokenHash,
		arg.OrgID,
		arg.AppID,
		arg.OperationID,
		arg.ExpectedVersion,
	)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const clearAppAccessPublicationWithdrawalConfirmation = `-- name: ClearAppAccessPublicationWithdrawalConfirmation :exec
UPDATE app_access_serving_publications SET withdrawal_confirmed_at=NULL,withdrawal_confirmed_authority_version=NULL,withdrawal_confirmed_generation=NULL
WHERE org_id=$1 AND app_id=$2 AND state='disabled'
`

type ClearAppAccessPublicationWithdrawalConfirmationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) ClearAppAccessPublicationWithdrawalConfirmation(ctx context.Context, arg ClearAppAccessPublicationWithdrawalConfirmationParams) error {
	_, err := q.db.Exec(ctx, clearAppAccessPublicationWithdrawalConfirmation, arg.OrgID, arg.AppID)
	return err
}

const completeAppAccessPublicationReadiness = `-- name: CompleteAppAccessPublicationReadiness :one
UPDATE app_access_publication_operations SET public_dns_status=$1,public_tls_status=$2,connector_dns_status=$3,connector_connect_status=$4,connector_tls_status=$5,error_code=$6,status=$7,origin_proof_completed_at=now(),public_proof_completed_at=now(),completed_at=CASE WHEN $7::text='failed' THEN now() ELSE NULL END,version=version+1
WHERE org_id=$8 AND app_id=$9 AND id=$10 AND version=$11 AND readiness_request_id=$12
 AND proxy_credential_id=$13 AND proxy_credential_version=$14 AND proxy_instance_token_hash=$15
 AND gateway_cert_serial=$16 AND status='checking' AND deadline>now() AND origin_proof_completed_at IS NULL AND $7::text IN('checking','failed') RETURNING id, org_id, app_id, actor_user_id, idempotency_key, reviewed_app_version, expected_app_version, revision, digest, origin_check_id, origin_check_purpose, gateway_id, hostname, generation, purpose, expected_active_authority_version, authority_version, gateway_cert_serial, readiness_request_id, proxy_instance_token_hash, deadline, version, status, proxy_credential_id, proxy_credential_version, claimed_at, origin_proof_completed_at, public_proof_completed_at, completed_at, public_dns_status, public_tls_status, connector_dns_status, connector_connect_status, connector_tls_status, error_code, created_at
`

type CompleteAppAccessPublicationReadinessParams struct {
	PublicDnsStatus        string      `json:"public_dns_status"`
	PublicTlsStatus        string      `json:"public_tls_status"`
	ConnectorDnsStatus     string      `json:"connector_dns_status"`
	ConnectorConnectStatus string      `json:"connector_connect_status"`
	ConnectorTlsStatus     string      `json:"connector_tls_status"`
	ErrorCode              string      `json:"error_code"`
	Status                 string      `json:"status"`
	OrgID                  uuid.UUID   `json:"org_id"`
	AppID                  uuid.UUID   `json:"app_id"`
	OperationID            uuid.UUID   `json:"operation_id"`
	ExpectedVersion        int64       `json:"expected_version"`
	ReadinessRequestID     uuid.UUID   `json:"readiness_request_id"`
	ProxyCredentialID      pgtype.UUID `json:"proxy_credential_id"`
	ProxyCredentialVersion *int64      `json:"proxy_credential_version"`
	ProxyInstanceTokenHash []byte      `json:"proxy_instance_token_hash"`
	GatewayCertSerial      string      `json:"gateway_cert_serial"`
}

func (q *Queries) CompleteAppAccessPublicationReadiness(ctx context.Context, arg CompleteAppAccessPublicationReadinessParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, completeAppAccessPublicationReadiness,
		arg.PublicDnsStatus,
		arg.PublicTlsStatus,
		arg.ConnectorDnsStatus,
		arg.ConnectorConnectStatus,
		arg.ConnectorTlsStatus,
		arg.ErrorCode,
		arg.Status,
		arg.OrgID,
		arg.AppID,
		arg.OperationID,
		arg.ExpectedVersion,
		arg.ReadinessRequestID,
		arg.ProxyCredentialID,
		arg.ProxyCredentialVersion,
		arg.ProxyInstanceTokenHash,
		arg.GatewayCertSerial,
	)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const confirmAppAccessPublicationWithdrawal = `-- name: ConfirmAppAccessPublicationWithdrawal :one
UPDATE app_access_serving_publications SET withdrawal_confirmed_at=now(),withdrawal_confirmed_authority_version=authority_version,withdrawal_confirmed_generation=generation
WHERE org_id=$1 AND app_id=$2 AND state='disabled' AND authority_version=$3 AND generation=$4
 AND EXISTS(SELECT 1 FROM organizations o WHERE o.id=$1 AND o.deleted_at IS NULL) RETURNING org_id, app_id, gateway_id, revision, digest, hostname, generation, purpose, authority_version, state, updated_at, withdrawal_confirmed_at, withdrawal_confirmed_authority_version, withdrawal_confirmed_generation
`

type ConfirmAppAccessPublicationWithdrawalParams struct {
	OrgID                    uuid.UUID `json:"org_id"`
	AppID                    uuid.UUID `json:"app_id"`
	ExpectedAuthorityVersion int64     `json:"expected_authority_version"`
	ExpectedGeneration       uuid.UUID `json:"expected_generation"`
}

// Only the service's post-commit monotonic wait may call this; wall-clock age is not withdrawal proof.
func (q *Queries) ConfirmAppAccessPublicationWithdrawal(ctx context.Context, arg ConfirmAppAccessPublicationWithdrawalParams) (AppAccessServingPublication, error) {
	row := q.db.QueryRow(ctx, confirmAppAccessPublicationWithdrawal,
		arg.OrgID,
		arg.AppID,
		arg.ExpectedAuthorityVersion,
		arg.ExpectedGeneration,
	)
	var i AppAccessServingPublication
	err := row.Scan(
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.AuthorityVersion,
		&i.State,
		&i.UpdatedAt,
		&i.WithdrawalConfirmedAt,
		&i.WithdrawalConfirmedAuthorityVersion,
		&i.WithdrawalConfirmedGeneration,
	)
	return i, err
}

const countClaimedAppAccessReadiness = `-- name: CountClaimedAppAccessReadiness :one
SELECT count(*)::bigint FROM app_access_publication_operations op
WHERE op.proxy_credential_id=$1 AND op.proxy_credential_version=$2
 AND op.status='checking' AND op.deadline>now()
`

type CountClaimedAppAccessReadinessParams struct {
	ProxyCredentialID      pgtype.UUID `json:"proxy_credential_id"`
	ProxyCredentialVersion *int64      `json:"proxy_credential_version"`
}

// lint:cross-org -- Dedicated installation proxy's bounded outstanding readiness claims span only its own current credential version.
func (q *Queries) CountClaimedAppAccessReadiness(ctx context.Context, arg CountClaimedAppAccessReadinessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimedAppAccessReadiness, arg.ProxyCredentialID, arg.ProxyCredentialVersion)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAppAccessPublicationOperation = `-- name: CreateAppAccessPublicationOperation :one
INSERT INTO app_access_publication_operations(org_id,app_id,actor_user_id,idempotency_key,reviewed_app_version,expected_app_version,revision,digest,origin_check_id,gateway_id,hostname,expected_active_authority_version,authority_version,gateway_cert_serial,deadline)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12::bigint+1,$13,LEAST($14::timestamptz,now()+interval '60 seconds')) RETURNING id, org_id, app_id, actor_user_id, idempotency_key, reviewed_app_version, expected_app_version, revision, digest, origin_check_id, origin_check_purpose, gateway_id, hostname, generation, purpose, expected_active_authority_version, authority_version, gateway_cert_serial, readiness_request_id, proxy_instance_token_hash, deadline, version, status, proxy_credential_id, proxy_credential_version, claimed_at, origin_proof_completed_at, public_proof_completed_at, completed_at, public_dns_status, public_tls_status, connector_dns_status, connector_connect_status, connector_tls_status, error_code, created_at
`

type CreateAppAccessPublicationOperationParams struct {
	OrgID                          uuid.UUID `json:"org_id"`
	AppID                          uuid.UUID `json:"app_id"`
	ActorUserID                    uuid.UUID `json:"actor_user_id"`
	IdempotencyKey                 uuid.UUID `json:"idempotency_key"`
	ReviewedAppVersion             int64     `json:"reviewed_app_version"`
	ExpectedAppVersion             int64     `json:"expected_app_version"`
	Revision                       int64     `json:"revision"`
	Digest                         string    `json:"digest"`
	OriginCheckID                  uuid.UUID `json:"origin_check_id"`
	GatewayID                      uuid.UUID `json:"gateway_id"`
	Hostname                       string    `json:"hostname"`
	ExpectedActiveAuthorityVersion int64     `json:"expected_active_authority_version"`
	GatewayCertSerial              string    `json:"gateway_cert_serial"`
	Deadline                       time.Time `json:"deadline"`
}

func (q *Queries) CreateAppAccessPublicationOperation(ctx context.Context, arg CreateAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, createAppAccessPublicationOperation,
		arg.OrgID,
		arg.AppID,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.ReviewedAppVersion,
		arg.ExpectedAppVersion,
		arg.Revision,
		arg.Digest,
		arg.OriginCheckID,
		arg.GatewayID,
		arg.Hostname,
		arg.ExpectedActiveAuthorityVersion,
		arg.GatewayCertSerial,
		arg.Deadline,
	)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const createDisabledAppAccessPublicationFromDraft = `-- name: CreateDisabledAppAccessPublicationFromDraft :execrows
INSERT INTO app_access_serving_publications(org_id,app_id,gateway_id,revision,digest,hostname,authority_version,state)
SELECT app.org_id,app.id,r.gateway_id,r.revision,r.digest,r.public_hostname,1,'disabled'
FROM app_access_applications app JOIN organizations o ON o.id=app.org_id AND o.deleted_at IS NULL
JOIN app_access_revisions r ON r.org_id=app.org_id AND r.app_id=app.id AND r.revision=app.draft_revision
WHERE app.org_id=$1 AND app.id=$2 AND app.version=$3 AND app.state='draft'
ON CONFLICT(org_id,app_id) DO NOTHING
`

type CreateDisabledAppAccessPublicationFromDraftParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	AppID              uuid.UUID `json:"app_id"`
	ExpectedAppVersion int64     `json:"expected_app_version"`
}

func (q *Queries) CreateDisabledAppAccessPublicationFromDraft(ctx context.Context, arg CreateDisabledAppAccessPublicationFromDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDisabledAppAccessPublicationFromDraft, arg.OrgID, arg.AppID, arg.ExpectedAppVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDisabledAppAccessPublicationFromOperation = `-- name: CreateDisabledAppAccessPublicationFromOperation :execrows
INSERT INTO app_access_serving_publications(org_id,app_id,gateway_id,revision,digest,hostname,generation,purpose,authority_version,state)
SELECT op.org_id,op.app_id,op.gateway_id,op.revision,op.digest,op.hostname,op.generation,op.purpose,op.authority_version,'disabled'
FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL
WHERE op.org_id=$1 AND op.app_id=$2 AND op.id=$3 AND op.status='cancelled' AND op.expected_active_authority_version=0
ON CONFLICT(org_id,app_id) DO NOTHING
`

type CreateDisabledAppAccessPublicationFromOperationParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	AppID       uuid.UUID `json:"app_id"`
	OperationID uuid.UUID `json:"operation_id"`
}

func (q *Queries) CreateDisabledAppAccessPublicationFromOperation(ctx context.Context, arg CreateDisabledAppAccessPublicationFromOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDisabledAppAccessPublicationFromOperation, arg.OrgID, arg.AppID, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableAppAccessServingPublication = `-- name: DisableAppAccessServingPublication :execrows
UPDATE app_access_serving_publications SET state='disabled',authority_version=authority_version+1,updated_at=now(),withdrawal_confirmed_at=NULL,withdrawal_confirmed_authority_version=NULL,withdrawal_confirmed_generation=NULL WHERE org_id=$1 AND app_id=$2 AND (state<>'disabled' OR withdrawal_confirmed_at IS NULL)
`

type DisableAppAccessServingPublicationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) DisableAppAccessServingPublication(ctx context.Context, arg DisableAppAccessServingPublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableAppAccessServingPublication, arg.OrgID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireAppAccessPublicationOperations = `-- name: ExpireAppAccessPublicationOperations :exec
UPDATE app_access_publication_operations SET status='expired',error_code='deadline_exceeded',completed_at=now(),version=version+1 WHERE org_id=$1 AND app_id=$2 AND status IN('queued','checking') AND deadline<=now()
`

type ExpireAppAccessPublicationOperationsParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) ExpireAppAccessPublicationOperations(ctx context.Context, arg ExpireAppAccessPublicationOperationsParams) error {
	_, err := q.db.Exec(ctx, expireAppAccessPublicationOperations, arg.OrgID, arg.AppID)
	return err
}

const failAppAccessPublicationOperation = `-- name: FailAppAccessPublicationOperation :one
UPDATE app_access_publication_operations SET status='failed',error_code=$1,completed_at=now(),version=version+1
WHERE org_id=$2 AND app_id=$3 AND id=$4 AND version=$5 AND status IN('queued','checking') RETURNING id, org_id, app_id, actor_user_id, idempotency_key, reviewed_app_version, expected_app_version, revision, digest, origin_check_id, origin_check_purpose, gateway_id, hostname, generation, purpose, expected_active_authority_version, authority_version, gateway_cert_serial, readiness_request_id, proxy_instance_token_hash, deadline, version, status, proxy_credential_id, proxy_credential_version, claimed_at, origin_proof_completed_at, public_proof_completed_at, completed_at, public_dns_status, public_tls_status, connector_dns_status, connector_connect_status, connector_tls_status, error_code, created_at
`

type FailAppAccessPublicationOperationParams struct {
	ErrorCode       string    `json:"error_code"`
	OrgID           uuid.UUID `json:"org_id"`
	AppID           uuid.UUID `json:"app_id"`
	OperationID     uuid.UUID `json:"operation_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) FailAppAccessPublicationOperation(ctx context.Context, arg FailAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, failAppAccessPublicationOperation,
		arg.ErrorCode,
		arg.OrgID,
		arg.AppID,
		arg.OperationID,
		arg.ExpectedVersion,
	)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAppAccessBrowserGatewayRuntime = `-- name: GetAppAccessBrowserGatewayRuntime :one
SELECT r.org_id, r.gateway_id, r.capability_version, r.reported_cert_serial, r.reported_at FROM app_access_browser_gateway_runtime r JOIN organizations o ON o.id=r.org_id AND o.deleted_at IS NULL WHERE r.org_id=$1 AND r.gateway_id=$2
`

type GetAppAccessBrowserGatewayRuntimeParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) GetAppAccessBrowserGatewayRuntime(ctx context.Context, arg GetAppAccessBrowserGatewayRuntimeParams) (AppAccessBrowserGatewayRuntime, error) {
	row := q.db.QueryRow(ctx, getAppAccessBrowserGatewayRuntime, arg.OrgID, arg.GatewayID)
	var i AppAccessBrowserGatewayRuntime
	err := row.Scan(
		&i.OrgID,
		&i.GatewayID,
		&i.CapabilityVersion,
		&i.ReportedCertSerial,
		&i.ReportedAt,
	)
	return i, err
}

const getAppAccessPublicationOperation = `-- name: GetAppAccessPublicationOperation :one
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL WHERE op.org_id=$1 AND op.app_id=$2 AND op.id=$3
`

type GetAppAccessPublicationOperationParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	AppID       uuid.UUID `json:"app_id"`
	OperationID uuid.UUID `json:"operation_id"`
}

func (q *Queries) GetAppAccessPublicationOperation(ctx context.Context, arg GetAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, getAppAccessPublicationOperation, arg.OrgID, arg.AppID, arg.OperationID)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAppAccessPublicationOperationByKey = `-- name: GetAppAccessPublicationOperationByKey :one
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL WHERE op.org_id=$1 AND op.app_id=$2 AND op.idempotency_key=$3
`

type GetAppAccessPublicationOperationByKeyParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	AppID          uuid.UUID `json:"app_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetAppAccessPublicationOperationByKey(ctx context.Context, arg GetAppAccessPublicationOperationByKeyParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, getAppAccessPublicationOperationByKey, arg.OrgID, arg.AppID, arg.IdempotencyKey)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAppAccessReadinessOperationByID = `-- name: GetAppAccessReadinessOperationByID :one
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL WHERE op.id=$1
`

// lint:cross-org -- Dedicated proxy derives immutable tenant/binding from server-issued operation ID before validating body tuple and claimed ownership.
func (q *Queries) GetAppAccessReadinessOperationByID(ctx context.Context, operationID uuid.UUID) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, getAppAccessReadinessOperationByID, operationID)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAppAccessServingPublication = `-- name: GetAppAccessServingPublication :one
SELECT p.org_id, p.app_id, p.gateway_id, p.revision, p.digest, p.hostname, p.generation, p.purpose, p.authority_version, p.state, p.updated_at, p.withdrawal_confirmed_at, p.withdrawal_confirmed_authority_version, p.withdrawal_confirmed_generation FROM app_access_serving_publications p JOIN organizations o ON o.id=p.org_id AND o.deleted_at IS NULL WHERE p.org_id=$1 AND p.app_id=$2
`

type GetAppAccessServingPublicationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) GetAppAccessServingPublication(ctx context.Context, arg GetAppAccessServingPublicationParams) (AppAccessServingPublication, error) {
	row := q.db.QueryRow(ctx, getAppAccessServingPublication, arg.OrgID, arg.AppID)
	var i AppAccessServingPublication
	err := row.Scan(
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.AuthorityVersion,
		&i.State,
		&i.UpdatedAt,
		&i.WithdrawalConfirmedAt,
		&i.WithdrawalConfirmedAuthorityVersion,
		&i.WithdrawalConfirmedGeneration,
	)
	return i, err
}

const getAppAccessServingPublicationLabel = `-- name: GetAppAccessServingPublicationLabel :one
SELECT r.name FROM app_access_serving_publications p JOIN organizations o ON o.id=p.org_id AND o.deleted_at IS NULL
JOIN app_access_revisions r ON r.org_id=p.org_id AND r.app_id=p.app_id AND r.revision=p.revision AND r.digest=p.digest AND r.gateway_id=p.gateway_id
WHERE p.org_id=$1 AND p.app_id=$2
`

type GetAppAccessServingPublicationLabelParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) GetAppAccessServingPublicationLabel(ctx context.Context, arg GetAppAccessServingPublicationLabelParams) (string, error) {
	row := q.db.QueryRow(ctx, getAppAccessServingPublicationLabel, arg.OrgID, arg.AppID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getPreviouslyActivatedAppAccessRevision = `-- name: GetPreviouslyActivatedAppAccessRevision :one
SELECT r.org_id, r.app_id, r.revision, r.name, r.description, r.icon, r.origin_url, r.gateway_id, r.public_hostname, r.idle_timeout_seconds, r.absolute_timeout_seconds, r.digest, r.created_at, r.allowed_destination_cidrs, r.origin_ca_pem, r.origin_ca_digest, r.icon_data_url FROM app_access_revisions r JOIN organizations o ON o.id=r.org_id AND o.deleted_at IS NULL
WHERE r.org_id=$1 AND r.app_id=$2 AND r.revision=$3
 AND EXISTS(SELECT 1 FROM app_access_publication_operations op WHERE op.org_id=r.org_id AND op.app_id=r.app_id AND op.revision=r.revision AND op.digest=r.digest AND op.status='activated')
`

type GetPreviouslyActivatedAppAccessRevisionParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	AppID    uuid.UUID `json:"app_id"`
	Revision int64     `json:"revision"`
}

func (q *Queries) GetPreviouslyActivatedAppAccessRevision(ctx context.Context, arg GetPreviouslyActivatedAppAccessRevisionParams) (AppAccessRevision, error) {
	row := q.db.QueryRow(ctx, getPreviouslyActivatedAppAccessRevision, arg.OrgID, arg.AppID, arg.Revision)
	var i AppAccessRevision
	err := row.Scan(
		&i.OrgID,
		&i.AppID,
		&i.Revision,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.OriginUrl,
		&i.GatewayID,
		&i.PublicHostname,
		&i.IdleTimeoutSeconds,
		&i.AbsoluteTimeoutSeconds,
		&i.Digest,
		&i.CreatedAt,
		&i.AllowedDestinationCidrs,
		&i.OriginCaPem,
		&i.OriginCaDigest,
		&i.IconDataUrl,
	)
	return i, err
}

const lastAppAccessPublicationOperation = `-- name: LastAppAccessPublicationOperation :one
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL WHERE op.org_id=$1 AND op.app_id=$2 ORDER BY op.created_at DESC,op.id DESC LIMIT 1
`

type LastAppAccessPublicationOperationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) LastAppAccessPublicationOperation(ctx context.Context, arg LastAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, lastAppAccessPublicationOperation, arg.OrgID, arg.AppID)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const listAppAccessReadinessCandidates = `-- name: ListAppAccessReadinessCandidates :many
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at,r.origin_url,r.allowed_destination_cidrs,r.origin_ca_pem,r.origin_ca_digest FROM app_access_publication_operations op
JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL
JOIN app_access_settings s ON s.org_id=op.org_id AND s.enabled
JOIN app_access_revisions r ON r.org_id=op.org_id AND r.app_id=op.app_id AND r.revision=op.revision AND r.digest=op.digest AND r.gateway_id=op.gateway_id AND r.public_hostname=op.hostname
WHERE op.deadline>now() AND (op.status='queued' OR (op.status='checking' AND op.proxy_credential_id=$1 AND op.proxy_credential_version=$2))
ORDER BY op.created_at,op.id LIMIT LEAST(GREATEST($3::integer,0),8)
`

type ListAppAccessReadinessCandidatesParams struct {
	ProxyCredentialID      pgtype.UUID `json:"proxy_credential_id"`
	ProxyCredentialVersion *int64      `json:"proxy_credential_version"`
	PageLimit              int32       `json:"page_limit"`
}

type ListAppAccessReadinessCandidatesRow struct {
	ID                             uuid.UUID          `json:"id"`
	OrgID                          uuid.UUID          `json:"org_id"`
	AppID                          uuid.UUID          `json:"app_id"`
	ActorUserID                    uuid.UUID          `json:"actor_user_id"`
	IdempotencyKey                 uuid.UUID          `json:"idempotency_key"`
	ReviewedAppVersion             int64              `json:"reviewed_app_version"`
	ExpectedAppVersion             int64              `json:"expected_app_version"`
	Revision                       int64              `json:"revision"`
	Digest                         string             `json:"digest"`
	OriginCheckID                  uuid.UUID          `json:"origin_check_id"`
	OriginCheckPurpose             string             `json:"origin_check_purpose"`
	GatewayID                      uuid.UUID          `json:"gateway_id"`
	Hostname                       string             `json:"hostname"`
	Generation                     uuid.UUID          `json:"generation"`
	Purpose                        string             `json:"purpose"`
	ExpectedActiveAuthorityVersion int64              `json:"expected_active_authority_version"`
	AuthorityVersion               int64              `json:"authority_version"`
	GatewayCertSerial              string             `json:"gateway_cert_serial"`
	ReadinessRequestID             uuid.UUID          `json:"readiness_request_id"`
	ProxyInstanceTokenHash         []byte             `json:"proxy_instance_token_hash"`
	Deadline                       time.Time          `json:"deadline"`
	Version                        int64              `json:"version"`
	Status                         string             `json:"status"`
	ProxyCredentialID              pgtype.UUID        `json:"proxy_credential_id"`
	ProxyCredentialVersion         *int64             `json:"proxy_credential_version"`
	ClaimedAt                      pgtype.Timestamptz `json:"claimed_at"`
	OriginProofCompletedAt         pgtype.Timestamptz `json:"origin_proof_completed_at"`
	PublicProofCompletedAt         pgtype.Timestamptz `json:"public_proof_completed_at"`
	CompletedAt                    pgtype.Timestamptz `json:"completed_at"`
	PublicDnsStatus                string             `json:"public_dns_status"`
	PublicTlsStatus                string             `json:"public_tls_status"`
	ConnectorDnsStatus             string             `json:"connector_dns_status"`
	ConnectorConnectStatus         string             `json:"connector_connect_status"`
	ConnectorTlsStatus             string             `json:"connector_tls_status"`
	ErrorCode                      string             `json:"error_code"`
	CreatedAt                      time.Time          `json:"created_at"`
	OriginUrl                      string             `json:"origin_url"`
	AllowedDestinationCidrs        []string           `json:"allowed_destination_cidrs"`
	OriginCaPem                    string             `json:"origin_ca_pem"`
	OriginCaDigest                 string             `json:"origin_ca_digest"`
}

// lint:cross-org -- Dedicated installation proxy derives tenants from persisted pending operations; human/body identifiers do not select work.
func (q *Queries) ListAppAccessReadinessCandidates(ctx context.Context, arg ListAppAccessReadinessCandidatesParams) ([]ListAppAccessReadinessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAppAccessReadinessCandidates, arg.ProxyCredentialID, arg.ProxyCredentialVersion, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppAccessReadinessCandidatesRow{}
	for rows.Next() {
		var i ListAppAccessReadinessCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.ActorUserID,
			&i.IdempotencyKey,
			&i.ReviewedAppVersion,
			&i.ExpectedAppVersion,
			&i.Revision,
			&i.Digest,
			&i.OriginCheckID,
			&i.OriginCheckPurpose,
			&i.GatewayID,
			&i.Hostname,
			&i.Generation,
			&i.Purpose,
			&i.ExpectedActiveAuthorityVersion,
			&i.AuthorityVersion,
			&i.GatewayCertSerial,
			&i.ReadinessRequestID,
			&i.ProxyInstanceTokenHash,
			&i.Deadline,
			&i.Version,
			&i.Status,
			&i.ProxyCredentialID,
			&i.ProxyCredentialVersion,
			&i.ClaimedAt,
			&i.OriginProofCompletedAt,
			&i.PublicProofCompletedAt,
			&i.CompletedAt,
			&i.PublicDnsStatus,
			&i.PublicTlsStatus,
			&i.ConnectorDnsStatus,
			&i.ConnectorConnectStatus,
			&i.ConnectorTlsStatus,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.OriginUrl,
			&i.AllowedDestinationCidrs,
			&i.OriginCaPem,
			&i.OriginCaDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimedAppAccessReadiness = `-- name: ListClaimedAppAccessReadiness :many
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL
WHERE op.proxy_credential_id=$1 AND op.proxy_credential_version=$2
 AND op.status='checking' AND op.deadline>now() ORDER BY op.claimed_at,op.id LIMIT 8
`

type ListClaimedAppAccessReadinessParams struct {
	ProxyCredentialID      pgtype.UUID `json:"proxy_credential_id"`
	ProxyCredentialVersion *int64      `json:"proxy_credential_version"`
}

// lint:cross-org -- Dedicated installation proxy's own current credential version identifies admitted outstanding work; stored operations derive tenant scope.
func (q *Queries) ListClaimedAppAccessReadiness(ctx context.Context, arg ListClaimedAppAccessReadinessParams) ([]AppAccessPublicationOperation, error) {
	rows, err := q.db.Query(ctx, listClaimedAppAccessReadiness, arg.ProxyCredentialID, arg.ProxyCredentialVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAccessPublicationOperation{}
	for rows.Next() {
		var i AppAccessPublicationOperation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.ActorUserID,
			&i.IdempotencyKey,
			&i.ReviewedAppVersion,
			&i.ExpectedAppVersion,
			&i.Revision,
			&i.Digest,
			&i.OriginCheckID,
			&i.OriginCheckPurpose,
			&i.GatewayID,
			&i.Hostname,
			&i.Generation,
			&i.Purpose,
			&i.ExpectedActiveAuthorityVersion,
			&i.AuthorityVersion,
			&i.GatewayCertSerial,
			&i.ReadinessRequestID,
			&i.ProxyInstanceTokenHash,
			&i.Deadline,
			&i.Version,
			&i.Status,
			&i.ProxyCredentialID,
			&i.ProxyCredentialVersion,
			&i.ClaimedAt,
			&i.OriginProofCompletedAt,
			&i.PublicProofCompletedAt,
			&i.CompletedAt,
			&i.PublicDnsStatus,
			&i.PublicTlsStatus,
			&i.ConnectorDnsStatus,
			&i.ConnectorConnectStatus,
			&i.ConnectorTlsStatus,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayAppAccessBrowserAssignments = `-- name: ListGatewayAppAccessBrowserAssignments :many
SELECT p.app_id,p.gateway_id,p.revision,p.digest,p.hostname,p.generation,p.purpose,p.authority_version,r.origin_url,r.allowed_destination_cidrs,r.origin_ca_pem,r.origin_ca_digest,'active'::text AS stage,NULL::uuid AS operation_id,NULL::uuid AS readiness_request_id,NULL::timestamptz AS deadline FROM app_access_serving_publications p
JOIN organizations o ON o.id=p.org_id AND o.deleted_at IS NULL
JOIN app_access_applications app ON app.org_id=p.org_id AND app.id=p.app_id AND app.state='draft'
JOIN app_access_revisions r ON r.org_id=p.org_id AND r.app_id=p.app_id AND r.gateway_id=p.gateway_id AND r.revision=p.revision AND r.digest=p.digest AND r.public_hostname=p.hostname
WHERE p.org_id=$1 AND p.gateway_id=$2 AND p.state='active'
UNION ALL
SELECT op.app_id,op.gateway_id,op.revision,op.digest,op.hostname,op.generation,op.purpose,op.authority_version,r.origin_url,r.allowed_destination_cidrs,r.origin_ca_pem,r.origin_ca_digest,'pending'::text AS stage,op.id AS operation_id,op.readiness_request_id,op.deadline FROM app_access_publication_operations op
JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL
JOIN app_access_applications app ON app.org_id=op.org_id AND app.id=op.app_id AND app.state='draft'
JOIN app_access_revisions r ON r.org_id=op.org_id AND r.app_id=op.app_id AND r.gateway_id=op.gateway_id AND r.revision=op.revision AND r.digest=op.digest AND r.public_hostname=op.hostname
WHERE op.org_id=$1 AND op.gateway_id=$2 AND op.status IN('queued','checking') AND op.deadline>now()
ORDER BY app_id,generation LIMIT 64
`

type ListGatewayAppAccessBrowserAssignmentsParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

type ListGatewayAppAccessBrowserAssignmentsRow struct {
	AppID                   uuid.UUID          `json:"app_id"`
	GatewayID               uuid.UUID          `json:"gateway_id"`
	Revision                int64              `json:"revision"`
	Digest                  string             `json:"digest"`
	Hostname                string             `json:"hostname"`
	Generation              uuid.UUID          `json:"generation"`
	Purpose                 string             `json:"purpose"`
	AuthorityVersion        int64              `json:"authority_version"`
	OriginUrl               string             `json:"origin_url"`
	AllowedDestinationCidrs []string           `json:"allowed_destination_cidrs"`
	OriginCaPem             string             `json:"origin_ca_pem"`
	OriginCaDigest          string             `json:"origin_ca_digest"`
	Stage                   string             `json:"stage"`
	OperationID             pgtype.UUID        `json:"operation_id"`
	ReadinessRequestID      pgtype.UUID        `json:"readiness_request_id"`
	Deadline                pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) ListGatewayAppAccessBrowserAssignments(ctx context.Context, arg ListGatewayAppAccessBrowserAssignmentsParams) ([]ListGatewayAppAccessBrowserAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listGatewayAppAccessBrowserAssignments, arg.OrgID, arg.GatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayAppAccessBrowserAssignmentsRow{}
	for rows.Next() {
		var i ListGatewayAppAccessBrowserAssignmentsRow
		if err := rows.Scan(
			&i.AppID,
			&i.GatewayID,
			&i.Revision,
			&i.Digest,
			&i.Hostname,
			&i.Generation,
			&i.Purpose,
			&i.AuthorityVersion,
			&i.OriginUrl,
			&i.AllowedDestinationCidrs,
			&i.OriginCaPem,
			&i.OriginCaDigest,
			&i.Stage,
			&i.OperationID,
			&i.ReadinessRequestID,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviouslyActivatedAppAccessRevisions = `-- name: ListPreviouslyActivatedAppAccessRevisions :many
SELECT r.revision,r.digest,r.name,r.public_hostname AS hostname,r.gateway_id,max(op.completed_at)::timestamptz AS activated_at
FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL
JOIN app_access_revisions r ON r.org_id=op.org_id AND r.app_id=op.app_id AND r.revision=op.revision AND r.digest=op.digest
WHERE op.org_id=$1 AND op.app_id=$2 AND op.status='activated'
GROUP BY r.revision,r.digest,r.name,r.public_hostname,r.gateway_id ORDER BY r.revision DESC LIMIT LEAST(GREATEST($3::integer,0),50)
`

type ListPreviouslyActivatedAppAccessRevisionsParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	AppID     uuid.UUID `json:"app_id"`
	PageLimit int32     `json:"page_limit"`
}

type ListPreviouslyActivatedAppAccessRevisionsRow struct {
	Revision    int64     `json:"revision"`
	Digest      string    `json:"digest"`
	Name        string    `json:"name"`
	Hostname    string    `json:"hostname"`
	GatewayID   uuid.UUID `json:"gateway_id"`
	ActivatedAt time.Time `json:"activated_at"`
}

func (q *Queries) ListPreviouslyActivatedAppAccessRevisions(ctx context.Context, arg ListPreviouslyActivatedAppAccessRevisionsParams) ([]ListPreviouslyActivatedAppAccessRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listPreviouslyActivatedAppAccessRevisions, arg.OrgID, arg.AppID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreviouslyActivatedAppAccessRevisionsRow{}
	for rows.Next() {
		var i ListPreviouslyActivatedAppAccessRevisionsRow
		if err := rows.Scan(
			&i.Revision,
			&i.Digest,
			&i.Name,
			&i.Hostname,
			&i.GatewayID,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppAccessPublicationOperation = `-- name: LockAppAccessPublicationOperation :one
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL WHERE op.org_id=$1 AND op.app_id=$2 AND op.id=$3 FOR UPDATE OF op
`

type LockAppAccessPublicationOperationParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	AppID       uuid.UUID `json:"app_id"`
	OperationID uuid.UUID `json:"operation_id"`
}

func (q *Queries) LockAppAccessPublicationOperation(ctx context.Context, arg LockAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, lockAppAccessPublicationOperation, arg.OrgID, arg.AppID, arg.OperationID)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const lockAppAccessServingPublication = `-- name: LockAppAccessServingPublication :one
SELECT p.org_id, p.app_id, p.gateway_id, p.revision, p.digest, p.hostname, p.generation, p.purpose, p.authority_version, p.state, p.updated_at, p.withdrawal_confirmed_at, p.withdrawal_confirmed_authority_version, p.withdrawal_confirmed_generation FROM app_access_serving_publications p JOIN organizations o ON o.id=p.org_id AND o.deleted_at IS NULL WHERE p.org_id=$1 AND p.app_id=$2 FOR UPDATE OF p
`

type LockAppAccessServingPublicationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) LockAppAccessServingPublication(ctx context.Context, arg LockAppAccessServingPublicationParams) (AppAccessServingPublication, error) {
	row := q.db.QueryRow(ctx, lockAppAccessServingPublication, arg.OrgID, arg.AppID)
	var i AppAccessServingPublication
	err := row.Scan(
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.AuthorityVersion,
		&i.State,
		&i.UpdatedAt,
		&i.WithdrawalConfirmedAt,
		&i.WithdrawalConfirmedAuthorityVersion,
		&i.WithdrawalConfirmedGeneration,
	)
	return i, err
}

const markAppAccessPublicationActivated = `-- name: MarkAppAccessPublicationActivated :one
UPDATE app_access_publication_operations SET status='activated',completed_at=now(),version=version+1 WHERE org_id=$1 AND app_id=$2 AND id=$3 AND version=$4 AND status='checking' AND deadline>now() RETURNING id, org_id, app_id, actor_user_id, idempotency_key, reviewed_app_version, expected_app_version, revision, digest, origin_check_id, origin_check_purpose, gateway_id, hostname, generation, purpose, expected_active_authority_version, authority_version, gateway_cert_serial, readiness_request_id, proxy_instance_token_hash, deadline, version, status, proxy_credential_id, proxy_credential_version, claimed_at, origin_proof_completed_at, public_proof_completed_at, completed_at, public_dns_status, public_tls_status, connector_dns_status, connector_connect_status, connector_tls_status, error_code, created_at
`

type MarkAppAccessPublicationActivatedParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	AppID           uuid.UUID `json:"app_id"`
	OperationID     uuid.UUID `json:"operation_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) MarkAppAccessPublicationActivated(ctx context.Context, arg MarkAppAccessPublicationActivatedParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, markAppAccessPublicationActivated,
		arg.OrgID,
		arg.AppID,
		arg.OperationID,
		arg.ExpectedVersion,
	)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const pendingAppAccessPublicationOperation = `-- name: PendingAppAccessPublicationOperation :one
SELECT op.id, op.org_id, op.app_id, op.actor_user_id, op.idempotency_key, op.reviewed_app_version, op.expected_app_version, op.revision, op.digest, op.origin_check_id, op.origin_check_purpose, op.gateway_id, op.hostname, op.generation, op.purpose, op.expected_active_authority_version, op.authority_version, op.gateway_cert_serial, op.readiness_request_id, op.proxy_instance_token_hash, op.deadline, op.version, op.status, op.proxy_credential_id, op.proxy_credential_version, op.claimed_at, op.origin_proof_completed_at, op.public_proof_completed_at, op.completed_at, op.public_dns_status, op.public_tls_status, op.connector_dns_status, op.connector_connect_status, op.connector_tls_status, op.error_code, op.created_at FROM app_access_publication_operations op JOIN organizations o ON o.id=op.org_id AND o.deleted_at IS NULL WHERE op.org_id=$1 AND op.app_id=$2 AND op.status IN('queued','checking') AND op.deadline>now()
`

type PendingAppAccessPublicationOperationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) PendingAppAccessPublicationOperation(ctx context.Context, arg PendingAppAccessPublicationOperationParams) (AppAccessPublicationOperation, error) {
	row := q.db.QueryRow(ctx, pendingAppAccessPublicationOperation, arg.OrgID, arg.AppID)
	var i AppAccessPublicationOperation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.ReviewedAppVersion,
		&i.ExpectedAppVersion,
		&i.Revision,
		&i.Digest,
		&i.OriginCheckID,
		&i.OriginCheckPurpose,
		&i.GatewayID,
		&i.Hostname,
		&i.Generation,
		&i.Purpose,
		&i.ExpectedActiveAuthorityVersion,
		&i.AuthorityVersion,
		&i.GatewayCertSerial,
		&i.ReadinessRequestID,
		&i.ProxyInstanceTokenHash,
		&i.Deadline,
		&i.Version,
		&i.Status,
		&i.ProxyCredentialID,
		&i.ProxyCredentialVersion,
		&i.ClaimedAt,
		&i.OriginProofCompletedAt,
		&i.PublicProofCompletedAt,
		&i.CompletedAt,
		&i.PublicDnsStatus,
		&i.PublicTlsStatus,
		&i.ConnectorDnsStatus,
		&i.ConnectorConnectStatus,
		&i.ConnectorTlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const reportAppAccessBrowserGatewayRuntime = `-- name: ReportAppAccessBrowserGatewayRuntime :one
INSERT INTO app_access_browser_gateway_runtime(org_id,gateway_id,capability_version,reported_cert_serial) VALUES($1,$2,$3,$4)
ON CONFLICT(org_id,gateway_id) DO UPDATE SET capability_version=EXCLUDED.capability_version,reported_cert_serial=EXCLUDED.reported_cert_serial,reported_at=now() RETURNING org_id, gateway_id, capability_version, reported_cert_serial, reported_at
`

type ReportAppAccessBrowserGatewayRuntimeParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	GatewayID          uuid.UUID `json:"gateway_id"`
	CapabilityVersion  int32     `json:"capability_version"`
	ReportedCertSerial string    `json:"reported_cert_serial"`
}

func (q *Queries) ReportAppAccessBrowserGatewayRuntime(ctx context.Context, arg ReportAppAccessBrowserGatewayRuntimeParams) (AppAccessBrowserGatewayRuntime, error) {
	row := q.db.QueryRow(ctx, reportAppAccessBrowserGatewayRuntime,
		arg.OrgID,
		arg.GatewayID,
		arg.CapabilityVersion,
		arg.ReportedCertSerial,
	)
	var i AppAccessBrowserGatewayRuntime
	err := row.Scan(
		&i.OrgID,
		&i.GatewayID,
		&i.CapabilityVersion,
		&i.ReportedCertSerial,
		&i.ReportedAt,
	)
	return i, err
}
