// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access_retention.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appAccessRetentionMorePending = `-- name: AppAccessRetentionMorePending :one
SELECT app_access_retention_has_work($1::uuid,$2::timestamptz,$3::timestamptz)::boolean AS more_pending
`

type AppAccessRetentionMorePendingParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	GrantCutoff time.Time `json:"grant_cutoff"`
	AuditCutoff time.Time `json:"audit_cutoff"`
}

func (q *Queries) AppAccessRetentionMorePending(ctx context.Context, arg AppAccessRetentionMorePendingParams) (bool, error) {
	row := q.db.QueryRow(ctx, appAccessRetentionMorePending, arg.OrgID, arg.GrantCutoff, arg.AuditCutoff)
	var more_pending bool
	err := row.Scan(&more_pending)
	return more_pending, err
}

const createAppAccessRetentionRun = `-- name: CreateAppAccessRetentionRun :one
WITH moment AS (SELECT clock_timestamp() AS value)
INSERT INTO app_access_retention_runs(org_id,started_at,grant_cutoff_at,audit_cutoff_at,lease_expires_at)
SELECT $1,value,value-interval '2160 hours',value-interval '8760 hours',value+interval '15 minutes' FROM moment RETURNING id, org_id, status, started_at, grant_cutoff_at, audit_cutoff_at, lease_expires_at, completed_at, grants_deleted, audits_deleted, batches, more_pending, error_code
`

func (q *Queries) CreateAppAccessRetentionRun(ctx context.Context, orgID uuid.UUID) (AppAccessRetentionRun, error) {
	row := q.db.QueryRow(ctx, createAppAccessRetentionRun, orgID)
	var i AppAccessRetentionRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.StartedAt,
		&i.GrantCutoffAt,
		&i.AuditCutoffAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.GrantsDeleted,
		&i.AuditsDeleted,
		&i.Batches,
		&i.MorePending,
		&i.ErrorCode,
	)
	return i, err
}

const expireAppAccessRetentionRun = `-- name: ExpireAppAccessRetentionRun :execrows
UPDATE app_access_retention_runs SET status='failed',error_code='lease_expired',more_pending=true,completed_at=clock_timestamp(),lease_expires_at=NULL
WHERE org_id=$1 AND status='running' AND lease_expires_at<=clock_timestamp()
`

func (q *Queries) ExpireAppAccessRetentionRun(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expireAppAccessRetentionRun, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeAppAccessRetentionFailure = `-- name: FinalizeAppAccessRetentionFailure :one
UPDATE app_access_retention_runs SET status='failed',error_code=$1::text,completed_at=clock_timestamp(),lease_expires_at=NULL
WHERE org_id=$2 AND id=$3 AND status='running' AND lease_expires_at>clock_timestamp() RETURNING id, org_id, status, started_at, grant_cutoff_at, audit_cutoff_at, lease_expires_at, completed_at, grants_deleted, audits_deleted, batches, more_pending, error_code
`

type FinalizeAppAccessRetentionFailureParams struct {
	ErrorCode string    `json:"error_code"`
	OrgID     uuid.UUID `json:"org_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) FinalizeAppAccessRetentionFailure(ctx context.Context, arg FinalizeAppAccessRetentionFailureParams) (AppAccessRetentionRun, error) {
	row := q.db.QueryRow(ctx, finalizeAppAccessRetentionFailure, arg.ErrorCode, arg.OrgID, arg.ID)
	var i AppAccessRetentionRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.StartedAt,
		&i.GrantCutoffAt,
		&i.AuditCutoffAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.GrantsDeleted,
		&i.AuditsDeleted,
		&i.Batches,
		&i.MorePending,
		&i.ErrorCode,
	)
	return i, err
}

const finalizeAppAccessRetentionSuccess = `-- name: FinalizeAppAccessRetentionSuccess :one
UPDATE app_access_retention_runs SET status='succeeded',more_pending=$1,completed_at=clock_timestamp(),lease_expires_at=NULL
WHERE org_id=$2 AND id=$3 AND status='running' AND lease_expires_at>clock_timestamp() RETURNING id, org_id, status, started_at, grant_cutoff_at, audit_cutoff_at, lease_expires_at, completed_at, grants_deleted, audits_deleted, batches, more_pending, error_code
`

type FinalizeAppAccessRetentionSuccessParams struct {
	MorePending bool      `json:"more_pending"`
	OrgID       uuid.UUID `json:"org_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) FinalizeAppAccessRetentionSuccess(ctx context.Context, arg FinalizeAppAccessRetentionSuccessParams) (AppAccessRetentionRun, error) {
	row := q.db.QueryRow(ctx, finalizeAppAccessRetentionSuccess, arg.MorePending, arg.OrgID, arg.ID)
	var i AppAccessRetentionRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.StartedAt,
		&i.GrantCutoffAt,
		&i.AuditCutoffAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.GrantsDeleted,
		&i.AuditsDeleted,
		&i.Batches,
		&i.MorePending,
		&i.ErrorCode,
	)
	return i, err
}

const isAppAccessRetentionDue = `-- name: IsAppAccessRetentionDue :one
SELECT (app_access_retention_has_work($1::uuid,statement_timestamp()-interval '2160 hours',statement_timestamp()-interval '8760 hours')
 AND NOT EXISTS(SELECT 1 FROM app_access_retention_runs r WHERE r.org_id=$1 AND r.status='running')
 AND COALESCE((SELECT r.started_at<=statement_timestamp()-interval '1 hour' OR (r.status='succeeded' AND r.more_pending) OR COALESCE(r.error_code='lease_expired',false)
  FROM app_access_retention_runs r WHERE r.org_id=$1 ORDER BY r.started_at DESC,r.id DESC LIMIT 1),true))::boolean AS due
`

func (q *Queries) IsAppAccessRetentionDue(ctx context.Context, orgID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAppAccessRetentionDue, orgID)
	var due bool
	err := row.Scan(&due)
	return due, err
}

const listDueAppAccessRetentionOrganizations = `-- name: ListDueAppAccessRetentionOrganizations :many
SELECT o.id FROM organizations o
WHERE EXISTS(SELECT 1 FROM app_access_retention_runs r WHERE r.org_id=o.id AND r.status='running' AND r.lease_expires_at<=statement_timestamp())
 OR (app_access_retention_has_work(o.id,statement_timestamp()-interval '2160 hours',statement_timestamp()-interval '8760 hours')
  AND NOT EXISTS(SELECT 1 FROM app_access_retention_runs r WHERE r.org_id=o.id AND r.status='running')
  AND COALESCE((SELECT r.started_at<=statement_timestamp()-interval '1 hour' OR (r.status='succeeded' AND r.more_pending) OR COALESCE(r.error_code='lease_expired',false)
   FROM app_access_retention_runs r WHERE r.org_id=o.id ORDER BY r.started_at DESC,r.id DESC LIMIT 1),true))
ORDER BY o.id LIMIT $1
`

// Fixed App Access retention has no public/manual cleanup API or caller cutoff.
// lint:cross-org — the leader enumerates only fixed-policy work or expired claims.
// lint:allow-deleted — soft-deleted organizations keep their fixed evidence policy.
func (q *Queries) ListDueAppAccessRetentionOrganizations(ctx context.Context, pageLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueAppAccessRetentionOrganizations, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAppAccessRetentionBatch = `-- name: PruneAppAccessRetentionBatch :one
SELECT app_access_retention_prune_batch($1::uuid)::bigint AS deleted
`

func (q *Queries) PruneAppAccessRetentionBatch(ctx context.Context, runID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, pruneAppAccessRetentionBatch, runID)
	var deleted int64
	err := row.Scan(&deleted)
	return deleted, err
}

const renewAppAccessRetentionRun = `-- name: RenewAppAccessRetentionRun :execrows
UPDATE app_access_retention_runs SET lease_expires_at=clock_timestamp()+interval '15 minutes'
WHERE org_id=$1 AND id=$2 AND status='running' AND lease_expires_at>clock_timestamp()
`

type RenewAppAccessRetentionRunParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) RenewAppAccessRetentionRun(ctx context.Context, arg RenewAppAccessRetentionRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewAppAccessRetentionRun, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
