// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access_parent_authority.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cASUserPasswordRehash = `-- name: CASUserPasswordRehash :execrows
UPDATE users SET password_hash = $1
WHERE id = $2 AND deleted_at IS NULL
 AND password_hash = $3 AND app_auth_epoch = $4
`

type CASUserPasswordRehashParams struct {
	NewHash       *string   `json:"new_hash"`
	UserID        uuid.UUID `json:"user_id"`
	ExpectedHash  *string   `json:"expected_hash"`
	ExpectedEpoch int64     `json:"expected_epoch"`
}

// lint:cross-org — verified native login has no organization context.
func (q *Queries) CASUserPasswordRehash(ctx context.Context, arg CASUserPasswordRehashParams) (int64, error) {
	result, err := q.db.Exec(ctx, cASUserPasswordRehash,
		arg.NewHash,
		arg.UserID,
		arg.ExpectedHash,
		arg.ExpectedEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const changePasswordCASAndBumpAppAuthEpoch = `-- name: ChangePasswordCASAndBumpAppAuthEpoch :one
UPDATE users SET password_hash = $1, app_auth_epoch = app_auth_epoch + 1
WHERE id = $2 AND deleted_at IS NULL
 AND password_hash = $3 AND app_auth_epoch = $4 RETURNING id, email, name, password_hash, email_verified_at, status, created_at, updated_at, deleted_at, can_create_orgs, must_change_password, cp_admin, app_auth_epoch
`

type ChangePasswordCASAndBumpAppAuthEpochParams struct {
	NewHash       *string   `json:"new_hash"`
	UserID        uuid.UUID `json:"user_id"`
	ExpectedHash  *string   `json:"expected_hash"`
	ExpectedEpoch int64     `json:"expected_epoch"`
}

// lint:cross-org — native password verification is user scoped.
func (q *Queries) ChangePasswordCASAndBumpAppAuthEpoch(ctx context.Context, arg ChangePasswordCASAndBumpAppAuthEpochParams) (User, error) {
	row := q.db.QueryRow(ctx, changePasswordCASAndBumpAppAuthEpoch,
		arg.NewHash,
		arg.UserID,
		arg.ExpectedHash,
		arg.ExpectedEpoch,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CanCreateOrgs,
		&i.MustChangePassword,
		&i.CpAdmin,
		&i.AppAuthEpoch,
	)
	return i, err
}

const createMfaChallengeWithAuthority = `-- name: CreateMfaChallengeWithAuthority :execrows
INSERT INTO mfa_challenges (user_id, token_hash, expires_at, verified_app_auth_epoch)
SELECT u.id, $1, $2::timestamptz, u.app_auth_epoch
FROM users u WHERE u.id = $3 AND u.deleted_at IS NULL AND u.status = 'active'
 AND u.app_auth_epoch = $4
`

type CreateMfaChallengeWithAuthorityParams struct {
	TokenHash     []byte    `json:"token_hash"`
	ExpiresAt     time.Time `json:"expires_at"`
	UserID        uuid.UUID `json:"user_id"`
	VerifiedEpoch int64     `json:"verified_epoch"`
}

// lint:cross-org — verified native password login challenge precedes organization selection.
func (q *Queries) CreateMfaChallengeWithAuthority(ctx context.Context, arg CreateMfaChallengeWithAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, createMfaChallengeWithAuthority,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserID,
		arg.VerifiedEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isAppParentLogoutRevoked = `-- name: IsAppParentLogoutRevoked :one
SELECT EXISTS(SELECT 1 FROM app_access_parent_logout_tombstones WHERE parent_hash = $1)
`

// lint:cross-org — exact hashed native parent token independently establishes its revocation lookup.
func (q *Queries) IsAppParentLogoutRevoked(ctx context.Context, parentHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, isAppParentLogoutRevoked, parentHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordAppParentLogout = `-- name: RecordAppParentLogout :exec
INSERT INTO app_access_parent_logout_tombstones (parent_hash, user_id, parent_expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (parent_hash) DO UPDATE SET parent_expires_at = GREATEST(app_access_parent_logout_tombstones.parent_expires_at, EXCLUDED.parent_expires_at)
`

type RecordAppParentLogoutParams struct {
	ParentHash      []byte    `json:"parent_hash"`
	UserID          uuid.UUID `json:"user_id"`
	ParentExpiresAt time.Time `json:"parent_expires_at"`
}

// lint:cross-org — exact native parent session logout is user scoped.
func (q *Queries) RecordAppParentLogout(ctx context.Context, arg RecordAppParentLogoutParams) error {
	_, err := q.db.Exec(ctx, recordAppParentLogout, arg.ParentHash, arg.UserID, arg.ParentExpiresAt)
	return err
}

const setUserPasswordAndBumpAppAuthEpoch = `-- name: SetUserPasswordAndBumpAppAuthEpoch :one
UPDATE users SET password_hash = $1, app_auth_epoch = app_auth_epoch + 1
WHERE id = $2 AND deleted_at IS NULL RETURNING id, email, name, password_hash, email_verified_at, status, created_at, updated_at, deleted_at, can_create_orgs, must_change_password, cp_admin, app_auth_epoch
`

type SetUserPasswordAndBumpAppAuthEpochParams struct {
	NewHash *string   `json:"new_hash"`
	UserID  uuid.UUID `json:"user_id"`
}

// lint:cross-org — native reset credential is user scoped.
func (q *Queries) SetUserPasswordAndBumpAppAuthEpoch(ctx context.Context, arg SetUserPasswordAndBumpAppAuthEpochParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPasswordAndBumpAppAuthEpoch, arg.NewHash, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CanCreateOrgs,
		&i.MustChangePassword,
		&i.CpAdmin,
		&i.AppAuthEpoch,
	)
	return i, err
}
