// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceAppAccessDraft = `-- name: AdvanceAppAccessDraft :exec
UPDATE app_access_applications SET version=version+1,draft_revision=version+1,updated_at=now() WHERE org_id=$1 AND id=$2 AND state='draft'
`

type AdvanceAppAccessDraftParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AdvanceAppAccessDraft(ctx context.Context, arg AdvanceAppAccessDraftParams) error {
	_, err := q.db.Exec(ctx, advanceAppAccessDraft, arg.OrgID, arg.ID)
	return err
}

const appAccessGatewayExists = `-- name: AppAccessGatewayExists :one
SELECT EXISTS(SELECT 1 FROM nodes WHERE org_id=$1 AND id=$2 AND status='active' AND enrolled_kind='gateway')
`

type AppAccessGatewayExistsParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AppAccessGatewayExists(ctx context.Context, arg AppAccessGatewayExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, appAccessGatewayExists, arg.OrgID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const appAccessOrganizationExists = `-- name: AppAccessOrganizationExists :one
SELECT EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL)
`

func (q *Queries) AppAccessOrganizationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, appAccessOrganizationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAppAccessApplication = `-- name: CreateAppAccessApplication :one
INSERT INTO app_access_applications(org_id) VALUES($1) RETURNING id
`

func (q *Queries) CreateAppAccessApplication(ctx context.Context, orgID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAppAccessApplication, orgID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureAppAccessSettings = `-- name: EnsureAppAccessSettings :exec
INSERT INTO app_access_settings(org_id) VALUES($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureAppAccessSettings(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureAppAccessSettings, orgID)
	return err
}

const getAppAccessApplication = `-- name: GetAppAccessApplication :one
SELECT id,org_id,version,draft_revision,state,created_at,updated_at FROM app_access_applications WHERE org_id = $1 AND app_access_applications.id = $2 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL)
`

type GetAppAccessApplicationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

type GetAppAccessApplicationRow struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	Version       int64     `json:"version"`
	DraftRevision int64     `json:"draft_revision"`
	State         string    `json:"state"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetAppAccessApplication(ctx context.Context, arg GetAppAccessApplicationParams) (GetAppAccessApplicationRow, error) {
	row := q.db.QueryRow(ctx, getAppAccessApplication, arg.OrgID, arg.ID)
	var i GetAppAccessApplicationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Version,
		&i.DraftRevision,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppAccessMFAPolicy = `-- name: GetAppAccessMFAPolicy :one
SELECT COALESCE((to_jsonb(a)->>'require_mfa')::boolean,false)::boolean AS require_mfa
FROM app_access_applications a JOIN organizations o ON o.id=a.org_id AND o.deleted_at IS NULL
WHERE a.org_id=$1 AND a.id=$2
`

type GetAppAccessMFAPolicyParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

// JSON projection keeps historical pre-policy schema reads compatible; writes require migration 176.
func (q *Queries) GetAppAccessMFAPolicy(ctx context.Context, arg GetAppAccessMFAPolicyParams) (bool, error) {
	row := q.db.QueryRow(ctx, getAppAccessMFAPolicy, arg.OrgID, arg.ID)
	var require_mfa bool
	err := row.Scan(&require_mfa)
	return require_mfa, err
}

const getAppAccessRevision = `-- name: GetAppAccessRevision :one
SELECT org_id, app_id, revision, name, description, icon, origin_url, gateway_id, public_hostname, idle_timeout_seconds, absolute_timeout_seconds, digest, created_at, allowed_destination_cidrs, origin_ca_pem, origin_ca_digest, icon_data_url FROM app_access_revisions WHERE org_id = $1 AND app_id = $2 AND revision = $3 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL)
`

type GetAppAccessRevisionParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	AppID    uuid.UUID `json:"app_id"`
	Revision int64     `json:"revision"`
}

func (q *Queries) GetAppAccessRevision(ctx context.Context, arg GetAppAccessRevisionParams) (AppAccessRevision, error) {
	row := q.db.QueryRow(ctx, getAppAccessRevision, arg.OrgID, arg.AppID, arg.Revision)
	var i AppAccessRevision
	err := row.Scan(
		&i.OrgID,
		&i.AppID,
		&i.Revision,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.OriginUrl,
		&i.GatewayID,
		&i.PublicHostname,
		&i.IdleTimeoutSeconds,
		&i.AbsoluteTimeoutSeconds,
		&i.Digest,
		&i.CreatedAt,
		&i.AllowedDestinationCidrs,
		&i.OriginCaPem,
		&i.OriginCaDigest,
		&i.IconDataUrl,
	)
	return i, err
}

const getAppAccessSettings = `-- name: GetAppAccessSettings :one
SELECT live_org.id AS org_id, COALESCE(setting.enabled,false)::boolean AS enabled, COALESCE(setting.version,1)::bigint AS version FROM organizations live_org LEFT JOIN app_access_settings setting ON setting.org_id=live_org.id WHERE live_org.id=$1 AND live_org.deleted_at IS NULL
`

type GetAppAccessSettingsRow struct {
	OrgID   uuid.UUID `json:"org_id"`
	Enabled bool      `json:"enabled"`
	Version int64     `json:"version"`
}

func (q *Queries) GetAppAccessSettings(ctx context.Context, id uuid.UUID) (GetAppAccessSettingsRow, error) {
	row := q.db.QueryRow(ctx, getAppAccessSettings, id)
	var i GetAppAccessSettingsRow
	err := row.Scan(&i.OrgID, &i.Enabled, &i.Version)
	return i, err
}

const insertAppAccessRevision = `-- name: InsertAppAccessRevision :exec
INSERT INTO app_access_revisions(org_id,app_id,revision,name,description,icon,origin_url,gateway_id,public_hostname,idle_timeout_seconds,absolute_timeout_seconds,digest,allowed_destination_cidrs,origin_ca_pem,origin_ca_digest,icon_data_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type InsertAppAccessRevisionParams struct {
	OrgID                   uuid.UUID `json:"org_id"`
	AppID                   uuid.UUID `json:"app_id"`
	Revision                int64     `json:"revision"`
	Name                    string    `json:"name"`
	Description             string    `json:"description"`
	Icon                    string    `json:"icon"`
	OriginUrl               string    `json:"origin_url"`
	GatewayID               uuid.UUID `json:"gateway_id"`
	PublicHostname          string    `json:"public_hostname"`
	IdleTimeoutSeconds      int32     `json:"idle_timeout_seconds"`
	AbsoluteTimeoutSeconds  int32     `json:"absolute_timeout_seconds"`
	Digest                  string    `json:"digest"`
	AllowedDestinationCidrs []string  `json:"allowed_destination_cidrs"`
	OriginCaPem             string    `json:"origin_ca_pem"`
	OriginCaDigest          string    `json:"origin_ca_digest"`
	IconDataUrl             string    `json:"icon_data_url"`
}

func (q *Queries) InsertAppAccessRevision(ctx context.Context, arg InsertAppAccessRevisionParams) error {
	_, err := q.db.Exec(ctx, insertAppAccessRevision,
		arg.OrgID,
		arg.AppID,
		arg.Revision,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.OriginUrl,
		arg.GatewayID,
		arg.PublicHostname,
		arg.IdleTimeoutSeconds,
		arg.AbsoluteTimeoutSeconds,
		arg.Digest,
		arg.AllowedDestinationCidrs,
		arg.OriginCaPem,
		arg.OriginCaDigest,
		arg.IconDataUrl,
	)
	return err
}

const listAppAccessApplicationIDs = `-- name: ListAppAccessApplicationIDs :many
SELECT a.id FROM app_access_applications a JOIN app_access_revisions r ON r.org_id=a.org_id AND r.app_id=a.id AND r.revision=a.draft_revision WHERE a.org_id=$1 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL) AND strpos(lower(r.name),lower($2::text))>0 AND (a.state<>'archived' OR $3::text='archived') AND ($3::text='' OR $3::text=CASE WHEN a.state='archived' THEN 'archived' WHEN EXISTS(SELECT 1 FROM app_access_serving_publications p WHERE p.org_id=a.org_id AND p.app_id=a.id AND p.state='active') THEN 'published' WHEN EXISTS(SELECT 1 FROM app_access_serving_publications p WHERE p.org_id=a.org_id AND p.app_id=a.id AND p.state='disabled') THEN 'disabled' ELSE 'unpublished' END) ORDER BY a.created_at,a.id LIMIT $5 OFFSET $4
`

type ListAppAccessApplicationIDsParams struct {
	OrgID            uuid.UUID `json:"org_id"`
	Search           string    `json:"search"`
	PublicationState string    `json:"publication_state"`
	PageOffset       int32     `json:"page_offset"`
	PageLimit        int32     `json:"page_limit"`
}

func (q *Queries) ListAppAccessApplicationIDs(ctx context.Context, arg ListAppAccessApplicationIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAppAccessApplicationIDs,
		arg.OrgID,
		arg.Search,
		arg.PublicationState,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveAppAccessOrganization = `-- name: LockActiveAppAccessOrganization :one
SELECT id FROM organizations WHERE id=$1 AND deleted_at IS NULL FOR SHARE
`

func (q *Queries) LockActiveAppAccessOrganization(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockActiveAppAccessOrganization, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockAppAccessApplication = `-- name: LockAppAccessApplication :one
SELECT version FROM app_access_applications WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockAppAccessApplicationParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) LockAppAccessApplication(ctx context.Context, arg LockAppAccessApplicationParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockAppAccessApplication, arg.OrgID, arg.ID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockAppAccessSettings = `-- name: LockAppAccessSettings :one
SELECT enabled FROM app_access_settings WHERE org_id=$1 FOR SHARE
`

func (q *Queries) LockAppAccessSettings(ctx context.Context, orgID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, lockAppAccessSettings, orgID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const ownsAppAccessHostname = `-- name: OwnsAppAccessHostname :one
SELECT app_id=$2 AND org_id=$3 FROM app_access_hostnames h WHERE hostname=$1 AND (to_jsonb(h)->>'released_at') IS NULL
`

type OwnsAppAccessHostnameParams struct {
	Hostname string    `json:"hostname"`
	AppID    uuid.UUID `json:"app_id"`
	OrgID    uuid.UUID `json:"org_id"`
}

// JSON projection preserves historical pre-release schema qualification.
func (q *Queries) OwnsAppAccessHostname(ctx context.Context, arg OwnsAppAccessHostnameParams) (*bool, error) {
	row := q.db.QueryRow(ctx, ownsAppAccessHostname, arg.Hostname, arg.AppID, arg.OrgID)
	var column_1 *bool
	err := row.Scan(&column_1)
	return column_1, err
}

const reserveAppAccessHostname = `-- name: ReserveAppAccessHostname :exec
INSERT INTO app_access_hostnames(hostname,org_id,app_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING
`

type ReserveAppAccessHostnameParams struct {
	Hostname string    `json:"hostname"`
	OrgID    uuid.UUID `json:"org_id"`
	AppID    uuid.UUID `json:"app_id"`
}

func (q *Queries) ReserveAppAccessHostname(ctx context.Context, arg ReserveAppAccessHostnameParams) error {
	_, err := q.db.Exec(ctx, reserveAppAccessHostname, arg.Hostname, arg.OrgID, arg.AppID)
	return err
}

const updateAppAccessMFAPolicy = `-- name: UpdateAppAccessMFAPolicy :execrows
UPDATE app_access_applications SET require_mfa=$1,version=version+1,updated_at=now()
WHERE org_id=$2 AND id=$3 AND version=$4 AND state='draft'
`

type UpdateAppAccessMFAPolicyParams struct {
	RequireMfa      bool      `json:"require_mfa"`
	OrgID           uuid.UUID `json:"org_id"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) UpdateAppAccessMFAPolicy(ctx context.Context, arg UpdateAppAccessMFAPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppAccessMFAPolicy,
		arg.RequireMfa,
		arg.OrgID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAppAccessSettings = `-- name: UpdateAppAccessSettings :execrows
UPDATE app_access_settings SET enabled=$2,version=version+1 WHERE org_id=$1 AND version=$3
`

type UpdateAppAccessSettingsParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	Enabled bool      `json:"enabled"`
	Version int64     `json:"version"`
}

func (q *Queries) UpdateAppAccessSettings(ctx context.Context, arg UpdateAppAccessSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppAccessSettings, arg.OrgID, arg.Enabled, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
