// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access_connector.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appAccessGatewayWorkCounts = `-- name: AppAccessGatewayWorkCounts :one
SELECT (SELECT count(*) FROM app_access_connector_assignments a WHERE a.org_id=$1 AND a.gateway_id=$2 AND a.withdrawn_at IS NULL)::bigint AS assignments,
 count(*) FILTER(WHERE status='running')::bigint AS running, count(*) FILTER(WHERE status='queued')::bigint AS queued,
 count(*) FILTER(WHERE created_at>now()-interval '1 minute')::bigint AS recent FROM app_access_origin_checks WHERE org_id=$1 AND gateway_id=$2
`

type AppAccessGatewayWorkCountsParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

type AppAccessGatewayWorkCountsRow struct {
	Assignments int64 `json:"assignments"`
	Running     int64 `json:"running"`
	Queued      int64 `json:"queued"`
	Recent      int64 `json:"recent"`
}

func (q *Queries) AppAccessGatewayWorkCounts(ctx context.Context, arg AppAccessGatewayWorkCountsParams) (AppAccessGatewayWorkCountsRow, error) {
	row := q.db.QueryRow(ctx, appAccessGatewayWorkCounts, arg.OrgID, arg.GatewayID)
	var i AppAccessGatewayWorkCountsRow
	err := row.Scan(
		&i.Assignments,
		&i.Running,
		&i.Queued,
		&i.Recent,
	)
	return i, err
}

const claimAppAccessChecks = `-- name: ClaimAppAccessChecks :exec
UPDATE app_access_origin_checks SET status='running' WHERE id IN(SELECT c.id FROM app_access_origin_checks c WHERE c.org_id=$1 AND c.gateway_id=$2 AND c.status='queued' AND c.deadline>now() ORDER BY c.created_at,c.id LIMIT $3 FOR UPDATE SKIP LOCKED)
`

type ClaimAppAccessChecksParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ClaimAppAccessChecks(ctx context.Context, arg ClaimAppAccessChecksParams) error {
	_, err := q.db.Exec(ctx, claimAppAccessChecks, arg.OrgID, arg.GatewayID, arg.Limit)
	return err
}

const completeAppAccessCheck = `-- name: CompleteAppAccessCheck :one
UPDATE app_access_origin_checks SET status=$3,dns_status=$4,connect_status=$5,tls_status=$6,error_code=$7,completed_at=now(),completed_cert_serial=$8 WHERE org_id=$1 AND id=$2 AND status='running' AND deadline>now() RETURNING id, org_id, app_id, gateway_id, revision, digest, generation, purpose, status, dns_status, connect_status, tls_status, error_code, created_at, deadline, completed_at, completed_cert_serial
`

type CompleteAppAccessCheckParams struct {
	OrgID               uuid.UUID `json:"org_id"`
	ID                  uuid.UUID `json:"id"`
	Status              string    `json:"status"`
	DnsStatus           string    `json:"dns_status"`
	ConnectStatus       string    `json:"connect_status"`
	TlsStatus           string    `json:"tls_status"`
	ErrorCode           string    `json:"error_code"`
	CompletedCertSerial string    `json:"completed_cert_serial"`
}

func (q *Queries) CompleteAppAccessCheck(ctx context.Context, arg CompleteAppAccessCheckParams) (AppAccessOriginCheck, error) {
	row := q.db.QueryRow(ctx, completeAppAccessCheck,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.DnsStatus,
		arg.ConnectStatus,
		arg.TlsStatus,
		arg.ErrorCode,
		arg.CompletedCertSerial,
	)
	var i AppAccessOriginCheck
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Generation,
		&i.Purpose,
		&i.Status,
		&i.DnsStatus,
		&i.ConnectStatus,
		&i.TlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.Deadline,
		&i.CompletedAt,
		&i.CompletedCertSerial,
	)
	return i, err
}

const createAppAccessAssignment = `-- name: CreateAppAccessAssignment :one
INSERT INTO app_access_connector_assignments(org_id,app_id,gateway_id,revision,digest) VALUES($1,$2,$3,$4,$5) RETURNING generation, org_id, app_id, gateway_id, revision, digest, purpose, withdrawn_at, applied_status, applied_error_code, applied_at, created_at
`

type CreateAppAccessAssignmentParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	AppID     uuid.UUID `json:"app_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
	Revision  int64     `json:"revision"`
	Digest    string    `json:"digest"`
}

func (q *Queries) CreateAppAccessAssignment(ctx context.Context, arg CreateAppAccessAssignmentParams) (AppAccessConnectorAssignment, error) {
	row := q.db.QueryRow(ctx, createAppAccessAssignment,
		arg.OrgID,
		arg.AppID,
		arg.GatewayID,
		arg.Revision,
		arg.Digest,
	)
	var i AppAccessConnectorAssignment
	err := row.Scan(
		&i.Generation,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Purpose,
		&i.WithdrawnAt,
		&i.AppliedStatus,
		&i.AppliedErrorCode,
		&i.AppliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAppAccessCheck = `-- name: CreateAppAccessCheck :one
INSERT INTO app_access_origin_checks(org_id,app_id,gateway_id,revision,digest,generation) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, org_id, app_id, gateway_id, revision, digest, generation, purpose, status, dns_status, connect_status, tls_status, error_code, created_at, deadline, completed_at, completed_cert_serial
`

type CreateAppAccessCheckParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	AppID      uuid.UUID `json:"app_id"`
	GatewayID  uuid.UUID `json:"gateway_id"`
	Revision   int64     `json:"revision"`
	Digest     string    `json:"digest"`
	Generation uuid.UUID `json:"generation"`
}

func (q *Queries) CreateAppAccessCheck(ctx context.Context, arg CreateAppAccessCheckParams) (AppAccessOriginCheck, error) {
	row := q.db.QueryRow(ctx, createAppAccessCheck,
		arg.OrgID,
		arg.AppID,
		arg.GatewayID,
		arg.Revision,
		arg.Digest,
		arg.Generation,
	)
	var i AppAccessOriginCheck
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Generation,
		&i.Purpose,
		&i.Status,
		&i.DnsStatus,
		&i.ConnectStatus,
		&i.TlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.Deadline,
		&i.CompletedAt,
		&i.CompletedCertSerial,
	)
	return i, err
}

const currentAppAccessAssignment = `-- name: CurrentAppAccessAssignment :one
SELECT generation, org_id, app_id, gateway_id, revision, digest, purpose, withdrawn_at, applied_status, applied_error_code, applied_at, created_at FROM app_access_connector_assignments WHERE org_id=$1 AND app_id=$2 AND withdrawn_at IS NULL
`

type CurrentAppAccessAssignmentParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) CurrentAppAccessAssignment(ctx context.Context, arg CurrentAppAccessAssignmentParams) (AppAccessConnectorAssignment, error) {
	row := q.db.QueryRow(ctx, currentAppAccessAssignment, arg.OrgID, arg.AppID)
	var i AppAccessConnectorAssignment
	err := row.Scan(
		&i.Generation,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Purpose,
		&i.WithdrawnAt,
		&i.AppliedStatus,
		&i.AppliedErrorCode,
		&i.AppliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireAppAccessChecks = `-- name: ExpireAppAccessChecks :exec
UPDATE app_access_origin_checks SET status='expired',error_code='deadline_exceeded',completed_at=now() WHERE org_id=$1 AND gateway_id=$2 AND status IN ('queued','running') AND deadline<=now()
`

type ExpireAppAccessChecksParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) ExpireAppAccessChecks(ctx context.Context, arg ExpireAppAccessChecksParams) error {
	_, err := q.db.Exec(ctx, expireAppAccessChecks, arg.OrgID, arg.GatewayID)
	return err
}

const finalizeAppAccessApplicationChecks = `-- name: FinalizeAppAccessApplicationChecks :exec
UPDATE app_access_origin_checks c SET
 status=CASE WHEN c.deadline<=now() THEN 'expired' ELSE 'withdrawn' END,
 error_code=CASE WHEN c.deadline<=now() THEN 'deadline_exceeded' ELSE 'assignment_changed' END,
 completed_at=now()
WHERE c.org_id=$1 AND c.app_id=$2 AND c.status IN('queued','running')
 AND (c.deadline<=now() OR EXISTS(SELECT 1 FROM app_access_connector_assignments a WHERE a.generation=c.generation AND a.withdrawn_at IS NOT NULL))
`

type FinalizeAppAccessApplicationChecksParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) FinalizeAppAccessApplicationChecks(ctx context.Context, arg FinalizeAppAccessApplicationChecksParams) error {
	_, err := q.db.Exec(ctx, finalizeAppAccessApplicationChecks, arg.OrgID, arg.AppID)
	return err
}

const getAppAccessAssignmentGeneration = `-- name: GetAppAccessAssignmentGeneration :one
SELECT generation, org_id, app_id, gateway_id, revision, digest, purpose, withdrawn_at, applied_status, applied_error_code, applied_at, created_at FROM app_access_connector_assignments WHERE org_id=$1 AND generation=$2
`

type GetAppAccessAssignmentGenerationParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	Generation uuid.UUID `json:"generation"`
}

func (q *Queries) GetAppAccessAssignmentGeneration(ctx context.Context, arg GetAppAccessAssignmentGenerationParams) (AppAccessConnectorAssignment, error) {
	row := q.db.QueryRow(ctx, getAppAccessAssignmentGeneration, arg.OrgID, arg.Generation)
	var i AppAccessConnectorAssignment
	err := row.Scan(
		&i.Generation,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Purpose,
		&i.WithdrawnAt,
		&i.AppliedStatus,
		&i.AppliedErrorCode,
		&i.AppliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAppAccessCheck = `-- name: GetAppAccessCheck :one
SELECT c.id, c.org_id, c.app_id, c.gateway_id, c.revision, c.digest, c.generation, c.purpose, c.status, c.dns_status, c.connect_status, c.tls_status, c.error_code, c.created_at, c.deadline, c.completed_at, c.completed_cert_serial FROM app_access_origin_checks c JOIN organizations o ON o.id=c.org_id AND o.deleted_at IS NULL WHERE c.org_id=$1 AND c.app_id=$2 AND c.id=$3
`

type GetAppAccessCheckParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetAppAccessCheck(ctx context.Context, arg GetAppAccessCheckParams) (AppAccessOriginCheck, error) {
	row := q.db.QueryRow(ctx, getAppAccessCheck, arg.OrgID, arg.AppID, arg.ID)
	var i AppAccessOriginCheck
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Generation,
		&i.Purpose,
		&i.Status,
		&i.DnsStatus,
		&i.ConnectStatus,
		&i.TlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.Deadline,
		&i.CompletedAt,
		&i.CompletedCertSerial,
	)
	return i, err
}

const getAppAccessGatewayRuntime = `-- name: GetAppAccessGatewayRuntime :one
SELECT r.org_id, r.gateway_id, r.capability_version, r.reported_cert_serial, r.reported_at FROM app_access_gateway_runtime r JOIN organizations o ON o.id=r.org_id AND o.deleted_at IS NULL WHERE r.org_id=$1 AND r.gateway_id=$2
`

type GetAppAccessGatewayRuntimeParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) GetAppAccessGatewayRuntime(ctx context.Context, arg GetAppAccessGatewayRuntimeParams) (AppAccessGatewayRuntime, error) {
	row := q.db.QueryRow(ctx, getAppAccessGatewayRuntime, arg.OrgID, arg.GatewayID)
	var i AppAccessGatewayRuntime
	err := row.Scan(
		&i.OrgID,
		&i.GatewayID,
		&i.CapabilityVersion,
		&i.ReportedCertSerial,
		&i.ReportedAt,
	)
	return i, err
}

const listGatewayAppAccessAssignments = `-- name: ListGatewayAppAccessAssignments :many
SELECT a.generation, a.org_id, a.app_id, a.gateway_id, a.revision, a.digest, a.purpose, a.withdrawn_at, a.applied_status, a.applied_error_code, a.applied_at, a.created_at,r.origin_url,r.allowed_destination_cidrs,r.origin_ca_pem,r.origin_ca_digest FROM app_access_connector_assignments a JOIN app_access_revisions r ON r.org_id=a.org_id AND r.app_id=a.app_id AND r.revision=a.revision WHERE a.org_id=$1 AND a.gateway_id=$2 AND a.withdrawn_at IS NULL ORDER BY a.created_at,a.generation LIMIT 64
`

type ListGatewayAppAccessAssignmentsParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

type ListGatewayAppAccessAssignmentsRow struct {
	Generation              uuid.UUID          `json:"generation"`
	OrgID                   uuid.UUID          `json:"org_id"`
	AppID                   uuid.UUID          `json:"app_id"`
	GatewayID               uuid.UUID          `json:"gateway_id"`
	Revision                int64              `json:"revision"`
	Digest                  string             `json:"digest"`
	Purpose                 string             `json:"purpose"`
	WithdrawnAt             pgtype.Timestamptz `json:"withdrawn_at"`
	AppliedStatus           string             `json:"applied_status"`
	AppliedErrorCode        string             `json:"applied_error_code"`
	AppliedAt               pgtype.Timestamptz `json:"applied_at"`
	CreatedAt               time.Time          `json:"created_at"`
	OriginUrl               string             `json:"origin_url"`
	AllowedDestinationCidrs []string           `json:"allowed_destination_cidrs"`
	OriginCaPem             string             `json:"origin_ca_pem"`
	OriginCaDigest          string             `json:"origin_ca_digest"`
}

func (q *Queries) ListGatewayAppAccessAssignments(ctx context.Context, arg ListGatewayAppAccessAssignmentsParams) ([]ListGatewayAppAccessAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listGatewayAppAccessAssignments, arg.OrgID, arg.GatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayAppAccessAssignmentsRow{}
	for rows.Next() {
		var i ListGatewayAppAccessAssignmentsRow
		if err := rows.Scan(
			&i.Generation,
			&i.OrgID,
			&i.AppID,
			&i.GatewayID,
			&i.Revision,
			&i.Digest,
			&i.Purpose,
			&i.WithdrawnAt,
			&i.AppliedStatus,
			&i.AppliedErrorCode,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.OriginUrl,
			&i.AllowedDestinationCidrs,
			&i.OriginCaPem,
			&i.OriginCaDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppAccessCheck = `-- name: LockAppAccessCheck :one
SELECT id, org_id, app_id, gateway_id, revision, digest, generation, purpose, status, dns_status, connect_status, tls_status, error_code, created_at, deadline, completed_at, completed_cert_serial FROM app_access_origin_checks WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockAppAccessCheckParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) LockAppAccessCheck(ctx context.Context, arg LockAppAccessCheckParams) (AppAccessOriginCheck, error) {
	row := q.db.QueryRow(ctx, lockAppAccessCheck, arg.OrgID, arg.ID)
	var i AppAccessOriginCheck
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Generation,
		&i.Purpose,
		&i.Status,
		&i.DnsStatus,
		&i.ConnectStatus,
		&i.TlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.Deadline,
		&i.CompletedAt,
		&i.CompletedCertSerial,
	)
	return i, err
}

const lockAppAccessGateway = `-- name: LockAppAccessGateway :one
SELECT n.id,n.org_id,n.cert_serial,n.status,n.enrolled_kind,n.cert_not_after FROM nodes n JOIN organizations o ON o.id=n.org_id AND o.deleted_at IS NULL WHERE n.org_id=$1 AND n.id=$2 FOR SHARE OF n
`

type LockAppAccessGatewayParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

type LockAppAccessGatewayRow struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	CertSerial   string             `json:"cert_serial"`
	Status       string             `json:"status"`
	EnrolledKind *string            `json:"enrolled_kind"`
	CertNotAfter pgtype.Timestamptz `json:"cert_not_after"`
}

func (q *Queries) LockAppAccessGateway(ctx context.Context, arg LockAppAccessGatewayParams) (LockAppAccessGatewayRow, error) {
	row := q.db.QueryRow(ctx, lockAppAccessGateway, arg.OrgID, arg.ID)
	var i LockAppAccessGatewayRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CertSerial,
		&i.Status,
		&i.EnrolledKind,
		&i.CertNotAfter,
	)
	return i, err
}

const lockAppAccessGatewayRuntime = `-- name: LockAppAccessGatewayRuntime :one
SELECT org_id, gateway_id, capability_version, reported_cert_serial, reported_at FROM app_access_gateway_runtime WHERE org_id=$1 AND gateway_id=$2 FOR UPDATE
`

type LockAppAccessGatewayRuntimeParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) LockAppAccessGatewayRuntime(ctx context.Context, arg LockAppAccessGatewayRuntimeParams) (AppAccessGatewayRuntime, error) {
	row := q.db.QueryRow(ctx, lockAppAccessGatewayRuntime, arg.OrgID, arg.GatewayID)
	var i AppAccessGatewayRuntime
	err := row.Scan(
		&i.OrgID,
		&i.GatewayID,
		&i.CapabilityVersion,
		&i.ReportedCertSerial,
		&i.ReportedAt,
	)
	return i, err
}

const pendingAppAccessCheck = `-- name: PendingAppAccessCheck :one
SELECT id, org_id, app_id, gateway_id, revision, digest, generation, purpose, status, dns_status, connect_status, tls_status, error_code, created_at, deadline, completed_at, completed_cert_serial FROM app_access_origin_checks WHERE org_id=$1 AND app_id=$2 AND generation=$3 AND status IN ('queued','running') AND deadline>now() ORDER BY created_at DESC LIMIT 1
`

type PendingAppAccessCheckParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	AppID      uuid.UUID `json:"app_id"`
	Generation uuid.UUID `json:"generation"`
}

func (q *Queries) PendingAppAccessCheck(ctx context.Context, arg PendingAppAccessCheckParams) (AppAccessOriginCheck, error) {
	row := q.db.QueryRow(ctx, pendingAppAccessCheck, arg.OrgID, arg.AppID, arg.Generation)
	var i AppAccessOriginCheck
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.GatewayID,
		&i.Revision,
		&i.Digest,
		&i.Generation,
		&i.Purpose,
		&i.Status,
		&i.DnsStatus,
		&i.ConnectStatus,
		&i.TlsStatus,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.Deadline,
		&i.CompletedAt,
		&i.CompletedCertSerial,
	)
	return i, err
}

const pruneAppAccessAssignmentHistory = `-- name: PruneAppAccessAssignmentHistory :exec
DELETE FROM app_access_connector_assignments a WHERE a.org_id=$1 AND a.app_id=$2 AND a.withdrawn_at IS NOT NULL
 AND a.generation IN(SELECT old.generation FROM app_access_connector_assignments old WHERE old.org_id=$1 AND old.app_id=$2 AND old.withdrawn_at IS NOT NULL ORDER BY old.created_at DESC,old.generation DESC OFFSET 64)
 AND NOT EXISTS(SELECT 1 FROM app_access_origin_checks c WHERE c.generation=a.generation)
`

type PruneAppAccessAssignmentHistoryParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) PruneAppAccessAssignmentHistory(ctx context.Context, arg PruneAppAccessAssignmentHistoryParams) error {
	_, err := q.db.Exec(ctx, pruneAppAccessAssignmentHistory, arg.OrgID, arg.AppID)
	return err
}

const pruneAppAccessCheckHistory = `-- name: PruneAppAccessCheckHistory :exec
DELETE FROM app_access_origin_checks target WHERE target.org_id=$1 AND target.app_id=$2 AND target.status NOT IN('queued','running') AND target.id IN(SELECT c.id FROM app_access_origin_checks c WHERE c.org_id=$1 AND c.app_id=$2 AND c.status NOT IN('queued','running') ORDER BY c.created_at DESC,c.id DESC OFFSET 64) AND NOT EXISTS(SELECT 1 FROM app_access_publication_operations op WHERE op.org_id=target.org_id AND op.app_id=target.app_id AND op.origin_check_id=target.id)
`

type PruneAppAccessCheckHistoryParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) PruneAppAccessCheckHistory(ctx context.Context, arg PruneAppAccessCheckHistoryParams) error {
	_, err := q.db.Exec(ctx, pruneAppAccessCheckHistory, arg.OrgID, arg.AppID)
	return err
}

const reportAppAccessApplied = `-- name: ReportAppAccessApplied :exec
UPDATE app_access_connector_assignments SET applied_status=$3,applied_error_code=$4,applied_at=now() WHERE org_id=$1 AND generation=$2
`

type ReportAppAccessAppliedParams struct {
	OrgID            uuid.UUID `json:"org_id"`
	Generation       uuid.UUID `json:"generation"`
	AppliedStatus    string    `json:"applied_status"`
	AppliedErrorCode string    `json:"applied_error_code"`
}

func (q *Queries) ReportAppAccessApplied(ctx context.Context, arg ReportAppAccessAppliedParams) error {
	_, err := q.db.Exec(ctx, reportAppAccessApplied,
		arg.OrgID,
		arg.Generation,
		arg.AppliedStatus,
		arg.AppliedErrorCode,
	)
	return err
}

const reportAppAccessGatewayRuntime = `-- name: ReportAppAccessGatewayRuntime :one
INSERT INTO app_access_gateway_runtime(org_id,gateway_id,capability_version,reported_cert_serial) VALUES($1,$2,$3,$4)
ON CONFLICT(org_id,gateway_id) DO UPDATE SET capability_version=EXCLUDED.capability_version,reported_cert_serial=EXCLUDED.reported_cert_serial,reported_at=now() RETURNING org_id, gateway_id, capability_version, reported_cert_serial, reported_at
`

type ReportAppAccessGatewayRuntimeParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	GatewayID          uuid.UUID `json:"gateway_id"`
	CapabilityVersion  int32     `json:"capability_version"`
	ReportedCertSerial string    `json:"reported_cert_serial"`
}

func (q *Queries) ReportAppAccessGatewayRuntime(ctx context.Context, arg ReportAppAccessGatewayRuntimeParams) (AppAccessGatewayRuntime, error) {
	row := q.db.QueryRow(ctx, reportAppAccessGatewayRuntime,
		arg.OrgID,
		arg.GatewayID,
		arg.CapabilityVersion,
		arg.ReportedCertSerial,
	)
	var i AppAccessGatewayRuntime
	err := row.Scan(
		&i.OrgID,
		&i.GatewayID,
		&i.CapabilityVersion,
		&i.ReportedCertSerial,
		&i.ReportedAt,
	)
	return i, err
}

const runningAppAccessChecks = `-- name: RunningAppAccessChecks :many
SELECT id, org_id, app_id, gateway_id, revision, digest, generation, purpose, status, dns_status, connect_status, tls_status, error_code, created_at, deadline, completed_at, completed_cert_serial FROM app_access_origin_checks WHERE org_id=$1 AND gateway_id=$2 AND status='running' AND deadline>now() ORDER BY created_at,id LIMIT 8
`

type RunningAppAccessChecksParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) RunningAppAccessChecks(ctx context.Context, arg RunningAppAccessChecksParams) ([]AppAccessOriginCheck, error) {
	rows, err := q.db.Query(ctx, runningAppAccessChecks, arg.OrgID, arg.GatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAccessOriginCheck{}
	for rows.Next() {
		var i AppAccessOriginCheck
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.GatewayID,
			&i.Revision,
			&i.Digest,
			&i.Generation,
			&i.Purpose,
			&i.Status,
			&i.DnsStatus,
			&i.ConnectStatus,
			&i.TlsStatus,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.Deadline,
			&i.CompletedAt,
			&i.CompletedCertSerial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawAppAccessApplicationAssignment = `-- name: WithdrawAppAccessApplicationAssignment :exec
UPDATE app_access_connector_assignments SET withdrawn_at=now() WHERE org_id=$1 AND app_id=$2 AND withdrawn_at IS NULL
`

type WithdrawAppAccessApplicationAssignmentParams struct {
	OrgID uuid.UUID `json:"org_id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) WithdrawAppAccessApplicationAssignment(ctx context.Context, arg WithdrawAppAccessApplicationAssignmentParams) error {
	_, err := q.db.Exec(ctx, withdrawAppAccessApplicationAssignment, arg.OrgID, arg.AppID)
	return err
}

const withdrawGatewayAppAccessAssignments = `-- name: WithdrawGatewayAppAccessAssignments :exec
UPDATE app_access_connector_assignments SET withdrawn_at=now() WHERE org_id=$1 AND gateway_id=$2 AND withdrawn_at IS NULL
`

type WithdrawGatewayAppAccessAssignmentsParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) WithdrawGatewayAppAccessAssignments(ctx context.Context, arg WithdrawGatewayAppAccessAssignmentsParams) error {
	_, err := q.db.Exec(ctx, withdrawGatewayAppAccessAssignments, arg.OrgID, arg.GatewayID)
	return err
}

const withdrawInvalidAppAccessChecks = `-- name: WithdrawInvalidAppAccessChecks :exec
UPDATE app_access_origin_checks c SET status='withdrawn',error_code='assignment_changed',completed_at=now() WHERE c.org_id=$1 AND c.gateway_id=$2 AND c.status IN ('queued','running') AND EXISTS(SELECT 1 FROM app_access_connector_assignments a WHERE a.generation=c.generation AND a.withdrawn_at IS NOT NULL)
`

type WithdrawInvalidAppAccessChecksParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) WithdrawInvalidAppAccessChecks(ctx context.Context, arg WithdrawInvalidAppAccessChecksParams) error {
	_, err := q.db.Exec(ctx, withdrawInvalidAppAccessChecks, arg.OrgID, arg.GatewayID)
	return err
}

const withdrawStaleAppAccessAssignments = `-- name: WithdrawStaleAppAccessAssignments :exec
UPDATE app_access_connector_assignments a SET withdrawn_at=now() WHERE a.org_id=$1 AND a.gateway_id=$2 AND a.withdrawn_at IS NULL AND NOT EXISTS(
 SELECT 1 FROM app_access_applications app JOIN app_access_revisions r ON r.org_id=app.org_id AND r.app_id=app.id AND r.revision=app.draft_revision
 WHERE app.org_id=a.org_id AND app.id=a.app_id AND r.revision=a.revision AND r.digest=a.digest AND r.gateway_id=a.gateway_id)
`

type WithdrawStaleAppAccessAssignmentsParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	GatewayID uuid.UUID `json:"gateway_id"`
}

func (q *Queries) WithdrawStaleAppAccessAssignments(ctx context.Context, arg WithdrawStaleAppAccessAssignmentsParams) error {
	_, err := q.db.Exec(ctx, withdrawStaleAppAccessAssignments, arg.OrgID, arg.GatewayID)
	return err
}
