// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_access_grants.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appAccessEvaluationUser = `-- name: AppAccessEvaluationUser :one
SELECT u.email_verified_at,u.must_change_password,u.status,m.access_revoked_at,m.role,m.roles FROM users u JOIN memberships m ON m.user_id=u.id
WHERE m.org_id=$1 AND u.id=$2 AND u.deleted_at IS NULL
`

type AppAccessEvaluationUserParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

type AppAccessEvaluationUserRow struct {
	EmailVerifiedAt    pgtype.Timestamptz `json:"email_verified_at"`
	MustChangePassword bool               `json:"must_change_password"`
	Status             string             `json:"status"`
	AccessRevokedAt    pgtype.Timestamptz `json:"access_revoked_at"`
	Role               string             `json:"role"`
	Roles              []string           `json:"roles"`
}

func (q *Queries) AppAccessEvaluationUser(ctx context.Context, arg AppAccessEvaluationUserParams) (AppAccessEvaluationUserRow, error) {
	row := q.db.QueryRow(ctx, appAccessEvaluationUser, arg.OrgID, arg.ID)
	var i AppAccessEvaluationUserRow
	err := row.Scan(
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.AccessRevokedAt,
		&i.Role,
		&i.Roles,
	)
	return i, err
}

const appAccessGrantSubjectAvailable = `-- name: AppAccessGrantSubjectAvailable :one
SELECT (g.subject_kind='user' AND EXISTS(SELECT 1 FROM users u JOIN memberships m ON m.user_id=u.id WHERE m.org_id=g.org_id AND u.id=g.user_id AND u.status='active' AND u.deleted_at IS NULL AND m.access_revoked_at IS NULL)) OR (g.subject_kind='group' AND EXISTS(SELECT 1 FROM user_groups ug WHERE ug.org_id=g.org_id AND ug.id=g.group_id))
FROM app_access_grants g WHERE g.org_id=$1 AND g.id=$2 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL)
`

type AppAccessGrantSubjectAvailableParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AppAccessGrantSubjectAvailable(ctx context.Context, arg AppAccessGrantSubjectAvailableParams) (*bool, error) {
	row := q.db.QueryRow(ctx, appAccessGrantSubjectAvailable, arg.OrgID, arg.ID)
	var column_1 *bool
	err := row.Scan(&column_1)
	return column_1, err
}

const appAccessRevokeImpact = `-- name: AppAccessRevokeImpact :one
WITH selected AS (
 SELECT g.id, g.org_id, g.app_id, g.subject_kind, g.subject_id, g.subject_label, g.user_id, g.group_id, g.enabled, g.starts_at, g.expires_at, g.version, g.revoked_at, g.created_at, g.updated_at FROM app_access_grants g JOIN organizations o ON o.id=g.org_id AND o.deleted_at IS NULL
 WHERE g.org_id=$2 AND g.id=$3
), eligible AS (
 SELECT u.id FROM users u JOIN memberships m ON m.user_id=u.id AND m.org_id=$2
 WHERE u.deleted_at IS NULL AND u.status='active' AND u.email_verified_at IS NOT NULL AND NOT u.must_change_password AND m.access_revoked_at IS NULL
 AND (CASE WHEN cardinality(m.roles)>0 THEN m.roles ELSE ARRAY[m.role] END) && $4::text[]
), affected AS (
 SELECT u.id FROM eligible u CROSS JOIN selected s WHERE s.enabled AND s.revoked_at IS NULL
 AND (s.starts_at IS NULL OR s.starts_at<=$1::timestamptz)
 AND (s.expires_at IS NULL OR $1::timestamptz<s.expires_at)
 AND ((s.subject_kind='user' AND s.user_id=u.id) OR (s.subject_kind='group' AND EXISTS(
 SELECT 1 FROM group_members gm JOIN user_groups ug ON ug.id=gm.group_id AND ug.org_id=gm.org_id WHERE gm.org_id=s.org_id AND gm.group_id=s.group_id AND gm.user_id=u.id)))
)
SELECT COALESCE((SELECT version FROM selected),0)::bigint AS grant_version, count(*)::bigint AS matching_user_count, count(*) FILTER(WHERE NOT EXISTS(
 SELECT 1 FROM app_access_grants g CROSS JOIN selected s
 WHERE g.org_id=s.org_id AND g.app_id=s.app_id AND g.id<>s.id AND g.enabled AND g.revoked_at IS NULL
 AND (g.starts_at IS NULL OR g.starts_at<=$1::timestamptz)
 AND (g.expires_at IS NULL OR $1::timestamptz<g.expires_at)
 AND ((g.subject_kind='user' AND g.user_id=affected.id) OR (g.subject_kind='group' AND EXISTS(
 SELECT 1 FROM group_members gm JOIN user_groups ug ON ug.id=gm.group_id AND ug.org_id=gm.org_id WHERE gm.org_id=g.org_id AND gm.group_id=g.group_id AND gm.user_id=affected.id)))
))::bigint AS users_losing_grant_match_count FROM affected
`

type AppAccessRevokeImpactParams struct {
	EvaluatedAt   time.Time `json:"evaluated_at"`
	OrgID         uuid.UUID `json:"org_id"`
	GrantID       uuid.UUID `json:"grant_id"`
	EligibleRoles []string  `json:"eligible_roles"`
}

type AppAccessRevokeImpactRow struct {
	GrantVersion               int64 `json:"grant_version"`
	MatchingUserCount          int64 `json:"matching_user_count"`
	UsersLosingGrantMatchCount int64 `json:"users_losing_grant_match_count"`
}

func (q *Queries) AppAccessRevokeImpact(ctx context.Context, arg AppAccessRevokeImpactParams) (AppAccessRevokeImpactRow, error) {
	row := q.db.QueryRow(ctx, appAccessRevokeImpact,
		arg.EvaluatedAt,
		arg.OrgID,
		arg.GrantID,
		arg.EligibleRoles,
	)
	var i AppAccessRevokeImpactRow
	err := row.Scan(&i.GrantVersion, &i.MatchingUserCount, &i.UsersLosingGrantMatchCount)
	return i, err
}

const createAppAccessGrant = `-- name: CreateAppAccessGrant :one
INSERT INTO app_access_grants(org_id,app_id,subject_kind,subject_id,subject_label,user_id,group_id,enabled,starts_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, org_id, app_id, subject_kind, subject_id, subject_label, user_id, group_id, enabled, starts_at, expires_at, version, revoked_at, created_at, updated_at
`

type CreateAppAccessGrantParams struct {
	OrgID        uuid.UUID          `json:"org_id"`
	AppID        uuid.UUID          `json:"app_id"`
	SubjectKind  string             `json:"subject_kind"`
	SubjectID    uuid.UUID          `json:"subject_id"`
	SubjectLabel string             `json:"subject_label"`
	UserID       pgtype.UUID        `json:"user_id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Enabled      bool               `json:"enabled"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAppAccessGrant(ctx context.Context, arg CreateAppAccessGrantParams) (AppAccessGrant, error) {
	row := q.db.QueryRow(ctx, createAppAccessGrant,
		arg.OrgID,
		arg.AppID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.SubjectLabel,
		arg.UserID,
		arg.GroupID,
		arg.Enabled,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i AppAccessGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.SubjectLabel,
		&i.UserID,
		&i.GroupID,
		&i.Enabled,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Version,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppAccessGrant = `-- name: GetAppAccessGrant :one
SELECT id, org_id, app_id, subject_kind, subject_id, subject_label, user_id, group_id, enabled, starts_at, expires_at, version, revoked_at, created_at, updated_at FROM app_access_grants WHERE app_access_grants.org_id=$1 AND app_access_grants.id=$2 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL)
`

type GetAppAccessGrantParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetAppAccessGrant(ctx context.Context, arg GetAppAccessGrantParams) (AppAccessGrant, error) {
	row := q.db.QueryRow(ctx, getAppAccessGrant, arg.OrgID, arg.ID)
	var i AppAccessGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.SubjectLabel,
		&i.UserID,
		&i.GroupID,
		&i.Enabled,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Version,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppAccessGrants = `-- name: ListAppAccessGrants :many
SELECT id, org_id, app_id, subject_kind, subject_id, subject_label, user_id, group_id, enabled, starts_at, expires_at, version, revoked_at, created_at, updated_at FROM app_access_grants WHERE app_access_grants.org_id=$1 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL)
 AND ($2::uuid IS NULL OR app_id=$2)
 AND ($3::text='' OR subject_kind=$3)
 AND ($4::uuid IS NULL OR subject_id=$4)
 ORDER BY created_at,id LIMIT $6 OFFSET $5
`

type ListAppAccessGrantsParams struct {
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	SubjectKind string      `json:"subject_kind"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	PageOffset  int32       `json:"page_offset"`
	PageLimit   int32       `json:"page_limit"`
}

func (q *Queries) ListAppAccessGrants(ctx context.Context, arg ListAppAccessGrantsParams) ([]AppAccessGrant, error) {
	rows, err := q.db.Query(ctx, listAppAccessGrants,
		arg.OrgID,
		arg.AppID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAccessGrant{}
	for rows.Next() {
		var i AppAccessGrant
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.SubjectLabel,
			&i.UserID,
			&i.GroupID,
			&i.Enabled,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.Version,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilteredAppAccessGrants = `-- name: ListFilteredAppAccessGrants :many
SELECT g.id, g.org_id, g.app_id, g.subject_kind, g.subject_id, g.subject_label, g.user_id, g.group_id, g.enabled, g.starts_at, g.expires_at, g.version, g.revoked_at, g.created_at, g.updated_at, r.name AS app_label, eligibility.available AS subject_available
FROM app_access_grants g
JOIN organizations o ON o.id=g.org_id AND o.deleted_at IS NULL
JOIN app_access_applications a ON a.org_id=g.org_id AND a.id=g.app_id
JOIN app_access_revisions r ON r.org_id=a.org_id AND r.app_id=a.id AND r.revision=a.draft_revision
CROSS JOIN LATERAL (
 SELECT ((g.subject_kind='user' AND EXISTS(
  SELECT 1 FROM users u JOIN memberships m ON m.user_id=u.id
  WHERE m.org_id=g.org_id AND u.id=g.user_id AND u.status='active'
   AND u.deleted_at IS NULL AND m.access_revoked_at IS NULL))
 OR (g.subject_kind='group' AND EXISTS(
  SELECT 1 FROM user_groups ug WHERE ug.org_id=g.org_id AND ug.id=g.group_id)))::boolean AS available
) eligibility
CROSS JOIN LATERAL (SELECT CASE
   WHEN g.revoked_at IS NOT NULL THEN 'revoked'
   WHEN NOT eligibility.available THEN 'subject_unavailable'
   WHEN NOT g.enabled THEN 'disabled'
   WHEN g.starts_at IS NOT NULL AND $1::timestamptz<g.starts_at THEN 'scheduled'
   WHEN g.expires_at IS NOT NULL AND $1::timestamptz>=g.expires_at THEN 'expired'
   ELSE 'active'
  END::text AS status) computed
WHERE g.org_id=$2
 AND ($3::uuid IS NULL OR g.app_id=$3)
 AND ($4::text='' OR g.subject_kind=$4)
 AND ($5::uuid IS NULL OR g.subject_id=$5)
 AND ($6::text=''
  OR strpos(lower(g.subject_label),lower($6::text))>0
  OR strpos(lower(r.name),lower($6::text))>0
  OR (g.subject_kind='user' AND EXISTS(
   SELECT 1 FROM users u JOIN memberships m ON m.user_id=u.id
   WHERE m.org_id=g.org_id AND u.id=g.user_id AND u.deleted_at IS NULL
    AND (strpos(lower(u.name),lower($6::text))>0 OR strpos(lower(u.email::text),lower($6::text))>0)))
  OR (g.subject_kind='group' AND EXISTS(
   SELECT 1 FROM user_groups ug WHERE ug.org_id=g.org_id AND ug.id=g.group_id
    AND strpos(lower(ug.name),lower($6::text))>0)))

 AND ($7::text='' OR computed.status=$7::text)
 AND ($8::text='' OR
      ($8::text='current' AND ($7::text<>'' OR computed.status IN ('active','disabled'))) OR
      ($8::text='history' AND computed.status IN ('revoked','expired')))
ORDER BY g.created_at,g.id LIMIT $10 OFFSET $9
`

type ListFilteredAppAccessGrantsParams struct {
	EvaluatedAt time.Time   `json:"evaluated_at"`
	OrgID       uuid.UUID   `json:"org_id"`
	AppID       pgtype.UUID `json:"app_id"`
	SubjectKind string      `json:"subject_kind"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Search      string      `json:"search"`
	Status      string      `json:"status"`
	View        string      `json:"view"`
	PageOffset  int32       `json:"page_offset"`
	PageLimit   int32       `json:"page_limit"`
}

type ListFilteredAppAccessGrantsRow struct {
	AppAccessGrant   AppAccessGrant `json:"app_access_grant"`
	AppLabel         string         `json:"app_label"`
	SubjectAvailable bool           `json:"subject_available"`
}

// Search and status are resolved in this same statement before pagination.
func (q *Queries) ListFilteredAppAccessGrants(ctx context.Context, arg ListFilteredAppAccessGrantsParams) ([]ListFilteredAppAccessGrantsRow, error) {
	rows, err := q.db.Query(ctx, listFilteredAppAccessGrants,
		arg.EvaluatedAt,
		arg.OrgID,
		arg.AppID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Search,
		arg.Status,
		arg.View,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilteredAppAccessGrantsRow{}
	for rows.Next() {
		var i ListFilteredAppAccessGrantsRow
		if err := rows.Scan(
			&i.AppAccessGrant.ID,
			&i.AppAccessGrant.OrgID,
			&i.AppAccessGrant.AppID,
			&i.AppAccessGrant.SubjectKind,
			&i.AppAccessGrant.SubjectID,
			&i.AppAccessGrant.SubjectLabel,
			&i.AppAccessGrant.UserID,
			&i.AppAccessGrant.GroupID,
			&i.AppAccessGrant.Enabled,
			&i.AppAccessGrant.StartsAt,
			&i.AppAccessGrant.ExpiresAt,
			&i.AppAccessGrant.Version,
			&i.AppAccessGrant.RevokedAt,
			&i.AppAccessGrant.CreatedAt,
			&i.AppAccessGrant.UpdatedAt,
			&i.AppLabel,
			&i.SubjectAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppAccessGrant = `-- name: LockAppAccessGrant :one
SELECT id, org_id, app_id, subject_kind, subject_id, subject_label, user_id, group_id, enabled, starts_at, expires_at, version, revoked_at, created_at, updated_at FROM app_access_grants WHERE app_access_grants.org_id=$1 AND app_access_grants.id=$2 AND EXISTS(SELECT 1 FROM organizations live_org WHERE live_org.id=$1 AND live_org.deleted_at IS NULL) FOR UPDATE
`

type LockAppAccessGrantParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) LockAppAccessGrant(ctx context.Context, arg LockAppAccessGrantParams) (AppAccessGrant, error) {
	row := q.db.QueryRow(ctx, lockAppAccessGrant, arg.OrgID, arg.ID)
	var i AppAccessGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.SubjectLabel,
		&i.UserID,
		&i.GroupID,
		&i.Enabled,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Version,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAppAccessGroupSubject = `-- name: LockAppAccessGroupSubject :one
SELECT name FROM user_groups WHERE org_id=$1 AND id=$2 FOR SHARE
`

type LockAppAccessGroupSubjectParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) LockAppAccessGroupSubject(ctx context.Context, arg LockAppAccessGroupSubjectParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAppAccessGroupSubject, arg.OrgID, arg.ID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const lockAppAccessUserSubject = `-- name: LockAppAccessUserSubject :one
SELECT u.name,u.email FROM memberships m JOIN users u ON u.id=m.user_id
WHERE m.org_id=$1 AND m.user_id=$2 AND m.access_revoked_at IS NULL AND u.status='active' AND u.deleted_at IS NULL FOR SHARE OF m,u
`

type LockAppAccessUserSubjectParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

type LockAppAccessUserSubjectRow struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) LockAppAccessUserSubject(ctx context.Context, arg LockAppAccessUserSubjectParams) (LockAppAccessUserSubjectRow, error) {
	row := q.db.QueryRow(ctx, lockAppAccessUserSubject, arg.OrgID, arg.UserID)
	var i LockAppAccessUserSubjectRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const matchingAppAccessGrants = `-- name: MatchingAppAccessGrants :many
SELECT g.id,g.expires_at FROM app_access_grants g
JOIN organizations o ON o.id=g.org_id AND o.deleted_at IS NULL
JOIN memberships m ON m.org_id=g.org_id AND m.user_id=$1 AND m.access_revoked_at IS NULL
JOIN users u ON u.id=m.user_id AND u.status='active' AND u.deleted_at IS NULL
WHERE g.org_id=$2 AND g.app_id=$3 AND g.enabled AND g.revoked_at IS NULL
 AND (g.starts_at IS NULL OR g.starts_at<=$4::timestamptz)
 AND (g.expires_at IS NULL OR $4::timestamptz<g.expires_at)
 AND ((g.subject_kind='user' AND g.user_id=u.id) OR (g.subject_kind='group' AND EXISTS(
 SELECT 1 FROM group_members gm JOIN user_groups ug ON ug.id=gm.group_id AND ug.org_id=gm.org_id
 WHERE gm.org_id=g.org_id AND gm.group_id=g.group_id AND gm.user_id=u.id))) ORDER BY g.id
`

type MatchingAppAccessGrantsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	OrgID       uuid.UUID `json:"org_id"`
	AppID       uuid.UUID `json:"app_id"`
	EvaluatedAt time.Time `json:"evaluated_at"`
}

type MatchingAppAccessGrantsRow struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) MatchingAppAccessGrants(ctx context.Context, arg MatchingAppAccessGrantsParams) ([]MatchingAppAccessGrantsRow, error) {
	rows, err := q.db.Query(ctx, matchingAppAccessGrants,
		arg.UserID,
		arg.OrgID,
		arg.AppID,
		arg.EvaluatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchingAppAccessGrantsRow{}
	for rows.Next() {
		var i MatchingAppAccessGrantsRow
		if err := rows.Scan(&i.ID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAppAccessGrant = `-- name: RevokeAppAccessGrant :one
UPDATE app_access_grants SET enabled=false,revoked_at=now(),version=version+1,updated_at=now() WHERE org_id=$1 AND id=$2 RETURNING id, org_id, app_id, subject_kind, subject_id, subject_label, user_id, group_id, enabled, starts_at, expires_at, version, revoked_at, created_at, updated_at
`

type RevokeAppAccessGrantParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) RevokeAppAccessGrant(ctx context.Context, arg RevokeAppAccessGrantParams) (AppAccessGrant, error) {
	row := q.db.QueryRow(ctx, revokeAppAccessGrant, arg.OrgID, arg.ID)
	var i AppAccessGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.SubjectLabel,
		&i.UserID,
		&i.GroupID,
		&i.Enabled,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Version,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppAccessGrant = `-- name: UpdateAppAccessGrant :one
UPDATE app_access_grants SET enabled=$3,starts_at=$4,expires_at=$5,version=version+1,updated_at=now() WHERE org_id=$1 AND id=$2 RETURNING id, org_id, app_id, subject_kind, subject_id, subject_label, user_id, group_id, enabled, starts_at, expires_at, version, revoked_at, created_at, updated_at
`

type UpdateAppAccessGrantParams struct {
	OrgID     uuid.UUID          `json:"org_id"`
	ID        uuid.UUID          `json:"id"`
	Enabled   bool               `json:"enabled"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateAppAccessGrant(ctx context.Context, arg UpdateAppAccessGrantParams) (AppAccessGrant, error) {
	row := q.db.QueryRow(ctx, updateAppAccessGrant,
		arg.OrgID,
		arg.ID,
		arg.Enabled,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i AppAccessGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.SubjectLabel,
		&i.UserID,
		&i.GroupID,
		&i.Enabled,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Version,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
