// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_logs (org_id, actor_user_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, actor_user_id, action, target_type, target_id, metadata, created_at, actor_system
`

type InsertAuditLogParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	TargetType  *string     `json:"target_type"`
	TargetID    *string     `json:"target_id"`
	Metadata    []byte      `json:"metadata"`
}

// audit_logs is append-only: there are intentionally NO update or delete queries
// here, and the DB enforces it (see 0002 triggers).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
		&i.ActorSystem,
	)
	return i, err
}

const insertSystemAuditLog = `-- name: InsertSystemAuditLog :one
INSERT INTO audit_logs (org_id, actor_system, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, actor_user_id, action, target_type, target_id, metadata, created_at, actor_system
`

type InsertSystemAuditLogParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ActorSystem *string     `json:"actor_system"`
	Action      string      `json:"action"`
	TargetType  *string     `json:"target_type"`
	TargetID    *string     `json:"target_id"`
	Metadata    []byte      `json:"metadata"`
}

// Append a system/service-initiated audit row: actor_user_id is NULL and the actor is NAMED in
// actor_system (e.g. 'idp-sync'). The metadata carries the CAUSE. Used when no human initiated
// the action (S7.5.2 idp-sync deprovisioning).
func (q *Queries) InsertSystemAuditLog(ctx context.Context, arg InsertSystemAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertSystemAuditLog,
		arg.OrgID,
		arg.ActorSystem,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
		&i.ActorSystem,
	)
	return i, err
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, org_id, actor_user_id, action, target_type, target_id, metadata, created_at, actor_system FROM audit_logs
WHERE org_id = $1
  AND ($2::uuid IS NULL OR actor_user_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
  AND ($6::timestamptz IS NULL OR (created_at, id) < ($6, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListAuditLogsByOrgParams struct {
	OrgID    pgtype.UUID        `json:"org_id"`
	Actor    pgtype.UUID        `json:"actor"`
	Action   *string            `json:"action"`
	FromTs   pgtype.Timestamptz `json:"from_ts"`
	ToTs     pgtype.Timestamptz `json:"to_ts"`
	CursorTs pgtype.Timestamptz `json:"cursor_ts"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	Lim      int32              `json:"lim"`
}

// Org-scoped audit feed with optional filters (actor / action / date range) and
// KEYSET pagination on (created_at, id) DESC. Every filter + cursor param is
// nullable, so the S4.3 dashboard passes none (latest N). The cursor is written
// as a ROW-VALUE comparison so it plans against (org_id, created_at DESC, id DESC)
// rather than an OR-expansion the planner can't use.
func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg,
		arg.OrgID,
		arg.Actor,
		arg.Action,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
