// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertAccessEventBatch = `-- name: InsertAccessEventBatch :batchexec
INSERT INTO access_events (
    id, org_id, seq, node_id, occurred_at, decision, rule_id,
    src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id,
    protocol, dst_port, deny_count, window_end, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18
)
`

type InsertAccessEventBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertAccessEventBatchParams struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	Seq           int64              `json:"seq"`
	NodeID        pgtype.UUID        `json:"node_id"`
	OccurredAt    time.Time          `json:"occurred_at"`
	Decision      string             `json:"decision"`
	RuleID        pgtype.UUID        `json:"rule_id"`
	SrcDeviceID   pgtype.UUID        `json:"src_device_id"`
	SrcUserID     pgtype.UUID        `json:"src_user_id"`
	SrcIp         string             `json:"src_ip"`
	DstIp         string             `json:"dst_ip"`
	DstResourceID pgtype.UUID        `json:"dst_resource_id"`
	DstGroupID    pgtype.UUID        `json:"dst_group_id"`
	Protocol      string             `json:"protocol"`
	DstPort       *int32             `json:"dst_port"`
	DenyCount     int32              `json:"deny_count"`
	WindowEnd     pgtype.Timestamptz `json:"window_end"`
	CreatedAt     time.Time          `json:"created_at"`
}

// The hot ingest path (review fold-2 #6): pipeline a whole batch's inserts in ONE round trip
// instead of N sequential Execs, so the process-global ingest mutex is held for far less time.
// Same plain insert as InsertAccessEvent (seq is unique via the counter; the unique index is
// the fail-LOUD backstop).
func (q *Queries) InsertAccessEventBatch(ctx context.Context, arg []InsertAccessEventBatchParams) *InsertAccessEventBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.OrgID,
			a.Seq,
			a.NodeID,
			a.OccurredAt,
			a.Decision,
			a.RuleID,
			a.SrcDeviceID,
			a.SrcUserID,
			a.SrcIp,
			a.DstIp,
			a.DstResourceID,
			a.DstGroupID,
			a.Protocol,
			a.DstPort,
			a.DenyCount,
			a.WindowEnd,
			a.CreatedAt,
		}
		batch.Queue(insertAccessEventBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertAccessEventBatchBatchResults{br, len(arg), false}
}

func (b *InsertAccessEventBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertAccessEventBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertDeviceStatus = `-- name: UpsertDeviceStatus :batchexec
INSERT INTO device_status (device_id, last_handshake_at, rx_bytes, tx_bytes, updated_at)
SELECT d.id, $1, $2, $3, now()
FROM devices d
WHERE d.node_id = $4 AND d.public_key = $5
  AND d.status = 'active' AND d.deleted_at IS NULL
ON CONFLICT (device_id) DO UPDATE
SET last_handshake_at = EXCLUDED.last_handshake_at,
    rx_bytes = EXCLUDED.rx_bytes,
    tx_bytes = EXCLUDED.tx_bytes,
    updated_at = now()
`

type UpsertDeviceStatusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertDeviceStatusParams struct {
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         int64              `json:"rx_bytes"`
	TxBytes         int64              `json:"tx_bytes"`
	NodeID          uuid.UUID          `json:"node_id"`
	PublicKey       string             `json:"public_key"`
}

// lint:cross-org — keyed by node_id (agent is cert-authorized) + pubkey. Batched
// (pgx.Batch) so a whole report is a single round-trip; no per-peer write
// amplification and the write lands on the lean status table, not the devices
// row. Maps pubkey->active device on this node; an unknown pubkey is a no-op.
// rx/tx are raw gauges.
func (q *Queries) UpsertDeviceStatus(ctx context.Context, arg []UpsertDeviceStatusParams) *UpsertDeviceStatusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LastHandshakeAt,
			a.RxBytes,
			a.TxBytes,
			a.NodeID,
			a.PublicKey,
		}
		batch.Queue(upsertDeviceStatus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertDeviceStatusBatchResults{br, len(arg), false}
}

func (b *UpsertDeviceStatusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertDeviceStatusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertNodePeerStatus = `-- name: UpsertNodePeerStatus :batchexec
INSERT INTO node_peer_status (node_id, public_key, last_handshake_at, rx_bytes, tx_bytes, updated_at)
SELECT $1, $2, $3, $4, $5, now()
WHERE EXISTS (
    SELECT 1 FROM nodes peer
    WHERE peer.wg_public_key = $2
      AND peer.org_id = (SELECT org_id FROM nodes WHERE id = $1)
      AND peer.id <> $1
)
ON CONFLICT (node_id, public_key) DO UPDATE
SET last_handshake_at = EXCLUDED.last_handshake_at,
    rx_bytes = EXCLUDED.rx_bytes,
    tx_bytes = EXCLUDED.tx_bytes,
    updated_at = now()
`

type UpsertNodePeerStatusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertNodePeerStatusParams struct {
	NodeID          uuid.UUID          `json:"node_id"`
	PublicKey       string             `json:"public_key"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         int64              `json:"rx_bytes"`
	TxBytes         int64              `json:"tx_bytes"`
}

// lint:cross-org — keyed by node_id (the agent is cert-authorized for its own node) + the PEER's pubkey.
// The SIBLING of UpsertDeviceStatus (S8.6): it stores a reporting GATEWAY's GATEWAY-peer telemetry
// (site-link peers). The EXISTS guard admits ONLY a pubkey that is ANOTHER node (a real gateway) in the
// SAME org — a DEVICE pubkey matches no node, so it no-ops here (device peers land in device_status,
// gateway peers land here; neither crosses). Batched (one round-trip per report). rx/tx are raw gauges.
func (q *Queries) UpsertNodePeerStatus(ctx context.Context, arg []UpsertNodePeerStatusParams) *UpsertNodePeerStatusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.NodeID,
			a.PublicKey,
			a.LastHandshakeAt,
			a.RxBytes,
			a.TxBytes,
		}
		batch.Queue(upsertNodePeerStatus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertNodePeerStatusBatchResults{br, len(arg), false}
}

func (b *UpsertNodePeerStatusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertNodePeerStatusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
