// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectivity_gateway.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listGatewayConnectivityKeys = `-- name: ListGatewayConnectivityKeys :many
SELECT device_id, session_id, generation
FROM connectivity_sessions
WHERE org_id = $1 AND gateway_id = $2
  AND device_id > $3 AND NOT revoked
  AND expires_at > clock_timestamp()
ORDER BY device_id
LIMIT 64
`

type ListGatewayConnectivityKeysParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	GatewayID     uuid.UUID `json:"gateway_id"`
	AfterDeviceID uuid.UUID `json:"after_device_id"`
}

type ListGatewayConnectivityKeysRow struct {
	DeviceID   uuid.UUID `json:"device_id"`
	SessionID  uuid.UUID `json:"session_id"`
	Generation int64     `json:"generation"`
}

// Candidate IDs only; caller must reauthorize each row through Store.Read.
func (q *Queries) ListGatewayConnectivityKeys(ctx context.Context, arg ListGatewayConnectivityKeysParams) ([]ListGatewayConnectivityKeysRow, error) {
	rows, err := q.db.Query(ctx, listGatewayConnectivityKeys, arg.OrgID, arg.GatewayID, arg.AfterDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayConnectivityKeysRow{}
	for rows.Next() {
		var i ListGatewayConnectivityKeysRow
		if err := rows.Scan(&i.DeviceID, &i.SessionID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
