// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectivity_shared.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const shareConnectivityEligibility = `-- name: ShareConnectivityEligibility :one
SELECT d.id AS device_id, d.org_id, d.user_id AS owner_id, d.node_id AS gateway_id,
       d.public_key AS device_public_key, n.wg_public_key AS gateway_public_key
FROM devices d
JOIN nodes n ON n.id = d.node_id AND n.org_id = d.org_id
JOIN users u ON u.id = d.user_id
JOIN memberships m ON m.org_id = d.org_id AND m.user_id = d.user_id
JOIN organizations o ON o.id = d.org_id
JOIN connectivity_profiles p ON p.org_id = d.org_id
WHERE d.id = $1 AND d.org_id = $2
  AND d.status = 'active' AND d.deleted_at IS NULL AND NOT d.health_blocked
  AND d.transport = 'wireguard' AND d.assigned_ip IS NOT NULL
  AND d.public_key ~ '^[A-Za-z0-9+/]{43}=$'
  AND n.status = 'active' AND u.status = 'active' AND u.deleted_at IS NULL
  AND o.deleted_at IS NULL AND p.enabled
FOR SHARE OF d, n, u, m, o, p
`

type ShareConnectivityEligibilityParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	OrgID    uuid.UUID `json:"org_id"`
}

type ShareConnectivityEligibilityRow struct {
	DeviceID         uuid.UUID `json:"device_id"`
	OrgID            uuid.UUID `json:"org_id"`
	OwnerID          uuid.UUID `json:"owner_id"`
	GatewayID        uuid.UUID `json:"gateway_id"`
	DevicePublicKey  string    `json:"device_public_key"`
	GatewayPublicKey string    `json:"gateway_public_key"`
}

// Match the WireGuard roster's active owner/membership/posture/key gates.
// Device serialization plus shared eligibility locks keep the snapshot stable
// until commit. No caller-supplied owner or gateway determines the binding.
func (q *Queries) ShareConnectivityEligibility(ctx context.Context, arg ShareConnectivityEligibilityParams) (ShareConnectivityEligibilityRow, error) {
	row := q.db.QueryRow(ctx, shareConnectivityEligibility, arg.DeviceID, arg.OrgID)
	var i ShareConnectivityEligibilityRow
	err := row.Scan(
		&i.DeviceID,
		&i.OrgID,
		&i.OwnerID,
		&i.GatewayID,
		&i.DevicePublicKey,
		&i.GatewayPublicKey,
	)
	return i, err
}

const shareConnectivitySession = `-- name: ShareConnectivitySession :one
SELECT device_id, org_id, owner_id, gateway_id, session_id, generation, created_at, expires_at, revoked, device_sequence, gateway_sequence, device_payload, gateway_payload FROM connectivity_sessions
WHERE org_id = $1 AND device_id = $2
FOR SHARE
`

type ShareConnectivitySessionParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	DeviceID uuid.UUID `json:"device_id"`
}

func (q *Queries) ShareConnectivitySession(ctx context.Context, arg ShareConnectivitySessionParams) (ConnectivitySession, error) {
	row := q.db.QueryRow(ctx, shareConnectivitySession, arg.OrgID, arg.DeviceID)
	var i ConnectivitySession
	err := row.Scan(
		&i.DeviceID,
		&i.OrgID,
		&i.OwnerID,
		&i.GatewayID,
		&i.SessionID,
		&i.Generation,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.DeviceSequence,
		&i.GatewaySequence,
		&i.DevicePayload,
		&i.GatewayPayload,
	)
	return i, err
}
