// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idpsync.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addIdpAccessSource = `-- name: AddIdpAccessSource :exec
INSERT INTO membership_access_sources (org_id, user_id, source_type, source_key)
VALUES ($1, $2, 'idp_sync', $3)
ON CONFLICT DO NOTHING
`

type AddIdpAccessSourceParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	UserID    uuid.UUID `json:"user_id"`
	SourceKey string    `json:"source_key"`
}

func (q *Queries) AddIdpAccessSource(ctx context.Context, arg AddIdpAccessSourceParams) error {
	_, err := q.db.Exec(ctx, addIdpAccessSource, arg.OrgID, arg.UserID, arg.SourceKey)
	return err
}

const addIdpGroupMember = `-- name: AddIdpGroupMember :execrows
INSERT INTO group_members (org_id, group_id, user_id, origin, idp_external_id)
VALUES ($1, $2, $3, 'idp_sync', $4)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddIdpGroupMemberParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	GroupID       uuid.UUID `json:"group_id"`
	UserID        uuid.UUID `json:"user_id"`
	IdpExternalID *string   `json:"idp_external_id"`
}

// Idempotent add of a synced member, recording the directory external id. Explicit origin='idp_sync'.
// Returns rows-affected: 0 on conflict = already present → the caller reports didChange=false and
// skips BOTH the audit and the org-wide re-push.
func (q *Queries) AddIdpGroupMember(ctx context.Context, arg AddIdpGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addIdpGroupMember,
		arg.OrgID,
		arg.GroupID,
		arg.UserID,
		arg.IdpExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindGroupToIdp = `-- name: BindGroupToIdp :one
UPDATE user_groups
SET origin = 'idp_sync', idp_provider = $3, idp_group_id = $4, updated_at = now()
WHERE id = $1 AND org_id = $2 AND origin = 'manual'
RETURNING id, org_id, name, description, created_at, updated_at, origin, idp_provider, idp_group_id
`

type BindGroupToIdpParams struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	IdpProvider *string   `json:"idp_provider"`
	IdpGroupID  *string   `json:"idp_group_id"`
}

// Flip an EXISTING manual group to idp_sync. The WHERE origin='manual' clause makes a re-bind of
// an already-synced group a no-row (the app layer maps that + the not-empty check to a 409). The
// disjointness (D1) and the not-empty rule are enforced above this; this only flips a clean group.
func (q *Queries) BindGroupToIdp(ctx context.Context, arg BindGroupToIdpParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, bindGroupToIdp,
		arg.ID,
		arg.OrgID,
		arg.IdpProvider,
		arg.IdpGroupID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.IdpProvider,
		&i.IdpGroupID,
	)
	return i, err
}

const countAccessSources = `-- name: CountAccessSources :one
SELECT count(*) FROM membership_access_sources WHERE org_id = $1 AND user_id = $2
`

type CountAccessSourcesParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CountAccessSources(ctx context.Context, arg CountAccessSourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessSources, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM group_members WHERE org_id = $1 AND group_id = $2
`

type CountGroupMembersParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	GroupID uuid.UUID `json:"group_id"`
}

// Any origin — the refuse-unless-empty guard (D1) must see a hand-added member too.
func (q *Queries) CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, arg.OrgID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdpSyncGroup = `-- name: CreateIdpSyncGroup :one
INSERT INTO user_groups (org_id, name, description, origin, idp_provider, idp_group_id)
VALUES ($1, $2, '', 'idp_sync', $3, $4)
RETURNING id, org_id, name, description, created_at, updated_at, origin, idp_provider, idp_group_id
`

type CreateIdpSyncGroupParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	IdpProvider *string   `json:"idp_provider"`
	IdpGroupID  *string   `json:"idp_group_id"`
}

// ── group mapping (create / bind / unbind) ───────────────────────────────────────
// Create a fresh Tunnex group already bound to an IdP group (origin='idp_sync').
func (q *Queries) CreateIdpSyncGroup(ctx context.Context, arg CreateIdpSyncGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createIdpSyncGroup,
		arg.OrgID,
		arg.Name,
		arg.IdpProvider,
		arg.IdpGroupID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.IdpProvider,
		&i.IdpGroupID,
	)
	return i, err
}

const deleteGroupMembersByGroup = `-- name: DeleteGroupMembersByGroup :execrows
DELETE FROM group_members WHERE org_id = $1 AND group_id = $2
`

type DeleteGroupMembersByGroupParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	GroupID uuid.UUID `json:"group_id"`
}

// Clear a group's membership (used on un-map, after the origin flip back to manual).
func (q *Queries) DeleteGroupMembersByGroup(ctx context.Context, arg DeleteGroupMembersByGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroupMembersByGroup, arg.OrgID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdpSyncConfig = `-- name: GetIdpSyncConfig :one

SELECT id, org_id, provider, client_id, secret_sealed, tenant_id, enabled, last_sync_at, last_sync_ok, last_sync_error, created_at, updated_at, delegated_admin_email FROM idp_sync_configs
WHERE org_id = $1 AND provider = $2
`

type GetIdpSyncConfigParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Provider string    `json:"provider"`
}

// S7.5.2 IdP-group sync. Enterprise. All tenant-scoped by org_id.
// The reconciler reads the desired membership from a DirectoryProvider (Graph/etc.) and drives
// these to converge group_members(origin='idp_sync') — NEVER touching manual rows (disjoint by D1).
// ── sync configs (per org, per provider) ─────────────────────────────────────────
func (q *Queries) GetIdpSyncConfig(ctx context.Context, arg GetIdpSyncConfigParams) (IdpSyncConfig, error) {
	row := q.db.QueryRow(ctx, getIdpSyncConfig, arg.OrgID, arg.Provider)
	var i IdpSyncConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ClientID,
		&i.SecretSealed,
		&i.TenantID,
		&i.Enabled,
		&i.LastSyncAt,
		&i.LastSyncOk,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DelegatedAdminEmail,
	)
	return i, err
}

const getOrgUserByEmail = `-- name: GetOrgUserByEmail :one
SELECT u.id, u.status
FROM users u
JOIN memberships m ON m.user_id = u.id AND m.org_id = $1
WHERE u.email = $2 AND u.deleted_at IS NULL
`

type GetOrgUserByEmailParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Email string    `json:"email"`
}

type GetOrgUserByEmailRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// ── directory email → Tunnex org user ────────────────────────────────────────────
// Resolve a directory member's email to a Tunnex user that BELONGS to this org (membership
// join). A directory member with no matching org user is skipped by the reconciler (sync grants
// access to existing users; it does not JIT-provision — that's S2.5). Case-insensitive: the
// provider already lower-cases; users.email is stored lower-cased.
func (q *Queries) GetOrgUserByEmail(ctx context.Context, arg GetOrgUserByEmailParams) (GetOrgUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getOrgUserByEmail, arg.OrgID, arg.Email)
	var i GetOrgUserByEmailRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const listEnabledIdpSyncConfigs = `-- name: ListEnabledIdpSyncConfigs :many
SELECT id, org_id, provider, client_id, secret_sealed, tenant_id, enabled, last_sync_at, last_sync_ok, last_sync_error, created_at, updated_at, delegated_admin_email FROM idp_sync_configs
WHERE enabled = true
ORDER BY org_id, provider
`

// The poller's work-list: every org/provider with sync turned on. Deliberately CROSS-ORG — the
// background poller iterates all tenants; each config is reconciled org-scoped downstream.
// lint:cross-org
func (q *Queries) ListEnabledIdpSyncConfigs(ctx context.Context) ([]IdpSyncConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledIdpSyncConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdpSyncConfig{}
	for rows.Next() {
		var i IdpSyncConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.ClientID,
			&i.SecretSealed,
			&i.TenantID,
			&i.Enabled,
			&i.LastSyncAt,
			&i.LastSyncOk,
			&i.LastSyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DelegatedAdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdpGroupMembers = `-- name: ListIdpGroupMembers :many
SELECT user_id, idp_external_id
FROM group_members
WHERE org_id = $1 AND group_id = $2 AND origin = 'idp_sync'
ORDER BY user_id
`

type ListIdpGroupMembersParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	GroupID uuid.UUID `json:"group_id"`
}

type ListIdpGroupMembersRow struct {
	UserID        uuid.UUID `json:"user_id"`
	IdpExternalID *string   `json:"idp_external_id"`
}

// ── idp-origin membership (the reconcile target) ─────────────────────────────────
// Current idp-origin members of one group (user id + recorded directory external id). Filtered to
// origin='idp_sync' so a hand-added row could never appear here and get computed into a removal
// (belt over disjoint). The external id lets a later removal resolve delete-vs-moved (D3 sweep).
func (q *Queries) ListIdpGroupMembers(ctx context.Context, arg ListIdpGroupMembersParams) ([]ListIdpGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listIdpGroupMembers, arg.OrgID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdpGroupMembersRow{}
	for rows.Next() {
		var i ListIdpGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.IdpExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdpSyncGroups = `-- name: ListIdpSyncGroups :many
SELECT id, idp_group_id
FROM user_groups
WHERE org_id = $1 AND origin = 'idp_sync' AND idp_provider = $2
ORDER BY id
`

type ListIdpSyncGroupsParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	IdpProvider *string   `json:"idp_provider"`
}

type ListIdpSyncGroupsRow struct {
	ID         uuid.UUID `json:"id"`
	IdpGroupID *string   `json:"idp_group_id"`
}

// ── idp_sync groups (the mappings to reconcile) ──────────────────────────────────
// Every Tunnex group bound to an IdP group for this org+provider — the units the reconciler
// walks. origin/shape is schema-guaranteed (0026), so idp_provider/idp_group_id are non-null.
func (q *Queries) ListIdpSyncGroups(ctx context.Context, arg ListIdpSyncGroupsParams) ([]ListIdpSyncGroupsRow, error) {
	rows, err := q.db.Query(ctx, listIdpSyncGroups, arg.OrgID, arg.IdpProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdpSyncGroupsRow{}
	for rows.Next() {
		var i ListIdpSyncGroupsRow
		if err := rows.Scan(&i.ID, &i.IdpGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordIdpSyncResult = `-- name: RecordIdpSyncResult :exec
UPDATE idp_sync_configs
SET last_sync_ok    = $3,
    last_sync_error = $4,
    last_sync_at    = CASE WHEN $5::boolean THEN $6 ELSE last_sync_at END,
    updated_at      = $6
WHERE org_id = $1 AND provider = $2
`

type RecordIdpSyncResultParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	Provider      string    `json:"provider"`
	LastSyncOk    bool      `json:"last_sync_ok"`
	LastSyncError *string   `json:"last_sync_error"`
	Column5       bool      `json:"column_5"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// One stamp for all three poll outcomes (the two-tier health, D2):
//
//	success  → ok=true,  advance_clock=true  (last_sync_at = now; error cleared)
//	transient→ ok=false, advance_clock=false (last_sync_at FROZEN at the last good sync — the
//	           staleness the escalation tier measures; a Graph outage must NOT reset that clock)
//	gone     → ok=false, advance_clock=true  (fetch itself succeeded, so data is fresh: immediate
//	           tier only, never escalates — a stable known-bad mapping, not a worsening outage)
//
// advance_clock also drives whether last_sync_error is cleared vs set.
func (q *Queries) RecordIdpSyncResult(ctx context.Context, arg RecordIdpSyncResultParams) error {
	_, err := q.db.Exec(ctx, recordIdpSyncResult,
		arg.OrgID,
		arg.Provider,
		arg.LastSyncOk,
		arg.LastSyncError,
		arg.Column5,
		arg.UpdatedAt,
	)
	return err
}

const removeIdpAccessSource = `-- name: RemoveIdpAccessSource :exec
DELETE FROM membership_access_sources
WHERE org_id = $1 AND user_id = $2 AND source_type = 'idp_sync' AND source_key = $3
`

type RemoveIdpAccessSourceParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	UserID    uuid.UUID `json:"user_id"`
	SourceKey string    `json:"source_key"`
}

func (q *Queries) RemoveIdpAccessSource(ctx context.Context, arg RemoveIdpAccessSourceParams) error {
	_, err := q.db.Exec(ctx, removeIdpAccessSource, arg.OrgID, arg.UserID, arg.SourceKey)
	return err
}

const removeIdpGroupMember = `-- name: RemoveIdpGroupMember :execrows
DELETE FROM group_members
WHERE org_id = $1 AND group_id = $2 AND user_id = $3 AND origin = 'idp_sync'
`

type RemoveIdpGroupMemberParams struct {
	OrgID   uuid.UUID `json:"org_id"`
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Remove a synced member — scoped to origin='idp_sync' so the reconcile can NEVER delete a
// manual membership even if one somehow shared the (group,user) key.
func (q *Queries) RemoveIdpGroupMember(ctx context.Context, arg RemoveIdpGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeIdpGroupMember, arg.OrgID, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreMembershipAfterIdpGrant = `-- name: RestoreMembershipAfterIdpGrant :exec
UPDATE memberships SET access_revoked_at = NULL WHERE org_id = $1 AND user_id = $2
`

type RestoreMembershipAfterIdpGrantParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RestoreMembershipAfterIdpGrant(ctx context.Context, arg RestoreMembershipAfterIdpGrantParams) error {
	_, err := q.db.Exec(ctx, restoreMembershipAfterIdpGrant, arg.OrgID, arg.UserID)
	return err
}

const unbindIdpGroup = `-- name: UnbindIdpGroup :one
UPDATE user_groups
SET origin = 'manual', idp_provider = NULL, idp_group_id = NULL, updated_at = now()
WHERE id = $1 AND org_id = $2 AND origin = 'idp_sync'
RETURNING id, org_id, name, description, created_at, updated_at, origin, idp_provider, idp_group_id
`

type UnbindIdpGroupParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Revert an idp_sync group to a plain (empty) manual group. Members are cleared separately.
func (q *Queries) UnbindIdpGroup(ctx context.Context, arg UnbindIdpGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, unbindIdpGroup, arg.ID, arg.OrgID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.IdpProvider,
		&i.IdpGroupID,
	)
	return i, err
}

const upsertIdpSyncConfig = `-- name: UpsertIdpSyncConfig :one
INSERT INTO idp_sync_configs (org_id, provider, client_id, secret_sealed, tenant_id, delegated_admin_email, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id, provider) DO UPDATE
    SET client_id = EXCLUDED.client_id,
        secret_sealed = EXCLUDED.secret_sealed,
        tenant_id = EXCLUDED.tenant_id,
        delegated_admin_email = EXCLUDED.delegated_admin_email,
        enabled = EXCLUDED.enabled,
        updated_at = now()
RETURNING id, org_id, provider, client_id, secret_sealed, tenant_id, enabled, last_sync_at, last_sync_ok, last_sync_error, created_at, updated_at, delegated_admin_email
`

type UpsertIdpSyncConfigParams struct {
	OrgID               uuid.UUID `json:"org_id"`
	Provider            string    `json:"provider"`
	ClientID            string    `json:"client_id"`
	SecretSealed        []byte    `json:"secret_sealed"`
	TenantID            *string   `json:"tenant_id"`
	DelegatedAdminEmail *string   `json:"delegated_admin_email"`
	Enabled             bool      `json:"enabled"`
}

// Connect / update a provider credential. The secret is pre-sealed (AES-GCM) by the caller;
// plaintext never reaches SQL. On re-set, credentials update but the sync-health columns are
// left intact (a credential rotation shouldn't fake a green health).
func (q *Queries) UpsertIdpSyncConfig(ctx context.Context, arg UpsertIdpSyncConfigParams) (IdpSyncConfig, error) {
	row := q.db.QueryRow(ctx, upsertIdpSyncConfig,
		arg.OrgID,
		arg.Provider,
		arg.ClientID,
		arg.SecretSealed,
		arg.TenantID,
		arg.DelegatedAdminEmail,
		arg.Enabled,
	)
	var i IdpSyncConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ClientID,
		&i.SecretSealed,
		&i.TenantID,
		&i.Enabled,
		&i.LastSyncAt,
		&i.LastSyncOk,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DelegatedAdminEmail,
	)
	return i, err
}
