// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: k8s.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countClusterCascade = `-- name: CountClusterCascade :one
SELECT
  (SELECT count(*) FROM k8s_services s WHERE s.cluster_id = $2 AND s.org_id = $1 AND s.deleted_at IS NULL) AS service_count,
  (SELECT count(*) FROM policy_rules r WHERE r.org_id = $1 AND r.dst_k8s_service_id IN (SELECT s2.id FROM k8s_services s2 WHERE s2.cluster_id = $2)) AS grant_count
`

type CountClusterCascadeParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ClusterID uuid.UUID `json:"cluster_id"`
}

type CountClusterCascadeRow struct {
	ServiceCount int64 `json:"service_count"`
	GrantCount   int64 `json:"grant_count"`
}

// CountClusterCascade returns what a DeregisterCluster will destroy, for the audit trail (H2): the number of
// LIVE exposed Services in the cluster, and the number of policy grants (rules) that reference ANY Service in
// it. Both are FK ON DELETE CASCADE'd when the cluster row is deleted, so the audit must capture them BEFORE
// the delete — a governance cascade must never vanish untraceably.
func (q *Queries) CountClusterCascade(ctx context.Context, arg CountClusterCascadeParams) (CountClusterCascadeRow, error) {
	row := q.db.QueryRow(ctx, countClusterCascade, arg.OrgID, arg.ClusterID)
	var i CountClusterCascadeRow
	err := row.Scan(&i.ServiceCount, &i.GrantCount)
	return i, err
}

const createK8sCluster = `-- name: CreateK8sCluster :one

INSERT INTO k8s_clusters (org_id, site_id, connector_node_id, name, vip_range, service_cidr, dns_zone, dns_vip, managed_by_machine)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, site_id, name, vip_range, created_at, updated_at, service_cidr, dns_zone, dns_vip, managed_by_machine, connector_node_id
`

type CreateK8sClusterParams struct {
	OrgID            uuid.UUID    `json:"org_id"`
	SiteID           uuid.UUID    `json:"site_id"`
	ConnectorNodeID  pgtype.UUID  `json:"connector_node_id"`
	Name             string       `json:"name"`
	VipRange         netip.Prefix `json:"vip_range"`
	ServiceCidr      netip.Prefix `json:"service_cidr"`
	DnsZone          string       `json:"dns_zone"`
	DnsVip           *netip.Addr  `json:"dns_vip"`
	ManagedByMachine pgtype.UUID  `json:"managed_by_machine"`
}

// S10.3: Kubernetes cluster + exposed-Service queries. Org-scoped (tenant isolation).
func (q *Queries) CreateK8sCluster(ctx context.Context, arg CreateK8sClusterParams) (K8sCluster, error) {
	row := q.db.QueryRow(ctx, createK8sCluster,
		arg.OrgID,
		arg.SiteID,
		arg.ConnectorNodeID,
		arg.Name,
		arg.VipRange,
		arg.ServiceCidr,
		arg.DnsZone,
		arg.DnsVip,
		arg.ManagedByMachine,
	)
	var i K8sCluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.VipRange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceCidr,
		&i.DnsZone,
		&i.DnsVip,
		&i.ManagedByMachine,
		&i.ConnectorNodeID,
	)
	return i, err
}

const createK8sService = `-- name: CreateK8sService :one
INSERT INTO k8s_services (org_id, cluster_id, name, namespace, protocol, port_low, port_high, vip, managed_by_machine)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, cluster_id, name, namespace, protocol, port_low, port_high, vip, created_at, updated_at, deleted_at, managed_by_machine
`

type CreateK8sServiceParams struct {
	OrgID            uuid.UUID   `json:"org_id"`
	ClusterID        uuid.UUID   `json:"cluster_id"`
	Name             string      `json:"name"`
	Namespace        string      `json:"namespace"`
	Protocol         string      `json:"protocol"`
	PortLow          *int32      `json:"port_low"`
	PortHigh         *int32      `json:"port_high"`
	Vip              netip.Addr  `json:"vip"`
	ManagedByMachine pgtype.UUID `json:"managed_by_machine"`
}

func (q *Queries) CreateK8sService(ctx context.Context, arg CreateK8sServiceParams) (K8sService, error) {
	row := q.db.QueryRow(ctx, createK8sService,
		arg.OrgID,
		arg.ClusterID,
		arg.Name,
		arg.Namespace,
		arg.Protocol,
		arg.PortLow,
		arg.PortHigh,
		arg.Vip,
		arg.ManagedByMachine,
	)
	var i K8sService
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClusterID,
		&i.Name,
		&i.Namespace,
		&i.Protocol,
		&i.PortLow,
		&i.PortHigh,
		&i.Vip,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ManagedByMachine,
	)
	return i, err
}

const deleteK8sCluster = `-- name: DeleteK8sCluster :exec
DELETE FROM k8s_clusters WHERE org_id = $1 AND id = $2
`

type DeleteK8sClusterParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) DeleteK8sCluster(ctx context.Context, arg DeleteK8sClusterParams) error {
	_, err := q.db.Exec(ctx, deleteK8sCluster, arg.OrgID, arg.ID)
	return err
}

const getK8sCluster = `-- name: GetK8sCluster :one
SELECT id, org_id, site_id, name, vip_range, created_at, updated_at, service_cidr, dns_zone, dns_vip, managed_by_machine, connector_node_id FROM k8s_clusters WHERE org_id = $1 AND id = $2
`

type GetK8sClusterParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetK8sCluster(ctx context.Context, arg GetK8sClusterParams) (K8sCluster, error) {
	row := q.db.QueryRow(ctx, getK8sCluster, arg.OrgID, arg.ID)
	var i K8sCluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.VipRange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceCidr,
		&i.DnsZone,
		&i.DnsVip,
		&i.ManagedByMachine,
		&i.ConnectorNodeID,
	)
	return i, err
}

const getK8sService = `-- name: GetK8sService :one
SELECT id, org_id, cluster_id, name, namespace, protocol, port_low, port_high, vip, created_at, updated_at, deleted_at, managed_by_machine FROM k8s_services WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetK8sServiceParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetK8sService(ctx context.Context, arg GetK8sServiceParams) (K8sService, error) {
	row := q.db.QueryRow(ctx, getK8sService, arg.OrgID, arg.ID)
	var i K8sService
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClusterID,
		&i.Name,
		&i.Namespace,
		&i.Protocol,
		&i.PortLow,
		&i.PortHigh,
		&i.Vip,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ManagedByMachine,
	)
	return i, err
}

const listActiveK8sServicesForOrg = `-- name: ListActiveK8sServicesForOrg :many
SELECT s.id, s.cluster_id, s.name, s.namespace, s.protocol, s.port_low, s.port_high,
       host(s.vip) AS vip, c.site_id, c.connector_node_id, host(c.vip_range) AS vip_range, c.service_cidr::text AS service_cidr,
       c.name AS cluster_name, c.dns_zone, COALESCE(host(c.dns_vip), '')::text AS dns_vip
FROM k8s_services s
JOIN k8s_clusters c ON c.id = s.cluster_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL
ORDER BY s.id
`

type ListActiveK8sServicesForOrgRow struct {
	ID              uuid.UUID   `json:"id"`
	ClusterID       uuid.UUID   `json:"cluster_id"`
	Name            string      `json:"name"`
	Namespace       string      `json:"namespace"`
	Protocol        string      `json:"protocol"`
	PortLow         *int32      `json:"port_low"`
	PortHigh        *int32      `json:"port_high"`
	Vip             string      `json:"vip"`
	SiteID          uuid.UUID   `json:"site_id"`
	ConnectorNodeID pgtype.UUID `json:"connector_node_id"`
	VipRange        string      `json:"vip_range"`
	ServiceCidr     string      `json:"service_cidr"`
	ClusterName     string      `json:"cluster_name"`
	DnsZone         string      `json:"dns_zone"`
	DnsVip          string      `json:"dns_vip"`
}

// ListActiveK8sServicesForOrg is the compiler's resolution source: id -> current VIP (+ proto/ports), LIVE
// only. A soft-deleted Service is absent, so a grant referencing it compiles to nothing (honest, not silent).
func (q *Queries) ListActiveK8sServicesForOrg(ctx context.Context, orgID uuid.UUID) ([]ListActiveK8sServicesForOrgRow, error) {
	rows, err := q.db.Query(ctx, listActiveK8sServicesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveK8sServicesForOrgRow{}
	for rows.Next() {
		var i ListActiveK8sServicesForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Name,
			&i.Namespace,
			&i.Protocol,
			&i.PortLow,
			&i.PortHigh,
			&i.Vip,
			&i.SiteID,
			&i.ConnectorNodeID,
			&i.VipRange,
			&i.ServiceCidr,
			&i.ClusterName,
			&i.DnsZone,
			&i.DnsVip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listK8sClusterZonesForOrg = `-- name: ListK8sClusterZonesForOrg :many
SELECT name, dns_zone, COALESCE(host(dns_vip), '')::text AS dns_vip FROM k8s_clusters WHERE org_id = $1
`

type ListK8sClusterZonesForOrgRow struct {
	Name    string `json:"name"`
	DnsZone string `json:"dns_zone"`
	DnsVip  string `json:"dns_vip"`
}

// ListK8sClusterZonesForOrg feeds (a) cross-mechanism one-zone-one-resolver enforcement (S10.3 (A)): a site
// dns_forwarding domain must not collide with a K8s cluster's DNS zone (<cluster>.<dns_zone>), and vice versa;
// and (b) the client-side resolver push (fork-1): the {<cluster>.<dns_zone> -> reserved DNS VIP} mapping the
// routed-forwards channel hands split-tunnel/OVPN clients so they resolve exposed Service names.
func (q *Queries) ListK8sClusterZonesForOrg(ctx context.Context, orgID uuid.UUID) ([]ListK8sClusterZonesForOrgRow, error) {
	rows, err := q.db.Query(ctx, listK8sClusterZonesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListK8sClusterZonesForOrgRow{}
	for rows.Next() {
		var i ListK8sClusterZonesForOrgRow
		if err := rows.Scan(&i.Name, &i.DnsZone, &i.DnsVip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listK8sClustersForOrg = `-- name: ListK8sClustersForOrg :many
SELECT id, org_id, site_id, name, vip_range, created_at, updated_at, service_cidr, dns_zone, dns_vip, managed_by_machine, connector_node_id FROM k8s_clusters WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListK8sClustersForOrg(ctx context.Context, orgID uuid.UUID) ([]K8sCluster, error) {
	rows, err := q.db.Query(ctx, listK8sClustersForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []K8sCluster{}
	for rows.Next() {
		var i K8sCluster
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.Name,
			&i.VipRange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceCidr,
			&i.DnsZone,
			&i.DnsVip,
			&i.ManagedByMachine,
			&i.ConnectorNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listK8sServedZonesForOrg = `-- name: ListK8sServedZonesForOrg :many
SELECT DISTINCT c.name, c.dns_zone, COALESCE(host(c.dns_vip), '')::text AS dns_vip
FROM k8s_clusters c
JOIN k8s_services s ON s.cluster_id = c.id AND s.deleted_at IS NULL
WHERE c.org_id = $1 AND c.connector_node_id IS NOT NULL
`

type ListK8sServedZonesForOrgRow struct {
	Name    string `json:"name"`
	DnsZone string `json:"dns_zone"`
	DnsVip  string `json:"dns_vip"`
}

// ListK8sServedZonesForOrg is the zones a connector ACTUALLY answers: a cluster with >=1 LIVE exposed Service
// AND an explicit connector. An unassigned cluster must not hand clients a resolver address that intentionally
// has no answering node.
// This is the SAME live-service set the agent's K8sDNSZones is built from (loadSiteTopology →
// ListActiveK8sServicesForOrg), so the client resolver push (routedranges) and the gateway's own answer set
// agree BY CONSTRUCTION (L2): a zone the gateway would REFUSE for (no Service yet) is never handed to a client
// as a resolver. DISTINCT collapses a multi-Service cluster to one zone row.
func (q *Queries) ListK8sServedZonesForOrg(ctx context.Context, orgID uuid.UUID) ([]ListK8sServedZonesForOrgRow, error) {
	rows, err := q.db.Query(ctx, listK8sServedZonesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListK8sServedZonesForOrgRow{}
	for rows.Next() {
		var i ListK8sServedZonesForOrgRow
		if err := rows.Scan(&i.Name, &i.DnsZone, &i.DnsVip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedVIPsInCluster = `-- name: ListUsedVIPsInCluster :many
SELECT host(vip) AS vip FROM k8s_services WHERE org_id = $1 AND cluster_id = $2 AND deleted_at IS NULL
`

type ListUsedVIPsInClusterParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ClusterID uuid.UUID `json:"cluster_id"`
}

// ListUsedVIPsInCluster returns the LIVE VIPs in a cluster (the used-set ipalloc allocates around).
// org_id-scoped for tenant isolation (defence-in-depth; the caller already authorized the cluster).
func (q *Queries) ListUsedVIPsInCluster(ctx context.Context, arg ListUsedVIPsInClusterParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsedVIPsInCluster, arg.OrgID, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var vip string
		if err := rows.Scan(&vip); err != nil {
			return nil, err
		}
		items = append(items, vip)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVIPRangesForOrg = `-- name: ListVIPRangesForOrg :many
SELECT vip_range::text AS vip_range FROM k8s_clusters WHERE org_id = $1
`

// ListVIPRangesForOrg feeds the subnetguard collector: EVERY disjointness check (cluster-VIP creation,
// pool resize, site-subnet approval) must include the org's VIP ranges so disjointness stays bidirectional
// (the validator-input-filtering law). Returns the raw cidr text.
func (q *Queries) ListVIPRangesForOrg(ctx context.Context, orgID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listVIPRangesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var vip_range string
		if err := rows.Scan(&vip_range); err != nil {
			return nil, err
		}
		items = append(items, vip_range)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setK8sClusterConnector = `-- name: SetK8sClusterConnector :execrows
UPDATE k8s_clusters
SET connector_node_id = $3
WHERE org_id = $1 AND id = $2
`

type SetK8sClusterConnectorParams struct {
	OrgID           uuid.UUID   `json:"org_id"`
	ID              uuid.UUID   `json:"id"`
	ConnectorNodeID pgtype.UUID `json:"connector_node_id"`
}

func (q *Queries) SetK8sClusterConnector(ctx context.Context, arg SetK8sClusterConnectorParams) (int64, error) {
	result, err := q.db.Exec(ctx, setK8sClusterConnector, arg.OrgID, arg.ID, arg.ConnectorNodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteK8sService = `-- name: SoftDeleteK8sService :exec
UPDATE k8s_services SET deleted_at = now() WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteK8sServiceParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteK8sService(ctx context.Context, arg SoftDeleteK8sServiceParams) error {
	_, err := q.db.Exec(ctx, softDeleteK8sService, arg.OrgID, arg.ID)
	return err
}
