// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: k8s_lifecycle_claims.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abortLifecycleJoinToken = `-- name: AbortLifecycleJoinToken :execrows
UPDATE node_join_tokens
SET lifecycle_token_sealed = NULL,
    lifecycle_aborted_at = now(),
    expires_at = LEAST(expires_at, now())
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND lifecycle_aborted_at IS NULL
`

type AbortLifecycleJoinTokenParams struct {
	OrgID              uuid.UUID   `json:"org_id"`
	LifecycleClaim     pgtype.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32       `json:"expected_generation"`
	LifecycleRequestID pgtype.UUID `json:"lifecycle_request_id"`
}

func (q *Queries) AbortLifecycleJoinToken(ctx context.Context, arg AbortLifecycleJoinTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, abortLifecycleJoinToken,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const acknowledgeLifecycleJoinToken = `-- name: AcknowledgeLifecycleJoinToken :execrows
UPDATE node_join_tokens
SET lifecycle_token_sealed = NULL,
    lifecycle_acknowledged_at = now()
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND consumed_at IS NULL
  AND lifecycle_aborted_at IS NULL
  AND lifecycle_token_sealed IS NOT NULL
`

type AcknowledgeLifecycleJoinTokenParams struct {
	OrgID              uuid.UUID   `json:"org_id"`
	LifecycleClaim     pgtype.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32       `json:"expected_generation"`
	LifecycleRequestID pgtype.UUID `json:"lifecycle_request_id"`
}

func (q *Queries) AcknowledgeLifecycleJoinToken(ctx context.Context, arg AcknowledgeLifecycleJoinTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeLifecycleJoinToken,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeLifecycleInstallOperation = `-- name: CompleteLifecycleInstallOperation :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
UPDATE node_lifecycle_install_operations operation
SET state = 'completed', completed_at = (SELECT now_at FROM server_clock)
WHERE operation.org_id = $1
  AND operation.lifecycle_claim = $2
  AND operation.lifecycle_generation = $3
  AND operation.lifecycle_request_id = $4
  AND operation.operation_id = $5
  AND operation.epoch = $6
  AND operation.state = 'active'
  AND operation.abort_requested_at IS NULL
  AND operation.not_after > (SELECT now_at FROM server_clock)
  AND EXISTS (
      SELECT 1
      FROM node_join_tokens token
      JOIN nodes node
        ON node.id = token.consumed_node_id
       AND node.org_id = token.org_id
       AND node.lifecycle_claim = token.lifecycle_claim
      WHERE token.id = operation.token_id
        AND token.org_id = operation.org_id
        AND token.lifecycle_claim = operation.lifecycle_claim
        AND token.lifecycle_generation = operation.lifecycle_generation
        AND token.lifecycle_request_id = operation.lifecycle_request_id
        AND token.consumed_at IS NOT NULL
        AND token.lifecycle_aborted_at IS NULL
        AND node.status = 'active'
  )
RETURNING operation.operation_id, operation.token_id, operation.org_id, operation.lifecycle_claim, operation.lifecycle_generation, operation.lifecycle_request_id, operation.epoch, operation.release_namespace, operation.release_name, operation.install_intent_digest, operation.requested_duration_seconds, operation.state, operation.not_after, operation.heartbeat_at, operation.abort_requested_at, operation.released_at, operation.completed_at, operation.taken_over_at, operation.aborted_at, operation.created_at, operation.updated_at
`

type CompleteLifecycleInstallOperationParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	LifecycleClaim     uuid.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32     `json:"expected_generation"`
	LifecycleRequestID uuid.UUID `json:"lifecycle_request_id"`
	OperationID        uuid.UUID `json:"operation_id"`
	ExpectedEpoch      int64     `json:"expected_epoch"`
}

func (q *Queries) CompleteLifecycleInstallOperation(ctx context.Context, arg CompleteLifecycleInstallOperationParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, completeLifecycleInstallOperation,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
		arg.OperationID,
		arg.ExpectedEpoch,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAbortedLifecycleJoinToken = `-- name: CreateAbortedLifecycleJoinToken :one
INSERT INTO node_join_tokens (
    org_id, node_name, token_hash, expires_at, issued_by, enrols_kind,
    lifecycle_claim, lifecycle_generation, lifecycle_request_id,
    lifecycle_token_sealed, lifecycle_aborted_at
)
VALUES (
    $1, $2, $3,
    TIMESTAMPTZ 'epoch', $4, 'gateway',
    $5, 0, $6,
    NULL, now()
)
ON CONFLICT (lifecycle_claim) WHERE lifecycle_claim IS NOT NULL DO NOTHING
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind, lifecycle_claim, lifecycle_generation, lifecycle_request_id, lifecycle_token_sealed, lifecycle_acknowledged_at, lifecycle_aborted_at
`

type CreateAbortedLifecycleJoinTokenParams struct {
	OrgID              uuid.UUID   `json:"org_id"`
	NodeName           *string     `json:"node_name"`
	TokenHash          []byte      `json:"token_hash"`
	IssuedBy           pgtype.UUID `json:"issued_by"`
	LifecycleClaim     pgtype.UUID `json:"lifecycle_claim"`
	LifecycleRequestID pgtype.UUID `json:"lifecycle_request_id"`
}

// Generation zero is a credentialless, permanently expired tombstone. The
// random hash has no disclosed preimage and exists only because the legacy
// token table keeps token_hash NOT NULL/unique during the mixed-version
// compatibility window.
func (q *Queries) CreateAbortedLifecycleJoinToken(ctx context.Context, arg CreateAbortedLifecycleJoinTokenParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, createAbortedLifecycleJoinToken,
		arg.OrgID,
		arg.NodeName,
		arg.TokenHash,
		arg.IssuedBy,
		arg.LifecycleClaim,
		arg.LifecycleRequestID,
	)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.LifecycleTokenSealed,
		&i.LifecycleAcknowledgedAt,
		&i.LifecycleAbortedAt,
	)
	return i, err
}

const createLifecycleInstallOperation = `-- name: CreateLifecycleInstallOperation :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
INSERT INTO node_lifecycle_install_operations (
    operation_id, token_id, org_id, lifecycle_claim,
    lifecycle_generation, lifecycle_request_id, epoch,
    release_namespace, release_name, install_intent_digest,
    requested_duration_seconds, not_after, heartbeat_at
)
SELECT
    $1, token.id, token.org_id, token.lifecycle_claim,
    token.lifecycle_generation, token.lifecycle_request_id, $2,
    $3, $4, $5,
    $6,
    LEAST(token.expires_at, server_clock.now_at + make_interval(secs => $6::integer)),
    server_clock.now_at
FROM node_join_tokens token
CROSS JOIN server_clock
WHERE token.id = $7
  AND token.org_id = $8
  AND token.lifecycle_claim = $9
  AND token.lifecycle_generation = $10
  AND token.lifecycle_request_id = $11
  AND token.lifecycle_acknowledged_at IS NOT NULL
  AND token.lifecycle_aborted_at IS NULL
  AND token.consumed_at IS NULL
  AND token.expires_at > server_clock.now_at
ON CONFLICT DO NOTHING
RETURNING operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at
`

type CreateLifecycleInstallOperationParams struct {
	OperationID              uuid.UUID   `json:"operation_id"`
	Epoch                    int64       `json:"epoch"`
	ReleaseNamespace         string      `json:"release_namespace"`
	ReleaseName              string      `json:"release_name"`
	InstallIntentDigest      string      `json:"install_intent_digest"`
	RequestedDurationSeconds int32       `json:"requested_duration_seconds"`
	TokenID                  uuid.UUID   `json:"token_id"`
	OrgID                    uuid.UUID   `json:"org_id"`
	LifecycleClaim           pgtype.UUID `json:"lifecycle_claim"`
	ExpectedGeneration       int32       `json:"expected_generation"`
	LifecycleRequestID       pgtype.UUID `json:"lifecycle_request_id"`
}

func (q *Queries) CreateLifecycleInstallOperation(ctx context.Context, arg CreateLifecycleInstallOperationParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, createLifecycleInstallOperation,
		arg.OperationID,
		arg.Epoch,
		arg.ReleaseNamespace,
		arg.ReleaseName,
		arg.InstallIntentDigest,
		arg.RequestedDurationSeconds,
		arg.TokenID,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLifecycleJoinToken = `-- name: CreateLifecycleJoinToken :one

INSERT INTO node_join_tokens (
    org_id, node_name, token_hash, expires_at, issued_by, enrols_kind,
    lifecycle_claim, lifecycle_generation, lifecycle_request_id,
    lifecycle_token_sealed
)
VALUES (
    $1, $2, $3, $4,
    $5, 'gateway', $6,
    1, $7, $8
)
ON CONFLICT (lifecycle_claim) WHERE lifecycle_claim IS NOT NULL DO NOTHING
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind, lifecycle_claim, lifecycle_generation, lifecycle_request_id, lifecycle_token_sealed, lifecycle_acknowledged_at, lifecycle_aborted_at
`

type CreateLifecycleJoinTokenParams struct {
	OrgID                uuid.UUID   `json:"org_id"`
	NodeName             *string     `json:"node_name"`
	TokenHash            []byte      `json:"token_hash"`
	ExpiresAt            time.Time   `json:"expires_at"`
	IssuedBy             pgtype.UUID `json:"issued_by"`
	LifecycleClaim       pgtype.UUID `json:"lifecycle_claim"`
	LifecycleRequestID   pgtype.UUID `json:"lifecycle_request_id"`
	LifecycleTokenSealed *string     `json:"lifecycle_token_sealed"`
}

// S20.5/D13a lifecycle-claim protocol. Every query is org-scoped. The token
// credential itself is never selected by these operator endpoints; only the
// temporarily sealed response is read by the exact remint transaction.
func (q *Queries) CreateLifecycleJoinToken(ctx context.Context, arg CreateLifecycleJoinTokenParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, createLifecycleJoinToken,
		arg.OrgID,
		arg.NodeName,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IssuedBy,
		arg.LifecycleClaim,
		arg.LifecycleRequestID,
		arg.LifecycleTokenSealed,
	)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.LifecycleTokenSealed,
		&i.LifecycleAcknowledgedAt,
		&i.LifecycleAbortedAt,
	)
	return i, err
}

const getLatestLifecycleInstallOperationForOrg = `-- name: GetLatestLifecycleInstallOperationForOrg :one
SELECT operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at FROM node_lifecycle_install_operations
WHERE org_id = $1
  AND lifecycle_claim = $2
ORDER BY epoch DESC
LIMIT 1
`

type GetLatestLifecycleInstallOperationForOrgParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	LifecycleClaim uuid.UUID `json:"lifecycle_claim"`
}

func (q *Queries) GetLatestLifecycleInstallOperationForOrg(ctx context.Context, arg GetLatestLifecycleInstallOperationForOrgParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, getLatestLifecycleInstallOperationForOrg, arg.OrgID, arg.LifecycleClaim)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLifecycleDatabaseTime = `-- name: GetLifecycleDatabaseTime :one

SELECT clock_timestamp()::timestamptz
`

// D13h install-operation epochs. The caller always locks the lifecycle token
// first; every operation mutation follows that same token -> operation order.
func (q *Queries) GetLifecycleDatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLifecycleDatabaseTime)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const getLifecycleInstallOperationForOrg = `-- name: GetLifecycleInstallOperationForOrg :one
SELECT operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at FROM node_lifecycle_install_operations
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND operation_id = $3
`

type GetLifecycleInstallOperationForOrgParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	LifecycleClaim uuid.UUID `json:"lifecycle_claim"`
	OperationID    uuid.UUID `json:"operation_id"`
}

func (q *Queries) GetLifecycleInstallOperationForOrg(ctx context.Context, arg GetLifecycleInstallOperationForOrgParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, getLifecycleInstallOperationForOrg, arg.OrgID, arg.LifecycleClaim, arg.OperationID)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLifecycleJoinTokenForOrg = `-- name: GetLifecycleJoinTokenForOrg :one
SELECT id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind, lifecycle_claim, lifecycle_generation, lifecycle_request_id, lifecycle_token_sealed, lifecycle_acknowledged_at, lifecycle_aborted_at FROM node_join_tokens
WHERE org_id = $1 AND lifecycle_claim = $2
`

type GetLifecycleJoinTokenForOrgParams struct {
	OrgID          uuid.UUID   `json:"org_id"`
	LifecycleClaim pgtype.UUID `json:"lifecycle_claim"`
}

func (q *Queries) GetLifecycleJoinTokenForOrg(ctx context.Context, arg GetLifecycleJoinTokenForOrgParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, getLifecycleJoinTokenForOrg, arg.OrgID, arg.LifecycleClaim)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.LifecycleTokenSealed,
		&i.LifecycleAcknowledgedAt,
		&i.LifecycleAbortedAt,
	)
	return i, err
}

const getNodeByLifecycleClaimForOrg = `-- name: GetNodeByLifecycleClaimForOrg :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind, lifecycle_claim FROM nodes
WHERE org_id = $1 AND lifecycle_claim = $2
`

type GetNodeByLifecycleClaimForOrgParams struct {
	OrgID          uuid.UUID   `json:"org_id"`
	LifecycleClaim pgtype.UUID `json:"lifecycle_claim"`
}

func (q *Queries) GetNodeByLifecycleClaimForOrg(ctx context.Context, arg GetNodeByLifecycleClaimForOrgParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByLifecycleClaimForOrg, arg.OrgID, arg.LifecycleClaim)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
		&i.LifecycleClaim,
	)
	return i, err
}

const heartbeatLifecycleInstallOperation = `-- name: HeartbeatLifecycleInstallOperation :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
UPDATE node_lifecycle_install_operations
SET heartbeat_at = GREATEST(heartbeat_at, (SELECT now_at FROM server_clock))
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND operation_id = $5
  AND epoch = $6
  AND state = 'active'
  AND not_after > (SELECT now_at FROM server_clock)
RETURNING operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at
`

type HeartbeatLifecycleInstallOperationParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	LifecycleClaim     uuid.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32     `json:"expected_generation"`
	LifecycleRequestID uuid.UUID `json:"lifecycle_request_id"`
	OperationID        uuid.UUID `json:"operation_id"`
	ExpectedEpoch      int64     `json:"expected_epoch"`
}

func (q *Queries) HeartbeatLifecycleInstallOperation(ctx context.Context, arg HeartbeatLifecycleInstallOperationParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, heartbeatLifecycleInstallOperation,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
		arg.OperationID,
		arg.ExpectedEpoch,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockLatestLifecycleInstallOperationForOrg = `-- name: LockLatestLifecycleInstallOperationForOrg :one
SELECT operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at FROM node_lifecycle_install_operations
WHERE org_id = $1
  AND lifecycle_claim = $2
ORDER BY epoch DESC
LIMIT 1
FOR UPDATE
`

type LockLatestLifecycleInstallOperationForOrgParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	LifecycleClaim uuid.UUID `json:"lifecycle_claim"`
}

func (q *Queries) LockLatestLifecycleInstallOperationForOrg(ctx context.Context, arg LockLatestLifecycleInstallOperationForOrgParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, lockLatestLifecycleInstallOperationForOrg, arg.OrgID, arg.LifecycleClaim)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockLifecycleJoinTokenForOrg = `-- name: LockLifecycleJoinTokenForOrg :one
SELECT id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind, lifecycle_claim, lifecycle_generation, lifecycle_request_id, lifecycle_token_sealed, lifecycle_acknowledged_at, lifecycle_aborted_at FROM node_join_tokens
WHERE org_id = $1 AND lifecycle_claim = $2
FOR UPDATE
`

type LockLifecycleJoinTokenForOrgParams struct {
	OrgID          uuid.UUID   `json:"org_id"`
	LifecycleClaim pgtype.UUID `json:"lifecycle_claim"`
}

func (q *Queries) LockLifecycleJoinTokenForOrg(ctx context.Context, arg LockLifecycleJoinTokenForOrgParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, lockLifecycleJoinTokenForOrg, arg.OrgID, arg.LifecycleClaim)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.LifecycleTokenSealed,
		&i.LifecycleAcknowledgedAt,
		&i.LifecycleAbortedAt,
	)
	return i, err
}

const lockNodeByLifecycleClaimForOrg = `-- name: LockNodeByLifecycleClaimForOrg :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind, lifecycle_claim FROM nodes
WHERE org_id = $1 AND lifecycle_claim = $2
FOR UPDATE
`

type LockNodeByLifecycleClaimForOrgParams struct {
	OrgID          uuid.UUID   `json:"org_id"`
	LifecycleClaim pgtype.UUID `json:"lifecycle_claim"`
}

func (q *Queries) LockNodeByLifecycleClaimForOrg(ctx context.Context, arg LockNodeByLifecycleClaimForOrgParams) (Node, error) {
	row := q.db.QueryRow(ctx, lockNodeByLifecycleClaimForOrg, arg.OrgID, arg.LifecycleClaim)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
		&i.LifecycleClaim,
	)
	return i, err
}

const markLifecycleInstallOperationAborted = `-- name: MarkLifecycleInstallOperationAborted :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
UPDATE node_lifecycle_install_operations
SET state = 'aborted', aborted_at = (SELECT now_at FROM server_clock)
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND operation_id = $5
  AND epoch = $6
  AND state = 'taken_over'
  AND abort_requested_at IS NOT NULL
RETURNING operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at
`

type MarkLifecycleInstallOperationAbortedParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	LifecycleClaim     uuid.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32     `json:"expected_generation"`
	LifecycleRequestID uuid.UUID `json:"lifecycle_request_id"`
	OperationID        uuid.UUID `json:"operation_id"`
	ExpectedEpoch      int64     `json:"expected_epoch"`
}

func (q *Queries) MarkLifecycleInstallOperationAborted(ctx context.Context, arg MarkLifecycleInstallOperationAbortedParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, markLifecycleInstallOperationAborted,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
		arg.OperationID,
		arg.ExpectedEpoch,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseLifecycleInstallOperation = `-- name: ReleaseLifecycleInstallOperation :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
UPDATE node_lifecycle_install_operations
SET state = 'released', released_at = (SELECT now_at FROM server_clock)
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND operation_id = $5
  AND epoch = $6
  AND state = 'active'
RETURNING operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at
`

type ReleaseLifecycleInstallOperationParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	LifecycleClaim     uuid.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32     `json:"expected_generation"`
	LifecycleRequestID uuid.UUID `json:"lifecycle_request_id"`
	OperationID        uuid.UUID `json:"operation_id"`
	ExpectedEpoch      int64     `json:"expected_epoch"`
}

func (q *Queries) ReleaseLifecycleInstallOperation(ctx context.Context, arg ReleaseLifecycleInstallOperationParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, releaseLifecycleInstallOperation,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
		arg.OperationID,
		arg.ExpectedEpoch,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remintLifecycleJoinToken = `-- name: RemintLifecycleJoinToken :one
UPDATE node_join_tokens
SET token_hash = $1,
    expires_at = $2,
    lifecycle_generation = lifecycle_generation + 1,
    lifecycle_request_id = $3,
    lifecycle_token_sealed = $4,
    lifecycle_acknowledged_at = NULL
WHERE id = $5
  AND org_id = $6
  AND lifecycle_claim = $7
  AND lifecycle_generation = $8
  AND consumed_at IS NULL
  AND lifecycle_aborted_at IS NULL
  AND expires_at <= $9
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind, lifecycle_claim, lifecycle_generation, lifecycle_request_id, lifecycle_token_sealed, lifecycle_acknowledged_at, lifecycle_aborted_at
`

type RemintLifecycleJoinTokenParams struct {
	TokenHash            []byte      `json:"token_hash"`
	ExpiresAt            time.Time   `json:"expires_at"`
	LifecycleRequestID   pgtype.UUID `json:"lifecycle_request_id"`
	LifecycleTokenSealed *string     `json:"lifecycle_token_sealed"`
	ID                   uuid.UUID   `json:"id"`
	OrgID                uuid.UUID   `json:"org_id"`
	LifecycleClaim       pgtype.UUID `json:"lifecycle_claim"`
	ExpectedGeneration   int32       `json:"expected_generation"`
	ServerTime           time.Time   `json:"server_time"`
}

func (q *Queries) RemintLifecycleJoinToken(ctx context.Context, arg RemintLifecycleJoinTokenParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, remintLifecycleJoinToken,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.LifecycleRequestID,
		arg.LifecycleTokenSealed,
		arg.ID,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.ServerTime,
	)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.LifecycleTokenSealed,
		&i.LifecycleAcknowledgedAt,
		&i.LifecycleAbortedAt,
	)
	return i, err
}

const requestAbortLifecycleInstallOperation = `-- name: RequestAbortLifecycleInstallOperation :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
UPDATE node_lifecycle_install_operations
SET abort_requested_at = (SELECT now_at FROM server_clock)
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND operation_id = $5
  AND epoch = $6
  AND state IN ('active', 'released')
  AND abort_requested_at IS NULL
RETURNING operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at
`

type RequestAbortLifecycleInstallOperationParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	LifecycleClaim     uuid.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32     `json:"expected_generation"`
	LifecycleRequestID uuid.UUID `json:"lifecycle_request_id"`
	OperationID        uuid.UUID `json:"operation_id"`
	ExpectedEpoch      int64     `json:"expected_epoch"`
}

func (q *Queries) RequestAbortLifecycleInstallOperation(ctx context.Context, arg RequestAbortLifecycleInstallOperationParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, requestAbortLifecycleInstallOperation,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
		arg.OperationID,
		arg.ExpectedEpoch,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const takeOverLifecycleInstallOperationForAbort = `-- name: TakeOverLifecycleInstallOperationForAbort :one
WITH server_clock AS MATERIALIZED (
    SELECT clock_timestamp()::timestamptz AS now_at
)
UPDATE node_lifecycle_install_operations
SET state = 'taken_over', epoch = epoch + 1,
    released_at = NULL, taken_over_at = (SELECT now_at FROM server_clock)
WHERE org_id = $1
  AND lifecycle_claim = $2
  AND lifecycle_generation = $3
  AND lifecycle_request_id = $4
  AND operation_id = $5
  AND epoch = $6
  AND abort_requested_at IS NOT NULL
  AND (state = 'released' OR (state = 'active' AND not_after <= (SELECT now_at FROM server_clock)))
RETURNING operation_id, token_id, org_id, lifecycle_claim, lifecycle_generation, lifecycle_request_id, epoch, release_namespace, release_name, install_intent_digest, requested_duration_seconds, state, not_after, heartbeat_at, abort_requested_at, released_at, completed_at, taken_over_at, aborted_at, created_at, updated_at
`

type TakeOverLifecycleInstallOperationForAbortParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	LifecycleClaim     uuid.UUID `json:"lifecycle_claim"`
	ExpectedGeneration int32     `json:"expected_generation"`
	LifecycleRequestID uuid.UUID `json:"lifecycle_request_id"`
	OperationID        uuid.UUID `json:"operation_id"`
	ExpectedEpoch      int64     `json:"expected_epoch"`
}

func (q *Queries) TakeOverLifecycleInstallOperationForAbort(ctx context.Context, arg TakeOverLifecycleInstallOperationForAbortParams) (NodeLifecycleInstallOperation, error) {
	row := q.db.QueryRow(ctx, takeOverLifecycleInstallOperationForAbort,
		arg.OrgID,
		arg.LifecycleClaim,
		arg.ExpectedGeneration,
		arg.LifecycleRequestID,
		arg.OperationID,
		arg.ExpectedEpoch,
	)
	var i NodeLifecycleInstallOperation
	err := row.Scan(
		&i.OperationID,
		&i.TokenID,
		&i.OrgID,
		&i.LifecycleClaim,
		&i.LifecycleGeneration,
		&i.LifecycleRequestID,
		&i.Epoch,
		&i.ReleaseNamespace,
		&i.ReleaseName,
		&i.InstallIntentDigest,
		&i.RequestedDurationSeconds,
		&i.State,
		&i.NotAfter,
		&i.HeartbeatAt,
		&i.AbortRequestedAt,
		&i.ReleasedAt,
		&i.CompletedAt,
		&i.TakenOverAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
