// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const changeMemberRole = `-- name: ChangeMemberRole :one
UPDATE memberships
SET role = $3
WHERE org_id = $1 AND user_id = $2
RETURNING id, org_id, user_id, role, created_at, updated_at, access_revoked_at
`

type ChangeMemberRoleParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) ChangeMemberRole(ctx context.Context, arg ChangeMemberRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, changeMemberRole, arg.OrgID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessRevokedAt,
	)
	return i, err
}

const countOrgsWhereSoleOwner = `-- name: CountOrgsWhereSoleOwner :one
SELECT count(*) FROM memberships m
WHERE m.user_id = $1 AND m.role = 'owner'
  AND (SELECT count(*) FROM memberships o WHERE o.org_id = m.org_id AND o.role = 'owner') = 1
`

// lint:cross-org — spans a user's orgs to protect the last-owner invariant on
// global deactivation; each row's org_id is used in the correlated subquery.
func (q *Queries) CountOrgsWhereSoleOwner(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgsWhereSoleOwner, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships
WHERE org_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, org_id, user_id, role, created_at, updated_at, access_revoked_at FROM memberships
WHERE org_id = $1 AND user_id = $2 AND access_revoked_at IS NULL
`

type GetMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessRevokedAt,
	)
	return i, err
}

const getMembershipIncludingRevoked = `-- name: GetMembershipIncludingRevoked :one
SELECT id, org_id, user_id, role, created_at, updated_at, access_revoked_at FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipIncludingRevokedParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipIncludingRevoked(ctx context.Context, arg GetMembershipIncludingRevokedParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipIncludingRevoked, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessRevokedAt,
	)
	return i, err
}

const listAccessSources = `-- name: ListAccessSources :many
SELECT source_type, source_key FROM membership_access_sources
WHERE org_id = $1 AND user_id = $2
ORDER BY source_type, source_key
`

type ListAccessSourcesParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListAccessSourcesRow struct {
	SourceType string `json:"source_type"`
	SourceKey  string `json:"source_key"`
}

func (q *Queries) ListAccessSources(ctx context.Context, arg ListAccessSourcesParams) ([]ListAccessSourcesRow, error) {
	rows, err := q.db.Query(ctx, listAccessSources, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessSourcesRow{}
	for rows.Next() {
		var i ListAccessSourcesRow
		if err := rows.Scan(&i.SourceType, &i.SourceKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT id, org_id, user_id, role, created_at, updated_at, access_revoked_at FROM memberships
WHERE org_id = $1 AND access_revoked_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListMembershipsByOrg(ctx context.Context, orgID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessRevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, org_id, user_id, role, created_at, updated_at, access_revoked_at FROM memberships
WHERE user_id = $1 AND access_revoked_at IS NULL
ORDER BY created_at
`

// lint:cross-org — intentionally spans orgs: a user's memberships across all
// their organizations (used to resolve which orgs a principal belongs to).
func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessRevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembersWithUser = `-- name: ListOrgMembersWithUser :many
SELECT m.user_id, m.role, m.created_at AS joined_at,
       u.email, u.name, u.status, (u.email_verified_at IS NOT NULL)::boolean AS email_verified,
       (SELECT count(*) FROM machine_credentials mc
         WHERE mc.user_id = m.user_id AND mc.revoked_at IS NULL)::bigint AS machine_credentials
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND u.deleted_at IS NULL
ORDER BY m.created_at
`

type ListOrgMembersWithUserRow struct {
	UserID             uuid.UUID `json:"user_id"`
	Role               string    `json:"role"`
	JoinedAt           time.Time `json:"joined_at"`
	Email              string    `json:"email"`
	Name               string    `json:"name"`
	Status             string    `json:"status"`
	EmailVerified      bool      `json:"email_verified"`
	MachineCredentials int64     `json:"machine_credentials"`
}

// The org roster for the Users page: membership joined to the user record so the
// UI has name/email/status/verified in one query. Soft-deleted users are
// excluded (their membership row survives a soft-delete); deactivated members
// stay on the roster (status carries that).
// ⛔ AND IT CARRIES WHAT DEACTIVATING THIS PERSON WOULD STOP (D23). A machine credential dies with its
// owner's deactivation — that is the whole point of the ownership binding — and until this column existed
// nothing in the product could tell an operator that BEFORE they clicked. A routine offboarding took down
// a GitOps pipeline and the two acts were never connected.
//
// ⚠ COUNTED ACROSS EVERY ORGANIZATION, because deactivation is a deployment-wide act on a person. A count
// scoped to this org would under-report the blast radius on the one screen that exists to state it.
func (q *Queries) ListOrgMembersWithUser(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembersWithUser, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersWithUserRow{}
	for rows.Next() {
		var i ListOrgMembersWithUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.EmailVerified,
			&i.MachineCredentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreMembershipAccess = `-- name: RestoreMembershipAccess :exec
UPDATE memberships SET access_revoked_at = NULL
WHERE org_id = $1 AND user_id = $2
`

type RestoreMembershipAccessParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RestoreMembershipAccess(ctx context.Context, arg RestoreMembershipAccessParams) error {
	_, err := q.db.Exec(ctx, restoreMembershipAccess, arg.OrgID, arg.UserID)
	return err
}

const revokeMembershipAccess = `-- name: RevokeMembershipAccess :execrows
UPDATE memberships SET access_revoked_at = now()
WHERE org_id = $1 AND user_id = $2 AND access_revoked_at IS NULL
`

type RevokeMembershipAccessParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeMembershipAccess(ctx context.Context, arg RevokeMembershipAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMembershipAccess, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE
    SET role = EXCLUDED.role
RETURNING id, org_id, user_id, role, created_at, updated_at, access_revoked_at
`

type UpsertMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

// Idempotent on (org_id, user_id).
func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, upsertMembership, arg.OrgID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessRevokedAt,
	)
	return i, err
}
