// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessEvent struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	Seq               int64              `json:"seq"`
	NodeID            pgtype.UUID        `json:"node_id"`
	OccurredAt        time.Time          `json:"occurred_at"`
	Decision          string             `json:"decision"`
	RuleID            pgtype.UUID        `json:"rule_id"`
	SrcDeviceID       pgtype.UUID        `json:"src_device_id"`
	SrcUserID         pgtype.UUID        `json:"src_user_id"`
	SrcIp             string             `json:"src_ip"`
	DstIp             string             `json:"dst_ip"`
	DstResourceID     pgtype.UUID        `json:"dst_resource_id"`
	DstGroupID        pgtype.UUID        `json:"dst_group_id"`
	Protocol          string             `json:"protocol"`
	DstPort           *int32             `json:"dst_port"`
	DenyCount         int32              `json:"deny_count"`
	WindowEnd         pgtype.Timestamptz `json:"window_end"`
	CreatedAt         time.Time          `json:"created_at"`
	PolicyHash        *string            `json:"policy_hash"`
	PolicyVersion     *int32             `json:"policy_version"`
	SrcConfigRevision *int64             `json:"src_config_revision"`
	SrcKind           *string            `json:"src_kind"`
	DecisionReason    *string            `json:"decision_reason"`
}

type AccessEventRetentionAuthorization struct {
	BackendPid    int32     `json:"backend_pid"`
	TransactionID int64     `json:"transaction_id"`
	AccessEventID uuid.UUID `json:"access_event_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type AccessEventRetentionRun struct {
	ID                     uuid.UUID          `json:"id"`
	OrgID                  uuid.UUID          `json:"org_id"`
	TriggerKind            string             `json:"trigger_kind"`
	Status                 string             `json:"status"`
	ManualIdempotencyKey   *string            `json:"manual_idempotency_key"`
	RequestedByUserID      pgtype.UUID        `json:"requested_by_user_id"`
	RetentionDays          int32              `json:"retention_days"`
	CleanupIntervalMinutes int32              `json:"cleanup_interval_minutes"`
	SettingsRevision       int64              `json:"settings_revision"`
	RowCap                 int32              `json:"row_cap"`
	BatchSize              int32              `json:"batch_size"`
	MaxBatches             int32              `json:"max_batches"`
	CutoffAt               time.Time          `json:"cutoff_at"`
	StartedAt              time.Time          `json:"started_at"`
	LeaseExpiresAt         pgtype.Timestamptz `json:"lease_expires_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	DeletedRows            int64              `json:"deleted_rows"`
	Batches                int32              `json:"batches"`
	MorePending            bool               `json:"more_pending"`
	ErrorCode              *string            `json:"error_code"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type AccessEventRetentionSetting struct {
	OrgID                  uuid.UUID `json:"org_id"`
	RetentionDays          int32     `json:"retention_days"`
	CleanupIntervalMinutes int32     `json:"cleanup_interval_minutes"`
	Revision               int64     `json:"revision"`
	UpdatedByUserID        uuid.UUID `json:"updated_by_user_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type AccessEventRetentionState struct {
	OrgID        uuid.UUID `json:"org_id"`
	RetainedRows int64     `json:"retained_rows"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AgentAccessRequest struct {
	ID                       uuid.UUID          `json:"id"`
	OrgID                    uuid.UUID          `json:"org_id"`
	DeviceID                 uuid.UUID          `json:"device_id"`
	DstKind                  string             `json:"dst_kind"`
	DstResourceID            pgtype.UUID        `json:"dst_resource_id"`
	DstGroupID               pgtype.UUID        `json:"dst_group_id"`
	DstSiteID                pgtype.UUID        `json:"dst_site_id"`
	DstK8sServiceID          pgtype.UUID        `json:"dst_k8s_service_id"`
	DstName                  string             `json:"dst_name"`
	Reason                   string             `json:"reason"`
	RequestedDurationSeconds int32              `json:"requested_duration_seconds"`
	State                    string             `json:"state"`
	RequestedByUserID        uuid.UUID          `json:"requested_by_user_id"`
	RequestedAt              time.Time          `json:"requested_at"`
	ApprovedByUserID         pgtype.UUID        `json:"approved_by_user_id"`
	ApprovedAt               pgtype.Timestamptz `json:"approved_at"`
	ApprovedExpiresAt        pgtype.Timestamptz `json:"approved_expires_at"`
	RejectedByUserID         pgtype.UUID        `json:"rejected_by_user_id"`
	RejectedAt               pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason          *string            `json:"rejection_reason"`
	CancelledByUserID        pgtype.UUID        `json:"cancelled_by_user_id"`
	CancelledAt              pgtype.Timestamptz `json:"cancelled_at"`
	RevokedByUserID          pgtype.UUID        `json:"revoked_by_user_id"`
	RevokedAt                pgtype.Timestamptz `json:"revoked_at"`
	PolicyRuleID             pgtype.UUID        `json:"policy_rule_id"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

type AgentAccessRequestEvent struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       uuid.UUID   `json:"org_id"`
	RequestID   uuid.UUID   `json:"request_id"`
	State       string      `json:"state"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorSystem *string     `json:"actor_system"`
	Metadata    []byte      `json:"metadata"`
	CreatedAt   time.Time   `json:"created_at"`
}

type AgentAccessRequestOperation struct {
	OrgID          uuid.UUID `json:"org_id"`
	RequestID      uuid.UUID `json:"request_id"`
	Operation      string    `json:"operation"`
	IdempotencyKey string    `json:"idempotency_key"`
	ParameterHash  string    `json:"parameter_hash"`
	CreatedAt      time.Time `json:"created_at"`
}

type AgentBootstrapToken struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	GatewayNodeID    uuid.UUID          `json:"gateway_node_id"`
	AgentName        string             `json:"agent_name"`
	TokenHash        []byte             `json:"token_hash"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	ConsumedDeviceID pgtype.UUID        `json:"consumed_device_id"`
	IssuedBy         pgtype.UUID        `json:"issued_by"`
	CreatedAt        time.Time          `json:"created_at"`
}

type AgentGroup struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type AgentGroupMember struct {
	OrgID           uuid.UUID `json:"org_id"`
	AgentGroupID    uuid.UUID `json:"agent_group_id"`
	DeviceID        uuid.UUID `json:"device_id"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

// F12 MCP shadow-mode metadata only; no credentials, session ids, contents, prompts, or tool results.
type AgentMcpInventory struct {
	DeviceID   uuid.UUID `json:"device_id"`
	Snapshot   []byte    `json:"snapshot"`
	ObservedAt time.Time `json:"observed_at"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// F13 agent MCP OAuth trust; tokens and client secrets are sealed and never returned by readable APIs.
type AgentMcpOauthConnection struct {
	ID                      uuid.UUID          `json:"id"`
	OrgID                   uuid.UUID          `json:"org_id"`
	DeviceID                uuid.UUID          `json:"device_id"`
	Endpoint                string             `json:"endpoint"`
	ProtectedResource       string             `json:"protected_resource"`
	Issuer                  string             `json:"issuer"`
	Scopes                  []byte             `json:"scopes"`
	ClientID                string             `json:"client_id"`
	ClientSecretSealed      *string            `json:"client_secret_sealed"`
	ClientSecretFingerprint *string            `json:"client_secret_fingerprint"`
	AccessTokenSealed       *string            `json:"access_token_sealed"`
	RefreshTokenSealed      *string            `json:"refresh_token_sealed"`
	TokenExpiresAt          pgtype.Timestamptz `json:"token_expires_at"`
	State                   string             `json:"state"`
	FailureCode             *string            `json:"failure_code"`
	ConnectedByUserID       pgtype.UUID        `json:"connected_by_user_id"`
	ConnectedAt             pgtype.Timestamptz `json:"connected_at"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
}

type AgentMcpProfile struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Name       string             `json:"name"`
	Endpoint   string             `json:"endpoint"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AgentMcpProfileAssignment struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	ProfileID        uuid.UUID          `json:"profile_id"`
	AgentGroupID     uuid.UUID          `json:"agent_group_id"`
	AssignedAt       time.Time          `json:"assigned_at"`
	State            string             `json:"state"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	EndedByUserID    pgtype.UUID        `json:"ended_by_user_id"`
	QuarantineReason *string            `json:"quarantine_reason"`
}

// F16 step-up permits. Exact policy identity plus request digest only; raw MCP arguments, results, OAuth tokens, and secrets are never retained.
type AgentMcpToolApprovalRequest struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	PolicyVersion    int64              `json:"policy_version"`
	Endpoint         string             `json:"endpoint"`
	ServerName       string             `json:"server_name"`
	ToolName         string             `json:"tool_name"`
	InputSchemaHash  string             `json:"input_schema_hash"`
	RequestDigest    string             `json:"request_digest"`
	State            string             `json:"state"`
	RequestedAt      time.Time          `json:"requested_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	ApprovedByUserID pgtype.UUID        `json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	DeniedByUserID   pgtype.UUID        `json:"denied_by_user_id"`
	DeniedAt         pgtype.Timestamptz `json:"denied_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
}

// F14 immutable MCP tool allow policies. Rules contain only stable inventory identities; never arguments, results, OAuth tokens, or client secrets.
type AgentMcpToolPolicyVersion struct {
	ID                  uuid.UUID `json:"id"`
	OrgID               uuid.UUID `json:"org_id"`
	DeviceID            uuid.UUID `json:"device_id"`
	Version             int64     `json:"version"`
	Rules               []byte    `json:"rules"`
	InventoryObservedAt time.Time `json:"inventory_observed_at"`
	CreatedByUserID     uuid.UUID `json:"created_by_user_id"`
	CreatedAt           time.Time `json:"created_at"`
}

type AgentPolicyTemplate struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type AgentPolicyTemplateAssignment struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	AgentGroupID         uuid.UUID          `json:"agent_group_id"`
	TemplateID           uuid.UUID          `json:"template_id"`
	TemplateVersionID    uuid.UUID          `json:"template_version_id"`
	State                string             `json:"state"`
	PreviewDigest        string             `json:"preview_digest"`
	IdempotencyKey       string             `json:"idempotency_key"`
	AppliedByUserID      uuid.UUID          `json:"applied_by_user_id"`
	PreviousAssignmentID pgtype.UUID        `json:"previous_assignment_id"`
	AppliedAt            time.Time          `json:"applied_at"`
	EndedAt              pgtype.Timestamptz `json:"ended_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type AgentPolicyTemplateRuleBinding struct {
	OrgID                 uuid.UUID `json:"org_id"`
	AssignmentID          uuid.UUID `json:"assignment_id"`
	TemplateVersionItemID uuid.UUID `json:"template_version_item_id"`
	PolicyRuleID          uuid.UUID `json:"policy_rule_id"`
	CreatedAt             time.Time `json:"created_at"`
}

type AgentPolicyTemplateVersion struct {
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
	TemplateID      uuid.UUID `json:"template_id"`
	Version         int32     `json:"version"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type AgentPolicyTemplateVersionItem struct {
	ID                uuid.UUID   `json:"id"`
	OrgID             uuid.UUID   `json:"org_id"`
	TemplateVersionID uuid.UUID   `json:"template_version_id"`
	Ordinal           int32       `json:"ordinal"`
	DstKind           string      `json:"dst_kind"`
	DstResourceID     pgtype.UUID `json:"dst_resource_id"`
	DstGroupID        pgtype.UUID `json:"dst_group_id"`
	DstSiteID         pgtype.UUID `json:"dst_site_id"`
	DstK8sServiceID   pgtype.UUID `json:"dst_k8s_service_id"`
	CreatedAt         time.Time   `json:"created_at"`
}

// F01 metadata keyed by the canonical agent device; owner/status/telemetry are deliberately not duplicated here.
type AgentProfile struct {
	DeviceID    uuid.UUID `json:"device_id"`
	Environment string    `json:"environment"`
	Runtime     string    `json:"runtime"`
	Labels      []byte    `json:"labels"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	// Optional existing organization group whose current members may view and manage this agent; not an ownership or policy grant.
	ManagingGroupID pgtype.UUID `json:"managing_group_id"`
}

type AgentRuntimeCredential struct {
	ID                  uuid.UUID          `json:"id"`
	OrgID               uuid.UUID          `json:"org_id"`
	DeviceID            uuid.UUID          `json:"device_id"`
	TokenHash           []byte             `json:"token_hash"`
	CreatedAt           time.Time          `json:"created_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	Revision            int64              `json:"revision"`
	State               string             `json:"state"`
	CandidateExpiresAt  pgtype.Timestamptz `json:"candidate_expires_at"`
	ActivatedAt         pgtype.Timestamptz `json:"activated_at"`
	TerminalAt          pgtype.Timestamptz `json:"terminal_at"`
	RotationRequestedAt pgtype.Timestamptz `json:"rotation_requested_at"`
	RotationDeadline    pgtype.Timestamptz `json:"rotation_deadline"`
	RotationRequestedBy pgtype.UUID        `json:"rotation_requested_by"`
}

// F04 managed-agent desired/applied revision and bounded runtime health; never credential or private-key material.
type AgentRuntimeState struct {
	DeviceID              uuid.UUID          `json:"device_id"`
	DesiredRevision       int64              `json:"desired_revision"`
	AppliedRevision       int64              `json:"applied_revision"`
	LastAttemptedRevision int64              `json:"last_attempted_revision"`
	ClientVersion         string             `json:"client_version"`
	LastSeenAt            pgtype.Timestamptz `json:"last_seen_at"`
	LastErrorCode         *string            `json:"last_error_code"`
	LastErrorRevision     *int64             `json:"last_error_revision"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	RouteFingerprint      string             `json:"route_fingerprint"`
}

type AgentWireguardRotation struct {
	DeviceID           uuid.UUID          `json:"device_id"`
	OrgID              uuid.UUID          `json:"org_id"`
	CurrentRevision    int64              `json:"current_revision"`
	RequestedRevision  *int64             `json:"requested_revision"`
	State              string             `json:"state"`
	CandidatePublicKey *string            `json:"candidate_public_key"`
	RequestedAt        pgtype.Timestamptz `json:"requested_at"`
	Deadline           pgtype.Timestamptz `json:"deadline"`
	RequestedBy        pgtype.UUID        `json:"requested_by"`
	StagedAt           pgtype.Timestamptz `json:"staged_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

// F15 append-only signed workflow assertions. Unverified entries are evidence only and never imply a workflow or human trigger.
type AgentWorkflowProvenance struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	DeviceID             uuid.UUID          `json:"device_id"`
	AssertionID          uuid.UUID          `json:"assertion_id"`
	KeyID                string             `json:"key_id"`
	WorkflowID           *string            `json:"workflow_id"`
	RunID                *string            `json:"run_id"`
	TriggerKind          *string            `json:"trigger_kind"`
	InitiatingSubjectRef *string            `json:"initiating_subject_ref"`
	Tool                 *string            `json:"tool"`
	Resource             *string            `json:"resource"`
	IssuedAt             pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Signature            *string            `json:"signature"`
	VerificationState    string             `json:"verification_state"`
	VerificationReason   string             `json:"verification_reason"`
	ReceivedAt           time.Time          `json:"received_at"`
}

type AgentWorkflowProvenanceUsedAssertion struct {
	DeviceID    uuid.UUID `json:"device_id"`
	AssertionID uuid.UUID `json:"assertion_id"`
	ClaimedAt   time.Time `json:"claimed_at"`
}

type AgentWorkflowSigningKey struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	DeviceID  uuid.UUID          `json:"device_id"`
	KeyID     string             `json:"key_id"`
	PublicKey []byte             `json:"public_key"`
	State     string             `json:"state"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AlertDelivery struct {
	ID              uuid.UUID          `json:"id"`
	OrgID           uuid.UUID          `json:"org_id"`
	DestinationID   uuid.UUID          `json:"destination_id"`
	EventKey        string             `json:"event_key"`
	Severity        string             `json:"severity"`
	DedupKey        string             `json:"dedup_key"`
	Payload         []byte             `json:"payload"`
	State           string             `json:"state"`
	Attempts        int32              `json:"attempts"`
	NextAttemptAt   time.Time          `json:"next_attempt_at"`
	LastError       *string            `json:"last_error"`
	SuppressedCount int32              `json:"suppressed_count"`
	SentAt          pgtype.Timestamptz `json:"sent_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type AlertDeliveryAttempt struct {
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
	DeliveryID     uuid.UUID `json:"delivery_id"`
	Attempt        int32     `json:"attempt"`
	Outcome        string    `json:"outcome"`
	ResponseStatus *int32    `json:"response_status"`
	Error          *string   `json:"error"`
	CreatedAt      time.Time `json:"created_at"`
}

type AlertDeliveryCooldown struct {
	OrgID           uuid.UUID `json:"org_id"`
	DestinationID   uuid.UUID `json:"destination_id"`
	EventKey        string    `json:"event_key"`
	DedupKey        string    `json:"dedup_key"`
	NextEligibleAt  time.Time `json:"next_eligible_at"`
	SuppressedCount int32     `json:"suppressed_count"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type AlertDestination struct {
	ID                  uuid.UUID          `json:"id"`
	OrgID               uuid.UUID          `json:"org_id"`
	Kind                string             `json:"kind"`
	Name                string             `json:"name"`
	EndpointSealed      []byte             `json:"endpoint_sealed"`
	EndpointFingerprint string             `json:"endpoint_fingerprint"`
	EndpointHost        string             `json:"endpoint_host"`
	AllowPrivate        bool               `json:"allow_private"`
	SeverityFloor       string             `json:"severity_floor"`
	CooldownSeconds     int32              `json:"cooldown_seconds"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	CreatedByUserID     uuid.UUID          `json:"created_by_user_id"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type AlertOccurrence struct {
	ID              uuid.UUID          `json:"id"`
	OrgID           uuid.UUID          `json:"org_id"`
	EventKey        string             `json:"event_key"`
	DedupKey        string             `json:"dedup_key"`
	ResourceType    string             `json:"resource_type"`
	ResourceID      string             `json:"resource_id"`
	ResourceName    string             `json:"resource_name"`
	Severity        string             `json:"severity"`
	Subject         string             `json:"subject"`
	Fields          []byte             `json:"fields"`
	State           string             `json:"state"`
	FirstObservedAt time.Time          `json:"first_observed_at"`
	LastObservedAt  time.Time          `json:"last_observed_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	OccurrenceCount int64              `json:"occurrence_count"`
}

type AlertSubscription struct {
	OrgID         uuid.UUID `json:"org_id"`
	DestinationID uuid.UUID `json:"destination_id"`
	EventKey      string    `json:"event_key"`
	CreatedAt     time.Time `json:"created_at"`
}

type AuditLog struct {
	ID          uuid.UUID   `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	TargetType  *string     `json:"target_type"`
	TargetID    *string     `json:"target_id"`
	Metadata    []byte      `json:"metadata"`
	CreatedAt   time.Time   `json:"created_at"`
	ActorSystem *string     `json:"actor_system"`
}

type AuditLogRetentionAuthorization struct {
	BackendPid    int32     `json:"backend_pid"`
	TransactionID int64     `json:"transaction_id"`
	AuditLogID    uuid.UUID `json:"audit_log_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type AuditLogRetentionRun struct {
	ID                     uuid.UUID          `json:"id"`
	OrgID                  uuid.UUID          `json:"org_id"`
	TriggerKind            string             `json:"trigger_kind"`
	Status                 string             `json:"status"`
	ManualIdempotencyKey   *string            `json:"manual_idempotency_key"`
	RequestedByUserID      pgtype.UUID        `json:"requested_by_user_id"`
	RetentionDays          int32              `json:"retention_days"`
	CleanupIntervalMinutes int32              `json:"cleanup_interval_minutes"`
	SettingsRevision       int64              `json:"settings_revision"`
	BatchSize              int32              `json:"batch_size"`
	MaxBatches             int32              `json:"max_batches"`
	CutoffAt               time.Time          `json:"cutoff_at"`
	StartedAt              time.Time          `json:"started_at"`
	LeaseExpiresAt         pgtype.Timestamptz `json:"lease_expires_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	DeletedRows            int64              `json:"deleted_rows"`
	Batches                int32              `json:"batches"`
	MorePending            bool               `json:"more_pending"`
	ErrorCode              *string            `json:"error_code"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type AuditLogRetentionSetting struct {
	OrgID                  uuid.UUID `json:"org_id"`
	RetentionDays          *int32    `json:"retention_days"`
	CleanupIntervalMinutes int32     `json:"cleanup_interval_minutes"`
	Revision               int64     `json:"revision"`
	UpdatedByUserID        uuid.UUID `json:"updated_by_user_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type AuthToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Purpose    string             `json:"purpose"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type CliAuthCode struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	CodeHash      []byte             `json:"code_hash"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     time.Time          `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type CliCredential struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   []byte             `json:"token_hash"`
	Fingerprint string             `json:"fingerprint"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type CliDeviceCode struct {
	ID             uuid.UUID          `json:"id"`
	DeviceCodeHash []byte             `json:"device_code_hash"`
	UserCodeHash   []byte             `json:"user_code_hash"`
	UserID         pgtype.UUID        `json:"user_id"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	ExpiresAt      time.Time          `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type Device struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	UserID            uuid.UUID          `json:"user_id"`
	NodeID            uuid.UUID          `json:"node_id"`
	Name              string             `json:"name"`
	Platform          string             `json:"platform"`
	PublicKey         string             `json:"public_key"`
	AssignedIp        *string            `json:"assigned_ip"`
	Status            string             `json:"status"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	FullTunnel        bool               `json:"full_tunnel"`
	ApprovedBy        pgtype.UUID        `json:"approved_by"`
	HealthBlocked     bool               `json:"health_blocked"`
	Transport         string             `json:"transport"`
	ProvisioningMode  string             `json:"provisioning_mode"`
	ProvisionedRanges []byte             `json:"provisioned_ranges"`
	// Why this device was revoked: 'cascade' (its gateway was revoked — restorable) or 'deliberate' (an operator revoked this device — never restorable). NULL = revoked before 0059, honestly unknown, treated as NOT restorable (S13.1 D5).
	RevokedCause *string `json:"revoked_cause"`
	// The tunnel address baked into this device's ISSUED config, snapshotted at issuance for every provisioning mode. Compared against assigned_ip at read time to derive needs_reexport. NULL = predates 0060, honestly unknown, not reported stale (S13.1 Slice 6).
	ProvisionedIp     *string `json:"provisioned_ip"`
	RevokedPrevStatus *string `json:"revoked_prev_status"`
	// The gateway whose endpoint + public key this device's ISSUED config baked. Compared against node_id at read time to derive needs_reexport for STATIC exports (S13.1 review fold F3).
	ProvisionedNodeID pgtype.UUID `json:"provisioned_node_id"`
	Kind              string      `json:"kind"`
}

type DeviceHealth struct {
	DeviceID       uuid.UUID          `json:"device_id"`
	Platform       string             `json:"platform"`
	OsVersion      string             `json:"os_version"`
	DiskEncrypted  *bool              `json:"disk_encrypted"`
	EvaluatedState string             `json:"evaluated_state"`
	FailedChecks   []byte             `json:"failed_checks"`
	CollectedAt    pgtype.Timestamptz `json:"collected_at"`
	ReportedAt     time.Time          `json:"reported_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type DeviceStatus struct {
	DeviceID        uuid.UUID          `json:"device_id"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         int64              `json:"rx_bytes"`
	TxBytes         int64              `json:"tx_bytes"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type DomainClaim struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	Domain            string             `json:"domain"`
	VerificationToken string             `json:"verification_token"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	LastCheckedAt     pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type FqdnGatewayDnsRequest struct {
	RequestID             uuid.UUID          `json:"request_id"`
	ProtocolVersion       int16              `json:"protocol_version"`
	OrgID                 uuid.UUID          `json:"org_id"`
	ResourceID            uuid.UUID          `json:"resource_id"`
	SiteID                uuid.UUID          `json:"site_id"`
	GatewayID             uuid.UUID          `json:"gateway_id"`
	Hostname              string             `json:"hostname"`
	RecordTypes           []byte             `json:"record_types"`
	Deadline              time.Time          `json:"deadline"`
	State                 string             `json:"state"`
	Response              []byte             `json:"response"`
	CreatedAt             time.Time          `json:"created_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	ExpiredAt             pgtype.Timestamptz `json:"expired_at"`
	ResolverConfigID      pgtype.UUID        `json:"resolver_config_id"`
	ResolverConfigVersion *int64             `json:"resolver_config_version"`
	ResolverEndpoints     []byte             `json:"resolver_endpoints"`
	ResolverProfileID     pgtype.UUID        `json:"resolver_profile_id"`
	ResolverMatchSuffix   *string            `json:"resolver_match_suffix"`
}

type FqdnResolverContextConfig struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	SiteID       uuid.UUID          `json:"site_id"`
	GatewayID    uuid.UUID          `json:"gateway_id"`
	Version      int64              `json:"version"`
	State        string             `json:"state"`
	CreatedAt    time.Time          `json:"created_at"`
	RetiredAt    pgtype.Timestamptz `json:"retired_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	ProviderHint *string            `json:"provider_hint"`
}

type FqdnResolverContextEndpoint struct {
	ConfigID  uuid.UUID  `json:"config_id"`
	OrgID     uuid.UUID  `json:"org_id"`
	Ordinal   int16      `json:"ordinal"`
	Address   netip.Addr `json:"address"`
	Port      int32      `json:"port"`
	Transport string     `json:"transport"`
}

type FqdnResolverContextProfile struct {
	ID            uuid.UUID `json:"id"`
	ConfigID      uuid.UUID `json:"config_id"`
	OrgID         uuid.UUID `json:"org_id"`
	Ordinal       int16     `json:"ordinal"`
	Name          string    `json:"name"`
	ProviderHint  string    `json:"provider_hint"`
	LegacyDefault bool      `json:"legacy_default"`
}

type FqdnResolverContextProfileEndpoint struct {
	ProfileID uuid.UUID  `json:"profile_id"`
	OrgID     uuid.UUID  `json:"org_id"`
	Ordinal   int16      `json:"ordinal"`
	Address   netip.Addr `json:"address"`
	Port      int32      `json:"port"`
	Transport string     `json:"transport"`
}

type FqdnResolverContextProfileSuffix struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ConfigID  uuid.UUID `json:"config_id"`
	OrgID     uuid.UUID `json:"org_id"`
	Suffix    string    `json:"suffix"`
}

type FqdnResource struct {
	ID             uuid.UUID   `json:"id"`
	OrgID          uuid.UUID   `json:"org_id"`
	Name           string      `json:"name"`
	Fqdn           string      `json:"fqdn"`
	Protocol       string      `json:"protocol"`
	PortLow        *int32      `json:"port_low"`
	PortHigh       *int32      `json:"port_high"`
	ResolverNodeID pgtype.UUID `json:"resolver_node_id"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	Label          *string     `json:"label"`
	ResolverSiteID pgtype.UUID `json:"resolver_site_id"`
}

type FqdnResourceAnswerGeneration struct {
	ID                  uuid.UUID          `json:"id"`
	OrgID               uuid.UUID          `json:"org_id"`
	ResourceID          uuid.UUID          `json:"resource_id"`
	Generation          int64              `json:"generation"`
	ResolverNodeID      uuid.UUID          `json:"resolver_node_id"`
	State               string             `json:"state"`
	EffectiveTtl        pgtype.Interval    `json:"effective_ttl"`
	ResolvedAt          time.Time          `json:"resolved_at"`
	LastGoodAt          pgtype.Timestamptz `json:"last_good_at"`
	ActivatedAt         pgtype.Timestamptz `json:"activated_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	FailureCode         *string            `json:"failure_code"`
	CreatedAt           time.Time          `json:"created_at"`
	ResolverSiteID      pgtype.UUID        `json:"resolver_site_id"`
	ResolverConfigID    pgtype.UUID        `json:"resolver_config_id"`
	ResolverProfileID   pgtype.UUID        `json:"resolver_profile_id"`
	ResolverMatchSuffix *string            `json:"resolver_match_suffix"`
}

type FqdnResourceGenerationAnswer struct {
	GenerationID uuid.UUID  `json:"generation_id"`
	OrgID        uuid.UUID  `json:"org_id"`
	Address      netip.Addr `json:"address"`
	CreatedAt    time.Time  `json:"created_at"`
}

type FqdnResourceRuleReference struct {
	PolicyRuleID uuid.UUID `json:"policy_rule_id"`
	OrgID        uuid.UUID `json:"org_id"`
	ResourceID   uuid.UUID `json:"resource_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type GroupMember struct {
	OrgID         uuid.UUID `json:"org_id"`
	GroupID       uuid.UUID `json:"group_id"`
	UserID        uuid.UUID `json:"user_id"`
	CreatedAt     time.Time `json:"created_at"`
	Origin        string    `json:"origin"`
	IdpExternalID *string   `json:"idp_external_id"`
}

type IdpSyncConfig struct {
	ID                  uuid.UUID          `json:"id"`
	OrgID               uuid.UUID          `json:"org_id"`
	Provider            string             `json:"provider"`
	ClientID            string             `json:"client_id"`
	SecretSealed        []byte             `json:"secret_sealed"`
	TenantID            *string            `json:"tenant_id"`
	Enabled             bool               `json:"enabled"`
	LastSyncAt          pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncOk          bool               `json:"last_sync_ok"`
	LastSyncError       *string            `json:"last_sync_error"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	DelegatedAdminEmail *string            `json:"delegated_admin_email"`
}

type Invitation struct {
	ID              uuid.UUID          `json:"id"`
	OrgID           uuid.UUID          `json:"org_id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       time.Time          `json:"expires_at"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	InvitedByUserID pgtype.UUID        `json:"invited_by_user_id"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type K8sBaseAuthorityAckReceipt struct {
	DeliveryID         uuid.UUID `json:"delivery_id"`
	OrgID              uuid.UUID `json:"org_id"`
	SiteID             uuid.UUID `json:"site_id"`
	NodeID             uuid.UUID `json:"node_id"`
	AuthorityRevision  int64     `json:"authority_revision"`
	PayloadDigest      string    `json:"payload_digest"`
	AppliedBaseVersion int64     `json:"applied_base_version"`
	AppliedBaseHash    string    `json:"applied_base_hash"`
	AgentAppliedAt     time.Time `json:"agent_applied_at"`
	ReceiptTime        time.Time `json:"receipt_time"`
	CreatedAt          time.Time `json:"created_at"`
}

type K8sBaseAuthorityDelivery struct {
	ID                 uuid.UUID `json:"id"`
	OrgID              uuid.UUID `json:"org_id"`
	SiteID             uuid.UUID `json:"site_id"`
	NodeID             uuid.UUID `json:"node_id"`
	AuthorityRevision  int64     `json:"authority_revision"`
	WireVersion        int32     `json:"wire_version"`
	BaseVersion        int64     `json:"base_version"`
	BaseHash           string    `json:"base_hash"`
	PayloadDigest      string    `json:"payload_digest"`
	Payload            []byte    `json:"payload"`
	TransitionRevision *int64    `json:"transition_revision"`
	ExpiresAt          time.Time `json:"expires_at"`
	CreatedAt          time.Time `json:"created_at"`
	AuthorityKind      string    `json:"authority_kind"`
}

type K8sBaseAuthorityDeliveryPool struct {
	DeliveryID           uuid.UUID `json:"delivery_id"`
	OrgID                uuid.UUID `json:"org_id"`
	SiteID               uuid.UUID `json:"site_id"`
	NodeID               uuid.UUID `json:"node_id"`
	ClusterID            uuid.UUID `json:"cluster_id"`
	PoolID               uuid.UUID `json:"pool_id"`
	PromotionGeneration  int64     `json:"promotion_generation"`
	Kind                 string    `json:"kind"`
	Disposition          *string   `json:"disposition"`
	Classification       []byte    `json:"classification"`
	ClassificationDigest *string   `json:"classification_digest"`
}

type K8sBaseAuthorityNodeState struct {
	OrgID                     uuid.UUID `json:"org_id"`
	SiteID                    uuid.UUID `json:"site_id"`
	NodeID                    uuid.UUID `json:"node_id"`
	NextAuthorityRevision     int64     `json:"next_authority_revision"`
	AcceptedAuthorityRevision int64     `json:"accepted_authority_revision"`
	AcceptedPayloadDigest     *string   `json:"accepted_payload_digest"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
}

type K8sCluster struct {
	ID               uuid.UUID    `json:"id"`
	OrgID            uuid.UUID    `json:"org_id"`
	SiteID           uuid.UUID    `json:"site_id"`
	Name             string       `json:"name"`
	VipRange         netip.Prefix `json:"vip_range"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	ServiceCidr      netip.Prefix `json:"service_cidr"`
	DnsZone          string       `json:"dns_zone"`
	DnsVip           *netip.Addr  `json:"dns_vip"`
	ManagedByMachine pgtype.UUID  `json:"managed_by_machine"`
	ConnectorNodeID  pgtype.UUID  `json:"connector_node_id"`
	ConnectorPoolID  pgtype.UUID  `json:"connector_pool_id"`
	Provider         string       `json:"provider"`
	Platform         string       `json:"platform"`
}

type K8sClusterScopeGrant struct {
	RuleID                uuid.UUID `json:"rule_id"`
	OrgID                 uuid.UUID `json:"org_id"`
	ClusterID             uuid.UUID `json:"cluster_id"`
	CreatedByUserID       uuid.UUID `json:"created_by_user_id"`
	InitialCandidateCount int32     `json:"initial_candidate_count"`
	Active                bool      `json:"active"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	Revision              int64     `json:"revision"`
}

type K8sClusterScopeInitialCandidate struct {
	RuleID            uuid.UUID `json:"rule_id"`
	OrgID             uuid.UUID `json:"org_id"`
	ClusterID         uuid.UUID `json:"cluster_id"`
	ServiceChildID    uuid.UUID `json:"service_child_id"`
	InventoryReportID uuid.UUID `json:"inventory_report_id"`
	Namespace         string    `json:"namespace"`
	ServiceUid        string    `json:"service_uid"`
	Protocol          string    `json:"protocol"`
	PortLow           int32     `json:"port_low"`
	PortHigh          int32     `json:"port_high"`
	Selected          bool      `json:"selected"`
	CreatedAt         time.Time `json:"created_at"`
}

type K8sClusterScopeMembership struct {
	RuleID          uuid.UUID          `json:"rule_id"`
	OrgID           uuid.UUID          `json:"org_id"`
	ClusterID       uuid.UUID          `json:"cluster_id"`
	ServiceChildID  uuid.UUID          `json:"service_child_id"`
	Namespace       string             `json:"namespace"`
	ServiceUid      string             `json:"service_uid"`
	Protocol        string             `json:"protocol"`
	PortLow         int32              `json:"port_low"`
	PortHigh        int32              `json:"port_high"`
	Status          string             `json:"status"`
	DecidedByUserID pgtype.UUID        `json:"decided_by_user_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	Origin          *string            `json:"origin"`
}

type K8sClusterScopeSetting struct {
	OrgID       uuid.UUID `json:"org_id"`
	Enabled     bool      `json:"enabled"`
	Revision    int64     `json:"revision"`
	ActorUserID uuid.UUID `json:"actor_user_id"`
	Cause       string    `json:"cause"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type K8sConnectorHandoffOperation struct {
	ID                                    uuid.UUID          `json:"id"`
	OrgID                                 uuid.UUID          `json:"org_id"`
	SiteID                                uuid.UUID          `json:"site_id"`
	PoolID                                uuid.UUID          `json:"pool_id"`
	ClusterID                             uuid.UUID          `json:"cluster_id"`
	OldNodeID                             uuid.UUID          `json:"old_node_id"`
	NewNodeID                             uuid.UUID          `json:"new_node_id"`
	ExpectedGeneration                    int64              `json:"expected_generation"`
	TargetGeneration                      int64              `json:"target_generation"`
	OldServingManifestIdentity            string             `json:"old_serving_manifest_identity"`
	CandidatePreparedManifestIdentity     string             `json:"candidate_prepared_manifest_identity"`
	OldWithdrawalManifestIdentity         string             `json:"old_withdrawal_manifest_identity"`
	NewServingManifestIdentity            string             `json:"new_serving_manifest_identity"`
	OldServingManifestRevision            int64              `json:"old_serving_manifest_revision"`
	CandidatePreparedManifestRevision     int64              `json:"candidate_prepared_manifest_revision"`
	OldWithdrawalManifestRevision         int64              `json:"old_withdrawal_manifest_revision"`
	NewServingManifestRevision            int64              `json:"new_serving_manifest_revision"`
	OldServingExpectedRouteDigest         string             `json:"old_serving_expected_route_digest"`
	OldServingExpectedVipMapDigest        string             `json:"old_serving_expected_vip_map_digest"`
	CandidatePreparedExpectedRouteDigest  string             `json:"candidate_prepared_expected_route_digest"`
	CandidatePreparedExpectedVipMapDigest string             `json:"candidate_prepared_expected_vip_map_digest"`
	OldWithdrawalExpectedRouteDigest      string             `json:"old_withdrawal_expected_route_digest"`
	OldWithdrawalExpectedVipMapDigest     string             `json:"old_withdrawal_expected_vip_map_digest"`
	NewServingExpectedRouteDigest         string             `json:"new_serving_expected_route_digest"`
	NewServingExpectedVipMapDigest        string             `json:"new_serving_expected_vip_map_digest"`
	OldLeaseIdentity                      string             `json:"old_lease_identity"`
	TargetLeaseIdentity                   string             `json:"target_lease_identity"`
	OldLeaseEpoch                         int64              `json:"old_lease_epoch"`
	TargetLeaseEpoch                      int64              `json:"target_lease_epoch"`
	OldLeaseExpiresAt                     time.Time          `json:"old_lease_expires_at"`
	TargetLeaseExpiresAt                  time.Time          `json:"target_lease_expires_at"`
	ObservedMembershipEpoch               *int64             `json:"observed_membership_epoch"`
	DecisionTransition                    string             `json:"decision_transition"`
	OldServingRole                        string             `json:"old_serving_role"`
	CandidatePreparedRole                 string             `json:"candidate_prepared_role"`
	OldWithdrawalRole                     string             `json:"old_withdrawal_role"`
	NewServingRole                        string             `json:"new_serving_role"`
	Phase                                 string             `json:"phase"`
	PreparedAckReceivedAt                 pgtype.Timestamptz `json:"prepared_ack_received_at"`
	WithdrawalAckReceivedAt               pgtype.Timestamptz `json:"withdrawal_ack_received_at"`
	WithdrawalExpiryReceivedAt            pgtype.Timestamptz `json:"withdrawal_expiry_received_at"`
	ServingAckReceivedAt                  pgtype.Timestamptz `json:"serving_ack_received_at"`
	CasReceiptAt                          pgtype.Timestamptz `json:"cas_receipt_at"`
	CasAuditID                            pgtype.UUID        `json:"cas_audit_id"`
	CasAuditApplied                       bool               `json:"cas_audit_applied"`
	FailureReason                         *string            `json:"failure_reason"`
	CreatedAt                             time.Time          `json:"created_at"`
	UpdatedAt                             time.Time          `json:"updated_at"`
}

type K8sConnectorPool struct {
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
	SiteID          uuid.UUID `json:"site_id"`
	ClusterID       uuid.UUID `json:"cluster_id"`
	PreferredNodeID uuid.UUID `json:"preferred_node_id"`
	ActiveNodeID    uuid.UUID `json:"active_node_id"`
	Generation      int64     `json:"generation"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type K8sConnectorPoolHaTransition struct {
	PoolID                    uuid.UUID          `json:"pool_id"`
	OrgID                     uuid.UUID          `json:"org_id"`
	SiteID                    uuid.UUID          `json:"site_id"`
	ClusterID                 uuid.UUID          `json:"cluster_id"`
	RequestedMode             string             `json:"requested_mode"`
	ActualMode                string             `json:"actual_mode"`
	ActiveNodeID              uuid.UUID          `json:"active_node_id"`
	PromotionGeneration       int64              `json:"promotion_generation"`
	MembershipEpoch           *int64             `json:"membership_epoch"`
	TransitionRevision        int64              `json:"transition_revision"`
	AchievedAuthorityRevision *int64             `json:"achieved_authority_revision"`
	ReasonCode                string             `json:"reason_code"`
	ActorUserID               pgtype.UUID        `json:"actor_user_id"`
	ActorSystem               *string            `json:"actor_system"`
	Cause                     string             `json:"cause"`
	RequestedAt               time.Time          `json:"requested_at"`
	AchievedAt                pgtype.Timestamptz `json:"achieved_at"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 time.Time          `json:"updated_at"`
}

type K8sConnectorPoolHealthCandidateTick struct {
	StateID      uuid.UUID `json:"state_id"`
	OrgID        uuid.UUID `json:"org_id"`
	SiteID       uuid.UUID `json:"site_id"`
	ClusterID    uuid.UUID `json:"cluster_id"`
	PoolID       uuid.UUID `json:"pool_id"`
	NodeID       uuid.UUID `json:"node_id"`
	HealthyTicks int32     `json:"healthy_ticks"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type K8sConnectorPoolHealthState struct {
	ID                       uuid.UUID          `json:"id"`
	OrgID                    uuid.UUID          `json:"org_id"`
	SiteID                   uuid.UUID          `json:"site_id"`
	ClusterID                uuid.UUID          `json:"cluster_id"`
	PoolID                   uuid.UUID          `json:"pool_id"`
	MembershipEpoch          int64              `json:"membership_epoch"`
	ObservedActiveNodeID     uuid.UUID          `json:"observed_active_node_id"`
	ObservedGeneration       int64              `json:"observed_generation"`
	StaleTicks               int32              `json:"stale_ticks"`
	PreferredFreshTicks      int32              `json:"preferred_fresh_ticks"`
	LastTransition           string             `json:"last_transition"`
	LastTransitionFromNodeID pgtype.UUID        `json:"last_transition_from_node_id"`
	LastTransitionToNodeID   pgtype.UUID        `json:"last_transition_to_node_id"`
	LastObservationKey       *string            `json:"last_observation_key"`
	LastObservationAt        pgtype.Timestamptz `json:"last_observation_at"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

type K8sConnectorPoolMember struct {
	PoolID        uuid.UUID `json:"pool_id"`
	OrgID         uuid.UUID `json:"org_id"`
	SiteID        uuid.UUID `json:"site_id"`
	NodeID        uuid.UUID `json:"node_id"`
	AdminPriority int32     `json:"admin_priority"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type K8sHaSetting struct {
	OrgID       uuid.UUID   `json:"org_id"`
	Enabled     bool        `json:"enabled"`
	Revision    int64       `json:"revision"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorSystem *string     `json:"actor_system"`
	Cause       string      `json:"cause"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type K8sLifecycleClaimUsage struct {
	Singleton        bool      `json:"singleton"`
	FirstPersistedAt time.Time `json:"first_persisted_at"`
}

type K8sLifecycleInstallOperationUsage struct {
	Singleton        bool      `json:"singleton"`
	FirstPersistedAt time.Time `json:"first_persisted_at"`
}

type K8sPoolOwnershipV2Capability struct {
	OrgID         uuid.UUID `json:"org_id"`
	SiteID        uuid.UUID `json:"site_id"`
	ClusterID     uuid.UUID `json:"cluster_id"`
	PoolID        uuid.UUID `json:"pool_id"`
	NodeID        uuid.UUID `json:"node_id"`
	WireVersion   int32     `json:"wire_version"`
	DeliveryRowID uuid.UUID `json:"delivery_row_id"`
	ReceiptTime   time.Time `json:"receipt_time"`
	ExpiresAt     time.Time `json:"expires_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type K8sPoolServiceUidProvenance struct {
	OrgID               uuid.UUID `json:"org_id"`
	SiteID              uuid.UUID `json:"site_id"`
	ClusterID           uuid.UUID `json:"cluster_id"`
	PoolID              uuid.UUID `json:"pool_id"`
	ActiveNodeID        uuid.UUID `json:"active_node_id"`
	PromotionGeneration int64     `json:"promotion_generation"`
	LedgerID            uuid.UUID `json:"ledger_id"`
	Namespace           string    `json:"namespace"`
	Service             string    `json:"service"`
	ServiceUid          string    `json:"service_uid"`
	ObservationRevision int64     `json:"observation_revision"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type K8sService struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	ClusterID        uuid.UUID          `json:"cluster_id"`
	Name             string             `json:"name"`
	Namespace        string             `json:"namespace"`
	Protocol         string             `json:"protocol"`
	PortLow          *int32             `json:"port_low"`
	PortHigh         *int32             `json:"port_high"`
	Vip              netip.Addr         `json:"vip"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ManagedByMachine pgtype.UUID        `json:"managed_by_machine"`
	IdentityID       pgtype.UUID        `json:"identity_id"`
}

type K8sServiceIdentity struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	ClusterID uuid.UUID          `json:"cluster_id"`
	Name      string             `json:"name"`
	Namespace string             `json:"namespace"`
	Vip       netip.Addr         `json:"vip"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type K8sServiceInventoryItem struct {
	ReportID     uuid.UUID `json:"report_id"`
	OrgID        uuid.UUID `json:"org_id"`
	ClusterID    uuid.UUID `json:"cluster_id"`
	InventoryRef uuid.UUID `json:"inventory_ref"`
	Namespace    string    `json:"namespace"`
	Service      string    `json:"service"`
	ServiceUid   string    `json:"service_uid"`
	PortCount    int32     `json:"port_count"`
	CreatedAt    time.Time `json:"created_at"`
}

type K8sServiceInventoryPort struct {
	ReportID     uuid.UUID `json:"report_id"`
	InventoryRef uuid.UUID `json:"inventory_ref"`
	PortRef      uuid.UUID `json:"port_ref"`
	Name         *string   `json:"name"`
	Protocol     string    `json:"protocol"`
	ServicePort  int32     `json:"service_port"`
	TargetPort   *int32    `json:"target_port"`
	CreatedAt    time.Time `json:"created_at"`
}

type K8sServiceInventoryReport struct {
	ID                  uuid.UUID `json:"id"`
	OrgID               uuid.UUID `json:"org_id"`
	SiteID              uuid.UUID `json:"site_id"`
	ClusterID           uuid.UUID `json:"cluster_id"`
	ConnectorNodeID     uuid.UUID `json:"connector_node_id"`
	ReplayStateID       uuid.UUID `json:"replay_state_id"`
	ReplaySequence      int64     `json:"replay_sequence"`
	PromotionGeneration int64     `json:"promotion_generation"`
	Digest              string    `json:"digest"`
	ServiceCount        int32     `json:"service_count"`
	ObservedAt          time.Time `json:"observed_at"`
	ReceivedAt          time.Time `json:"received_at"`
	FreshUntil          time.Time `json:"fresh_until"`
	CreatedAt           time.Time `json:"created_at"`
}

type K8sServiceInventoryRetentionAuthorization struct {
	BackendPid    int32     `json:"backend_pid"`
	TransactionID int64     `json:"transaction_id"`
	ReportID      uuid.UUID `json:"report_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type K8sServiceUidObservationCurrent struct {
	LedgerID       uuid.UUID `json:"ledger_id"`
	OrgID          uuid.UUID `json:"org_id"`
	Namespace      string    `json:"namespace"`
	Service        string    `json:"service"`
	Uid            string    `json:"uid"`
	State          string    `json:"state"`
	ReplaySequence int64     `json:"replay_sequence"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type K8sServiceUidObservationCurrentAttribution struct {
	LedgerID       uuid.UUID `json:"ledger_id"`
	OrgID          uuid.UUID `json:"org_id"`
	Namespace      string    `json:"namespace"`
	Service        string    `json:"service"`
	ReplayStateID  uuid.UUID `json:"replay_state_id"`
	ReplaySequence int64     `json:"replay_sequence"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type K8sServiceUidObservationLedger struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	SiteID        uuid.UUID `json:"site_id"`
	ClusterID     uuid.UUID `json:"cluster_id"`
	ScopeIdentity string    `json:"scope_identity"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type K8sServiceUidObservationReceipt struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	ReplayStateID uuid.UUID `json:"replay_state_id"`
	Sequence      int64     `json:"sequence"`
	Digest        string    `json:"digest"`
	ReceiptTime   time.Time `json:"receipt_time"`
	CreatedAt     time.Time `json:"created_at"`
}

type K8sServiceUidObservationReplayState struct {
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
	SiteID          uuid.UUID `json:"site_id"`
	ClusterID       uuid.UUID `json:"cluster_id"`
	ConnectorNodeID uuid.UUID `json:"connector_node_id"`
	ScopeIdentity   string    `json:"scope_identity"`
	Sequence        int64     `json:"sequence"`
	Digest          string    `json:"digest"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type K8sServiceUidObservationRetired struct {
	LedgerID              uuid.UUID `json:"ledger_id"`
	OrgID                 uuid.UUID `json:"org_id"`
	Namespace             string    `json:"namespace"`
	Service               string    `json:"service"`
	Uid                   string    `json:"uid"`
	RetiredReplaySequence int64     `json:"retired_replay_sequence"`
	RetiredAt             time.Time `json:"retired_at"`
}

type MachineCredential struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	TokenHash   []byte             `json:"token_hash"`
	Fingerprint string             `json:"fingerprint"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	UserID      pgtype.UUID        `json:"user_id"`
}

type Membership struct {
	ID              uuid.UUID          `json:"id"`
	OrgID           uuid.UUID          `json:"org_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Role            string             `json:"role"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	AccessRevokedAt pgtype.Timestamptz `json:"access_revoked_at"`
}

type MembershipAccessSource struct {
	OrgID      uuid.UUID `json:"org_id"`
	UserID     uuid.UUID `json:"user_id"`
	SourceType string    `json:"source_type"`
	SourceKey  string    `json:"source_key"`
	CreatedAt  time.Time `json:"created_at"`
}

type MfaChallenge struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	Attempts  int32     `json:"attempts"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Node struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	Name              string             `json:"name"`
	Status            string             `json:"status"`
	CertSerial        string             `json:"cert_serial"`
	AgentVersion      string             `json:"agent_version"`
	EnrolledAt        time.Time          `json:"enrolled_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	WgPublicKey       string             `json:"wg_public_key"`
	Endpoint          string             `json:"endpoint"`
	Capabilities      []byte             `json:"capabilities"`
	PolicyDesyncSince pgtype.Timestamptz `json:"policy_desync_since"`
	PolicyReportedAt  pgtype.Timestamptz `json:"policy_reported_at"`
	SiteID            pgtype.UUID        `json:"site_id"`
	HubPriority       *int32             `json:"hub_priority"`
	// Expiry of the currently-issued agent cert. Stamped at enroll/renew from the certificate's own NotAfter. Rows predating migration 0054 carry a BOUND backfilled by 0055 as last_seen_at + CertTTL (an UPPER bound on the true expiry, so it can never false-positive; overwritten by the real value on the next enroll/renew). NULL = never reported, honestly unknown. Past = the agent CANNOT reconnect (S11 WF-S11-6).
	CertNotAfter pgtype.Timestamptz `json:"cert_not_after"`
	// base64(SPKI DER) of the public key bound by the current agent certificate, stamped at enroll and renew. Verification material for proof-of-possession re-key (S13.1 D7). NULL = enrolled before 0057 and not yet renewed: PoP cannot recover that node, only a join token can.
	CertPublicKey *string `json:"cert_public_key"`
	// SHA-256 of cert_public_key's SPKI DER, lowercase hex. GENERATED from the key so the two cannot drift. The second re-key identifier (S13.1 D10); NOT unique — the lookup refuses on multiple matches.
	CertKeyFingerprint *string `json:"cert_key_fingerprint"`
	// When the CURRENT cert_serial was first seen authenticating on the agent channel. NULL = issued but never used, which is the only state the D3 redelivery carve-out authorizes. Cleared by RekeyNode in the same statement that replaces cert_serial (S13.1).
	CertDeliveredAt pgtype.Timestamptz `json:"cert_delivered_at"`
	// FALSE only while the CURRENT cert_serial has never authenticated — the only state the D3 redelivery carve-out authorizes. DEFAULT TRUE so any writer that does not know this column (an older control-plane replica mid-roll, or CreateNode) lands in the CLOSED state (S13.1).
	CertDelivered  bool        `json:"cert_delivered"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
	EnrolledKind   *string     `json:"enrolled_kind"`
	LifecycleClaim pgtype.UUID `json:"lifecycle_claim"`
}

type NodeJoinToken struct {
	ID                      uuid.UUID          `json:"id"`
	OrgID                   uuid.UUID          `json:"org_id"`
	NodeName                *string            `json:"node_name"`
	TokenHash               []byte             `json:"token_hash"`
	ExpiresAt               time.Time          `json:"expires_at"`
	ConsumedAt              pgtype.Timestamptz `json:"consumed_at"`
	ConsumedNodeID          pgtype.UUID        `json:"consumed_node_id"`
	CreatedAt               time.Time          `json:"created_at"`
	IssuedBy                pgtype.UUID        `json:"issued_by"`
	EnrolsKind              string             `json:"enrols_kind"`
	LifecycleClaim          pgtype.UUID        `json:"lifecycle_claim"`
	LifecycleGeneration     int32              `json:"lifecycle_generation"`
	LifecycleRequestID      pgtype.UUID        `json:"lifecycle_request_id"`
	LifecycleTokenSealed    *string            `json:"lifecycle_token_sealed"`
	LifecycleAcknowledgedAt pgtype.Timestamptz `json:"lifecycle_acknowledged_at"`
	LifecycleAbortedAt      pgtype.Timestamptz `json:"lifecycle_aborted_at"`
}

type NodeLifecycleEnrollmentAuthorization struct {
	BackendPid     int32     `json:"backend_pid"`
	TransactionID  int64     `json:"transaction_id"`
	TokenID        uuid.UUID `json:"token_id"`
	OrgID          uuid.UUID `json:"org_id"`
	NodeName       string    `json:"node_name"`
	LifecycleClaim uuid.UUID `json:"lifecycle_claim"`
}

type NodeLifecycleInstallOperation struct {
	OperationID              uuid.UUID          `json:"operation_id"`
	TokenID                  uuid.UUID          `json:"token_id"`
	OrgID                    uuid.UUID          `json:"org_id"`
	LifecycleClaim           uuid.UUID          `json:"lifecycle_claim"`
	LifecycleGeneration      int32              `json:"lifecycle_generation"`
	LifecycleRequestID       uuid.UUID          `json:"lifecycle_request_id"`
	Epoch                    int64              `json:"epoch"`
	ReleaseNamespace         string             `json:"release_namespace"`
	ReleaseName              string             `json:"release_name"`
	InstallIntentDigest      string             `json:"install_intent_digest"`
	RequestedDurationSeconds int32              `json:"requested_duration_seconds"`
	State                    string             `json:"state"`
	NotAfter                 time.Time          `json:"not_after"`
	HeartbeatAt              time.Time          `json:"heartbeat_at"`
	AbortRequestedAt         pgtype.Timestamptz `json:"abort_requested_at"`
	ReleasedAt               pgtype.Timestamptz `json:"released_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
	TakenOverAt              pgtype.Timestamptz `json:"taken_over_at"`
	AbortedAt                pgtype.Timestamptz `json:"aborted_at"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

type NodePeerStatus struct {
	NodeID          uuid.UUID          `json:"node_id"`
	PublicKey       string             `json:"public_key"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         int64              `json:"rx_bytes"`
	TxBytes         int64              `json:"tx_bytes"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type NodeRekeyChallenge struct {
	Nonce          []byte             `json:"nonce"`
	CertSerial     *string            `json:"cert_serial"`
	CreatedAt      time.Time          `json:"created_at"`
	ExpiresAt      time.Time          `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	Identifier     *string            `json:"identifier"`
	IdentifierKind string             `json:"identifier_kind"`
}

type OrgHealthCheck struct {
	OrgID     uuid.UUID `json:"org_id"`
	CheckKind string    `json:"check_kind"`
	Mode      string    `json:"mode"`
	Param     []byte    `json:"param"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OrgHubSet struct {
	OrgID      uuid.UUID   `json:"org_id"`
	Configured []uuid.UUID `json:"configured"`
	Generation int64       `json:"generation"`
	UpdatedAt  time.Time   `json:"updated_at"`
	Demoted    []uuid.UUID `json:"demoted"`
}

type OrgIpv6Pool struct {
	OrgID     uuid.UUID `json:"org_id"`
	PoolCidr  string    `json:"pool_cidr"`
	CreatedAt time.Time `json:"created_at"`
}

type OrgMfa struct {
	OrgID     uuid.UUID `json:"org_id"`
	Enforce   bool      `json:"enforce"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Organization struct {
	ID                          uuid.UUID          `json:"id"`
	Name                        string             `json:"name"`
	Slug                        string             `json:"slug"`
	CreatedAt                   time.Time          `json:"created_at"`
	UpdatedAt                   time.Time          `json:"updated_at"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	MaxDevicesPerUser           int32              `json:"max_devices_per_user"`
	PoolCidr                    string             `json:"pool_cidr"`
	ZeroTrustMode               string             `json:"zero_trust_mode"`
	DeviceApproval              string             `json:"device_approval"`
	FlowSeq                     int64              `json:"flow_seq"`
	OvpnEnabled                 bool               `json:"ovpn_enabled"`
	MaxAgentIdentities          *int32             `json:"max_agent_identities"`
	ManagedAgentRuntimeEnabled  bool               `json:"managed_agent_runtime_enabled"`
	AgentPolicyTemplatesEnabled bool               `json:"agent_policy_templates_enabled"`
	AgentJitAccessEnabled       bool               `json:"agent_jit_access_enabled"`
	AlertingEnabled             bool               `json:"alerting_enabled"`
	FqdnResourcesEnabled        bool               `json:"fqdn_resources_enabled"`
}

type OvpnClientCert struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	DeviceID   uuid.UUID          `json:"device_id"`
	Serial     string             `json:"serial"`
	CommonName string             `json:"common_name"`
	NotAfter   time.Time          `json:"not_after"`
	IssuedAt   time.Time          `json:"issued_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	// What revoked this cert, which determines what may revive it: deliberate (nothing revives it), cascade (a gateway restore), user_deactivated (that user being reactivated, and only that).
	RevokedCause *string `json:"revoked_cause"`
}

type OvpnCrl struct {
	OrgID     uuid.UUID `json:"org_id"`
	CrlPem    []byte    `json:"crl_pem"`
	Number    int64     `json:"number"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OvpnServerCert struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	NodeID    uuid.UUID `json:"node_id"`
	Serial    string    `json:"serial"`
	CertPem   string    `json:"cert_pem"`
	SealedKey string    `json:"sealed_key"`
	NotAfter  time.Time `json:"not_after"`
	IssuedAt  time.Time `json:"issued_at"`
}

type PlatformSecret struct {
	Name         string    `json:"name"`
	SecretSealed []byte    `json:"secret_sealed"`
	PublicPem    *string   `json:"public_pem"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PolicyRule struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	SrcGroupID        pgtype.UUID        `json:"src_group_id"`
	DstKind           string             `json:"dst_kind"`
	DstResourceID     pgtype.UUID        `json:"dst_resource_id"`
	DstGroupID        pgtype.UUID        `json:"dst_group_id"`
	CreatedAt         time.Time          `json:"created_at"`
	SrcKind           string             `json:"src_kind"`
	SrcUserID         pgtype.UUID        `json:"src_user_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	DstSiteID         pgtype.UUID        `json:"dst_site_id"`
	SrcSiteID         pgtype.UUID        `json:"src_site_id"`
	SrcCidr           *string            `json:"src_cidr"`
	Disabled          bool               `json:"disabled"`
	DstK8sServiceID   pgtype.UUID        `json:"dst_k8s_service_id"`
	ManagedByMachine  pgtype.UUID        `json:"managed_by_machine"`
	SrcDeviceID       pgtype.UUID        `json:"src_device_id"`
	DstK8sClusterID   pgtype.UUID        `json:"dst_k8s_cluster_id"`
	SrcAgentGroupID   pgtype.UUID        `json:"src_agent_group_id"`
	DstFqdnResourceID pgtype.UUID        `json:"dst_fqdn_resource_id"`
}

type PoolVipOwnershipDelivery struct {
	ID                   uuid.UUID `json:"id"`
	OrgID                uuid.UUID `json:"org_id"`
	SiteID               uuid.UUID `json:"site_id"`
	ClusterID            uuid.UUID `json:"cluster_id"`
	PoolID               uuid.UUID `json:"pool_id"`
	ConnectorNodeID      uuid.UUID `json:"connector_node_id"`
	TargetNodeID         uuid.UUID `json:"target_node_id"`
	OperationID          uuid.UUID `json:"operation_id"`
	WireVersion          int32     `json:"wire_version"`
	ManifestIdentity     string    `json:"manifest_identity"`
	Role                 string    `json:"role"`
	PromotionGeneration  int64     `json:"promotion_generation"`
	ManifestRevision     int64     `json:"manifest_revision"`
	LeaseEpoch           int64     `json:"lease_epoch"`
	DeliveryPhase        string    `json:"delivery_phase"`
	DeliveryID           uuid.UUID `json:"delivery_id"`
	DeliveryNonce        string    `json:"delivery_nonce"`
	OwnedRoutes          []byte    `json:"owned_routes"`
	ExpectedRouteDigest  string    `json:"expected_route_digest"`
	ExpectedVipMapDigest string    `json:"expected_vip_map_digest"`
	PriorLeaseEpoch      int64     `json:"prior_lease_epoch"`
	ExpiresAt            time.Time `json:"expires_at"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
	OwnershipManifest    []byte    `json:"ownership_manifest"`
}

type PoolVipOwnershipDeliveryAckReceipt struct {
	ID                         uuid.UUID `json:"id"`
	OrgID                      uuid.UUID `json:"org_id"`
	DeliveryRowID              uuid.UUID `json:"delivery_row_id"`
	StateID                    uuid.UUID `json:"state_id"`
	Fingerprint                string    `json:"fingerprint"`
	ReceiptTime                time.Time `json:"receipt_time"`
	AppliedRole                *string   `json:"applied_role"`
	AppliedManifestIdentity    *string   `json:"applied_manifest_identity"`
	AppliedPromotionGeneration *int64    `json:"applied_promotion_generation"`
	AppliedManifestRevision    *int64    `json:"applied_manifest_revision"`
	AppliedLeaseEpoch          *int64    `json:"applied_lease_epoch"`
	OwnedRouteDigest           *string   `json:"owned_route_digest"`
	VipMapDigest               *string   `json:"vip_map_digest"`
	CreatedAt                  time.Time `json:"created_at"`
	AppliedManifest            []byte    `json:"applied_manifest"`
}

type PoolVipOwnershipDeliveryState struct {
	ID                  uuid.UUID `json:"id"`
	OrgID               uuid.UUID `json:"org_id"`
	SiteID              uuid.UUID `json:"site_id"`
	ClusterID           uuid.UUID `json:"cluster_id"`
	PoolID              uuid.UUID `json:"pool_id"`
	ConnectorNodeID     uuid.UUID `json:"connector_node_id"`
	ScopeIdentity       string    `json:"scope_identity"`
	PromotionGeneration int64     `json:"promotion_generation"`
	ManifestRevision    int64     `json:"manifest_revision"`
	LeaseEpoch          int64     `json:"lease_epoch"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type PoolVipOwnershipHandoffProvenance struct {
	OperationID            uuid.UUID   `json:"operation_id"`
	OrgID                  uuid.UUID   `json:"org_id"`
	SiteID                 uuid.UUID   `json:"site_id"`
	ClusterID              uuid.UUID   `json:"cluster_id"`
	PoolID                 uuid.UUID   `json:"pool_id"`
	OldNodeID              uuid.UUID   `json:"old_node_id"`
	NewNodeID              uuid.UUID   `json:"new_node_id"`
	ExpectedGeneration     int64       `json:"expected_generation"`
	TargetGeneration       int64       `json:"target_generation"`
	DecisionTransition     string      `json:"decision_transition"`
	OldLeaseIdentity       string      `json:"old_lease_identity"`
	TargetLeaseIdentity    string      `json:"target_lease_identity"`
	MembershipSnapshot     []uuid.UUID `json:"membership_snapshot"`
	OldServingEnvelope     []byte      `json:"old_serving_envelope"`
	NewPreparedEnvelope    []byte      `json:"new_prepared_envelope"`
	OldWithdrawalEnvelope  []byte      `json:"old_withdrawal_envelope"`
	NewServingEnvelope     []byte      `json:"new_serving_envelope"`
	OldServingExpiresAt    time.Time   `json:"old_serving_expires_at"`
	NewPreparedExpiresAt   time.Time   `json:"new_prepared_expires_at"`
	OldWithdrawalExpiresAt time.Time   `json:"old_withdrawal_expires_at"`
	NewServingExpiresAt    time.Time   `json:"new_serving_expires_at"`
	CreatedAt              time.Time   `json:"created_at"`
}

type PoolVipOwnershipHandoffProvenanceCapability struct {
	OperationID   uuid.UUID `json:"operation_id"`
	OrgID         uuid.UUID `json:"org_id"`
	SiteID        uuid.UUID `json:"site_id"`
	ClusterID     uuid.UUID `json:"cluster_id"`
	PoolID        uuid.UUID `json:"pool_id"`
	NodeID        uuid.UUID `json:"node_id"`
	WireVersion   int32     `json:"wire_version"`
	DeliveryRowID uuid.UUID `json:"delivery_row_id"`
	ReceiptTime   time.Time `json:"receipt_time"`
	ExpiresAt     time.Time `json:"expires_at"`
}

type PoolVipOwnershipHandoffProvenanceServiceUid struct {
	OperationID         uuid.UUID `json:"operation_id"`
	OrgID               uuid.UUID `json:"org_id"`
	SiteID              uuid.UUID `json:"site_id"`
	ClusterID           uuid.UUID `json:"cluster_id"`
	PoolID              uuid.UUID `json:"pool_id"`
	ActiveNodeID        uuid.UUID `json:"active_node_id"`
	PromotionGeneration int64     `json:"promotion_generation"`
	Namespace           string    `json:"namespace"`
	Service             string    `json:"service"`
	ServiceUid          string    `json:"service_uid"`
	ObservationRevision int64     `json:"observation_revision"`
}

type Resource struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	Cidr      string    `json:"cidr"`
	Protocol  string    `json:"protocol"`
	PortLow   *int32    `json:"port_low"`
	PortHigh  *int32    `json:"port_high"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Label     *string   `json:"label"`
}

type Site struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	Name          string    `json:"name"`
	LinkTransport string    `json:"link_transport"`
	LinkMtu       *int32    `json:"link_mtu"`
	DnsForwarding []byte    `json:"dns_forwarding"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type SiteSubnet struct {
	ID        uuid.UUID    `json:"id"`
	SiteID    uuid.UUID    `json:"site_id"`
	Cidr      netip.Prefix `json:"cidr"`
	CreatedAt time.Time    `json:"created_at"`
	Status    string       `json:"status"`
}

type SsoConfig struct {
	ID                 uuid.UUID `json:"id"`
	OrgID              uuid.UUID `json:"org_id"`
	Provider           string    `json:"provider"`
	ClientID           string    `json:"client_id"`
	ClientSecretSealed []byte    `json:"client_secret_sealed"`
	Enabled            bool      `json:"enabled"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	TenantID           *string   `json:"tenant_id"`
	SecretFingerprint  string    `json:"secret_fingerprint"`
}

type SystemSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	Name               string             `json:"name"`
	PasswordHash       *string            `json:"password_hash"`
	EmailVerifiedAt    pgtype.Timestamptz `json:"email_verified_at"`
	Status             string             `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CanCreateOrgs      bool               `json:"can_create_orgs"`
	MustChangePassword bool               `json:"must_change_password"`
	CpAdmin            bool               `json:"cp_admin"`
}

type UserGroup struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Origin      string    `json:"origin"`
	IdpProvider *string   `json:"idp_provider"`
	IdpGroupID  *string   `json:"idp_group_id"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  []byte             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type UserTotp struct {
	UserID           uuid.UUID          `json:"user_id"`
	SecretEnc        []byte             `json:"secret_enc"`
	Confirmed        bool               `json:"confirmed"`
	LastUsedTimestep *int64             `json:"last_used_timestep"`
	CreatedAt        time.Time          `json:"created_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}
