// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearNodePolicyDesyncSince = `-- name: ClearNodePolicyDesyncSince :exec
UPDATE nodes SET policy_desync_since = NULL WHERE id = $1 AND org_id = $2 AND policy_desync_since IS NOT NULL
`

type ClearNodePolicyDesyncSinceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// S7.4b (X-4): clear the desync stamp on RECONVERGENCE or non-enforcing (applied == pushed,
// or pushed == "" ). Convergence is a STATE predicate — revert-to-clear (admin reverts the
// pushed target back to the applied hash) legitimately clears. CP-only, single-writer, org-scoped.
func (q *Queries) ClearNodePolicyDesyncSince(ctx context.Context, arg ClearNodePolicyDesyncSinceParams) error {
	_, err := q.db.Exec(ctx, clearNodePolicyDesyncSince, arg.ID, arg.OrgID)
	return err
}

const consumeJoinToken = `-- name: ConsumeJoinToken :one
UPDATE node_join_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind
`

// lint:cross-org — the token itself is the credential; the org comes from the
// returned row. Single-use + expiring.
func (q *Queries) ConsumeJoinToken(ctx context.Context, tokenHash []byte) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, consumeJoinToken, tokenHash)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
	)
	return i, err
}

const consumeRekeyChallenge = `-- name: ConsumeRekeyChallenge :one
UPDATE node_rekey_challenges
SET consumed_at = now()
WHERE nonce = $1 AND identifier = $2 AND identifier_kind = $3
  AND consumed_at IS NULL AND expires_at > now()
RETURNING nonce, cert_serial, created_at, expires_at, consumed_at, identifier, identifier_kind
`

type ConsumeRekeyChallengeParams struct {
	Nonce          []byte  `json:"nonce"`
	Identifier     *string `json:"identifier"`
	IdentifierKind string  `json:"identifier_kind"`
}

// lint:cross-org — a challenge carries no org and cannot: it is issued before the caller is known to be anyone,
// and binding it to an org would require resolving the serial at issue time, which is the enumeration oracle D9
// exists to avoid. The org is established later, from the node the serial resolves to.
// SINGLE-USE, enforced by the UPDATE's own WHERE clause rather than by a read-then-write: two concurrent submits
// with the same nonce cannot both win, because only one row can transition consumed_at from NULL. A read-check-write
// would have a race exactly wide enough to matter here.
//
// Returns the row only when it was unconsumed AND unexpired AND bound to this exact identifier AND KIND. No rows =
// refuse, and the caller must not distinguish which of those it was.
// The read half of the same removed shim (review pass 1 #20): coalesce(identifier, cert_serial) existed to consume
// a challenge written by a previous version that did not know the column. No such version exists — 0058 created
// this table in the same release — so the fallback could only ever match rows this version wrote itself.
func (q *Queries) ConsumeRekeyChallenge(ctx context.Context, arg ConsumeRekeyChallengeParams) (NodeRekeyChallenge, error) {
	row := q.db.QueryRow(ctx, consumeRekeyChallenge, arg.Nonce, arg.Identifier, arg.IdentifierKind)
	var i NodeRekeyChallenge
	err := row.Scan(
		&i.Nonce,
		&i.CertSerial,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Identifier,
		&i.IdentifierKind,
	)
	return i, err
}

const countLiveNodes = `-- name: CountLiveNodes :one
SELECT count(*) FROM nodes
WHERE revoked_at IS NULL
`

// lint:cross-org — DELIBERATELY SPANS EVERY ORGANIZATION. This is the count the licence ceiling is
// checked against, and the licence is a property of the DEPLOYMENT, not of a tenant.
//
// ⛔ THE PER-ORG VERSION BELOW WAS A PAID CEILING THE CUSTOMER COULD LIFT BY CLICKING "+ New". Starter
// allows 5 gateways and UNLIMITED organizations, so counting per org made the real ceiling 5 × N — with no
// exploit, no API misuse, and no hacking: the button that raises it is in the product's own header. Growth
// was 20 × N. Community and trial were only ever safe because their org ceiling is 1, which is an accident
// of two numbers agreeing rather than a boundary.
//
// > ## ⛔ **ONE SIGNED KEY, ONE DEPLOYMENT, ONE COUNT.** A ceiling scoped more narrowly than the thing that
// > ## grants it is not a ceiling.
//
// ⛔ LIVE ONLY, same as the per-org query: a revoked gateway is not a gateway, and counting one would let a
// revoke permanently consume a band slot.
func (q *Queries) CountLiveNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveNodesForOrg = `-- name: CountLiveNodesForOrg :one
SELECT count(*) FROM nodes
WHERE org_id = $1 AND revoked_at IS NULL
`

// The gateway count SHOWN for a single organization (S12.1 slice 4).
//
// ⚠ NOT THE CEILING CHECK ANY MORE — see CountLiveNodes above. This one answers "how many does THIS org
// run", which is a display question; the licence question is deployment-wide.
//
// ⛔ LIVE ONLY: a revoked gateway is not a gateway. Counting it would let a revoke permanently consume a
// band slot — the same defect class as the agent unique-index that a revoke bricked.
// ⚠ nodes has no deleted_at — revoked_at IS the retirement marker here. Checked against the live schema
// rather than assumed from the sibling tables that do have one.
func (q *Queries) CountLiveNodesForOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveNodesForOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO node_join_tokens (org_id, node_name, token_hash, expires_at, issued_by, enrols_kind)
VALUES ($1, $2, $3, $4, $5, COALESCE(NULLIF($6::text, ''), 'gateway'))
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind
`

type CreateJoinTokenParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	NodeName   *string     `json:"node_name"`
	TokenHash  []byte      `json:"token_hash"`
	ExpiresAt  time.Time   `json:"expires_at"`
	IssuedBy   pgtype.UUID `json:"issued_by"`
	EnrolsKind string      `json:"enrols_kind"`
}

// ⛔ issued_by IS THE HUMAN, AND IT WAS ALREADY IN HAND (S15.2 slice 1).
// IssueJoinToken has always received the actor and written them to the audit log ALONE, so every token
// minted before this column existed discarded its issuer to a table nobody joins against. The fact existed
// at exactly the moment it was thrown away.
// ⚠ ISSUED_BY, NOT OWNER: enrolment is an agent redeeming this token unattended, so the installer is not
// capturable by construction. This column claims only what happened, never who installed the agent.
// ⚠ `enrols_kind` is the OPERATOR'S DECLARATION, captured at the same instant as the issuer. Absence is
// the CLOSED state: the column defaults to 'gateway', so a caller that omits it mints a plain gateway.
func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.OrgID,
		arg.NodeName,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IssuedBy,
		arg.EnrolsKind,
	)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (org_id, name, cert_serial, agent_version, cert_not_after, cert_public_key, owner_user_id, enrolled_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind
`

type CreateNodeParams struct {
	OrgID         uuid.UUID          `json:"org_id"`
	Name          string             `json:"name"`
	CertSerial    string             `json:"cert_serial"`
	AgentVersion  string             `json:"agent_version"`
	CertNotAfter  pgtype.Timestamptz `json:"cert_not_after"`
	CertPublicKey *string            `json:"cert_public_key"`
	OwnerUserID   pgtype.UUID        `json:"owner_user_id"`
	EnrolledKind  *string            `json:"enrolled_kind"`
}

// owner_user_id is carried from the redeemed token's issuer (S15.2 slice 1). ⚠ It may be NULL: tokens minted
// before 0066 have no issuer and never will, and D25 ruled an agent is NEVER refused at use for want of an
// owner — it degrades and is flagged. The refusal lives at enrolment (slice 2), on NEW nodes.
// ⚠ `enrolled_kind` is carried from the redeemed token. NULL is impossible for a node enrolled after 0069
// (the token's column is NOT NULL); a NULL here means the node predates the marker — UNDETERMINED.
func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.OrgID,
		arg.Name,
		arg.CertSerial,
		arg.AgentVersion,
		arg.CertNotAfter,
		arg.CertPublicKey,
		arg.OwnerUserID,
		arg.EnrolledKind,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const createRekeyChallenge = `-- name: CreateRekeyChallenge :exec
INSERT INTO node_rekey_challenges (nonce, identifier, identifier_kind, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRekeyChallengeParams struct {
	Nonce          []byte    `json:"nonce"`
	Identifier     *string   `json:"identifier"`
	IdentifierKind string    `json:"identifier_kind"`
	ExpiresAt      time.Time `json:"expires_at"`
}

// lint:cross-org — a challenge is not org-scoped: it is issued BEFORE the caller is known to be anyone, and the
// identifier it names is only resolved to a node at submit time. That is the anti-enumeration property (D9), not an
// oversight.
// The KIND is stored alongside the value (D10) so a nonce issued for one identifier kind cannot be spent under the
// other. Two kinds sharing a string is not realistic today; a format change is how "not realistic" stops holding.
// THE ROLLING-UPGRADE SHIM IS GONE (review pass 1 #20). It wrote cert_serial alongside identifier so a
// previous-version replica could consume a challenge this version issued — protecting a control-plane version
// THAT CANNOT EXIST: node_rekey_challenges is created by migration 0058, in the SAME RELEASE as 0061. No shipped
// version has ever read this table, let alone that column.
//
// It was built because TestMigrationsAreBackwardCompatibleForOneVersion refused a RENAME — and that guard is a
// line-level regex over migration text with no notion of which tables the previous version knew, so it fired on a
// rename inside a table one version ago did not have. Its verdict was taken as authority and a shim was built to
// satisfy it. The column stays until the registered contract migration drops it; nothing writes it now.
func (q *Queries) CreateRekeyChallenge(ctx context.Context, arg CreateRekeyChallengeParams) error {
	_, err := q.db.Exec(ctx, createRekeyChallenge,
		arg.Nonce,
		arg.Identifier,
		arg.IdentifierKind,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRekeyChallenges = `-- name: DeleteExpiredRekeyChallenges :execrows
DELETE FROM node_rekey_challenges
WHERE expires_at < now() - interval '1 hour'
`

// lint:cross-org — a retention sweep over a table with no org column, by design (see ConsumeRekeyChallenge).
// Pruning for a table an unauthenticated endpoint writes to. Consumed rows are kept briefly too — a consumed nonce
// must keep failing rather than becoming unknown, so deleting it the instant it is spent would turn replay into
// "no such challenge" and lose the distinction in the log.
func (q *Queries) DeleteExpiredRekeyChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRekeyChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJoinTokensForNode = `-- name: DeleteJoinTokensForNode :execrows
DELETE FROM node_join_tokens WHERE consumed_node_id = $1
`

// lint:cross-org — keyed by consumed_node_id, which the caller resolved from an org-scoped node row.
// Cleans the enrolment token that produced a gateway being deleted (S12.12 D2).
//
// ⛔ IT IS A DELIBERATE CLEANUP, NOT THE REMOVAL OF AN OBSTACLE, and the distinction is recorded because
// the ruling was made against the opposite premise. `consumed_node_id` is ON DELETE SET NULL
// (0008_nodes.up.sql:46), NOT NO ACTION — it never would have blocked the delete. The ruling stands anyway:
// a token that enrolled a gateway an operator has just deleted should not still enrol another.
//
// ⚠ Refusing the delete over a leftover token would have made the NEWEST gateways the hardest to remove,
// since a token is most likely to still exist on one enrolled recently. That is backwards.
func (q *Queries) DeleteJoinTokensForNode(ctx context.Context, consumedNodeID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJoinTokensForNode, consumedNodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevokedNode = `-- name: DeleteRevokedNode :execrows
DELETE FROM nodes WHERE id = $1 AND org_id = $2 AND revoked_at IS NOT NULL
`

type DeleteRevokedNodeParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// ⛔ HARD DELETE, AND ONLY FOR A REVOKED NODE (S12.12 D2). The status predicate is the whole safety
// argument: by the time a node is revoked, the transfer step has already moved every live device off it
// (Revoke refuses otherwise), so the CASCADE columns have nothing left to destroy. It is the SEQUENCE that
// makes this delete safe, not the FK actions.
//
// WHAT GOES WITH IT, read from the schema rather than assumed:
//
//	· devices.node_id           ON DELETE CASCADE — empty by construction, see above.
//	· node_peer_status          ON DELETE CASCADE — telemetry about a node that no longer exists.
//	· ovpn_server_certs         ON DELETE CASCADE — this gateway's server credential, which nothing else can use.
//	· node_join_tokens.consumed_node_id ON DELETE SET NULL — the enrolment token SURVIVES, unlinked.
//
// ⚠ AND THE TOKEN IS THE ONE AN OPERATOR MUST BE TOLD ABOUT. It is not deleted by the FK, so the caller
// deletes it deliberately (D2): a token whose gateway is gone should not still enrol one. The confirm says
// so, because that token may be in a colleague's terminal history, about to be run.
//
// Returns rows-affected so the caller can tell "no such node" from "that node is not revoked" instead of
// reporting a success that deleted nothing.
func (q *Queries) DeleteRevokedNode(ctx context.Context, arg DeleteRevokedNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevokedNode, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNodeByCertSerial = `-- name: GetNodeByCertSerial :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind FROM nodes
WHERE cert_serial = $1
`

// lint:cross-org — the mTLS client cert IS the identity; the org comes from the
// node row. Used to authorize every agent request.
func (q *Queries) GetNodeByCertSerial(ctx context.Context, certSerial string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByCertSerial, certSerial)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const getNodeByOrgName = `-- name: GetNodeByOrgName :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind FROM nodes
WHERE org_id = $1 AND name = $2 AND revoked_at IS NULL
`

type GetNodeByOrgNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

// ACTIVE rows only (S11 WF-S11-8). Since 0056 a name may be held by several REVOKED rows plus at most one
// active one, so an unfiltered name lookup is ambiguous — and a :one query answering "multiple rows" is a
// confusing runtime failure rather than a compile-time one. Filtering here makes the query correct by
// construction instead of correct by the caller remembering.
func (q *Queries) GetNodeByOrgName(ctx context.Context, arg GetNodeByOrgNameParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByOrgName, arg.OrgID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const getNodeForOrg = `-- name: GetNodeForOrg :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind FROM nodes WHERE id = $1 AND org_id = $2
`

type GetNodeForOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// An ORG-SCOPED node by id, whatever its status. Revoked rows included deliberately: the operator restore
// (S13.1 Slice 7) names a REVOKED node as its source — that is the whole point — and a lookup that filtered them
// out would make the one legitimate case unreachable. The caller decides what each side must be.
func (q *Queries) GetNodeForOrg(ctx context.Context, arg GetNodeForOrgParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeForOrg, arg.ID, arg.OrgID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const getNodeForOrgForUpdate = `-- name: GetNodeForOrgForUpdate :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind FROM nodes WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type GetNodeForOrgForUpdateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// The node row, ORG-SCOPED and LOCKED (review pass 1 #7). The restore reads it inside its own transaction and
// refuses if the node is not active — because revoke takes the same row lock, so a revoke that lands mid-restore
// either commits first (we see it revoked and refuse) or waits for us. Without the lock the restore authorized on
// state read BEFORE the identity commit and applied AFTER it, and a re-key racing an operator revoke re-activated
// the very devices that revoke had just cascaded.
func (q *Queries) GetNodeForOrgForUpdate(ctx context.Context, arg GetNodeForOrgForUpdateParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeForOrgForUpdate, arg.ID, arg.OrgID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const getNodeHubPriority = `-- name: GetNodeHubPriority :one
SELECT hub_priority FROM nodes WHERE id = $1 AND org_id = $2
`

type GetNodeHubPriorityParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// lint:cross-org — org-scoped. The node's current hub_priority (nullable) so SetHubPriority can audit the
// old→new transition (S8.6 Slice 6 — the pin is a topology-consequential act).
func (q *Queries) GetNodeHubPriority(ctx context.Context, arg GetNodeHubPriorityParams) (*int32, error) {
	row := q.db.QueryRow(ctx, getNodeHubPriority, arg.ID, arg.OrgID)
	var hub_priority *int32
	err := row.Scan(&hub_priority)
	return hub_priority, err
}

const getNodesByCertKeyFingerprint = `-- name: GetNodesByCertKeyFingerprint :many
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind FROM nodes
WHERE cert_key_fingerprint = $1
LIMIT 2
`

// The SECOND re-key identifier (S13.1 D10). :many, and the plurality is the POINT.
//
// cert_key_fingerprint is deliberately NOT unique (see migration 0061: a UNIQUE index would turn a lookup ambiguity
// into a migration failure on any fleet that already enrolled two nodes with the same key). So this query returns up
// to TWO rows and its caller REFUSES when it gets more than one. A `:one` query would have raised a runtime
// "multiple rows" error — a refusal by accident, at a moment when identity is being trusted, distinguishable in
// timing and in the log from a clean refusal. Ambiguity here fails CLOSED, deliberately and visibly.
//
// EXACT MATCH ONLY — `=` on the full 64-hex digest. Never a prefix, never a LIKE: a prefix match would let a caller
// narrow the fleet's key space one request at a time, which is precisely the enumeration property D9 chose the
// serial over the node name to avoid.
//
// REVOKED ROWS ARE NOT FILTERED, matching GetNodeByCertSerial. A revoked node must be refused by the GONE-GATE, at
// the same stage and with the same logged reason as it is on the serial path — filtering it out here would make the
// two identifiers produce different diagnostics for the same condition, and an operator reading "no node holds this
// key" for a node they revoked yesterday is being misled by their own tooling.
// lint:cross-org — same reasoning as GetNodeByCertSerial and RekeyNode: the caller is an unauthenticated agent with
// no session and no org context, and the recorded key material IS the identity claim being tested.
func (q *Queries) GetNodesByCertKeyFingerprint(ctx context.Context, certKeyFingerprint *string) ([]Node, error) {
	rows, err := q.db.Query(ctx, getNodesByCertKeyFingerprint, certKeyFingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CertSerial,
			&i.AgentVersion,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WgPublicKey,
			&i.Endpoint,
			&i.Capabilities,
			&i.PolicyDesyncSince,
			&i.PolicyReportedAt,
			&i.SiteID,
			&i.HubPriority,
			&i.CertNotAfter,
			&i.CertPublicKey,
			&i.CertKeyFingerprint,
			&i.CertDeliveredAt,
			&i.CertDelivered,
			&i.OwnerUserID,
			&i.EnrolledKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgHubSet = `-- name: GetOrgHubSet :one
SELECT org_id, configured, demoted, generation, updated_at FROM org_hub_set WHERE org_id = $1
`

type GetOrgHubSetRow struct {
	OrgID      uuid.UUID   `json:"org_id"`
	Configured []uuid.UUID `json:"configured"`
	Demoted    []uuid.UUID `json:"demoted"`
	Generation int64       `json:"generation"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

// lint:cross-org — org-scoped by PK. The persisted transit-hub election (S8.6 REDUCE): the two
// writer-partitioned fields (configured + demoted) + the D5 generation. The ACTIVE order is DERIVED from
// these by deriveActive (never stored). No rows until the first ReconcileHubSet.
func (q *Queries) GetOrgHubSet(ctx context.Context, orgID uuid.UUID) (GetOrgHubSetRow, error) {
	row := q.db.QueryRow(ctx, getOrgHubSet, orgID)
	var i GetOrgHubSetRow
	err := row.Scan(
		&i.OrgID,
		&i.Configured,
		&i.Demoted,
		&i.Generation,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformSecret = `-- name: GetPlatformSecret :one
SELECT name, secret_sealed, public_pem, created_at, updated_at FROM platform_secrets WHERE name = $1
`

func (q *Queries) GetPlatformSecret(ctx context.Context, name string) (PlatformSecret, error) {
	row := q.db.QueryRow(ctx, getPlatformSecret, name)
	var i PlatformSecret
	err := row.Scan(
		&i.Name,
		&i.SecretSealed,
		&i.PublicPem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformSecret = `-- name: InsertPlatformSecret :exec
INSERT INTO platform_secrets (name, secret_sealed, public_pem)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO NOTHING
`

type InsertPlatformSecretParams struct {
	Name         string  `json:"name"`
	SecretSealed []byte  `json:"secret_sealed"`
	PublicPem    *string `json:"public_pem"`
}

// Create-if-absent; the caller reads-back on conflict. Never overwrites, so a
// concurrent boot can't clobber the CA (fail-loud-never-regenerate lives above).
func (q *Queries) InsertPlatformSecret(ctx context.Context, arg InsertPlatformSecretParams) error {
	_, err := q.db.Exec(ctx, insertPlatformSecret, arg.Name, arg.SecretSealed, arg.PublicPem)
	return err
}

const listActiveNodeIDsForOrg = `-- name: ListActiveNodeIDsForOrg :many
SELECT id FROM nodes
WHERE org_id = $1 AND status = 'active'
`

// S7.2 push targeting: every active gateway in the org. A policy change is org-wide,
// and member-removal can orphan a device whose node would drop out of a device-join
// query — so the push set is ALL active nodes (an unaffected node's re-fetch recompiles
// to identical bytes = reconcile no-op, so over-notifying is safe + correct).
func (q *Queries) ListActiveNodeIDsForOrg(ctx context.Context, orgID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveNodeIDsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsForOrg = `-- name: ListAgentsForOrg :many
SELECT d.id AS device_id, d.name, d.assigned_ip AS address, d.status,
       d.public_key,
       u.email AS owner_email,
       n.id AS node_id, n.name AS gateway_name,
       ds.last_handshake_at, ds.rx_bytes, ds.tx_bytes, ds.updated_at AS status_reported_at,
       n.last_seen_at AS gateway_last_seen_at
FROM devices d
JOIN nodes n ON n.id = d.node_id
LEFT JOIN users u ON u.id = d.user_id
LEFT JOIN device_status ds ON ds.device_id = d.id
WHERE d.org_id = $1 AND d.kind = 'agent' AND d.deleted_at IS NULL
ORDER BY (u.email IS NULL) DESC, d.name
`

type ListAgentsForOrgRow struct {
	DeviceID          uuid.UUID          `json:"device_id"`
	Name              string             `json:"name"`
	Address           *string            `json:"address"`
	Status            string             `json:"status"`
	PublicKey         string             `json:"public_key"`
	OwnerEmail        *string            `json:"owner_email"`
	NodeID            uuid.UUID          `json:"node_id"`
	GatewayName       string             `json:"gateway_name"`
	LastHandshakeAt   pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes           *int64             `json:"rx_bytes"`
	TxBytes           *int64             `json:"tx_bytes"`
	StatusReportedAt  pgtype.Timestamptz `json:"status_reported_at"`
	GatewayLastSeenAt pgtype.Timestamptz `json:"gateway_last_seen_at"`
}

// S15.3 — the agent surface's one query.
//
// ⛔ AN AGENT IS A PEER HOMED ON A GATEWAY, NOT A GATEWAY. It holds its own /32, its traffic is FORWARDED
// through the gateway it is homed on, and the policy chain therefore sees it. A gateway would be the thing
// traffic passes THROUGH — nothing it originates is ever forwarded, so no grant could ever match it.
//
// lint:allow-deleted — resolves a RECORDED IDENTITY for display: filtering u.deleted_at would blank the
// owner of an agent whose owner was soft-deleted.
// ⛔ LIVENESS COMES FROM `device_status`, WHICH THE GATEWAY WRITES — NOT FROM ANYTHING THE AGENT SENDS.
// An agent runs plain wg-quick: it has no control-plane channel and reports nothing about itself, ever. The
// gateway's 30s status push is the ONLY source of a peer's handshake, which is why the REPORTER'S OWN CLOCK
// is selected alongside it: without it, a silent gateway and a dead agent are the same row, and the surface
// would blame the agent for the gateway's silence.
//
// ⛔ AND THE CLOCK MUST BE THE ONE ON *THIS* CHANNEL. The gateway runs TWO independent loops on the same
// 30s cadence: `/agent/report` (which bumps `nodes.last_seen_at`) and `/agent/status` (which carries peer
// handshakes). Reading `last_seen_at` alone would mean watching the wrong loop — if the status push failed
// by itself, the gateway would look healthy while no handshake data flowed at all, and every agent would
// read a confident "never connected". `device_status.updated_at` is stamped by the status upsert itself, so
// it is the freshness of the channel the handshake actually travels on.
//
// `n.last_seen_at` is kept for ONE case the status clock cannot cover: an agent so newly created that no
// push has mentioned it yet has no `device_status` row at all.
func (q *Queries) ListAgentsForOrg(ctx context.Context, orgID uuid.UUID) ([]ListAgentsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForOrgRow{}
	for rows.Next() {
		var i ListAgentsForOrgRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Name,
			&i.Address,
			&i.Status,
			&i.PublicKey,
			&i.OwnerEmail,
			&i.NodeID,
			&i.GatewayName,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
			&i.StatusReportedAt,
			&i.GatewayLastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailoverOrgs = `-- name: ListFailoverOrgs :many
SELECT org_id FROM org_hub_set WHERE array_length(configured, 1) > 1
`

// lint:cross-org — CP-internal (the failover tick iterates every org). Orgs whose persisted hub set has
// MORE THAN ONE member — i.e. a pinned HA set with at least one standby; a single-hub org has nothing to
// fail over (S8.6 Slice 4). Reads the CONFIGURED membership (the intent) — the reduce's field rename.
func (q *Queries) ListFailoverOrgs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFailoverOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var org_id uuid.UUID
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeOwnerEmails = `-- name: ListNodeOwnerEmails :many
SELECT n.id AS node_id, u.email AS owner_email
FROM nodes n
JOIN users u ON u.id = n.owner_user_id
WHERE n.org_id = $1
`

type ListNodeOwnerEmailsRow struct {
	NodeID     uuid.UUID `json:"node_id"`
	OwnerEmail string    `json:"owner_email"`
}

// ⛔ A SEPARATE RESOLVER, NOT A WIDER ListNodes — and the reason is a measurement, not taste. Widening the
// list row rippled into FOUR consumers (LoadSiteTopoBatch, PolicyHealthForNodes, NodeDisplayExtrasForNodes,
// toAPINode), none of which know or care about ownership. A shared row type is a coupling; this keeps the
// pure helpers' inputs narrow.
//
// ⛔ RESOLVED FROM `users`, NOT FROM THE MEMBER ROSTER (S15.1/D22, applied to agents). The roster cannot
// name an owner who has LEFT the org, and that is exactly the row an accountability surface exists for.
// `users` survives both membership deletion and deactivation.
//
// lint:allow-deleted — DELIBERATE, the same argument as ListMachineCredentialsForOrg: this does not ACT on
// a user, it RESOLVES A RECORDED IDENTITY for display. Scoping deleted_at would blank the owner of an agent
// whose owner was soft-deleted — the failure D22 was ruled to end, reached from another direction.
func (q *Queries) ListNodeOwnerEmails(ctx context.Context, orgID uuid.UUID) ([]ListNodeOwnerEmailsRow, error) {
	rows, err := q.db.Query(ctx, listNodeOwnerEmails, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeOwnerEmailsRow{}
	for rows.Next() {
		var i ListNodeOwnerEmailsRow
		if err := rows.Scan(&i.NodeID, &i.OwnerEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodePeerStatusForOrg = `-- name: ListNodePeerStatusForOrg :many
SELECT nps.node_id, nps.public_key, nps.last_handshake_at, nps.rx_bytes, nps.tx_bytes, nps.updated_at
FROM node_peer_status nps
JOIN nodes n ON n.id = nps.node_id
WHERE n.org_id = $1
`

// lint:cross-org — org-scoped via the reporting node's org. Every gateway's node-peer telemetry for the
// org: the input to D3's per-hub freshness clock + the S8.5 L1 site-link card metrics (read path defined
// with the storage, consumed by S8.6 Slice 4 + Slice 6).
func (q *Queries) ListNodePeerStatusForOrg(ctx context.Context, orgID uuid.UUID) ([]NodePeerStatus, error) {
	rows, err := q.db.Query(ctx, listNodePeerStatusForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodePeerStatus{}
	for rows.Next() {
		var i NodePeerStatus
		if err := rows.Scan(
			&i.NodeID,
			&i.PublicKey,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind FROM nodes
WHERE org_id = $1
ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context, orgID uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CertSerial,
			&i.AgentVersion,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WgPublicKey,
			&i.Endpoint,
			&i.Capabilities,
			&i.PolicyDesyncSince,
			&i.PolicyReportedAt,
			&i.SiteID,
			&i.HubPriority,
			&i.CertNotAfter,
			&i.CertPublicKey,
			&i.CertKeyFingerprint,
			&i.CertDeliveredAt,
			&i.CertDelivered,
			&i.OwnerUserID,
			&i.EnrolledKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCertDelivered = `-- name: MarkCertDelivered :exec
UPDATE nodes SET cert_delivered = true, cert_delivered_at = now() WHERE id = $1 AND cert_delivered = false
`

// Delivery is recorded THE FIRST TIME a certificate authenticates, and only then: the WHERE clause makes this a
// no-op on every subsequent request, so the agent channel pays one write per credential rather than one per call.
//
// This is what makes the D3 redelivery carve-out safe. A RUNNING gateway's certificate has authenticated by
// definition, so it is delivered, so the carve-out cannot touch it — the live-node case is excluded structurally
// rather than by a check someone must remember to write.
// lint:cross-org — keyed by node id, resolved from the presented client certificate; the caller IS the node.
func (q *Queries) MarkCertDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCertDelivered, id)
	return err
}

const peekJoinToken = `-- name: PeekJoinToken :one
SELECT id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at, issued_by, enrols_kind FROM node_join_tokens
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

// lint:cross-org — the token itself is the credential; the org comes from the returned row.
//
// ⛔ READ WITHOUT CONSUMING, so a refusal that the operator can FIX does not destroy their token.
// `node_name_mismatch` burned it twice in one session: the operator names a gateway in the UI, the agent
// registers under its container hostname, and the two disagree — a mistake fixed in five seconds, except
// the token is gone and the next attempt fails with `invalid_join_token`, which describes a completely
// different problem and sends them looking in the wrong place.
//
// ⚠ THIS DOES NOT WEAKEN SINGLE-USE. ConsumeJoinToken still performs the atomic claim; this only lets the
// pre-flight checks run first, and both happen inside one transaction.
func (q *Queries) PeekJoinToken(ctx context.Context, tokenHash []byte) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, peekJoinToken, tokenHash)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
		&i.IssuedBy,
		&i.EnrolsKind,
	)
	return i, err
}

const rekeyNode = `-- name: RekeyNode :one
UPDATE nodes
SET cert_serial = $2, cert_public_key = $3, cert_not_after = $4, agent_version = $5, last_seen_at = now(),
    cert_delivered = false, cert_delivered_at = NULL
WHERE id = $1 AND cert_serial = $6 AND status = 'active'
RETURNING id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind
`

type RekeyNodeParams struct {
	ID            uuid.UUID          `json:"id"`
	CertSerial    string             `json:"cert_serial"`
	CertPublicKey *string            `json:"cert_public_key"`
	CertNotAfter  pgtype.Timestamptz `json:"cert_not_after"`
	AgentVersion  string             `json:"agent_version"`
	CertSerial_2  string             `json:"cert_serial_2"`
}

// THE IDENTITY CHANGE, atomic (S13.1 D2). SAME node id — that is the whole point: the gateway that comes back IS
// the gateway that left, keeping its site binding, its history and its metrics series.
//
// Rotates the serial, the recorded public key and the expiry together. A row half-re-keyed — new certificate,
// old recorded key — is a node whose proof-of-possession material no longer matches what it holds, so the columns
// move in one statement.
//
// Guarded on the CALLER having already authorized: status must still be what it was when RekeyAuthorized ran, so a
// node revoked or renewed in the meantime cannot be re-keyed on a stale decision.
// lint:cross-org — authorization here is the CERT SERIAL plus proof of possession, not an org membership: the
// caller is an unauthenticated agent that holds no session and no org context, which is the whole premise of
// recovery (its certificate is the thing that failed). The serial is globally unique (nodes_cert_serial_key), so it
// identifies exactly one node and therefore exactly one org — the same reasoning that annotates
// GetNodeByCertSerial, which is how every authenticated agent request already resolves its node.
// IT CANNOT RESURRECT. This statement does not mention `status` or `revoked_at` at ALL — not "sets them
// carefully", does not reference them. Re-key is therefore incapable of un-revoking a node rather than merely
// forbidden from it, the same instinct as the gone-gate having no liveness parameter to pass. And it is guarded on
// `status = 'active'` so a revoked row cannot be re-keyed even if a future caller reached here without the gate.
// TestRekeyQueryCannotResurrect enforces both halves against this text.
// cert_delivered_at IS CLEARED IN THIS SAME STATEMENT (S13.1 D3 condition 1), not in a follow-up write.
// A new serial that inherited the old serial's delivered marker leaves the redelivery gate either permanently
// shut (the new certificate looks delivered before it has ever been used, so a lost response is unrecoverable) or
// permanently open (if the inherited value were NULL) — and neither state announces itself. One statement, so the
// marker cannot disagree with the serial it describes.
func (q *Queries) RekeyNode(ctx context.Context, arg RekeyNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, rekeyNode,
		arg.ID,
		arg.CertSerial,
		arg.CertPublicKey,
		arg.CertNotAfter,
		arg.AgentVersion,
		arg.CertSerial_2,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const renewNodeCert = `-- name: RenewNodeCert :exec
UPDATE nodes
SET cert_serial = $2, agent_version = $3, cert_not_after = $4, cert_public_key = $5, last_seen_at = now()
WHERE id = $1 AND status = 'active'
`

type RenewNodeCertParams struct {
	ID            uuid.UUID          `json:"id"`
	CertSerial    string             `json:"cert_serial"`
	AgentVersion  string             `json:"agent_version"`
	CertNotAfter  pgtype.Timestamptz `json:"cert_not_after"`
	CertPublicKey *string            `json:"cert_public_key"`
}

// lint:cross-org — keyed by node id after the caller authorized via the current
// cert; renewal rotates the serial and stamps activity/version.
func (q *Queries) RenewNodeCert(ctx context.Context, arg RenewNodeCertParams) error {
	_, err := q.db.Exec(ctx, renewNodeCert,
		arg.ID,
		arg.CertSerial,
		arg.AgentVersion,
		arg.CertNotAfter,
		arg.CertPublicKey,
	)
	return err
}

const revokeNode = `-- name: RevokeNode :exec
UPDATE nodes
SET status = 'revoked', revoked_at = now()
WHERE org_id = $1 AND id = $2
`

type RevokeNodeParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

// KEEPS THE SITE BINDING. The unbind added for WF-S11-14 was RULED REVERSED ON EVIDENCE after review, because the
// status filter on ListSiteNodesForOrg was sufficient for the compiler input on its own and the unbind bought
// nothing while costing three things:
//
//  1. BindNodeToSite has no status guard and authorizes purely on site_id being NULL, so an unbound-by-revocation
//     gateway could be bound to any site via API/CLI/GitOps — previously refused as already-bound. The site then
//     held a dead gateway that the status-filtered compiler input excludes, so cross-site traffic was silently
//     denied while the UI showed a gateway present: the exact policy-reads-correct-traffic-denied class the
//     filter was added to close.
//  2. assembleTopology joins a site's gateways with `n.site_id === s.id`, so a revoked gateway vanished from the
//     Sites card entirely — indistinguishable from a site that never had one, and it made the badge-suppression
//     fix landed in the same commit unreachable.
//  3. Nothing recorded which site the gateway served. The node.revoked audit row's metadata was an empty map, so
//     after the unbind neither UI, API nor audit log could answer it — while the docs told the operator to
//     re-apply that very binding.
//
// THE PRINCIPLE THIS ESTABLISHES CONCRETELY: revocation preserves what it invalidates. Marking a row revoked is
// enough; destroying the facts that explain it is not part of the job. Readers that must ignore a revoked gateway
// filter on status — which is one predicate in one place, versus three consequences spread across three surfaces.
func (q *Queries) RevokeNode(ctx context.Context, arg RevokeNodeParams) error {
	_, err := q.db.Exec(ctx, revokeNode, arg.OrgID, arg.ID)
	return err
}

const setNodeHubPriority = `-- name: SetNodeHubPriority :execrows
UPDATE nodes SET hub_priority = $1 WHERE id = $2 AND org_id = $3
`

type SetNodeHubPriorityParams struct {
	HubPriority *int32    `json:"hub_priority"`
	NodeID      uuid.UUID `json:"node_id"`
	OrgID       uuid.UUID `json:"org_id"`
}

// lint:cross-org — org-scoped. The admin pin (S8.6 D1): a nullable rank; NULL clears the pin. Org-checked
// so a cross-org node id no-ops (0 rows -> typed 404 at the service).
func (q *Queries) SetNodeHubPriority(ctx context.Context, arg SetNodeHubPriorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeHubPriority, arg.HubPriority, arg.NodeID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNodeWGInfo = `-- name: SetNodeWGInfo :execrows
UPDATE nodes
SET wg_public_key = $1,
    endpoint = COALESCE(NULLIF($2::text, ''), nodes.endpoint),
    capabilities = $3::jsonb,
    last_seen_at = now(),
    -- S7.4b fold [1]: the applied-policy REPORT time (this write IS the report), distinct from
    -- last_seen_at (also bumped by DesiredState polls) — the desync freshness gate reads this.
    policy_reported_at = now()
WHERE id = $4 AND status = 'active'
`

type SetNodeWGInfoParams struct {
	WgPublicKey  string    `json:"wg_public_key"`
	Endpoint     string    `json:"endpoint"`
	Capabilities []byte    `json:"capabilities"`
	ID           uuid.UUID `json:"id"`
}

// lint:cross-org — keyed by id after cert authorization; the node reports its
// locally-generated WireGuard public key and its public endpoint (host:port that
// peer configs dial). Returns rows affected so the caller can distinguish a real
// write from a no-op (e.g. node revoked mid-report).
// endpoint uses COALESCE(NULLIF(...)) so an agent that reports an empty endpoint
// (env unset on a restart) never clobbers a previously-good value.
func (q *Queries) SetNodeWGInfo(ctx context.Context, arg SetNodeWGInfoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeWGInfo,
		arg.WgPublicKey,
		arg.Endpoint,
		arg.Capabilities,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampNodePolicyDesyncSince = `-- name: StampNodePolicyDesyncSince :exec
UPDATE nodes SET policy_desync_since = $3 WHERE id = $1 AND org_id = $2 AND policy_desync_since IS NULL
`

type StampNodePolicyDesyncSinceParams struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	PolicyDesyncSince pgtype.Timestamptz `json:"policy_desync_since"`
}

// S7.4b (X-4): stamp the term-3 desync ONSET, CONTROL-PLANE-ONLY, idempotent per episode —
// the WHERE ... IS NULL preserves the first onset (a repeated mismatch never re-stamps a
// newer time). Called from exactly one site (nodes.trackDesync); the value is the CP clock,
// never an agent string. org_id-scoped (tenant isolation).
func (q *Queries) StampNodePolicyDesyncSince(ctx context.Context, arg StampNodePolicyDesyncSinceParams) error {
	_, err := q.db.Exec(ctx, stampNodePolicyDesyncSince, arg.ID, arg.OrgID, arg.PolicyDesyncSince)
	return err
}

const touchNodeSeen = `-- name: TouchNodeSeen :exec
UPDATE nodes
SET last_seen_at = now()
WHERE id = $1
`

// lint:cross-org — keyed by id after cert authorization.
func (q *Queries) TouchNodeSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchNodeSeen, id)
	return err
}

const updateNodeIdentity = `-- name: UpdateNodeIdentity :one
UPDATE nodes
SET name = COALESCE($3, name),
    endpoint = COALESCE($4, endpoint),
    updated_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
RETURNING id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority, cert_not_after, cert_public_key, cert_key_fingerprint, cert_delivered_at, cert_delivered, owner_user_id, enrolled_kind
`

type UpdateNodeIdentityParams struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	Name     *string   `json:"name"`
	Endpoint *string   `json:"endpoint"`
}

// Edits a gateway's NAME and/or ENDPOINT (S12.12 D3) — the two things an operator can get wrong at
// enrolment and, until now, could never correct.
//
// ⛔ THE TWO FIELDS ARE NOT SYMMETRIC AND THE CALLER MUST TREAT THEM DIFFERENTLY. The name is a LABEL:
// nothing consumes it structurally, so changing it costs nothing. The endpoint is HELD BY PEERS and BAKED
// INTO EVERY ISSUED DEVICE CONFIG, so changing it invalidates those configs — which is why the caller
// snapshots nothing here and instead marks the devices, and why the confirm has to say so.
//
// COALESCE so a caller may send either field alone; sending neither is a no-op the caller refuses earlier.
// A REVOKED node is excluded: it is terminal, nothing will serve it again, and letting an operator rename
// one produces a tidier record of something that does not exist.
func (q *Queries) UpdateNodeIdentity(ctx context.Context, arg UpdateNodeIdentityParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeIdentity,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Endpoint,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
		&i.CertNotAfter,
		&i.CertPublicKey,
		&i.CertKeyFingerprint,
		&i.CertDeliveredAt,
		&i.CertDelivered,
		&i.OwnerUserID,
		&i.EnrolledKind,
	)
	return i, err
}

const upsertOrgHubSetConfigured = `-- name: UpsertOrgHubSetConfigured :one
INSERT INTO org_hub_set (org_id, configured, generation)
VALUES ($1, $2, 1)
ON CONFLICT (org_id) DO UPDATE
SET configured = EXCLUDED.configured,
    generation = CASE WHEN org_hub_set.configured IS DISTINCT FROM EXCLUDED.configured
                      THEN org_hub_set.generation + 1
                      ELSE org_hub_set.generation END,
    updated_at = now()
RETURNING org_id, configured, demoted, generation, updated_at
`

type UpsertOrgHubSetConfiguredParams struct {
	OrgID      uuid.UUID   `json:"org_id"`
	Configured []uuid.UUID `json:"configured"`
}

type UpsertOrgHubSetConfiguredRow struct {
	OrgID      uuid.UUID   `json:"org_id"`
	Configured []uuid.UUID `json:"configured"`
	Demoted    []uuid.UUID `json:"demoted"`
	Generation int64       `json:"generation"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

// lint:cross-org — org-scoped by PK. ReconcileHubSet's writer (S8.6 REDUCE): writes `configured` ONLY —
// the CONFIGURED membership (pins/capability/order). ATOMIC bump: the generation increments in the SAME
// statement ONLY when `configured` actually changes (IS DISTINCT FROM) — an idempotent re-election never
// bumps (no idle tick eroding the fence), concurrent reconciles converge. On INSERT `demoted` defaults to
// '{}' (a fresh set has nothing demoted). This writer NEVER touches `demoted` (the field partition — the
// controller owns it), so a bind landing during a live failover updates membership without clobbering the
// demotion state.
func (q *Queries) UpsertOrgHubSetConfigured(ctx context.Context, arg UpsertOrgHubSetConfiguredParams) (UpsertOrgHubSetConfiguredRow, error) {
	row := q.db.QueryRow(ctx, upsertOrgHubSetConfigured, arg.OrgID, arg.Configured)
	var i UpsertOrgHubSetConfiguredRow
	err := row.Scan(
		&i.OrgID,
		&i.Configured,
		&i.Demoted,
		&i.Generation,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgHubSetDemoted = `-- name: UpsertOrgHubSetDemoted :one
UPDATE org_hub_set
SET demoted = $1,
    generation = CASE WHEN org_hub_set.demoted IS DISTINCT FROM $1::uuid[]
                      THEN org_hub_set.generation + 1
                      ELSE org_hub_set.generation END,
    updated_at = now()
WHERE org_id = $2
RETURNING org_id, configured, demoted, generation, updated_at
`

type UpsertOrgHubSetDemotedParams struct {
	Demoted []uuid.UUID `json:"demoted"`
	OrgID   uuid.UUID   `json:"org_id"`
}

type UpsertOrgHubSetDemotedRow struct {
	OrgID      uuid.UUID   `json:"org_id"`
	Configured []uuid.UUID `json:"configured"`
	Demoted    []uuid.UUID `json:"demoted"`
	Generation int64       `json:"generation"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

// lint:cross-org — org-scoped by PK. The failover controller's writer (S8.6 REDUCE): writes `demoted` ONLY
// — the members currently promoted-past for staleness. UPDATE (not upsert): a demotion only makes sense for
// an org that already has a configured hub set, so no row → 0 rows → the controller skips (nothing to fail
// over). ATOMIC bump: generation increments ONLY when `demoted` actually changes. NEVER touches
// `configured` (the field partition — ReconcileHubSet owns it).
func (q *Queries) UpsertOrgHubSetDemoted(ctx context.Context, arg UpsertOrgHubSetDemotedParams) (UpsertOrgHubSetDemotedRow, error) {
	row := q.db.QueryRow(ctx, upsertOrgHubSetDemoted, arg.Demoted, arg.OrgID)
	var i UpsertOrgHubSetDemotedRow
	err := row.Scan(
		&i.OrgID,
		&i.Configured,
		&i.Demoted,
		&i.Generation,
		&i.UpdatedAt,
	)
	return i, err
}
