// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_configs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getEnabledSSOConfigByProvider = `-- name: GetEnabledSSOConfigByProvider :one
SELECT id, org_id, provider, client_id, client_secret_sealed, enabled, created_at, updated_at, tenant_id, secret_fingerprint FROM sso_configs
WHERE provider = $1 AND client_id = $2 AND enabled = true
`

type GetEnabledSSOConfigByProviderParams struct {
	Provider string `json:"provider"`
	ClientID string `json:"client_id"`
}

// lint:cross-org — SSO callback resolves the config by (provider, client_id)
// before an org context exists; org_id is a column on the returned row.
func (q *Queries) GetEnabledSSOConfigByProvider(ctx context.Context, arg GetEnabledSSOConfigByProviderParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, getEnabledSSOConfigByProvider, arg.Provider, arg.ClientID)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ClientID,
		&i.ClientSecretSealed,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.SecretFingerprint,
	)
	return i, err
}

const getSSOConfig = `-- name: GetSSOConfig :one
SELECT id, org_id, provider, client_id, client_secret_sealed, enabled, created_at, updated_at, tenant_id, secret_fingerprint FROM sso_configs
WHERE org_id = $1 AND provider = $2
`

type GetSSOConfigParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetSSOConfig(ctx context.Context, arg GetSSOConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, getSSOConfig, arg.OrgID, arg.Provider)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ClientID,
		&i.ClientSecretSealed,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.SecretFingerprint,
	)
	return i, err
}

const upsertSSOConfig = `-- name: UpsertSSOConfig :one
INSERT INTO sso_configs (org_id, provider, client_id, client_secret_sealed, secret_fingerprint, tenant_id, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id, provider) DO UPDATE
    SET client_id = EXCLUDED.client_id,
        client_secret_sealed = EXCLUDED.client_secret_sealed,
        secret_fingerprint = EXCLUDED.secret_fingerprint,
        tenant_id = EXCLUDED.tenant_id,
        enabled = EXCLUDED.enabled
RETURNING id, org_id, provider, client_id, client_secret_sealed, enabled, created_at, updated_at, tenant_id, secret_fingerprint
`

type UpsertSSOConfigParams struct {
	OrgID              uuid.UUID `json:"org_id"`
	Provider           string    `json:"provider"`
	ClientID           string    `json:"client_id"`
	ClientSecretSealed []byte    `json:"client_secret_sealed"`
	SecretFingerprint  string    `json:"secret_fingerprint"`
	TenantID           *string   `json:"tenant_id"`
	Enabled            bool      `json:"enabled"`
}

func (q *Queries) UpsertSSOConfig(ctx context.Context, arg UpsertSSOConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, upsertSSOConfig,
		arg.OrgID,
		arg.Provider,
		arg.ClientID,
		arg.ClientSecretSealed,
		arg.SecretFingerprint,
		arg.TenantID,
		arg.Enabled,
	)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ClientID,
		&i.ClientSecretSealed,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.SecretFingerprint,
	)
	return i, err
}
