// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const generateID = `-- name: GenerateID :one
SELECT uuid_generate_v7() AS id
`

// Returns a fresh time-ordered UUIDv7 from the database. Demonstrates the sqlc
// pipeline and the uuid override; callers may also generate v7 ids in Go.
func (q *Queries) GenerateID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, generateID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT value FROM system_settings WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertSystemSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSystemSetting, arg.Key, arg.Value)
	return err
}
