import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { ImportRecording } from "../src/components/ImportRecording";
const state=vi.hoisted(()=>({denied:false}));
const recording={session_id:"11111111-1111-4111-8111-111111111111",expires_at:"2026-10-05T00:00:00Z",status:"available",events:[{seq:0,millis:0,type:"output",data:btoa("hello"),rows:0,cols:0}]};
vi.mock("../src/lib/api",()=>({apiErrorMessage:()=>"Import access denied",api:{POST:vi.fn(async()=>state.denied?{error:{}}:{data:recording})}}));
afterEach(()=>{cleanup();state.denied=false;vi.clearAllMocks()});
function file(name:string,text:string){const bytes=new TextEncoder().encode(text);return {name,size:bytes.length,text:vi.fn(async()=>text),arrayBuffer:vi.fn(async()=>bytes.buffer)} as unknown as File}
it("JSON imports stay local and clear previous snapshots before reading",async()=>{const {api}=await import("../src/lib/api");const imported=vi.fn(),reset=vi.fn();render(<ImportRecording orgId="org" onImport={imported} onReset={reset}/>);fireEvent.change(screen.getByLabelText("Import recording file"),{target:{files:[file("manual.json",JSON.stringify(recording))]}});await waitFor(()=>expect(imported).toHaveBeenCalled());expect(imported.mock.calls[0][0]).toMatchObject({source:"json",name:"manual.json"});expect(reset).toHaveBeenCalled();expect(api.POST).not.toHaveBeenCalled()});
it("encrypted packages upload only after an explicit decrypt action",async()=>{const {api}=await import("../src/lib/api");const imported=vi.fn();const bytes="TUNNEX-RECORDING-V2\nencrypted-envelope";render(<ImportRecording orgId="org" onImport={imported}/>);fireEvent.change(screen.getByLabelText("Import recording file"),{target:{files:[file("archive.tunnex-recording",bytes)]}});await screen.findByRole("button",{name:"Decrypt package for replay"});expect(api.POST).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Decrypt package for replay"}));await waitFor(()=>expect(imported).toHaveBeenCalled());expect(api.POST).toHaveBeenCalledWith("/api/v1/organizations/{orgId}/server-access/recording-import",{params:{path:{orgId:"org"}},body:{package:btoa(bytes)}});expect(imported.mock.calls[0][0]).toMatchObject({source:"encrypted-package"})});
it("denied decrypt clears the prior snapshot and never opens a replay",async()=>{state.denied=true;const imported=vi.fn(),reset=vi.fn();render(<ImportRecording orgId="org" onImport={imported} onReset={reset}/>);fireEvent.change(screen.getByLabelText("Import recording file"),{target:{files:[file("archive.tunnex-recording","TUNNEX-RECORDING-V2\nencrypted-envelope")]}});fireEvent.click(await screen.findByRole("button",{name:"Decrypt package for replay"}));await screen.findByText("Import access denied");expect(imported).not.toHaveBeenCalled();expect(reset).toHaveBeenCalled();expect(screen.queryByRole("button",{name:"Decrypt package for replay"})).toBeNull()});
it("raw chunks cannot be uploaded by renaming them as packages",async()=>{const {api}=await import("../src/lib/api");render(<ImportRecording orgId="org" onImport={vi.fn()}/>);fireEvent.change(screen.getByLabelText("Import recording file"),{target:{files:[file("chunk.tunnex-recording","raw chunk")]}});fireEvent.click(await screen.findByRole("button",{name:"Decrypt package for replay"}));await screen.findByText(/complete .tunnex-recording package/);expect(api.POST).not.toHaveBeenCalled()});

it("cancelling a staged encrypted package does not upload it",async()=>{const {api}=await import("../src/lib/api");render(<ImportRecording orgId="org" onImport={vi.fn()}/>);fireEvent.change(screen.getByLabelText("Import recording file"),{target:{files:[file("archive.tunnex-recording","TUNNEX-RECORDING-V2\nencrypted-envelope")]}});fireEvent.click(await screen.findByRole("button",{name:"Cancel package import"}));expect(api.POST).not.toHaveBeenCalled();expect(screen.queryByRole("button",{name:"Decrypt package for replay"})).toBeNull()});
