import { afterEach, expect, it } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { NetworkDetailList } from "../src/components/NetworkDetailList";
afterEach(cleanup);
it("bounds large inventories with selectable limits and searches beyond the current page", () => {
 const items = Array.from({length: 55}, (_, i) => `Gateway ${i + 1}`);
 render(<NetworkDetailList label="Gateways" items={items} searchText={item => item} renderItem={item => <li key={item}>{item}</li>} />);
 expect(screen.getAllByRole("listitem")).toHaveLength(20);
 fireEvent.change(screen.getByRole("combobox", {name:"Rows per page"}), {target:{value:"10"}});
 expect(screen.getAllByRole("listitem")).toHaveLength(10);
 fireEvent.click(screen.getByRole("button", {name:"Next gateways"}));
 expect(screen.getByText("Gateway 11")).toBeTruthy();
 expect(screen.queryByText("Gateway 1")).toBeNull();
 fireEvent.change(screen.getByRole("combobox", {name:"Rows per page"}), {target:{value:"50"}});
 expect(screen.getAllByRole("listitem")).toHaveLength(50);
 expect(screen.getByText("Gateway 1")).toBeTruthy();
 fireEvent.click(screen.getByRole("button", {name:"Next gateways"}));
 expect(screen.getAllByRole("listitem")).toHaveLength(5);
 expect(screen.getByText("Gateway 51")).toBeTruthy();
 expect(screen.getByRole("button", {name:"Next gateways"})).toHaveProperty("disabled",true);
 fireEvent.click(screen.getByRole("button", {name:"Previous gateways"}));
 expect(screen.getByText("Gateway 1")).toBeTruthy();
 fireEvent.change(screen.getByRole("textbox", {name:"Search Gateways"}), {target:{value:"Gateway 55"}});
 expect(screen.getAllByRole("listitem")).toHaveLength(1);
 expect(screen.getByText("Gateway 55")).toBeTruthy();
 expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();
 fireEvent.change(screen.getByRole("textbox", {name:"Search Gateways"}), {target:{value:""}});
 expect(screen.getByText("Gateway 1")).toBeTruthy();
 expect(screen.getAllByRole("listitem")).toHaveLength(50);
});
it("clamps pagination when rows are removed", () => {
 const props = {label:"Ranges", searchText:(item:string)=>item, renderItem:(item:string)=><li key={item}>{item}</li>};
 const items = Array.from({length:55},(_,i)=>`Range ${i}`);
 const view=render(<NetworkDetailList {...props} items={items}/>);
 fireEvent.change(screen.getByRole("combobox",{name:"Rows per page"}),{target:{value:"50"}});
 fireEvent.click(screen.getByRole("button",{name:"Next ranges"}));
 expect(screen.getAllByRole("listitem")).toHaveLength(5);
 view.rerender(<NetworkDetailList {...props} items={items.slice(0,1)}/>);
 expect(screen.getByText("Range 0")).toBeTruthy();
 expect(screen.getAllByRole("listitem")).toHaveLength(1);
 expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();
 expect(screen.queryByRole("combobox",{name:"Rows per page"})).toBeNull();
 expect(screen.queryByRole("button",{name:"Next ranges"})).toBeNull();
});
