import {afterEach,expect,it,vi} from "vitest";
import {act,cleanup,fireEvent,render,screen} from "@testing-library/react";
import {BrowserRdp} from "../src/components/BrowserRdp";
import type {components} from "@tunnex/shared";
const mocks=vi.hoisted(()=>({client:null as any,socket:null as any,mouse:null as any}));
vi.mock("guacamole-common-js",()=>({default:{Tunnel:class {static State={OPEN:1,CLOSED:2};setState(){}},Parser:class {receive(){}},Client:class {element=document.createElement("div");sendMouseState=vi.fn();sendKeyEvent=vi.fn();sendAck=vi.fn();onclipboard:any;constructor(){mocks.client=this}getDisplay(){return {getElement:()=>this.element,getWidth:()=>1280,getHeight:()=>720,getScale:()=>1}}connect(){}disconnect(){}sendSize(){}},Keyboard:class {reset(){}},Mouse:class {constructor(){mocks.mouse=this}}}}));
vi.mock("../src/lib/api",()=>({api:{DELETE:vi.fn(async()=>({}))},apiErrorMessage:()=>"error"}));
afterEach(()=>{cleanup();vi.unstubAllGlobals();mocks.client=mocks.socket=mocks.mouse=null});
async function setup(policy:string){vi.stubGlobal("ResizeObserver",class {observe(){}disconnect(){}});vi.stubGlobal("WebSocket",class {static OPEN=1;readyState=1;send=vi.fn();close(){}constructor(){mocks.socket=this}});render(<BrowserRdp orgId="org" session={{id:"session",account:"Administrator"} as components["schemas"]["ServerAccessSession"]} passwordRef={{current:""}} clipboardPolicy={policy} onClose={()=>{}}/>);await act(async()=>{});}
it.each([['off',false,false],['paste',true,false],['copy',false,true],['both',true,true]])("enforces %s control visibility",async(policy,paste,copy)=>{await setup(policy as string);expect(!!screen.queryByRole("button",{name:"Paste text"})).toBe(paste);expect(!!screen.queryByRole("button",{name:"Copy text"})).toBe(copy);if(copy)expect((screen.getByRole("button",{name:"Copy text"}) as HTMLButtonElement).disabled).toBe(true)});
it("targets viewport-relative desktop coordinates and focuses keyboard after ancestor scrolling",async()=>{await setup("both");const element=mocks.client.element;vi.spyOn(element,"getBoundingClientRect").mockReturnValue({left:283,top:165} as DOMRect);fireEvent.mouseDown(element,{clientX:724,clientY:861});mocks.mouse.onmousedown({x:441,y:-121,left:true});expect(mocks.client.sendMouseState).toHaveBeenCalledWith({x:441,y:696,left:true});expect(document.activeElement).toBe(screen.getByLabelText("Windows desktop for Administrator"));});
it("acknowledges remote clipboard streams and clears copyable text after disconnect",async()=>{await setup("both");await act(async()=>mocks.socket.onmessage({data:JSON.stringify({type:"output",data:btoa("3.nop;")})}));const stream={index:3} as any;act(()=>{mocks.client.onclipboard(stream,"text/plain");stream.onblob(btoa("Tunnex remote clipboard test"));stream.onend();});expect(mocks.client.sendAck).toHaveBeenCalledWith(3,"OK",0);expect((screen.getByRole("button",{name:"Copy text"}) as HTMLButtonElement).disabled).toBe(false);act(()=>mocks.socket.onclose());expect((screen.getByRole("button",{name:"Copy text"}) as HTMLButtonElement).disabled).toBe(true);});
