import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { RecordingArchiveForm } from "../src/components/RecordingArchiveForm";
import { RecordingStorageForm } from "../src/components/RecordingStorageForm";
const state=vi.hoisted(()=>({value:{kind:"postgres",credentials_configured:false} as Record<string,unknown>,fail:false,bodies:[] as Record<string,unknown>[]}));
vi.mock("../src/lib/api",()=>({apiErrorMessage:()=>"Storage unavailable",api:{GET:vi.fn(async()=>({data:state.value})),PUT:vi.fn(async(_path:string,args:{body:Record<string,unknown>})=>{state.bodies.push(args.body);return state.fail?{error:{}}:{data:state.value}}),POST:vi.fn(async(_path:string,args:{body:Record<string,unknown>})=>{state.bodies.push(args.body);return state.fail?{error:{}}:{data:{ok:true}}})}}));
afterEach(()=>{cleanup();state.value={kind:"postgres",credentials_configured:false};state.fail=false;state.bodies=[];vi.clearAllMocks()});
it("tests a provider without claiming its configuration is saved",async()=>{render(<RecordingStorageForm orgId="org"/>);fireEvent.click(await screen.findByRole("button",{name:"Test storage connection"}));await screen.findByText(/connection test passed/);expect(screen.queryByText(/Legacy storage connection saved/)).toBeNull();expect(state.bodies).toEqual([{kind:"postgres"}])});
it("never returns saved secrets to inputs and retains same-destination credentials by omission",async()=>{state.value={kind:"s3",endpoint:"https://objects.local",bucket:"records",region:"local",access_key_id:"public-id",credentials_configured:true};render(<RecordingStorageForm orgId="org"/>);const secret=await screen.findByLabelText("Secret access key") as HTMLInputElement;expect(secret.type).toBe("password");expect(secret.value).toBe("");expect(secret.required).toBe(false);fireEvent.click(screen.getByRole("button",{name:"Save recording storage"}));await waitFor(()=>expect(state.bodies.length).toBe(1));expect(state.bodies[0]).not.toHaveProperty("secret_access_key");fireEvent.change(screen.getByLabelText("Bucket"),{target:{value:"other"}});expect((screen.getByLabelText("Secret access key") as HTMLInputElement).required).toBe(true)});
it("failed save preserves edits and never claims success",async()=>{state.fail=true;render(<RecordingStorageForm orgId="org"/>);fireEvent.change(await screen.findByLabelText("Storage provider"),{target:{value:"filesystem"}});fireEvent.change(screen.getByLabelText("Mounted recording directory"),{target:{value:"/mnt/records"}});fireEvent.click(screen.getByRole("button",{name:"Save recording storage"}));await screen.findByText("Storage unavailable");expect((screen.getByLabelText("Mounted recording directory") as HTMLInputElement).value).toBe("/mnt/records");expect(screen.queryByText(/Legacy storage connection saved/)).toBeNull()});
it("submits Google Cloud Storage HMAC credentials with its XML endpoint defaults",async()=>{render(<RecordingStorageForm orgId="org"/>);fireEvent.change(await screen.findByLabelText("Storage provider"),{target:{value:"gcs"}});fireEvent.change(screen.getByLabelText("Bucket"),{target:{value:"terminal-recordings"}});fireEvent.change(screen.getByLabelText("HMAC access key ID"),{target:{value:"test-hmac-id"}});fireEvent.change(screen.getByLabelText("HMAC secret access key"),{target:{value:"test-hmac-secret"}});fireEvent.click(screen.getByRole("button",{name:"Test storage connection"}));await screen.findByText(/connection test passed/);expect(state.bodies[0]).toMatchObject({kind:"gcs",endpoint:"https://storage.googleapis.com",region:"auto",bucket:"terminal-recordings",access_key_id:"test-hmac-id",secret_access_key:"test-hmac-secret"});expect((screen.getByLabelText("HMAC secret access key") as HTMLInputElement).type).toBe("password")});

it("shows PostgreSQL as the default recommended destination while retaining optional providers",async()=>{render(<RecordingStorageForm orgId="org"/>);const provider=await screen.findByRole("combobox",{name:"Storage provider"});expect((provider as HTMLSelectElement).value).toBe("postgres");expect(screen.getByRole("option",{name:"PostgreSQL (default, recommended)"})).toBeTruthy();expect(screen.getByText(/PostgreSQL is the default and recommended recording destination/)).toBeTruthy();for(const name of ["Mounted filesystem / EFS / EBS","S3-compatible object storage","Google Cloud Storage","Azure Blob Storage"])expect(screen.getByRole("option",{name})).toBeTruthy();expect(screen.getByText(/Existing recordings retain their original destination/)).toBeTruthy()});

it("automatic S3 archive reuses storage validation and omits the primary provider from archive requests",async()=>{state.value={enabled:false,credentials_configured:false};render(<RecordingArchiveForm orgId="org"/>);fireEvent.click(await screen.findByRole("switch"));fireEvent.change(screen.getByLabelText("Storage endpoint"),{target:{value:"https://archive.local"}});fireEvent.change(screen.getByLabelText("Bucket"),{target:{value:"archives"}});fireEvent.change(screen.getByLabelText("Region"),{target:{value:"local"}});fireEvent.change(screen.getByLabelText("Access key ID"),{target:{value:"test-id"}});fireEvent.change(screen.getByLabelText("Secret access key"),{target:{value:"test-secret"}});fireEvent.click(screen.getByRole("button",{name:"Test S3 archive connection"}));await screen.findByText(/S3 archive connection test passed/);expect(state.bodies[0]).toMatchObject({enabled:true,endpoint:"https://archive.local",bucket:"archives",region:"local",access_key_id:"test-id",secret_access_key:"test-secret"});expect(state.bodies[0]).not.toHaveProperty("kind");expect(screen.queryByRole("combobox",{name:"Storage provider"})).toBeNull()});

it("retains a configured S3 connection for manual exports with automatic archiving off",async()=>{state.value={enabled:false,endpoint:"https://archive.local",bucket:"manual-archives",region:"local",access_key_id:"test-id",credentials_configured:true};render(<RecordingArchiveForm orgId="org"/>);const toggle=await screen.findByRole("switch");expect(toggle.getAttribute("aria-checked")).toBe("false");expect((screen.getByLabelText("Secret access key") as HTMLInputElement).required).toBe(false);fireEvent.click(screen.getByRole("button",{name:"Test S3 archive connection"}));await screen.findByText(/S3 archive connection test passed/);expect(state.bodies[0]).toMatchObject({enabled:false,endpoint:"https://archive.local",bucket:"manual-archives",region:"local",access_key_id:"test-id"});expect(state.bodies[0]).not.toHaveProperty("secret_access_key");expect(screen.getByText(/saved S3 connection remains available for manual Export to S3 while this is off/)).toBeTruthy()});

it("saving a legacy connection never claims to redirect new captures",async()=>{render(<RecordingStorageForm orgId="org"/>);fireEvent.click(await screen.findByRole("button",{name:"Save recording storage"}));await screen.findByText("Legacy storage connection saved. New recordings continue to use PostgreSQL.");expect(screen.getByText(/New recordings always use PostgreSQL; use the S3 archive settings above for exports/)).toBeTruthy()});
