import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { ServerAccountGrants } from "../src/components/ServerAccountGrants";
import { ServerSessions } from "../src/components/ServerSessions";
import type { components } from "@tunnex/shared";
afterEach(cleanup);
const server={id:"server-1",name:"Target"} as components["schemas"]["ServerAccessServer"];
const grant=(id:string,offset:number,enabled=true,user="user-1")=>({id,server_id:server.id,account:"ubuntu",user_id:user,enabled,starts_at:new Date(Date.now()-7200000).toISOString(),expires_at:new Date(Date.now()+offset).toISOString()}) as components["schemas"]["ServerAccessGrant"];
function menuAction(label:string,action:string){const trigger=screen.getByRole("button",{name:label});if(trigger.getAttribute("aria-expanded")!=="true")fireEvent.click(trigger);return within(screen.getByRole("menu",{name:label})).getByRole("menuitem",{name:action})}
it("hides revoked and superseded history and renews the exact expired recipient",()=>{
 const renew=vi.fn();render(<ServerAccountGrants grants={[grant("old",-10000),grant("active",60000),grant("revoked",60000,false,"user-2"),grant("expired",-10000,true,"user-3")]} servers={[server]} members={[]} groups={[]} disabled={false} onRevoke={vi.fn()} onRenew={renew}/>);
 expect(screen.getAllByRole("row")).toHaveLength(3);expect(screen.queryByText("user-2")).toBeNull();expect(within(screen.getByRole("table")).getByText("Active")).toBeTruthy();expect(within(screen.getByRole("table")).getByText("Expired")).toBeTruthy();
 fireEvent.click(menuAction("Grant actions for user-3 · ubuntu on Target","Extend access"));fireEvent.change(screen.getByLabelText("Extend duration (hours)"),{target:{value:"2"}});fireEvent.click(screen.getByRole("button",{name:"Confirm extension"}));
 const body=renew.mock.calls[0][0];expect(body).toMatchObject({server_id:server.id,account:"ubuntu",user_id:"user-3"});expect(Date.parse(body.expires_at)-Date.parse(body.starts_at)).toBeCloseTo(7200000,-2);
});
it("preserves a group recipient and cancels without granting access",()=>{
 const renew=vi.fn();const dismiss=vi.fn();const g={...grant("expired",-10000),user_id:undefined,group_id:"group-1"};render(<ServerAccountGrants grants={[g]} servers={[server]} members={[]} groups={[]} disabled={false} onRevoke={vi.fn()} onRenew={renew} onRenewDismiss={dismiss}/>);
 fireEvent.click(menuAction("Grant actions for group-1 · ubuntu on Target","Extend access"));fireEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(renew).not.toHaveBeenCalled();expect(dismiss).toHaveBeenCalledTimes(1);fireEvent.click(menuAction("Grant actions for group-1 · ubuntu on Target","Extend access"));fireEvent.click(screen.getByRole("button",{name:"Confirm extension"}));expect(renew.mock.calls[0][0]).toMatchObject({group_id:"group-1"});expect(renew.mock.calls[0][0].user_id).toBeUndefined();expect(dismiss).toHaveBeenCalledTimes(1);
});
it("separates connection checks and paginates real sessions",()=>{
 const end=vi.fn();const sessions=Array.from({length:21},(_,i)=>({id:`session-${i}`,kind:"terminal",status:"connected",reason:"",server_id:server.id,user_id:"user-1",account:"ubuntu",created_at:new Date().toISOString(),expires_at:new Date().toISOString(),recording_enabled:false})) as components["schemas"]["ServerAccessSession"][];sessions.push({...sessions[0],id:"check-1",kind:"check",status:"passed"});
 render(<MemoryRouter><ServerSessions sessions={sessions} servers={[server]} members={[]} disabled={false} onRefresh={vi.fn()} onEnd={end} onReplay={vi.fn()} importControl={<p>Import details</p>}/></MemoryRouter>);
 expect(screen.getAllByRole("row")).toHaveLength(21);expect(screen.queryByText("check-1")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Next sessions"}));expect(screen.getAllByRole("row")).toHaveLength(2);fireEvent.click(menuAction("Session actions for session-","End session"));expect(end).toHaveBeenCalledWith("session-20");fireEvent.change(screen.getByLabelText("Session view"),{target:{value:"checks"}});expect(screen.getByText("check-1")).toBeTruthy();expect(screen.queryByRole("menuitem",{name:"End session"})).toBeNull();
});
it("pages only eligible latest grants and resets the page when size or filters change",()=>{
 const revoke=vi.fn();const renew=vi.fn();const grants=Array.from({length:55},(_,i)=>grant(`grant-${i}`,i===54?-10000:60000,true,`user-${String(i).padStart(3,"0")}`));
 grants.push(grant("superseded",-10000,true,"user-000"),grant("revoked",60000,false,"revoked-user"),{...grant("future",60000,true,"future-user"),starts_at:new Date(Date.now()+60000).toISOString()},{...grant("removed",60000,true,"removed-user"),server_id:"removed-server"});
 render(<MemoryRouter><ServerAccountGrants grants={grants} servers={[server]} members={[]} groups={[]} disabled={false} onRevoke={revoke} onRenew={renew}/></MemoryRouter>);
 expect(screen.getAllByRole("row")).toHaveLength(21);expect(screen.queryByText("revoked-user")).toBeNull();expect(screen.queryByText("future-user")).toBeNull();expect(screen.queryByText("removed-user")).toBeNull();
 fireEvent.change(screen.getByLabelText("Rows per page"),{target:{value:"10"}});expect(screen.getAllByRole("row")).toHaveLength(11);fireEvent.click(screen.getByRole("button",{name:"Next account grants"}));expect(screen.getByText("Page 2")).toBeTruthy();expect(screen.queryByText("user-000")).toBeNull();
 fireEvent.change(screen.getByLabelText("Search account grants"),{target:{value:"user-054"}});expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();expect(screen.getAllByRole("row")).toHaveLength(2);expect(within(screen.getByRole("table")).getByText("Expired")).toBeTruthy();
 fireEvent.change(screen.getByLabelText("Search account grants"),{target:{value:""}});fireEvent.change(screen.getByLabelText("Rows per page"),{target:{value:"50"}});expect(screen.getAllByRole("row")).toHaveLength(51);fireEvent.click(screen.getByRole("button",{name:"Next account grants"}));expect(screen.getAllByRole("row")).toHaveLength(6);expect(screen.getByText("51–55 shown")).toBeTruthy();
 fireEvent.change(screen.getByLabelText("Account grant status"),{target:{value:"expired"}});expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();expect(screen.getAllByRole("row")).toHaveLength(2);expect(screen.getByText("user-054")).toBeTruthy();expect(revoke).not.toHaveBeenCalled();expect(renew).not.toHaveBeenCalled();
});
it("keeps empty access guidance without empty table headers or pagination",()=>{
 render(<MemoryRouter><ServerAccountGrants grants={[grant("revoked",60000,false)]} servers={[server]} members={[]} groups={[]} disabled={false} onRevoke={vi.fn()} onRenew={vi.fn()}/></MemoryRouter>);
 expect(screen.getByRole("heading",{name:"No active or expired grants"})).toBeTruthy();expect(screen.queryByRole("table")).toBeNull();expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();expect(screen.queryByRole("combobox",{name:"Rows per page"})).toBeNull();expect(screen.getByRole("link",{name:"View servers"}).getAttribute("href")).toBe("/browser-access/terminal");expect(screen.queryByRole("button",{name:"Next account grants"})).toBeNull();
 fireEvent.change(screen.getByLabelText("Search account grants"),{target:{value:"missing"}});expect(screen.getByRole("heading",{name:"No matching grants"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Clear access filters"}));expect(screen.getByLabelText("Search account grants").getAttribute("value")).toBe("");expect(screen.getByRole("heading",{name:"No active or expired grants"})).toBeTruthy();
});
it("keeps grant busy and duration guards inside the extension drawer",()=>{
 const renew=vi.fn();const revoke=vi.fn();const grants=[grant("expired",-10000,true,"user-3")];const props={grants,servers:[server],members:[],groups:[],onRevoke:revoke,onRenew:renew,verification:<p>Additional verification required</p>};
 const view=render(<MemoryRouter><ServerAccountGrants {...props} disabled={true}/></MemoryRouter>);
 const action=menuAction("Grant actions for user-3 · ubuntu on Target","Extend access");expect(action.hasAttribute("disabled")).toBe(true);expect(screen.getByText("Wait for the current action to finish.")).toBeTruthy();fireEvent.click(action);expect(screen.queryByRole("dialog")).toBeNull();expect(renew).not.toHaveBeenCalled();
 view.rerender(<MemoryRouter><ServerAccountGrants {...props} disabled={false}/></MemoryRouter>);fireEvent.click(menuAction("Grant actions for user-3 · ubuntu on Target","Extend access"));expect(within(screen.getByRole("dialog",{name:"Extend access"})).getByText("Additional verification required")).toBeTruthy();
 for(const hours of ["0","169"]){fireEvent.change(screen.getByLabelText("Extend duration (hours)"),{target:{value:hours}});expect(screen.getByRole("button",{name:"Confirm extension"}).hasAttribute("disabled")).toBe(true);fireEvent.submit(screen.getByRole("button",{name:"Confirm extension"}).closest("form")!);expect(renew).not.toHaveBeenCalled()}
 fireEvent.change(screen.getByLabelText("Extend duration (hours)"),{target:{value:"2"}});view.rerender(<MemoryRouter><ServerAccountGrants {...props} disabled={true}/></MemoryRouter>);fireEvent.submit(screen.getByRole("button",{name:"Confirm extension"}).closest("form")!);expect(renew).not.toHaveBeenCalled();expect(screen.getByRole("button",{name:"Cancel"}).hasAttribute("disabled")).toBe(true);expect(revoke).not.toHaveBeenCalled();
});
const session=(id:string,overrides:Partial<components["schemas"]["ServerAccessSession"]>={})=>({id,kind:"terminal",status:"connected",reason:"",server_id:server.id,user_id:"user-1",account:"ubuntu",created_at:new Date().toISOString(),expires_at:new Date().toISOString(),recording_enabled:false,...overrides}) as components["schemas"]["ServerAccessSession"];
it("applies session size and search after kind filtering and clamps a shrinking list",()=>{
 const sessions=Array.from({length:55},(_,i)=>session(`sess${String(i).padStart(4,"0")}`));sessions.push(session("check001",{kind:"check",status:"passed"}));const props={servers:[server],members:[],disabled:false,onRefresh:vi.fn(),onEnd:vi.fn(),onReplay:vi.fn(),importControl:null};
 const view=render(<MemoryRouter><ServerSessions {...props} sessions={sessions}/></MemoryRouter>);
 expect(screen.getAllByRole("row")).toHaveLength(21);expect(screen.queryByText("check001")).toBeNull();fireEvent.change(screen.getByLabelText("Rows per page"),{target:{value:"10"}});expect(screen.getAllByRole("row")).toHaveLength(11);fireEvent.click(screen.getByRole("button",{name:"Next sessions"}));expect(screen.getByText("Page 2")).toBeTruthy();
 fireEvent.change(screen.getByLabelText("Search sessions"),{target:{value:"sess0054"}});expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();expect(screen.getAllByRole("row")).toHaveLength(2);expect(screen.getByText("sess0054")).toBeTruthy();fireEvent.change(screen.getByLabelText("Search sessions"),{target:{value:""}});fireEvent.change(screen.getByLabelText("Rows per page"),{target:{value:"50"}});expect(screen.getAllByRole("row")).toHaveLength(51);fireEvent.click(screen.getByRole("button",{name:"Next sessions"}));expect(screen.getAllByRole("row")).toHaveLength(6);expect(screen.getByText("51–55 shown")).toBeTruthy();
 view.rerender(<MemoryRouter><ServerSessions {...props} sessions={[sessions[0],sessions[55]]}/></MemoryRouter>);expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();expect(screen.getAllByRole("row")).toHaveLength(2);fireEvent.change(screen.getByLabelText("Session view"),{target:{value:"checks"}});expect(screen.getByText("check001")).toBeTruthy();expect(screen.queryByText("sess0000")).toBeNull();expect(props.onEnd).not.toHaveBeenCalled();expect(props.onReplay).not.toHaveBeenCalled();
});
it("preserves recording, end-session and audit authority in session menus",()=>{
 const replay=vi.fn();const end=vi.fn();render(<MemoryRouter><ServerSessions sessions={[session("ended001",{status:"ended",recording_enabled:true,reason:"connection_lost"}),session("editor01",{kind:"editor",recording_enabled:true}),session("check001",{kind:"check",status:"passed",recording_enabled:true})]} servers={[server]} members={[]} disabled={true} onRefresh={vi.fn()} onEnd={end} onReplay={replay} importControl={null}/></MemoryRouter>);
 fireEvent.click(menuAction("Session actions for ended001","Replay"));expect(replay).toHaveBeenCalledWith("ended001");const events=menuAction("Session actions for ended001","Session events");expect(events.getAttribute("href")).toBe("/audit?target_type=server_access&target_id=ended001");expect(screen.queryByRole("menuitem",{name:"End session"})).toBeNull();fireEvent.click(menuAction("Session actions for ended001","Details"));expect(within(screen.getByRole("dialog",{name:"Session details"})).getByText("connection lost")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Close Session details"}));
 const endAction=menuAction("Session actions for editor01","End session");expect(endAction.hasAttribute("disabled")).toBe(true);expect(screen.queryByRole("menuitem",{name:"Replay"})).toBeNull();fireEvent.click(endAction);expect(end).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText("Session view"),{target:{value:"checks"}});menuAction("Session actions for check001","Session events");expect(screen.queryByRole("menuitem",{name:"Replay"})).toBeNull();expect(screen.queryByRole("menuitem",{name:"End session"})).toBeNull();
});
it("distinguishes an empty session view from a search with no matches",()=>{
 render(<MemoryRouter><ServerSessions sessions={[]} servers={[server]} members={[]} disabled={false} onRefresh={vi.fn()} onEnd={vi.fn()} onReplay={vi.fn()} importControl={null}/></MemoryRouter>);
 expect(screen.getByRole("heading",{name:"No server sessions"})).toBeTruthy();expect(screen.queryByRole("table")).toBeNull();expect(screen.queryByRole("navigation",{name:"Table pagination"})).toBeNull();expect(screen.queryByRole("combobox",{name:"Rows per page"})).toBeNull();expect(screen.queryByRole("button",{name:"Next sessions"})).toBeNull();fireEvent.change(screen.getByLabelText("Session view"),{target:{value:"checks"}});expect(screen.getByRole("heading",{name:"No connection checks"})).toBeTruthy();fireEvent.change(screen.getByLabelText("Search sessions"),{target:{value:"missing"}});expect(screen.getByRole("heading",{name:"No matching sessions"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Clear session search"}));expect(screen.getByRole("heading",{name:"No connection checks"})).toBeTruthy();
});
