import { afterEach, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { TerminalReplay } from "../src/components/TerminalReplay";
const state=vi.hoisted(()=>({operations:[] as string[],callbacks:[] as (()=>void)[],denied:false,networkError:false,status:"complete",archiveStatus:"none",exportDenied:false}));
vi.mock("@xterm/xterm",()=>({Terminal:class{loadAddon(){}open(){}reset(){state.operations.push("reset")}resize(c:number,r:number){state.operations.push(`resize:${c}:${r}`)}write(bytes:Uint8Array,done:()=>void){state.operations.push(`write:${new TextDecoder().decode(bytes)}`);state.callbacks.push(done)}dispose(){}}}));
vi.mock("@xterm/addon-fit",()=>({FitAddon:class{fit(){}}}));
vi.mock("../src/lib/api",()=>({apiErrorCode:()=>"archive_not_configured",apiErrorMessage:()=>"Access denied",api:{POST:vi.fn(async()=>state.exportDenied?{error:{}}:({data:{status:"pending"}})),GET:vi.fn(async()=>{if(state.networkError)throw new Error("offline");return state.denied?{error:{}}:({data:{status:state.status,archive_status:state.archiveStatus,events:[{type:"output",data:btoa("first"),millis:0},{type:"resize",cols:100,rows:40,millis:1},{type:"output",data:btoa("last"),millis:2}]}})})}}));
afterEach(()=>{cleanup();state.operations=[];state.callbacks=[];state.denied=false;state.networkError=false;state.status="complete";state.archiveStatus="none";state.exportDenied=false;vi.restoreAllMocks()});
it("seek waits for parsed output before applying resize and subsequent output",async()=>{render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);const range=await screen.findByRole("slider");fireEvent.change(range,{target:{value:"3"}});await waitFor(()=>expect(state.operations).toEqual(["reset","write:first"]));state.callbacks.shift()!();expect(state.operations).toEqual(["reset","write:first","resize:100:40","write:last"]);state.callbacks.shift()!();await waitFor(()=>expect((range as HTMLInputElement).value).toBe("3"))});
it("a superseded seek cannot continue its queued output callback",async()=>{render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);const range=await screen.findByRole("slider");fireEvent.change(range,{target:{value:"3"}});await waitFor(()=>expect(state.callbacks.length).toBe(1));fireEvent.click(screen.getByRole("button",{name:"Restart replay"}));state.callbacks.shift()!();expect(state.operations).toEqual(["reset","write:first","reset"])});

it("withdrawn replay authority clears visible content and cancels queued rendering",async()=>{let poll:()=>void=()=>{};const interval=setInterval;vi.spyOn(globalThis,"setInterval").mockImplementation(((callback:()=>void,millis:number)=>{if(millis===5000)poll=callback;return interval(callback,millis)}) as typeof setInterval);render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);const range=await screen.findByRole("slider");fireEvent.change(range,{target:{value:"3"}});await waitFor(()=>expect(state.callbacks.length).toBe(1));state.denied=true;await act(async()=>{poll();await Promise.resolve()});await screen.findByText("Access denied");state.callbacks.shift()!();expect(state.operations).toEqual(["reset","write:first","reset"]);expect(screen.queryByRole("slider")).toBeNull();expect(screen.queryByRole("button",{name:"Play replay"})).toBeNull()});

it("network loss clears replay content and cancels already queued rendering",async()=>{let poll:()=>void=()=>{};const interval=setInterval;vi.spyOn(globalThis,"setInterval").mockImplementation(((callback:()=>void,millis:number)=>{if(millis===5000)poll=callback;return interval(callback,millis)}) as typeof setInterval);render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);const range=await screen.findByRole("slider");fireEvent.change(range,{target:{value:"3"}});await waitFor(()=>expect(state.callbacks.length).toBe(1));state.networkError=true;await act(async()=>{poll();await Promise.resolve()});await screen.findByText("Could not verify recording access.");state.callbacks.shift()!();expect(state.operations).toEqual(["reset","write:first","reset"]);expect(screen.queryByRole("slider")).toBeNull()});

it("offers viewer S3 export separately from manual download without claiming archive completion",async()=>{render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);const exportButton=await screen.findByRole("button",{name:"Export to S3"});expect(screen.getByRole("button",{name:"Manual download"})).toBeTruthy();fireEvent.click(exportButton);await screen.findByText(/S3 export requested/);expect(screen.queryByText("S3 archive is available.")).toBeNull();expect(screen.getByText(/Manual download creates portable JSON/)).toBeTruthy()});
it("manual download checks its own authorized endpoint and does not trigger export",async()=>{const {api}=await import("../src/lib/api");vi.mocked(api.POST).mockClear();render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);const button=await screen.findByRole("button",{name:"Manual download"});state.denied=true;fireEvent.click(button);await screen.findByText("Access denied");expect(api.GET).toHaveBeenLastCalledWith("/api/v1/organizations/{orgId}/server-access/sessions/{sessionId}/recording/download",{params:{path:{orgId:"org",sessionId:"session"}},parseAs:"blob"});expect(api.POST).not.toHaveBeenCalled();expect(screen.getByRole("button",{name:"Manual download"}).hasAttribute("disabled")).toBe(false)});

it("cannot export a recording that is still capturing",async()=>{state.status="capturing";render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);expect((await screen.findByRole("button",{name:"Export to S3"}) as HTMLButtonElement).disabled).toBe(true)});
it("an unexported recording does not imply missing S3 configuration",async()=>{render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);await screen.findByRole("button",{name:"Export to S3"});expect(screen.queryByText("Ask an administrator to configure S3 archiving.")).toBeNull();state.exportDenied=true;fireEvent.click(screen.getByRole("button",{name:"Export to S3"}));await screen.findByText("Ask an administrator to configure S3 archiving.")});
it("manual export acknowledgement preserves PostgreSQL payload until retention expiry",async()=>{render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);fireEvent.click(await screen.findByRole("button",{name:"Export to S3"}));await screen.findByText(/PostgreSQL payload remains through retention and is deleted only after verified archiving at expiry/)});

it.each(["expired","failed","disabled"])("disables manual download when recording payload is %s",async status=>{state.status=status;render(<TerminalReplay orgId="org" sessionId="session" onClose={()=>{}}/>);expect((await screen.findByRole("button",{name:"Manual download"}) as HTMLButtonElement).disabled).toBe(true)});

it.each(["json","encrypted-package"] as const)("imported %s replay remains an unverified snapshot without live, export or download actions",async source=>{const {api}=await import("../src/lib/api");vi.mocked(api.GET).mockClear();vi.mocked(api.POST).mockClear();render(<TerminalReplay imported={{name:"imported-file",source,recording:{status:"available",events:[{seq:0,millis:0,type:"output",data:btoa("hello"),rows:0,cols:0}]}}} onClose={()=>{}}/>);await screen.findByRole("button",{name:"Play replay"});expect(screen.getByRole("heading",{name:"Imported recording"})).toBeTruthy();expect(screen.getByRole("note").textContent).toContain("Original actor, server and audit assertions are unverified");expect(screen.queryByRole("button",{name:"Export to S3"})).toBeNull();expect(screen.queryByRole("button",{name:"Manual download"})).toBeNull();expect(api.GET).not.toHaveBeenCalled();expect(api.POST).not.toHaveBeenCalled()});
