{{- include "tunnex-host-posture.validate" . -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tunnex-host-posture.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnex-host-posture.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
