import { SandboxCandidateProfiles } from "../components/SandboxImageProfiles";
import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {api,apiErrorMessage,type SandboxSetup} from "../lib/api";
import {useOrg} from "../lib/useOrg";
import {Button,ErrorText,Field,Input,Loading} from "../components/ui";
import {SandboxHeader,RuntimeSpecs,RuntimeMark} from "../components/SandboxChrome";
import {SandboxBlockedReasons} from "../components/SandboxAvailability";
export function SandboxSetupPage(){
 const {org,loading,failed}=useOrg();
 if(loading)return <Loading/>;if(failed)return <ErrorText>Organizations could not be loaded.</ErrorText>;if(!org)return <p>Select an organization to configure sandboxes.</p>;
 return <Setup key={org.id} orgId={org.id}/>;
}
function Setup({orgId}:{orgId:string}){
 const [data,setData]=useState<SandboxSetup|null>(null),[error,setError]=useState<string|null>(null),[pending,setPending]=useState(false),[revision,setRevision]=useState(0);
 const [enabled,setEnabled]=useState(false),[perUser,setPerUser]=useState(2),[total,setTotal]=useState(20);
 function loaded(value:SandboxSetup){setData(value);setEnabled(value.settings.enabled);setPerUser(value.settings.max_per_user);setTotal(value.settings.max_total)}
 useEffect(()=>{let active=true;setData(null);setError(null);void api.GET("/api/v1/organizations/{orgId}/sandbox-setup",{params:{path:{orgId}}}).then(result=>{if(!active)return;if(result.error)setError(apiErrorMessage(result.error,"Sandbox setup requires administrator permission and server support."));else if(result.data)loaded(result.data)}).catch(()=>{if(active)setError("Sandbox setup could not be loaded.")});return()=>{active=false}},[orgId,revision]);
 async function save(){if(!data||pending)return;setPending(true);setError(null);try{const result=await api.PUT("/api/v1/organizations/{orgId}/sandbox-setup",{params:{path:{orgId}},body:{expected:data.settings,settings:{enabled,max_per_user:perUser,max_total:total}}});if(result.error)setError(apiErrorMessage(result.error,"Settings could not be saved. Refresh before retrying."));else if(result.data)loaded(result.data)}catch{setError("Settings could not be confirmed. Refresh before retrying.")}finally{setPending(false)}}
 async function publish(id:string,current:boolean){if(!data||pending)return;setPending(true);setError(null);try{const result=await api.PUT("/api/v1/organizations/{orgId}/sandbox-catalog/{templateId}",{params:{path:{orgId,templateId:id}},body:{expected_enabled:current,enabled:!current}});if(result.error)setError(apiErrorMessage(result.error,"Catalog publication could not be saved. Refresh before retrying."));else if(result.data)loaded(result.data)}catch{setError("Catalog update could not be confirmed. Refresh before retrying.")}finally{setPending(false)}}
 const canActivate=!!data?.creation_status.runtime_ready&&!data.creation_status.blocked_reasons.includes("historical_reservation_invalid")&&data.policy_mode==="enforcing"&&data.catalog.some(entry=>entry.enabled&&entry.runtime_compatible);
 return <div className="sb-workspace"><SandboxHeader title="Sandbox setup" subtitle="Runtime, limits & catalog." actions={<><Link to="/sandboxes" className="sb-inline-link">← Workspaces</Link><Button disabled={pending} variant="ghost" onClick={()=>setRevision(r=>r+1)}>Refresh</Button></>}/>{error&&<ErrorText>{error}</ErrorText>}{!data?(!error&&<Loading/>):<>
 <div className="sb-console-surface sb-setup-console"><section className="sb-setup-readiness"><div className="sb-section-title"><h2>Readiness</h2></div><p className="sb-help">Runtime: {data.creation_status.runtime_ready?"Qualified and connected":"Unavailable"}. Policy mode: {data.policy_mode}.</p>{data.runtime_limits&&<p className="sb-help">Runtime limit: {data.runtime_limits.max_workloads} retained workload; {data.runtime_limits.workloads} occupied. Overall retained limit: {data.runtime_limits.max_retained}; {data.runtime_limits.retained} occupied.{data.runtime_limits.reservation_id&&<> Historical reservation: {data.runtime_limits.reservation_state}. Its position never becomes reusable workload capacity.</>}</p>}<details className="sb-setup-reasons"><summary>Setup requirements · {data.creation_status.blocked_reasons.length} blockers</summary><SandboxBlockedReasons status={data.creation_status} setupLink={false}/></details></section>
 <form className="sb-setup-settings" onSubmit={event=>{event.preventDefault();void save()}}><h2>Organization settings</h2><label className="sb-scope-choice my-4"><input type="checkbox" aria-label="Enable sandbox creation" checked={enabled} disabled={pending||!data.creation_status.can_admin||(!data.settings.enabled&&!canActivate)} onChange={event=>setEnabled(event.target.checked)}/><span>Enable sandbox creation</span></label>{!data.settings.enabled&&!canActivate&&<p className="sb-help mb-4">Activation blocked. View setup requirements above.</p>}<div className="sb-setup-fields"><Field label="Retained sandboxes per user"><Input type="number" min={1} max={100} required disabled={pending||!data.creation_status.can_admin} value={perUser} onChange={e=>setPerUser(Number(e.target.value))}/></Field><Field label="Retained sandboxes in organization"><Input type="number" min={1} max={10000} required disabled={pending||!data.creation_status.can_admin} value={total} onChange={e=>setTotal(Number(e.target.value))}/></Field><Button className="sb-primary" disabled={pending||!data.creation_status.can_admin||perUser>total}>Save settings</Button></div><p className="sb-help mt-3">Turning creation off withdraws workspace access. Lower limits apply to new workspaces.</p></form>
 <section className="sb-setup-catalog"><h2>Runtime catalog</h2><p className="sb-help mb-4">Publish a qualified configuration to make it available.</p>{!data.catalog.length&&<p>No configurations registered. Ask an operator to add a qualified image.</p>}<div className="sb-environment-list">{data.catalog.map(entry=><article className="sb-setup-catalog-row" key={entry.template.id}><div className="sb-row-identity"><RuntimeMark template={entry.template}/><div><h3>{entry.template.name}</h3><p className="sb-help">{entry.enabled?"Published":"Unpublished"} · {!data.creation_status.runtime_ready?"Runtime unavailable":entry.runtime_compatible?"Runtime compatible":"Runtime mismatch"}</p></div></div><Button disabled={pending||!data.creation_status.can_manage_catalog} onClick={()=>{if(entry.enabled&&!window.confirm("Unpublish this configuration? Existing sandbox access will be withdrawn until it is published again."))return;void publish(entry.template.id,entry.enabled)}}>{entry.enabled?"Unpublish":"Publish configuration"}</Button><details className="sb-catalog-measurement"><summary>Resources & image identity</summary><RuntimeSpecs template={entry.template}/><code className="sb-help break-all">{entry.template.image_digest}</code></details></article>)}</div></section>
 <details className="sb-catalog"><summary><span><strong>Profiles in preparation</strong><span className="sb-muted">Operator verification required</span></span><span className="sb-disclosure-label">Browse profiles</span></summary><div className="sb-catalog-body"><SandboxCandidateProfiles profiles={data.candidate_profiles}/>{!data.candidate_profiles?.length&&<p className="sb-help">No candidate measurements are available.</p>}</div></details></div></>}</div>;
}
