import { aiOperationExample, aiOperationSpec } from "./aiOperationExample";
export type CodeExample = { label: string; language: string; source: string };
export function aiLanguageExamples(base: string, model: string, mode: string): CodeExample[] {
  const curl = aiOperationExample(base, model, mode);
  const result: CodeExample[] = curl ? [{ label: "cURL", language: "shell", source: curl }] : [];
  const op = aiOperationSpec(model, mode);
  if (!op) return result;
  const url = base + "/" + op.route, body = JSON.stringify(op.body), q = JSON.stringify;
  const headers: Record<string,string> = { "Authorization": "Bearer YOUR_TUNNEX_CREDENTIAL", "Content-Type": "application/json" };
  if (mode === "video_generation") headers["Idempotency-Key"] = "REUSE_A_UNIQUE_KEY_FOR_THIS_JOB";
  const jsHeaders = JSON.stringify(headers, null, 2).replace('"Bearer YOUR_TUNNEX_CREDENTIAL"', '`Bearer ${process.env.TUNNEX_API_KEY}`');
  const js = `const response = await fetch(${q(url)}, {\n  method: "POST",\n  headers: ${jsHeaders},\n  body: ${q(body)},\n});\nif (!response.ok) throw new Error(await response.text());\n${mode === "audio_speech" ? 'const { writeFile } = await import("node:fs/promises");\nawait writeFile("speech.mp3", Buffer.from(await response.arrayBuffer()));' : 'console.log(await response.json());'}`;
  const pyHeaders = JSON.stringify(headers).replace('"Bearer YOUR_TUNNEX_CREDENTIAL"', '"Bearer " + os.environ["TUNNEX_API_KEY"]');
  result.push({label:"Python",language:"python",source:`import json, os, urllib.request\n\nrequest = urllib.request.Request(\n    ${q(url)},\n    data=${q(body)}.encode(),\n    headers=${pyHeaders},\n    method="POST",\n)\nwith urllib.request.urlopen(request) as response:\n    ${mode === "audio_speech" ? 'with open("speech.mp3", "wb") as output:\n        output.write(response.read())' : 'print(json.loads(response.read()))'}`});
  result.push({label:"JavaScript",language:"javascript",source:js},{label:"TypeScript",language:"typescript",source:js});
  const extraGo = mode === "video_generation" ? '\n    req.Header.Set("Idempotency-Key", "REUSE_A_UNIQUE_KEY_FOR_THIS_JOB")' : '';
  result.push({label:"Go",language:"go",source:`package main\n\nimport ("bytes"; "fmt"; "io"; "net/http"; "os")\n\nfunc main() {\n    req, err := http.NewRequest("POST", ${q(url)}, bytes.NewBufferString(${q(body)}))\n    if err != nil { panic(err) }\n    req.Header.Set("Authorization", "Bearer " + os.Getenv("TUNNEX_API_KEY"))\n    req.Header.Set("Content-Type", "application/json")${extraGo}\n    res, err := http.DefaultClient.Do(req)\n    if err != nil { panic(err) }\n    defer res.Body.Close()\n    data, err := io.ReadAll(res.Body)\n    if err != nil { panic(err) }\n    if res.StatusCode >= 300 { panic(string(data)) }\n    ${mode === "audio_speech" ? 'if err := os.WriteFile("speech.mp3", data, 0600); err != nil { panic(err) }; fmt.Println("Saved speech.mp3")' : 'fmt.Println(string(data))'}\n}`});
  const extraJava = mode === "video_generation" ? '\n    .header("Idempotency-Key", "REUSE_A_UNIQUE_KEY_FOR_THIS_JOB")' : '';
  result.push({label:"Java",language:"java",source:`import java.net.URI;\nimport java.net.http.*;\nimport java.nio.file.*;\n\nclass Example {\n  public static void main(String[] args) throws Exception {\n    var request = HttpRequest.newBuilder(URI.create(${q(url)}))\n    .header("Authorization", "Bearer " + System.getenv("TUNNEX_API_KEY"))\n    .header("Content-Type", "application/json")${extraJava}\n    .POST(HttpRequest.BodyPublishers.ofString(${q(body)})).build();\n    var response = HttpClient.newHttpClient().send(request, HttpResponse.BodyHandlers.ofByteArray());\n    if (response.statusCode() >= 300) throw new RuntimeException(new String(response.body()));\n    ${mode === "audio_speech" ? 'Files.write(Path.of("speech.mp3"), response.body());' : 'System.out.println(new String(response.body()));'}\n  }\n}`});
  result.push({label:"C#",language:"csharp",source:`using System;\nusing System.IO;\nusing System.Net.Http;\nusing System.Net.Http.Headers;\nusing System.Text;\n\nusing var client = new HttpClient();\nclient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Environment.GetEnvironmentVariable("TUNNEX_API_KEY"));\n${mode === "video_generation" ? 'client.DefaultRequestHeaders.Add("Idempotency-Key", "REUSE_A_UNIQUE_KEY_FOR_THIS_JOB");\n' : ''}using var response = await client.PostAsync(${q(url)}, new StringContent(${q(body)}, Encoding.UTF8, "application/json"));\nresponse.EnsureSuccessStatusCode();\n${mode === "audio_speech" ? 'await File.WriteAllBytesAsync("speech.mp3", await response.Content.ReadAsByteArrayAsync());' : 'Console.WriteLine(await response.Content.ReadAsStringAsync());'}`});
  const phpQuote = (v:string) => "'" + v.replace(/\\/g,"\\\\").replace(/'/g,"\\'") + "'";
  result.push({label:"PHP",language:"php",source:`<?php\n$ch = curl_init(${phpQuote(url)});\ncurl_setopt_array($ch, [\n  CURLOPT_POST => true,\n  CURLOPT_RETURNTRANSFER => true,\n  CURLOPT_HTTPHEADER => ["Authorization: Bearer " . getenv("TUNNEX_API_KEY"), "Content-Type: application/json"${mode === "video_generation" ? ', "Idempotency-Key: REUSE_A_UNIQUE_KEY_FOR_THIS_JOB"' : ''}],\n  CURLOPT_POSTFIELDS => ${phpQuote(body)},\n]);\n$result = curl_exec($ch);\nif ($result === false || curl_getinfo($ch, CURLINFO_HTTP_CODE) >= 300) { throw new Exception(curl_error($ch) ?: $result); }\n${mode === "audio_speech" ? 'file_put_contents("speech.mp3", $result);' : 'echo $result;'}\ncurl_close($ch);`});
  result.push({label:"Ruby",language:"ruby",source:`require "net/http"\nrequire "uri"\n\nuri = URI(${q(url)})\nrequest = Net::HTTP::Post.new(uri)\nrequest["Authorization"] = "Bearer " + ENV.fetch("TUNNEX_API_KEY")\nrequest["Content-Type"] = "application/json"\n${mode === "video_generation" ? 'request["Idempotency-Key"] = "REUSE_A_UNIQUE_KEY_FOR_THIS_JOB"\n' : ''}request.body = ${phpQuote(body)}\nresponse = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") { |http| http.request(request) }\nraise response.body unless response.is_a?(Net::HTTPSuccess)\n${mode === "audio_speech" ? 'File.binwrite("speech.mp3", response.body)' : 'puts response.body'}`});
  const parsed = new URL(url);
  result.push({label:"HTTP / REST",language:"http",source:`POST ${parsed.pathname} HTTP/1.1\nHost: ${parsed.host}\n${Object.entries(headers).map(([key,value])=>`${key}: ${value}`).join("\n")}\n\n${JSON.stringify(op.body,null,2)}`});
  return result;
}
